### ISSUE TITLE
A lot of compile errors.

### ISSUE THREAD

**Issue by zxhfirefox** [danielgindi/ios-charts#10]
I compile with Xcode 6.2, and there are a lot of errors. like:
1. @objc is only available for class type.
2. as! should be as.

for me, these look like the code is written in old swift(it changes a lot).

**Comment by danielgindi** [comment]
Haha that's hilarious! Old Swift...  
Man that's the new Swift! :-)  
If only you would have bothered actually reading the **bold** letters in the README at the top, specifying that you need to compile with **Xcode 6.3**...

**Comment by zxhfirefox** [comment]
@danielgindi , sorry for my stupid.

**Comment by zxhfirefox** [comment]
@danielgindi , I find the swift blog, sorry again = =
