### ISSUE TITLE
Bar Chart > Range bar 

### ISSUE THREAD

**Issue by clementcohen** [danielgindi/ios-charts#100]
Hi,  is it possible to  make a range bar with this?  I need a bar graph from point A to point B  and not 0 to point A

Thanks in advance

Clement

**Comment by danielgindi** [comment]
I didn't quite understand what you mean...

**Comment by danielgindi** [comment]
Oops I hit the Close and comment by mistake.

**Comment by clementcohen** [comment]
I need a bar as follow 
http://www.sd84.k12.id.us/sms/departments/susan.augustyn/unit1/images/rangebar-vert.gif

**Comment by danielgindi** [comment]
Well it's not yet possible, except for candlestick charts.
But that should be quite easy to implement... Do you want to give it a try? :-)

**Comment by clementcohen** [comment]
I don't really know how to do it :-/  yeah the candlestick but without stick ;-) 

I'm pretty new with iOS development

**Comment by AlBirdie** [comment]
That's very simple. Take a look at the CandleStickChartDataRenderer's drawDataSet method. The shadow is the line. Skip all the shadow calculations and drawing code and you're done.

**Comment by danielgindi** [comment]
Have you succeeded with this?

**Comment by smilydronavalli** [comment]
Thanks,its working fine
