### ISSUE TITLE
Can't import "module-swift.h"

### ISSUE THREAD

**Issue by jorgefrazaocosta** [danielgindi/ios-charts#11]
I try to import to one project (teste). When I build the "#import teste-Swift.h" can't be found, resulting in the "Cannot find protocol declaration for 'ChartViewDelegate'. What I'm doing wrong?

**Comment by jorgefrazaocosta** [comment]
BTW, I'm using the Xcode 6.3 beta 4. And as Apple refer in their documentation, tihs import should work. 

Naming Your Product Module

The name of the Xcode-generated header for Swift code, and the name of the Objective-C bridging header that Xcode creates for you, are generated from your product module name. By default, your product module name is the same as your product name.

I have checked over the Build Settings the Product Module Name.

**Comment by jorgefrazaocosta** [comment]
I don't have added the BalloonMarker.swift so I didn't had the Swift Compiler. After add and configure the bridging-header everything Run fine. It only runs on 8.1 and above?

**Comment by danielgindi** [comment]
It should run on iOS 7 too.

When adding to a project you need to add it as "Embedded Binary". I should
add this to the Readme

**Comment by jorgefrazaocosta** [comment]
Are you sure? I tried in my project and with ChartsDemo and didn't work in any project.

**Comment by danielgindi** [comment]
I didn't test it- but there's not even one line of code using a specific
8.0 API. And swift compiles for 7.0 too.

So I guess it's just a matter of the minimum version on the project's
configuration.

I will look into it tomorrow!

**Comment by jorgefrazaocosta** [comment]
No problem. Thanks for this amazing work. I also need to try some processes that I found on stackoverflow.
