### ISSUE TITLE
Can we create thumb for each chart?

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#111]
Can we create a thumb view or a thumb image for each chart? 

Say I have a dashboard, and I want to display many cells that is a chart. I need a very small view for each chart acts as the thumb view. 

I feel use images converted from chart view could improve the perfomance, but I don't know how to do it.

**Comment by danielgindi** [comment]
Did you even try to look at the API of your chart?

**Comment by liuxuan30** [comment]
I am sorry if I makes you feel that way. I did take a look at it, but I am not familiar with swift, and I don't see there is a API can create a thumb. Are you implying that I could send any size and the chart could fit accordingly? e.g. if I give 50x50 and 200x200 for two radar charts, the 50x50 size can still display the radar correctly and same content as the 200x200 one? 

I do see there is a API getChartImage, is this what you are refering for creating chart image?

**Comment by danielgindi** [comment]
It has nothing to do with Swift, or Thumbs. The ChartsDemo has a menu on
each screen, allowing you to "Save to camera roll". Which uses Charts API.

**Comment by liuxuan30** [comment]
alright, thanks, I will try it
