### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by a5544321** [danielgindi/ios-charts#112]
Hello,is there any property or protocol to tell if I drag the chartView to the end of left or right?
I want to do something like "pull to refresh"
I found there is a OnFling listener in Android version document,but I can't find in ios charts
Can anyone help?  Thanks

**Comment by danielgindi** [comment]
The onFling is something that comes by default when you implement the basic Gesture recognizer on Android. 
On iOS we do not have to have that overhead by default - and if you want to have a swipe gesture recognized, just add a recognizer. You do not have to modify any of the Charts code - just add a recognizer to its gestureRecognizers array.

**Comment by a5544321** [comment]
Thank you for your answer.But my problem is sometimes I will zoomIn the chart and swipe it left and right
but I only want to do something only when I scroll to the end . Is that doable?
And after I try to add a swipeRecognizer on chartView .It didn't work only if I swipe very very very fast.
Thank you.

**Comment by danielgindi** [comment]
Swipe gesture is a fast gesture, but you probably can change its
configuration.
If you received the delegate's messages you can know whenever the position
has changed, and compare it with the viewport.

**Comment by a5544321** [comment]
Sorry , is your delegate means chartView delegate? I only can find chartvalue select and unselect in it. And I don't know what your position mean. Is viewport means viewportHandler? What property in it I should compare with position? Thanks..

**Comment by danielgindi** [comment]
You need to pull the latest version.

**Comment by a5544321** [comment]
OK
Thanks a lot!
