### ISSUE TITLE
Add 'drawHighlightEnabled' to ChartDataSet

### ISSUE THREAD

**Issue by AlBirdie** [danielgindi/ios-charts#114]
With the current implementation we can basically configure everything on a dataset, from values, to circles (if available), over to colors and so on.
What is missing is a boolean that determines whether we want to actually draw a highlight or not.

In case of a CombinedChart, there are use cases where you only want to highlight a certain dataset and not all of them.

**Comment by AlBirdie** [comment]
Excellent. Really like how this library is thriving! As always, thanks a lot Daniel!

**Comment by danielgindi** [comment]
;-)
