### ISSUE TITLE
Adding a minimum parameter to setVisibleXRange

### ISSUE THREAD

**Issue by dorsoft** [danielgindi/ios-charts#115]
I'm working on a financial app and it is critical to limit the pinch gesture zoom in.
I've managed to implement this feature, could you please add it to the master branch ?

My implementation:

1. Add the following to BarLineChartViewBase
 public func setVisibleXRange(xMinRange: CGFloat, xMaxRange: CGFloat)
    {
        var maxScale = _deltaX / (xMinRange);
        var minScale = _deltaX / (xMaxRange);
        _viewPortHandler.setScaleXRange(minScale, maxScaleX: maxScale);
    }

2. Add the following to ChartViewPortHandler 
A. 
     /// maximum scale value on the x-axis
      private var _maxScaleX = CGFloat(FLT_MAX);

B.  
   public func setScaleXRange(minScaleX: CGFloat, maxScaleX: CGFloat)
    {
        _maxScaleX = maxScaleX;
        setMinimumScaleX(minScaleX);
    }

C. Inside limitTransAndScale()
 /// limits the maximum scale and X translation of the given matrix
    private func limitTransAndScale(inout #matrix: CGAffineTransform, content: CGRect?)
    {
        // min scale-x is 1f
        _scaleX = max(_minScaleX, matrix.a);
        
        if (_scaleX > _maxScaleX)
        {
            _scaleX = _maxScaleX;
        }
.
.

Thanks

**Comment by danielgindi** [comment]
You could make a PR. Just make sure that if you add another argument, the
first one will be named also as the naming of the function does not reflect
the exact meaning of the first argument.

**Comment by dorsoft** [comment]
I've created a PR

**Comment by dorsoft** [comment]
When trying to zoom in/out using the pinch gesture when the zoom in/out limit is reached the chart starts to pan.

I've fixed this issue in the PR, I'm not sure this is the best way to do that

**Comment by danielgindi** [comment]
https://github.com/danielgindi/ios-charts/pull/119
