### ISSUE TITLE
non-public selectors while submitting app

### ISSUE THREAD

**Issue by hamdan** [danielgindi/ios-charts#116]
got it warning while submitting application
itunes store operation succeeded with a warning
the app references non-public selectors in playload/myProject.app/myProject:legend,setDescriptionText; setForm;setFormSize:,setLabelPosition:,setValueFont:

**Comment by danielgindi** [comment]
It's ok. It's like the "id" issue with Facebook's SDK. It tries to recognize any private API selectors that you are using, but it is actually public API of Charts. So you're ok!

**Comment by hamdan** [comment]
thanks for fast reply.  will i am not using any external sdk like Facebook  only using ios-chart .Are you sure apple will not reject app?

**Comment by danielgindi** [comment]
Yes

‏בתאריך יום שישי, 29 במאי 2015, hamdan <notifications@github.com> כתב:

**Comment by Fenil15** [comment]
I got this error today while uploading on itunes. Here's is the conflicting method : legend, setCircleRadius:, setLabelPosition:, setLabelText:, setMargin:, setMinSize:, setScaleEnabled:, setValueFont:, setValueFormatter:, setYOffset: 

Charts version : 2.2.5

Any suggestion or idea will be really helpful?
