### ISSUE TITLE
y axis spaces between labels are too wide

### ISSUE THREAD

**Issue by dorsoft** [danielgindi/ios-charts#120]
The y axis spaces between labels are too wide even when spaceBetweenLabels=0.
I've fixed this issue by changing ChartXAxisRenderer - computeAxis (line 33) from:

var max = Int(round(xValAverageLength + Float(_xAxis.spaceBetweenLabels))); 
to
var max = Int(round((xValAverageLength / 2) + Float(_xAxis.spaceBetweenLabels)));

I'm not sure if this is the best way to resolve the issue, it might be better to change ChartData - calcXValAverageLength (line 113):
sum += _xVals[i] == nil ? 0 : _xVals[i]!.lengthOfBytesUsingEncoding(NSUTF16StringEncoding);

**Comment by danielgindi** [comment]
Can you show an example? I can't think of a case where the spacing between labels is to wide, as it could absolutely be zero. Maybe you are talking about the modulus of which labels to show. You can set a custom modulus to 0.

**Comment by dorsoft** [comment]
To see this issue you can use the candle chart sample:
1. Set the x labels to something like "yyyy MMM dd HH:mm"
2. Set xAxis.spaceBetweenLabels = 0, xAxis.axisLabelModulus = 0

And you will get something like the screen shot
![ios simulator screen shot jun 2 2015 11 55 02 am](https://cloud.githubusercontent.com/assets/8214769/7932162/d00470f2-091e-11e5-9b88-d317d00ebc36.png)

**Comment by dorsoft** [comment]
The thing is that ChartData.calcXValAverageLength returns the average x label length in bytes (not chars) and ChartXAxisRenderer.computeAxis uses the retuned value as chars count.
