### ISSUE TITLE
Down-casted Array element failed to match the target type

### ISSUE THREAD

**Issue by nhjariwala** [danielgindi/ios-charts#121]
Getting error on swift 
        
        var set1: BarChartDataSet = BarChartDataSet(yVals: yVals, label: "")

while setting dataSet and its redirected to class BarChartDataSet in below function

    /// calculates the maximum stacksize that occurs in the Entries array of this DataSet
    private func calcStackSize(yVals: [BarChartDataEntry]!)
    {
        for (var i = 0; i < yVals.count; i++)
        {
            var vals = yVals[i].values; // Error here
            
            if (vals != nil && vals.count > _stackSize)
            {
                _stackSize = vals.count;
            }
        }
    }

**Comment by danielgindi** [comment]
So your array contains element of the wrong type...

‏בתאריך יום שני, 1 ביוני 2015, nhjariwala <notifications@github.com> כתב:

**Comment by nhjariwala** [comment]
here is the code
   
    let months =
    [
        "19/03/2015", "18/03/2015", "17/03/2015", "16/03/2015"
    ]
    
        var xVals = Array<String>()
        xVals.append(months[0])
        xVals.append(months[1])
        xVals.append(months[2])
        xVals.append(months[3])
         
        var yVals = Array<ChartDataEntry>();
        yVals.append(ChartDataEntry(value: 10.0, xIndex: 0))
        yVals.append(ChartDataEntry(value: 20.0, xIndex: 1))
        yVals.append(ChartDataEntry(value: 30.0, xIndex: 2))
        yVals.append(ChartDataEntry(value: 15.0, xIndex: 3))
        
        var set1: BarChartDataSet = BarChartDataSet(yVals: yVals, label: "")
    
        var data: BarChartData = BarChartData(xVals: xVals, dataSet: set1)
        mBarChart.data = data
    }

Can you please point out the error ? 
Thnx

**Comment by danielgindi** [comment]
Do you seriously do not see how casting ChartDataEntry "down" to
BarChartDataEntry would give you such an error?

‏בתאריך יום שני, 1 ביוני 2015, nhjariwala <notifications@github.com> כתב:

**Comment by nhjariwala** [comment]
I have tried several thing from Objective-C demo but not getting success So I have found the LineChart Samples on https://github.com/danielgindi/ios-charts/issues/29 So I have tried same thing on BarChart.

**Comment by danielgindi** [comment]
You should really read the code at the point where it expects a
BarChartDataEntry

‏בתאריך יום שני, 1 ביוני 2015, nhjariwala <notifications@github.com> כתב:

**Comment by nhjariwala** [comment]
Opps extremely silly mistake I haven't figured out it .. Thanks you so much for point out this .

**Comment by sodeve19** [comment]
Hi @nhjariwala, can you say what was the mistake? Thanks

**Comment by nhjariwala** [comment]
Hi @sodeve19 , 
Earlier I was used the 
       
        var yVals = Array<ChartDataEntry>();

but need to change DataEntry as per the chart in my case I used BarChart so 
       
        var yVals = Array<BarChartDataEntry>();

and it was resolved the issue. Thanks ;)
