### ISSUE TITLE
Candle chart - make the shadow same color as an increasing/decreasing candle color 

### ISSUE THREAD

**Issue by dorsoft** [danielgindi/ios-charts#122]
I'm developing a financial app, it is customary to color the candle shadow the same color as the candle itself. e.g. green/red for increasing/decreasing.

I've managed to accomplish that by adding the following code:
A. CandleChartDataSet line 31
/// use candle color for the shadow
    public var makeShadowSameColorAsCandle = false

B. CandleStickChartRenderer - drawDataSet (line 104) changed from:

CGContextSetStrokeColorWithColor(context, (dataSet.shadowColor ?? dataSet.colorAt(j)).CGColor);

to

           var shadowColor = dataSet.shadowColor ?? dataSet.colorAt(j);
            if (dataSet.makeShadowSameColorAsCandle)
            {
                if (e.open >= e.close)
                {
                    shadowColor = dataSet.decreasingColor ?? dataSet.colorAt(j);
                }
                else
                {
                    shadowColor = dataSet.increasingColor ?? dataSet.colorAt(j);
                }
            }
            
            CGContextSetStrokeColorWithColor(context, shadowColor.CGColor);    

Could you please add it to the master ?

**Comment by AlBirdie** [comment]
I've had the same requirement and altered the CandleStickChartRenderer almost identically to your solution. However, what is missing is the case for e.open == e.close, so a neutral shadow color.

**Comment by dorsoft** [comment]
Nice catch @AlBirdie, I guess we could use something like:

var shadowColor = dataSet.shadowColor ?? dataSet.colorAt(j);
        if (dataSet.makeShadowSameColorAsCandle)
        {
            if (e.open > e.close)
            {
                shadowColor = dataSet.decreasingColor ?? dataSet.colorAt(j);
            }
            else if (e.open < e.close) 
            {
                shadowColor = dataSet.increasingColor ?? dataSet.colorAt(j);
            }
        }
      CGContextSetStrokeColorWithColor(context, shadowColor.CGColor);

**Comment by AlBirdie** [comment]
Yes, that's it. :)

**Comment by dorsoft** [comment]
On top of that it is customary to draw a horizontal line when the candle height is zero, I've added this feature as well
