### ISSUE TITLE
Lines clipping top and bottom with lineWidth > 1

### ISSUE THREAD

**Issue by justinswart** [danielgindi/ios-charts#123]
When using a lineWidth greater than 1.0, my chart is clipping at the min and max values.  Is this something that I can adjust by subclassing the ChartViewPortHandler or somehow padding the chart top and bottom?

![screen shot 2015-06-01 at 4 14 53 pm](https://cloud.githubusercontent.com/assets/3735375/7914903/4435c1e2-087a-11e5-99d1-c077d2a686af.png)

**Comment by danielgindi** [comment]
You do not have to subclass - just add some offset

**Comment by justinswart** [comment]
I've tried chart.setViewPortOffsets(left: 10, top: 30, right: 10, bottom: 30) as well as setting chart.extraBottomOffset, this makes the space between the segmented control and the bottom of the chart larger but it doesn't prevent the blue line from clipping at its edge.  I've also tried chart.clipsToBounds = false.

Appreciate any other suggestions!
