### ISSUE TITLE
Install with cocoapod into project supporting iOS 7 and later

### ISSUE THREAD

**Issue by DarkInsight85** [danielgindi/ios-charts#125]
As topic, I am trying to install this library with cocoapod (pod 'Charts', '~> 2.1'), but I encountered an error stating that the library only support iOS 8 and later.

Is it possible to install this library with cocoapod into project supporting iOS 7 and later?

**Comment by danielgindi** [comment]
Nope. You need to drag the files manually to your project. iOS 7 does not support frameworks so you have to compile yourself.
