### ISSUE TITLE
Any way to add/use image for xVals?

### ISSUE THREAD

**Issue by liebeskind** [danielgindi/ios-charts#126]
I am trying to have text and UIImage show up next to each other on the x axis of a bar chart.  Any suggestions on how to do this?

**Comment by danielgindi** [comment]
There's currently no support for that. You can try adding it yourself in the `XAxisRenderer` - or adding those externally with `UIImageView`s, taking the correct coordinates from the ViewPortHandler

**Comment by liebeskind** [comment]
Thanks Daniel.  Is there any way to get an array of y coordinates for each xAxis line in a horizontal bar chart?  I can then add UIImageViews to the Superview to externally place them at the .Top of each line.

I can't figure out how to get those values with ViewPortHandler.

**Comment by danielgindi** [comment]
The viewport tells you were content is drawn.
Then you can use the tranformer to convert x values to pixels (those are
the positions for the labels).
And there are properties that tell you which x indexes are visible

‏בתאריך יום רביעי, 3 ביוני 2015, Daniel <notifications@github.com> כתב:

**Comment by liebeskind** [comment]
Any chance you have or know of any examples where this is done?

I know how to use the viewPort to get the content area using             

    barChartView.viewPortHandler.contentRect

but I am not sure how to get xAxis values  or use the transformer to convert to pixels.

**Comment by danielgindi** [comment]
Give it a value of x=1,y=0 and it will convert that x to the proper pixel
value for xIndex 1. Same for 2 etc.

**Comment by liebeskind** [comment]
Thanks Daniel - what method should I use on viewPortHandler to do this?  What do I give a value of x=1, y=0 to?

**Comment by danielgindi** [comment]
The transformer, not the viewport. You need to ask the Chart to give you
the transformer

‏בתאריך יום רביעי, 3 ביוני 2015, Daniel <notifications@github.com> כתב:

**Comment by liebeskind** [comment]
OK - I believe I've made a bit of progress.  I set up the chart with:

    var yVals: [BarChartDataEntry] = []
    for idx in 0...numOptions {
            var index = "option\(idx)Votes"
            var votes = quest.objectForKey(index) as? Int
            if let vote = votes {
                yVals.append(BarChartDataEntry(value: Float(vote), xIndex: idx))
            }
        }

    let set2 = BarChartDataSet(yVals: yVals, label: "Votes")
    let dataBar = BarChartData(xVals: xVals, dataSet: set2)

Then I use ChartTransformer to generate values:

    var somePoints = ChartTransformer(viewPortHandler: barChartView.viewPortHandler).generateTransformedValuesHorizontalBarChart(yVals, dataSet: 1, barData: dataBar, phaseY: 1.0)
    println(somePoints)

*[(1.0, 1.0), (1.0, 2.0), (1.0, 3.0), (1.0, 4.0)]*

Then I try to convert the values to pixels:

    ChartTransformer(viewPortHandler: barChartView.viewPortHandler).pointValuesToPixel(&somePoints)
        println(somePoints)
*[(1.0, 1.0), (1.0, 2.0), (1.0, 3.0), (1.0, 4.0)]*

It's clear that I'm doing something wrong, but feels like I'm on the right track.  Thank you for your assistance so far - I continue to appreciate any guidance.

**Comment by liebeskind** [comment]
Daniel, thanks for your help with this.  Figured it out.

    var imagePos = barChartView.getPosition(yVals[opt], axis: .Left)

*(219.090912112191, 270.833333333333)*

Can then pull the x and y with

    imagePos.y
    imagePos.x

This is great!  Very cool functionality.

**Comment by walinaqvi** [comment]
Hi @liebeskind where did you add these images so it scroll along with bars of graph ?

**Comment by Gagan6696** [comment]
Can you guys please share the sample. So that it becomes easy to use
