### ISSUE TITLE
Cannot load underlying module for 'Charts'

### ISSUE THREAD

**Issue by knseir** [danielgindi/ios-charts#129]
I'm just getting started with this library : 
- I followed all the steps described under 'Usage' on the main page (https://github.com/danielgindi/ios-charts)
- I added a UIView and made it subclass LineChartView
- in ViewController.swift: the line 'import Charts' gives an error: 'Cannot load underlying module for 'Charts'
Why is that ?

Thank you !

**Comment by danielgindi** [comment]
Can you a try `git pull` and recompile? (#144)

**Comment by knseir** [comment]
Hi Daniel, it still doesn't work, I'm sorry

**Comment by danielgindi** [comment]
Did you by any chance import the Framework, or the code itself?

**Comment by danielgindi** [comment]
iOS 7.0 does not support Frameworks...

**Comment by knseir** [comment]
I'm using iOS 8
I imported the framework. Here are some screenshots: 

![screen shot 2015-06-11 at 1 15 37 pm](https://cloud.githubusercontent.com/assets/10488165/8104770/0822c898-103c-11e5-9256-e2359e78d33e.png)
![screen shot 2015-06-11 at 1 14 49 pm](https://cloud.githubusercontent.com/assets/10488165/8104771/0854521e-103c-11e5-8ce2-bc8a48127af4.png)

**Comment by danielgindi** [comment]
When you go to Build Phases, do you see it under the linked frameworks?

**Comment by knseir** [comment]
Yes. Screenshots below : 

![screen shot 2015-06-11 at 3 06 33 pm](https://cloud.githubusercontent.com/assets/10488165/8106621/854f64a2-104b-11e5-9a0f-5d6535ca02da.png)

**Comment by danielgindi** [comment]
That's weird.

**Comment by danielgindi** [comment]
https://github.com/Alamofire/Alamofire/issues/122

**Comment by knseir** [comment]
hmm... So, should I install cocoa pods or add the swift files ?
I actually tried installing cocoa pods yesterday, it didn't work but I'm not sure I did it right

**Comment by danielgindi** [comment]
No, it means that you need to remove the framework, let your project build
completely, and then add the Framework... They say there's a bug like that,
so let's give it a try!

**Comment by knseir** [comment]
Yes ! it worked. 
I actually had to build once Without removing the framework
I just removed 'import Charts', built the project, added the import line and built again
Thank you

**Comment by danielgindi** [comment]
```Swift
let FDEG2RAD = CGFloat(M_PI / 180.0)
var drawAngles = [CGFloat]()
var absoluteAngles = [CGFloat]()
var lastAbsoluteAngle: CGFloat = 0.0
var center = chart.centerCircleBox
var r: CGFloat = YOUR_DRAWING_RADIUS_HERE
let rotationAngle = chart.rotationAngle
for (var i = 0; i < data.entries.count; i++)
{
  let entry = data.entries[i]
  var angle = CGFloat(value) / CGFloat(chart.data.yValueSum) * 360.0
  drawAngles.append(angle)
  absoluteAngles.append(lastAbsoluteAngle + angle)
  lastAbsoluteAngle += angle;

  var x = (r * cos(((rotationAngle + absoluteAngles[i] - offset) * _animator.phaseY) * FDEG2RAD) + center.x);
  var y = (r * sin(((rotationAngle + absoluteAngles[i] - offset) * _animator.phaseY) * FDEG2RAD) + center.y);

  // Put whatever you want now on the x/y
}
```

**Comment by danielgindi** [comment]
Ha ha! That's one of the stupidest bugs I've ever had to solve...

**Comment by knseir** [comment]
This one actually looks like it might from Xcode...

**Comment by danielgindi** [comment]
Yeah, it's xcode alright...

**Comment by aspgod** [comment]
The solution works, Thanks

**Comment by beausmith** [comment]
I had this same issue and googled for "Cannot load underlying module for charts" and ended up here. I followed [danielgindi](https://github.com/danielgindi/ios-charts/issues/129#issuecomment-111116308)'s instructions:

1. Remove "Charts.framework" from Project > "Build Phases" >  "Link Binary With Libraries"
2. Build project.
3. Add "Charts.framework" back to "Link Binary With Libraries"
4. Build project.

Success!

**Comment by aknza** [comment]
Nice bug :) I'm trying for three days. Thanks !

**Comment by Vektrat** [comment]
For future reference, and for an easier fix, in my case by cleaning the build and re-launching it also fixed the issue. (**Product -> Clean**)

**Comment by alebla26** [comment]
Thanks to this thread, my evening continues. 3 hour headache solved. You guys are the best.

**Comment by yul1** [comment]
It really works. Thank you all.
