### ISSUE TITLE
Cannot assign a value of type 'ChartLimitLabelPosition' to a value of type 'ChartLimitLine.ChartLimitLabelPosition'

### ISSUE THREAD

**Issue by robomotic** [danielgindi/ios-charts#131]
Yo guys,
excellent work this project is!
I was converting the demos from ObjC to Swift one by one but I have incurred in two compilation issues.
Example 1:
```javascript
        // x-axis limit line
        var llXAxis = ChartLimitLine(limit:10.0,label:"Index 10")
        llXAxis.lineWidth = 4.0;
        llXAxis.lineDashLengths = [(10.0), (10.0), (0.0)]
        llXAxis.labelPosition = ChartLimitLabelPosition.Right
        llXAxis.valueFont = UIFont.systemFontOfSize(10.0)
```
That gives me the error:
Cannot assign a value of type 'ChartLimitLabelPosition' to a value of type 'ChartLimitLine.ChartLimitLabelPosition'

Another issue is this one:
```javascript
self.chartView!.legend.form = ChartLegendForm.Line
```
Cannot assign a value of type 'ChartLegendForm' to a value of type 'ChartLegend.ChartLegendForm'

Any help is welcome.
I can also publish the Swift code at the end once I manage to compile it!

**Comment by danielgindi** [comment]
`self.chartView!.legend.form = .Line`. It's Swift.

**Comment by robomotic** [comment]
Wow thanx, my fault Swift syntax is still weird to me!
