### ISSUE TITLE
Error while drawing radar chart

### ISSUE THREAD

**Issue by kajensen** [danielgindi/ios-charts#132]
Let me preface this by saying this is the first time I've imported a swift project into an objective c (or really using swift, i'm not 100% sure whats happening when I look at swift code). I tried to setup just a test radar chart through IB, just like the demo. I actually use the exact demo code to generate the data. It crashes here after setting the data:
![screen](https://cloud.githubusercontent.com/assets/6947273/8025542/4f62ba28-0d27-11e5-817b-c9b29ed84dde.png)

**Comment by danielgindi** [comment]
This is not a crash- it's a breakpoint.

>

**Comment by kajensen** [comment]
Yeah I know what a breakpoint is :) haha. I put those there to figure out what was going on. But I just deleted everything and re-installed it and it works...haha! Great lib, can't wait to check it out! Is there any way to get the source to compile quicker? It lags on "compiling swift files" for a long time and this is my first and only swift lib

**Comment by danielgindi** [comment]
That's in Apple's hands, improving with each Xcode release

**Comment by kajensen** [comment]
hi again. Sorry to bother you, but I can't seem to implement a Bubble chart, I get "fatal error: NSArray element failed to match the Swift Array Element type". I have checked the types right before the crash occurs and they seem to be the correct type? And the call is casting with a "?" so it should nil them instead of raising an error. I am quite perplexed, hopefully you can help if you have time.
screen:
![screen](https://cloud.githubusercontent.com/assets/6947273/8036852/5c004ede-0dc8-11e5-8d44-8095bda3b7f7.png)
code:
     
     NSMutableArray *xVals = [@[@"S",@"M",@"T",@"W",@"T",@"F",@"S"] mutableCopy];
    
    NSMutableArray *yValsTemp = [[NSMutableArray alloc] init];
    for (NSInteger i = 0; i < ActivityTypeCount; i++) {
        NSMutableArray *yValTemp = [[NSMutableArray alloc] init];
        for (NSString *day in xVals) {
            [yValTemp addObject:@[@(0),@(0)]];
        }
        [yValsTemp addObject:yValTemp];
    }

    for (PFSavedGo *pfSavedGo in _pfGos) {
        NSInteger dayOfWeek = [Convert dayOfTheWeek:pfSavedGo.createdAt]-1;//1-7, huh?
        ActivityType activityType = pfSavedGo.usedActivity.activityType;
        if (activityType < [yValsTemp count]) {
            NSMutableArray *yVal = [yValsTemp objectAtIndex:activityType];
            if (dayOfWeek < [yVal count]) {
                NSArray *actDay = [yVal objectAtIndex:dayOfWeek];
                NSNumber *val = actDay[0];
                NSNumber *size = actDay[1];
                [yVal replaceObjectAtIndex:dayOfWeek withObject:@[@(val.doubleValue + [Convert milesOrKilometersFromMeters:pfSavedGo.distanceInMeters]),@(size.integerValue + pfSavedGo.timeInSeconds)]];
            }
            //NSLog(@"%@",yVal);
        }
    }
    
    NSMutableArray *yValsActual = [[NSMutableArray alloc] init];
    for (NSInteger i = 0; i < ActivityTypeCount; i++) {
        NSMutableArray *yValTemp = [yValsTemp objectAtIndex:i];
        NSMutableArray *yValActual = [[NSMutableArray alloc] init];
        for (NSArray *day in yValTemp) {
            NSNumber *val = day[0];
            NSNumber *size = day[1];
            [yValActual addObject:[[BubbleChartDataEntry alloc] initWithXIndex:i value:val.intValue size:size.doubleValue]];
        }
        [yValsActual addObject:yValActual];
    }
    
    NSMutableArray *dataSets = [[NSMutableArray alloc] init];
    for (NSInteger i = 0; i < ActivityTypeCount; i++) {
        NSMutableArray *yValActual = [yValsActual objectAtIndex:i];
        BubbleChartDataSet *set = [[BubbleChartDataSet alloc] initWithYVals:yValActual label:[PFActivity majorActivityTypeStringForType:i]];
        [set setColor:ChartColorTemplates.colorful[i] alpha:0.50f];
        [set setDrawValuesEnabled:YES];
        [dataSets addObject:set];
    }
    
    BubbleChartData *data = [[BubbleChartData alloc] initWithXVals:xVals dataSets:dataSets];
    [data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:7.f]];
    [data setHighlightCircleWidth: 1.5];
    [data setValueTextColor:UIColor.whiteColor];
    
    _chartView.data = data;
