### ISSUE TITLE
Still seeing undeclared UIColor, CGFloat error with latest code

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#133]
I am trying to add the whole `charts` directory into my Objective-C project, so the structure is:

ThirdParty
|
  ios-charts
  |
    classes
    |
      Animation, Charts, Components, Data, Filters, Renderers, Utils

What I changed the project setting:
1. enable  embedded content contains swift code
2. Defines Module: YES

I also see the setting shows the $Module_name-Swift.h was set, but I don't see xcode generates it.

After I try build,

It throws lots of errors like undeclared CGFloat, UIColor, etc. I searched the closed issues, but they are not my case. My code is the latest.

What did I miss?

**Comment by liuxuan30** [comment]
The files having errors:
BubbleChartDataSet.swift, BubbleChartDataEntry.swfit, BubbleChartDataEntry,swift, BubbleChartData.swift, BubbleChartRenderer.swift

**Comment by liuxuan30** [comment]
Alright, I found that the BubbleChart related swift file is missing something like:
```Swift
import Foundation
import CoreGraphics.CGBase
import UIKit
```
Now the question is, I see some files are using `import CoreGraphics.CGBase` while some are `import CoreGraphics`, and some are `import UIKit`, while some are `import UIKit.UIColor`

I am not if we should follow the small package principle? I am not sure if I use `import UIKit.UIColor` will better than `import UIKit` in performance perspective

**Comment by quentinhayot** [comment]
Same issue here with the swift files drop method (for iOS 7 support). Had to add the imports you specified.
