### ISSUE TITLE
Warnings on the comments

### ISSUE THREAD

**Issue by noais** [danielgindi/ios-charts#135]
The generated file Charts-Swift.h have warnings on all comments like:

"Charts-Swift.h:149:20: Empty paragraph passed to '\param’ command”.

Every param is not described producing warnings.

**Comment by danielgindi** [comment]
It's probably some configuration in your project, this is not the default behaviour

**Comment by noais** [comment]
Yes, I'm using clang static analyser. I'm going to exclude this file from this analise. Thanks

**Comment by michael-snapptec** [comment]
Can someone give some more information about this? I'm having the same issue, but all of the "solutions" I see would involve an edit on the code of the Charts library itself. I'd love to know what the setting is in my project that is causing this. I have this same issue in two related projects, but one of them is newly created, and I haven't monkeyed with the settings in Xcode or anything. Any ideas?

**Comment by noais** [comment]
Have you some analyser like clang?

**Comment by michael-snapptec** [comment]
I am assuming that Xcode is using clang. I'm using Xcode 8, and I haven't changed any static analyzer settings on my project.

**Comment by ugenlik** [comment]
When I set `Apple Clang - Warnings -> Documentation Comments` to NO this warnings disappeared
