### ISSUE TITLE
iOS7 can't build success

### ISSUE THREAD

**Issue by edison0951** [danielgindi/ios-charts#136]
I have add all swift code to my project and setting the xxxx-Swift.h and xxxx-Bridging-Header.h. When I use in some objective-c file, so I "#import "xxxx-Swift.h". But it will build error. I use demo project, it works  because it import as Framework，so what can I do in iOS7?

**Comment by edison0951** [comment]
I have resolved

**Comment by liuxuan30** [comment]
You might want to post a solution if anyone had same issue.

For me, I have to drag the swift files into project and check embdeed contents with swift code, and set a module name, so we will have a bridge header.

**Comment by Nobin272** [comment]
Hi, I have problem in building the project with the iOS-Charts (Objective-C). I need to include iOS7 support as well. I am getting "Duplicate interface definition for Class 'ChartData'" errors in ${PROJECT_NAME}-swift.h file. 

Kindly advice and I am stuck here. :(

**Comment by danielgindi** [comment]
Check to see if you've included it twice. Maybe as code AND as a
framework?..
>
>

**Comment by Nobin272** [comment]
Hi Daniel, 
Thanks for the quick response. I checked that.
I followed the below steps:
1. Copy the entire "Charts" folder into project (Including Project file.) 
2. Add the Project framework as Embedded Binaries as per the guideline.
3. Enable the "Embedded Content Contains Swift Code" in Build settings.

I am just confused with steps for iOS7, Copying all the swift files in to the project.
this step is after including the Project as Embedded Binary?

**Comment by danielgindi** [comment]
It's either or

**Comment by liuxuan30** [comment]
You only use swift code files if you want to support iOS 7. Don't link the framework again. Project file is also useless. Think about the swift file as .h and .m combined together.

**Comment by Nobin272** [comment]
Thanks Daniel. Now it seems to be building fine.

I removed the "Embedded Binary" linking and Project File from the project.
1. Only added the Swift files in project.
2. Built it. :+1: 

Really appreciated your help. Its a great library.

**Comment by mika76** [comment]
What about the supporting files folder? Also how do you then use this? I can't seem to find a ChartViewController or anything of the sort?

**Comment by Nobin272** [comment]
I added Supporting Files also ("Charts.h"). Then import "@{SWIFT_MODULENAME}-Swift.h" and "Charts.h" file in viewcontroller. Then You will be able to use those classes.

**Comment by Airsola** [comment]
@Nobin272 thx~
