### ISSUE TITLE
compiling time costs 2-3 minutes after import swift code files, is it normal?

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#137]
I have dragged the ios charts swift files into my Objective-C project, successfully compile and show beautiful chart now. 

But I notice the whole compile time (do clean first) is cost from ~20-30 secs to ~2-3 minutes. Is it normal? I am wondering, if I just use Embedded Framework, will it be as fast as the pure Objective-C project of mine? 

PS: I have to support iOS 7 for now, but I am considering when to drop it after iOS 9 is released.

**Comment by danielgindi** [comment]
Compiling Swift is generally slower now than compiling ObjC. I do not know if it's slower for iOS 7, but I do know that it is faster in latest Xcode than in the previous version - and we can expect more improvements in the next versions.

You shouldn't drop iOS 7 support until one of these is true:
1. iOS 9.0 is alive for at least 6 months
2. You have analytics in your app, showing your iOS 7 user base dropped below 5%

**Comment by liuxuan30** [comment]
Thanks daniel, I have data that shows there are ~8%-15% iOS 7 users still struggling with my app, especially some 4S devices.

I was planning if iOS 9 drop 4S, I could do that too, however...  :(

Besides, are you implying using embedded framework won't help reduce compile time? I was wondering if this is the main reason, since a framework should be compiled or optimized at some level.

**Comment by danielgindi** [comment]
Yes I think that embedded framework just helps you regarding order of things. If new files are added to the framework, you don't have to drag more files to your project. You are already compiling a Framework...

But I might miss some things, maybe special optimizations in Frameworks, or maybe compilation for iOS 9, for example, behaves differently in Swift - as iOS 9 allows you to have different binaries for different devices or OS versions.

The only way to really know is to watch the WWDC videos and listen closely, and actually test the different situations...

**Comment by danielgindi** [comment]
Anyway, there's nothing we can really do here so I'm closing it. If you have an update feel free to reopen :-)
