### ISSUE TITLE
Drawing circles for values on the radar chart

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#138]
Say it is a radar chart view,  can ios-charts draw a dot circle at each data point (a specific yValue and xIndex)?

**Comment by danielgindi** [comment]
Can you provide an example?

**Comment by liuxuan30** [comment]
I capture this chart from a JS radar chart. For each data point, it has a doct circle. When highlighting, the dot circle can be hollow (filled by white color, stroke with the old color)

Current ios-chart radar chart don't have a dot. It not easy to see if there is a data point. Having some dots will make it easier.

**Comment by liuxuan30** [comment]
![radar](https://cloud.githubusercontent.com/assets/4375169/8105647/7c054796-106d-11e5-8259-6332cc47ca97.png)

I capture this chart from a JS radar chart. For each data point, it has a doct circle. When highlighting, the dot circle can be hollow (filled by white color, stroke with the old color)

Current ios-chart radar chart don't have a dot. It not easy to see if there is a data point. Having some dots will make it easier.

**Comment by liuxuan30** [comment]
@danielgindi Do you think this is worthy to have? I am about to finish implementing this feature on my side.

**Comment by liuxuan30** [comment]
Seems only I have this requirement. I will close it. If anyone raise same request, i could share my code.

**Comment by alexwillrock** [comment]
this is a very cool feature, it is strange that the developers did not include it by default, really need this feature
thx

**Comment by liuxuan30** [comment]
@alexwillrock you are the first one to ask for a dot since Jun..

You could add the dots just like drawCircles in line chart renderer into Radar chart renderer.

**Comment by shrikantwalekar-tudip** [comment]
@liuxuan30, I need the same feature you are talking about. would you please file PR.

**Comment by liuxuan30** [comment]
I actually did it already, PR is right above your comment.

**Comment by shrikantwalekar-tudip** [comment]
@liuxuan30 , I did that . and able to show circle on tap of point.
I want my chart to look like the image above.

but not able to plot single point or points like line chart, in case- if there are multiple radar Chart Data sets and if any data set contains only one point then that point is not visible. Also the circles are visible only after tap. Please guide me if I am doing something wrong.
![screen shot 2016-02-03 at 8 57 07 pm](https://cloud.githubusercontent.com/assets/14139567/12787220/72916214-caba-11e5-8acb-9d06e0c56e9b.png)

**Comment by liuxuan30** [comment]
you should check out radar chart renderer highlight method to achieve your goals. Either highlight all data sets or just not highlight any of them. up to you.

**Comment by shrikantwalekar-tudip** [comment]
Hey @liuxuan30, here I am sharing little piece of code, plz tell me how can I use radar chart renderer highlight method to achieve my goal, I am very new to this technology, plz help me out        


            radarChartDataSetTemp.lineWidth = 2
            radarChartDataSetTemp.drawValuesEnabled = true            
            finalRadarChartDataSet.append(radarChartDataSetTemp)
        }               
        chartView.drawHighlightCircle = true
        chartView.circleOuterRadius = 4
        chartView.circleFillColor = colorsArray[j]
        chartView.circleInnerRadius = 2
        chartView.circleStrokeAlpha = 1
        chartView.circleStrokeWidth = CGFloat(2.0)
        
        chartView.delegate = self
        let radarChartData = RadarChartData(xVals: dataPoints, dataSets: finalRadarChartDataSet)
        chartView.data = radarChartData
//        chartView.highlightPerTapEnabled = false
        chartView.drawMarkers = false
        chartView.yAxis.drawLabelsEnabled = false
        radarChartData.setValueFont(UIFont.boldSystemFontOfSize(15.0))

**Comment by liuxuan30** [comment]
I mean you have to figure out what you want to do. A dot when highlighting, or a dot always in the chart? It's different.
For highlighting, you have to override `drawHighlighted` method to get your work done. For normal rendering, you have to override `drawDataSet`. They are both in radar chart renderer.
If you want to highlight all data for same xIndex, you may look at chart highlighter code as well.
If you are beginner, I suggest you walk through the code first. These customizations requires a good understanding of the code.

**Comment by CivelXu** [comment]
How draw all Circles in radar chart?
