### ISSUE TITLE
Any demo in swift ?

### ISSUE THREAD

**Issue by benju69** [danielgindi/ios-charts#139]
Hi
I try to make a barchart in swift but I need help.
The demos are in Objective C, can I have a sample in swift ?
Thanks

**Comment by liuxuan30** [comment]
it is in the ChartsDemo folder.

**Comment by benju69** [comment]
My problem is to set data

**Comment by liuxuan30** [comment]
and what's your question? Set data to whatever you want.

**Comment by anhnt92** [comment]
same question

**Comment by liuxuan30** [comment]
Read https://github.com/PhilJay/MPAndroidChart/wiki
15. The ChartData class
16. ChartData subclasses
17. The DataSet class
18. DataSet subclasses

It tells you how to set data.
I believe you have the ability to write it in swift:)

**Comment by danielgindi** [comment]
Yeah, the only difference is maybe the `Chart` keyword prepended to most classes for namespacing, and an enhanced Swift syntax. I believe you'll be fine :-)

**Comment by anismansuri63** [comment]
You don't need swift demo at all.
Select chart which you want to make in swift from demo.
e.g MultipleLinesChart.
Just convert Objective-C code to swift.
https://objectivec2swift.com/#/home/main
Use above site. There will be minor changes after you convert code.

**Comment by liuxuan30** [comment]
OS X contains swift code.. that's enough
