### ISSUE TITLE
Import with Swift(not objc) not working

### ISSUE THREAD

**Issue by ricardo85x** [danielgindi/ios-charts#14]
Hi

I am trying to build a very simple code using swift. 
But I can't figure out how can I import the Classes.

When I set the view to be PieChartView and create a :
@IBOutlet weak var testView: PieChartView!

I got "use of undeclared type: PieChartView

I did try to import PieChartView, but xcode can't find it.

I am using Xcode 6.3 beta 4 and already setup the "Embedded Binaries" and "Linked Frameworks and Libraries" to the Charts.framework.

Also I can't find one sample code of swift on the web.

Thanks

**Comment by danielgindi** [comment]
You need to import the Charts namespace.

**Comment by ricardo85x** [comment]
Hello Daniel
I am not sure how to do that.

The import Charts also do not work.

I did tried to create a bridging header with: #import <Charts/Charts.h>

And in my ViewController I did add:
import Charts.

It did compile, but I got this error when the app start:

fatal error: unexpectedly found nil while unwrapping an Optional value

on ChartViewBase file in the line with:
            if (noDataTextDescription!.lengthOfBytesUsingEncoding(NSUTF16StringEncoding) > 0)

**Comment by danielgindi** [comment]
You are using the wring version of Swift, you haven't read the Readme.

**Comment by ricardo85x** [comment]
Version 6.3 (6D554n)

**Comment by ricardo85x** [comment]
I replace this line with:             if (noDataTextDescription != nil && noDataTextDescription!.lengthOfBytesUsingEncoding(NSUTF16StringEncoding) > 0)

and now it is working

**Comment by danielgindi** [comment]
Ok, you were right, there is an issue :-)

**Comment by danielgindi** [comment]
I have already pushed a fix

**Comment by ricardo85x** [comment]
thanks!
Now I was able to create a working chart :)
