### ISSUE TITLE
Bar chart some values < 0

### ISSUE THREAD

**Issue by MihaelIsaev** [danielgindi/ios-charts#141]
Hello!

How to show values < 0 in BarChart?

**Comment by AlBirdie** [comment]
Just set the chart's axis 'setStartAtZeroEnabled' to NO.
e.g.: [[chart getAxis:AxisDependencyRight] setStartAtZeroEnabled:NO]];

**Comment by danielgindi** [comment]
Thanks @AlBirdie :-)
