### ISSUE TITLE
unsuccessful at installing for ios 7.0

### ISSUE THREAD

**Issue by swangy** [danielgindi/ios-charts#144]
so looking through all the requests for swift demos it seems many people are running into this issue, but the author seems truculent in his indignation and insists that this is not a swift school.  seems as though this is an issue with this project, though.

like many others, i started a blank project and copied ALL the swift files and subfolders in the Charts/Classes folder into an iOS 7 project but importing Charts namespace continues to spit out the 'Cannot load the module 'charts' error.  

what am i missing?

**Comment by vishw3** [comment]
https://github.com/vishw3/IOSChart-IOS-7.0-Support

**Comment by danielgindi** [comment]
Please separate the two issues:
1. People who are asking how to write Swift code - this is not a Swift school...
2. People who are having trouble with compilations

We are all doing everything we can to help people get along with the library.

Please elaborate more on your trouble. A complete error log would be great.

**Comment by danielgindi** [comment]
See #133. We may have just solved your problem...

**Comment by swangy** [comment]
using the latest version..
1. new project
2. drag drop /Classes folder
3. import Charts namespace

![screen shot 2015-06-11 at 7 11 11 am](https://cloud.githubusercontent.com/assets/752891/8105676/3d00caac-1009-11e5-9a44-0391ff605eb0.png)

**Comment by danielgindi** [comment]
Are the Swift files of Charts marked in the "Target Membership"?

**Comment by swangy** [comment]
Did not have that...!  for those looking for the solution:

4. Add target membership with Classes folder


![screen shot 2015-06-11 at 7 31 07 am](https://cloud.githubusercontent.com/assets/752891/8106020/048855fc-100c-11e5-8d9b-51a13226672c.png)

**Comment by swangy** [comment]
you might want to amend your readme to reflect this, it's not clear at all for those who dont have xcode experience.
