### ISSUE TITLE
Projects using Charts

### ISSUE THREAD

**Issue by danielgindi** [danielgindi/ios-charts#145]
I'd love to have a list of projects using Charts!
So if anyone has anything in the AppStore already, that would be great to hear :-)
If it has a counterpart in Android, even better...

**Comment by sunjames** [comment]
I Used Charts in my Project ,when I submit my project in the AppStore  remind Error

**Comment by danielgindi** [comment]
Not much cooperation here. Closing.

**Comment by toriaezunama** [comment]
For what it's worth my app [Spendr](https://itunes.apple.com/app/id1027219728) is using iOS-Charts. 
Thanks again for this library I will continue to use it in other projects and as Spendr grows to include more stats related views.
