### ISSUE TITLE
[feature request] enable legend view scrollable

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#151]
I am not sure if the legend view is scrollable. I went through the code, but not found how can I enable it. If I have several legends and their label is long, it is better we can scroll the legend view to enable user can scroll on the legend. e.g. the legend view is a UIScrollView.

**Comment by danielgindi** [comment]
Don't you prefer calculating how much dpace is needed for the legend and extending the view?

**Comment by liuxuan30** [comment]
usually the chart is centered, and the legend is at the bottom. If the legends are too many, finally it will go out of screen. If we extend the legend view, it either invade the chart's space, having some overlap, or some part of the legend is out of screen.

**Comment by danielgindi** [comment]
What I do in an existing app is notifyDataSetChange() to tell it to
calculate the legend,
and then take the required size from the legend - and append it to the
view's height. And then of course tell the legend that it has more space.

**Comment by liuxuan30** [comment]
if the legend height is very large, will the chart itself shrink its height?

**Comment by danielgindi** [comment]
Yes. And you can control the "how much" through properties introduces lately

**Comment by liuxuan30** [comment]
@danielgindi I tested, the legend will horizontally expand if I have 5 or more legend items with out wrapping. If not support scrolling (which I think is the best way), consider support legend wrapping?

**Comment by danielgindi** [comment]
There is legend wrapping currently for bottom legends, you just have to
turn it on :)

‏בתאריך יום שישי, 19 ביוני 2015, Xuan <notifications@github.com> כתב:

**Comment by liuxuan30** [comment]
holy sht... I just saw wordWrapEnabled is in the middle of the code after I implemented my legend view with scroll view...
BTW, I still recommend you to support scrolling:) This will not shrink the chart size.

**Comment by danielgindi** [comment]
Well we do not plan to support scrollable legends currently, as it is not a commonly required feature and not a good UX in most cases...
Maybe in the future :-)
