### ISSUE TITLE
Radar chart radius is still affected by label size when label drawing is disabled

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#153]
![radardiff](https://cloud.githubusercontent.com/assets/4375169/8178760/e7242446-1443-11e5-8b71-26ed1ae3c45f.png)

I have setup two radar chart as shown in the screen shot. I am confused why the left one is smaller than right one. I just feed the same frame for both of them, only data is different. What I want is the same size for radar chart.

I found that `_viewPortHandler.contentRect` is giving different rect at diffrent phase. In init function, `_viewPortHandler.contentRect` is giving the right size.

I disabled the legend like this:
```swift
self.radarChart.legend.enabled = NO;
self.radarChart.data = radarData; // after set legend disabled
```
and checking stack trace, it shows the stack is notifyDataSetChanged() ->  calculateOffsets(),

in calculateOffsets(), 
```swift
        legendTop += self.extraTopOffset;
        legendRight += self.extraRightOffset;
        legendBottom += self.extraBottomOffset;
        legendLeft += self.extraLeftOffset;

        var minOffset = CGFloat(10.0);
        
        if (self.isKindOfClass(RadarChartView))
        {
            let x = (self as! RadarChartView).xAxis;
            
            if (x.isEnabled)
            {
                minOffset = max(10.0, x.labelWidth);
            }
        }
        var offsetLeft = max(minOffset, legendLeft);
        var offsetTop = max(minOffset, legendTop);
        var offsetRight = max(minOffset, legendRight);
        var offsetBottom = max(minOffset, max(self.requiredBaseOffset, legendBottom));

        _viewPortHandler.restrainViewPort(offsetLeft: offsetLeft, offsetTop: offsetTop, offsetRight: offsetRight, offsetBottom: offsetBottom);
```
the minOffset depends on the xAxis label width, the left radar is 11.56 whilte the right radar is 40. then it leads to diffrent size and even the factor is somewhat weird.
```swift
    /// Returns the factor that is needed to transform values into pixels.
    public var factor: CGFloat
    {
        var content = _viewPortHandler.contentRect;
        return min(content.width / 2.0, content.height / 2.0)
                / CGFloat(_yAxis.axisRange);
    }
```
The factor depends on the axisRange as well, and my left radar range is 120.0 while the left one is 140000000.0.

I am not sure if this a bug. but if false, how can I fix it? I need the left one and right one is equal radius.

**Comment by liuxuan30** [comment]
More frame info:

my chart bound is (0,0,157,40)

but after calculateOffsets(),

the left radar contentRect is 
(11.56, 11.56, 133.88, 16.88)

the right one is:
(40.46, 40.46, 76.08, -40.92)
Seems it messed up. the factor is also weird, but under this situation, the right radar is giving a fair size, but the left one is not.
It seems it messed up,

**Comment by danielgindi** [comment]
Does this happen on Android version too?

**Comment by liuxuan30** [comment]
I am not android developer, thus I am no sure...

**Comment by liuxuan30** [comment]
@danielgindi could you elaberate what's the viewport purpose for radar chart?

also, I am struggling with 
```swift
 public var factor: CGFloat
    {
        var content = _viewPortHandler.contentRect;
        return min(content.width / 2.0, content.height / 2.0)
                / CGFloat(_yAxis.axisRange);
    }
```
It reads the _yAxis.axisRange, however, this could vary from 120 to 14000000. Is this a bug or by design?

**Comment by liuxuan30** [comment]
@danielgindi   With further investigation, I think a very small view frame can easily be impacted. for exmaple, what I am doing is create a thumb view, the height is only 40. and ios-charts is doing calculations, leads to the viewPortHandler.contentRect has a very small height or even negative height. 

even I manually set the offset like this:
```swift
    self.thumbView.data = radarData;
    [self.thumbView.viewPortHandler restrainViewPortWithOffsetLeft:0 offsetTop:0 offsetRight:0 offsetBottom:0];
```

However, in ChartViewBase: drawRect, 
```swift
        if (!_offsetsCalculated)
        {
            calculateOffsets();
            _offsetsCalculated = true;
        }
```
This overwrite my changes again while drawing. 

I think this part should be enhanced to be able to fit in small view frame? What do you think?

**Comment by liuxuan30** [comment]
besides, 
```
        var offsetLeft = max(minOffset, legendLeft);
        var offsetTop = max(minOffset, legendTop);
        var offsetRight = max(minOffset, legendRight);
        var offsetBottom = max(minOffset, max(self.requiredBaseOffset, legendBottom));
``` 
this will make the radar chart not center aligned vertically.

I don't understand why offsetTop is set to either minOffset or legendTop. There should be a standalone yRequiredBaseOffset and xRequiredBaseOffset. using single RequiredBaseOffset and set it to xAxis.labelWidth is not good

**Comment by davecom** [comment]
I'm seeing the same bug.  Did you find a workaround?

**Comment by liuxuan30** [comment]
@davecom I don't have the issue recently, and I forget what I changed... But based on the comments, I guess it's about to change:
```Swift
if (!_offsetsCalculated)
        {
            calculateOffsets();
            _offsetsCalculated = true;
        }
```
I add a Bool property, if it's a thumb view, don't caculate:
```Swift
        if (!_offsetsCalculated)
        {
            if (!isSmallView)
            {
                calculateOffsets()
            }
            _offsetsCalculated = true
        }
```

**Comment by davecom** [comment]
I actually think this issue may be the same as #205

**Comment by liuxuan30** [comment]
@davecom I guess not, because I have disabled draw labels for small size charts. Unless it indeed has bug even I disabled it it still count it.
