### ISSUE TITLE
[feature request] support fixed yAxis interval and xAxis labelCount

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#155]
Setting yAxis.labelCount will not always get the same count. For example radar chart, if I set the yAxis.labelCount to be 3, I may get 5 label displayed. This is caused by `computeAxisValues(min yMin: Double, max yMax: Double)` has some logic to compute the intervals. This is sometimes confusing since I want to the final labelCount to be same as what  I set.

Adaptive compue is a very good design, but sometimes people just want that smart. Supporting fixed labelCount for both xAxis and yAxis gives another choice.

**Comment by danielgindi** [comment]
I actually do not completely understand the requirement...

**Comment by liuxuan30** [comment]
At first, I thought setting yAxis.labelCount will lead to setting the 'interval' on yAxis. Take an example, 

If I set yAxis.labelCount = 3, I hope there are only 3 labels on the yAxis, like [0,3,6] as the labels. If I set to 6, may be [0,1,2,3,4,5], or [0,3,6,9,12,15].

However, it turned out that setting yAxis.labelCount will not always get the same count as we want. `computeAxisValues(min yMin: Double, max yMax: Double)` will calculate how many values.

What I want is a 'fixed' count.

**Comment by danielgindi** [comment]
Well for obvious reasons this number cannot be fixed, and only be approximated. Like any other such calculation... It is also, btw, specified in the docs :-)

**Comment by danielgindi** [comment]
/// the number of label entries the y-axis should have
    /// max = 25,
    /// min = 2,
    /// default = 6,
    /// be aware that this number is not fixed and can only be approximated

**Comment by carrchr** [comment]
I'm not very good with Swift, yet, otherwise I would try tackling it myself. Have you looked at MPAndroidChart feature: [Added feature that allows the label-count to be exactly set and evenl...](https://github.com/PhilJay/MPAndroidChart/commit/d07ceda265830d585cda65d1132ebba283f2941c)  
Will this be possible in ios-charts?

**Comment by danielgindi** [comment]
It exists already https://github.com/danielgindi/ios-charts/commit/edd9c2ec6d433ba9599d4939080a690dc199ca86
