### ISSUE TITLE
hi can this demo be done under one .xcodeproj

### ISSUE THREAD

**Issue by vishw3** [danielgindi/ios-charts#16]
when i open charts demo.xcodeproj in Xcode it consist of charts.xcodeproj.is it possible to directly take .swift files from charts and implement in charts demo project with out importing whole charts.xcodeproj

**Comment by danielgindi** [comment]
It's possible.

It's the most convenient to just drag the Charts.xcodeproj to your project, but if you like you can drag the Swift files.

NOTE: If you download an update, and there are new files in the project or any structure changes, you will get errors about missing files...

I would recommend dragging in the files individually only if you want to compile for iOS 7.0.

**Comment by vishw3** [comment]
thanks for the quick reply. and i don't need to compile for iOS 7 but i thought it would be better because as most of them will not be implementing all type of charts so it might be overhead suppose if i want to use only bar graph i can take related .swift files and work on it leaving rest all behind this was my motive.

**Comment by danielgindi** [comment]
You shouldn't worry about it. It's not "overhead". It's over-optimizing.
And premature-optimization.

Some extra code won't kill you app - and in most cases will not even exist
as the compiler will strip it out.

**Comment by vishw3** [comment]
ok i wasn't aware of this thanks again.
