### ISSUE TITLE
Issues with chart rendering...

### ISSUE THREAD

**Issue by justinmakaila** [danielgindi/ios-charts#161]
When rendering a bar chart on screen, it always displays improperly:

![screen shot 2015-06-18 at 8 20 00 am](https://cloud.githubusercontent.com/assets/1638996/8230995/3cf6e2f0-1593-11e5-9170-bb2b1aab0aac.png)

I initialize the chart with the standard `init()` and then set it's `data` property with a `BarChartData` instance.

Any ideas?

**Comment by AlBirdie** [comment]
initWithFrame()!

**Comment by justinmakaila** [comment]
Worked like a charm, turns out it was a react native issue; I had to add a method to the class to have it set the frame appropriately.

**Comment by gutenye** [comment]
@justinmakaila How do you use this library in React Native?
