### ISSUE TITLE
When i set valueformatter , Have problem.

### ISSUE THREAD

**Issue by paneaktae** [danielgindi/ios-charts#163]
lineChart.leftAxis.valueFormatter = NSNumberFormatter()
lineChart.leftAxis.valueFormatter?.numberStyle = NSNumberFormatterStyle.NoStyle

When i set valueformatter to normal number , It works but number display same This picture, Please Help me thank you.
![screen shot 2558-06-19 at 10 26 13 am](https://cloud.githubusercontent.com/assets/11417557/8246753/e69c9f22-166d-11e5-9d20-c2d98774f908.png)

**Comment by liuxuan30** [comment]
this is because your yAxis label has decimals. You need to check if you set maximumFractionDigits to 0. non-zero means it can have decimals if possible

**Comment by paneaktae** [comment]
iI try to set
            lineChart.leftAxis.valueFormatter = NSNumberFormatter()
            lineChart.leftAxis.valueFormatter?.numberStyle = NSNumberFormatterStyle.NoStyle
            lineChart.leftAxis.valueFormatter?.maximumFractionDigits = 0

, But have problem same that picture. TT

**Comment by liuxuan30** [comment]
Can you just walk through the API and definitions by yourself first? Your set the maximumFractionDigits to 0, do you know the meaning of maximumFractionDigits?

**Comment by danielgindi** [comment]
You can also open a stackoverflow issue if you want help with iOS APIs
