### ISSUE TITLE
Make scroll to graph without pinch

### ISSUE THREAD

**Issue by ali-pl** [danielgindi/ios-charts#164]
Hi there

Is it possible to make scroll the graph with out pinching the view and it will make scroll automatically;

**Comment by AlBirdie** [comment]
Absolutely, take a look at the pinchGesture and implement the refreshMatrix method yourself, i.e. in a loop or timed method that constantly adjusts the CGAffineTransform matrix and sets it accordingly.

**Comment by ali-pl** [comment]
I am sorry , I didn't get you.Can you explain in more details please?

**Comment by ali-pl** [comment]
Sorry I typed automatically , Actually I am in need of scrolling the view and it will work like if you see paging in scrollview.like I am scrolling through different pages and can see different data on view as view getting scrolled.
