### ISSUE TITLE
Radar chart + Bar Line chart Base + startAtZeroEnabled = false + negative values

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#166]
When turning off startAtZeroEnabled, the negative values are not proper drawn. the radius ratio for each inner web is not correct.

The main trouble is:
```swift
        var labelCount = _chart.yAxis.entryCount;
        
        for (var j = 0; j < labelCount; j++)
        {
            for (var i = 0, xValCount = _chart.data!.xValCount; i < xValCount; i++)
            {
                var r = CGFloat(_chart.yAxis.entries[j] - _chart.chartYMin) * factor;
...
```
Take an example if _chart.yAxis.entries is: [-100000.0, 0.0, 100000.0, 200000.0, 300000.0, 400000.0]

and _chart.chartYMin is -35991.2689931.

The minimum raw data is -7501.57 and max is 277395.38. 
![negabug](https://cloud.githubusercontent.com/assets/4375169/8249438/8fcd97c6-169c-11e5-98b9-d882ef37e943.png)

**Comment by liuxuan30** [comment]
Provide data here:
data set 0:
[ChartDataEntry, xIndex: 0, value -7501.574034, ChartDataEntry, xIndex: 1, value 73587.954072, ChartDataEntry, xIndex: 2, value 68861.089668, ChartDataEntry, xIndex: 3, value 79499.134258, ChartDataEntry, xIndex: 4, value 53615.304423]

data set 1:
[ChartDataEntry, xIndex: 0, value 35790.059533, ChartDataEntry, xIndex: 1, value 20118.91748, ChartDataEntry, xIndex: 2, value 42567.845168, ChartDataEntry, xIndex: 3, value 38749.916356, ChartDataEntry, xIndex: 4, value 13551.626137]

data set 2:
[ChartDataEntry, xIndex: 0, value 163400.659256, ChartDataEntry, xIndex: 1, value 187068.443587, ChartDataEntry, xIndex: 2, value 277395.375557, ChartDataEntry, xIndex: 3, value 133373.871463, ChartDataEntry, xIndex: 4, value 132363.776504]

xVals could be any string.

**Comment by danielgindi** [comment]
Well this is not very clear to me. Can you show a visual example of how negative values should behave in a Radar chart vs. how it is now?

**Comment by liuxuan30** [comment]
![radarafterfix](https://cloud.githubusercontent.com/assets/4375169/8297351/1a7cd54a-198f-11e5-9f02-231439bb7cd8.png)

After I apply the code change, it renders like above, which I think is correct. the center will be -100K, and the interval between each inner web is equal. You could compare it to the previous screenshot.

As I mentioned in the pull request, the magic is `_yAxis.axisMinimum = _yAxis.entries[0]` I am not sure why it is absent currently, only `_yAxis.axisMaximum = _yAxis.entries[entryCount - 1]` is there.

**Comment by liuxuan30** [comment]
@danielgindi I am starting using scatter chart view, and I find that these views also have such problems with the negative values and axis rendering. Are you aware of this?

First thing is the interval is not correctly cacluated if it involves with negative values;

second is the axis rendering about the minimum number is exceeding the bounds like below:

When the axis comes to postive values, everything is fine; however when it is below zero, the y label can draw on out of the xAxis
![overlap](https://cloud.githubusercontent.com/assets/4375169/8391195/985aff78-1ceb-11e5-849d-4fd7bcd3ec1b.png)

**Comment by liuxuan30** [comment]
I have also fixed the issue the negative axis labels will be drawn out bound in https://github.com/liuxuan30/ios-charts/commit/be60addb94a3d95fa5de3af743f46b39ad474192

The interesting part is when the yAxis.entries contains negative values, the transformer will calculate a larger value than the viewPortHandler contentRect bound. I think the transformer is doing its job, just need to clip those labels that beyond the contentRect.

**Comment by danielgindi** [comment]
I'm actually not seeing the problem in your screenshot. You are really not clear about this

**Comment by liuxuan30** [comment]
Don't you see the first one, the radar chart, there is a small one not like others? and the distance between each inner web is not equal. Say the -100K should be the center, but -100 ~ 0 distance is not equal 0 ~ 100K

 - Can you try add some negative values on your side, so you can see it? I still believe there is defect while calculating the yAxis range for negative values.

Provide data here:
data set 0:
[ChartDataEntry, xIndex: 0, value -7501.574034, ChartDataEntry, xIndex: 1, value 73587.954072, ChartDataEntry, xIndex: 2, value 68861.089668, ChartDataEntry, xIndex: 3, value 79499.134258, ChartDataEntry, xIndex: 4, value 53615.304423]

data set 1:
[ChartDataEntry, xIndex: 0, value 35790.059533, ChartDataEntry, xIndex: 1, value 20118.91748, ChartDataEntry, xIndex: 2, value 42567.845168, ChartDataEntry, xIndex: 3, value 38749.916356, ChartDataEntry, xIndex: 4, value 13551.626137]

data set 2:
[ChartDataEntry, xIndex: 0, value 163400.659256, ChartDataEntry, xIndex: 1, value 187068.443587, ChartDataEntry, xIndex: 2, value 277395.375557, ChartDataEntry, xIndex: 3, value 133373.871463, ChartDataEntry, xIndex: 4, value 132363.776504]

Try this data
