### ISSUE TITLE
BarChartView work with TableView 

### ISSUE THREAD

**Issue by ramoslin02** [danielgindi/ios-charts#167]
if I use BarChartView with TableView， the tableView Can't scroll any more！ BarChartView can scale while the tableView can't scroll. How can I solve this problem?

**Comment by liuxuan30** [comment]
it sounds like the problem  is about the responder chain. Your bar chart becomes the first responder of pan gesture, so the table view cannot receive it. You may want to overide it and figure a way to trigger the table view to scroll?

**Comment by danielgindi** [comment]
You don't have to. The bar/line charts take care of that automatically.
When you are reaching the end of scrolling inside the chart, you can start
the gesture againand scroll the tableView.
Just if you are using CocoaPods, make sure you are taking last commit, not
the release version, as this is not in the release version yet.

‏בתאריך יום שישי, 19 ביוני 2015, Xuan <notifications@github.com> כתב:

**Comment by danielgindi** [comment]
See https://github.com/danielgindi/ios-charts/commit/90ef98ec64b96e032f8a4d71bd5e35018243fbe8

**Comment by ramoslin02** [comment]
@danielgindi  Thank you for your kindly answer.

**Comment by newbiebie** [comment]
I have the same problem
