### ISSUE TITLE
Unable to hide Y values

### ISSUE THREAD

**Issue by Navideck-fotis** [danielgindi/ios-charts#17]
I am implementing a Pie chart and I am unable to hide Y values.
I tried setting dataSet.drawValuesEnabled = NO but this hid both X and Y labels.
On the contrary I am able to hide X labels by [_chartView setDrawSliceTextEnabled:NO]

**Comment by PhilJay** [comment]
Try

```objc
[pieDataSet setDrawValues: NO];
```

**Comment by Navideck-fotis** [comment]
Only PieChartData declares the setDrawValues method. I tried it and it hides both X and Y.

**Comment by PhilJay** [comment]
Sorry, my bad. The field you need to set to `NO` is called "drawValuesEnabled", it's public.

**Comment by danielgindi** [comment]
There's a setter for "drawSliceTextEnabled" but I think that's for X values
>
>

**Comment by danielgindi** [comment]
@PhilJay Are we implementing a property to exclusively hide Y values?

**Comment by PhilJay** [comment]
Yes, this already exists in Andriod and can be done via calling `setDrawValues(...)` on any `DataSet` object.

**Comment by danielgindi** [comment]
I can confirm that this is indeed implemented and working. `setDrawValues` is used for toggling Y values in the code.

**Comment by danielgindi** [comment]
It is now fixed - there was a bug in the iOS version, that were fixed a few days ago in the Android version

**Comment by Navideck-fotis** [comment]
I confirm the fix. dataSet.drawValuesEnabled = NO; did the trick
