### ISSUE TITLE
Clearing all highlighted values

### ISSUE THREAD

**Issue by mcooksey** [danielgindi/ios-charts#171]
I am highlighting a value on my chart with a BalloonMarker when it is tapped, like what is done in the ChartsDemo application. 

Now, I need to remove a selection programmatically. I looked in the Android documentation and saw in "Interacting with the Chart" it says:

 highlightValues(Highlight[] highs): Highlights the values at the given indices in the given DataSets. Provide null or an empty array to undo all highlighting. 

However, this doesn't seem to be exposed to my object anywhere. Is this implemented? Any ideas how to accomplish this?

**Comment by danielgindi** [comment]
It actually is exposed, as `highlightValues` exactly, on every chart view.

**Comment by mcooksey** [comment]
@danielgindi I honestly have no idea how I missed that..

It's possible I was looking for that property on the data set, not the chart itself. 

Either way, sorry about that! Thanks for the help!

**Comment by danielgindi** [comment]
No problem! Have fun!

**Comment by carlosandresSanchez** [comment]
Is exposed highlightValues in Combined Chart View? It does not appear to me

**Comment by mcooksey** [comment]
@carlosandresSanchez yes it is. In my case, I'm using a CombinedChartView and have an instance of that class named chartView.

In order to clear all highlighted values, I had to do:

```objective-c
[self.chartView highlightValues:NULL];
```

Hope this helps!

**Comment by Visangle** [comment]
@mcooksey good! This helps me a lot!!

**Comment by kscheff** [comment]
in Version 3.0.2 I use a combinedChartView for different data sets. When switching over to a new data set I call 
`combinedChartView.initialize()
` 
However this misses out to clear previous highlights. I would expect that .initialize() provides me a clean chart with no left overs.

**Comment by augustocadini** [comment]
> @carlosandresSanchez yes it is. In my case, I'm using a CombinedChartView and have an instance of that class named chartView.
> 
> In order to clear all highlighted values, I had to do:
> 
> ```objc
> [self.chartView highlightValues:NULL];
> ```
> 
> Hope this helps!

This is no longer available, have another solution?
