### ISSUE TITLE
AddEntry issue in ChartData

### ISSUE THREAD

**Issue by wizzardchao** [danielgindi/ios-charts#173]
I find entriesForXIndex uses binary search for xIndex, which means the entries are ordered by xIndex.
But the addEntry method doesn't do extra to maintain the order, just append the new entry.

Thus, I'm wondering if it means the new added entry should have a larger xIndex which should be noticed by user?

**Comment by danielgindi** [comment]
Actually it is, but we should add extra checking to automatically insert in
the correct position. Thanks for the pointer
>
>

**Comment by danielgindi** [comment]
Well after further investigation, it looks like we may be supporting other kinds of charts where xIndexes has an additional dimension. It's a bit foggy right now. Specifically a case where lines will be drawn between values - in the xIndex order.

But I still think this is an important functionality, so it's definitely going to be a different function name.
