### ISSUE TITLE
Annotation label support?

### ISSUE THREAD

**Issue by simonhopkin** [danielgindi/ios-charts#175]
Hi, thanks for the work you have done here in porting this library from Android.  

Could you please let me know if its possible to add annotations to charts?  I want to add a label to the chart indicating the point at which some event occurred, for example if the chart is displaying heart rate bpm over time I would like to add a label to the chart indicating when the user started to exercise or sleep.

**Comment by liuxuan30** [comment]
do you mean `BalloonMarker`? It will pop up a small windows to let you display something.

**Comment by simonhopkin** [comment]
I don't think BaloonMarker is suitable as I want to show multiple events on
a chart.  I think only 1 marker is supported per chart?

**Comment by danielgindi** [comment]
Well the chart supports more than 1. By default, a TAP will unmark the previous highlights - but you could do whatever you like and there are public functions to set the current highlight or highlights.

*Anyway* you could use any marker view you want and put wherever you want over the chart view.

**Comment by 4np** [comment]
Hi Daniel,

I have been investigating exactly the same thing as Simon and I ended up having the same conclusion. Observe the following Line Chart (rendered using [HighCharts](http://www.highcharts.com/).

![screen shot 2016-01-27 at 5 33 09 pm](https://cloud.githubusercontent.com/assets/1049693/12620325/28ecc516-c51c-11e5-8778-16f60b76e84b.png)

You have a ```ChartMarker``` on the chart on the right that highlights the line point on touch. In addition there are ```Annotations``` in this chart represented by the speech bubbles. Those also support touch events. 

Right now, you can only define one type of ChartMarker for a Line Chart, e.g.

```
        let lineChartView = LineChartView(frame: myFrame)
        ...
        
        // configure marker
        lineChartView.marker = PAChartMarker()
```

I have tried using ```highlightValues``` to try to add in something like this even though that will render with the same ChartMarker as the on-touch highlight marker, but at least it was worth the try:

```
var highlights = [ChartHighlight]()
// some logic that determine where those three annotations need to show {
highlights.append(ChartHighlight(xIndex: xIndex, dataSetIndex: datasets.count))
// }
lineChartView.highlightValues(highlights)
```

However this fails as well. The logic in [ChartData.swift](https://github.com/danielgindi/ios-charts/blob/ff94c797fd236f9938274924c8326d9ab7606346/Charts/Classes/Data/Implementations/Standard/ChartData.swift#L435) seems to expect the ```_indicesToHighlight``` to have ```ChartHighlight``` instances for every ```xIndex```, or none.

Is there any way to get Annotations working like this?

Thanks for your reply! :)
