### ISSUE TITLE
Render Crash Due to Rect NAN from rectValueToPixel in BarChartRenderer.swift

### ISSUE THREAD

**Issue by mrossetti** [danielgindi/ios-charts#177]
I'd offer a fix for this but this is my very first look at ios-charts and I've only got about 20 minutes in on this project. With that said, the bug is exposed in the ChartsDemo using the Sinus Bar Chart but reducing the element count to 1 by dragging the control at the bottom of the chart as far to the left as possible.

BarChartRenderer.drawDataSet attempts to pixelize the rect to be drawn on line 124 by calling trans.rectValueToPixel(&barRect). When there is only one element to be drawn, barRect is (-0.3, 0.0, 0.6, 0.0) before the call and (nan, nan, nan, nan) after the call. Apparently, the affine transform performed in rectValueToPixel does not like something about the incoming rect. 

None of the other charts allow less than two elements to be presented so, without some additional futzing, I was unable to see if this bug is manifest for single-element bar charts.

(If I get time, I'll research further.)

**Comment by danielgindi** [comment]
Fixed! Thanks guys :-)
