### ISSUE TITLE
Last item's visibility issue when zooming

### ISSUE THREAD

**Issue by fiftycy** [danielgindi/ios-charts#18]
Hello. Am using the LineChartView and i have noticed that while zooming (pinch) the last value of the line is not shown. You can't even scroll to that value. What i do is am pinch zooming in and at a certain level of zooming i cant scroll to the last item value. The value is not visible in the screen except the line going to that value. 

Additionally, can i draw the line skipping the first and the last value as a result my line will not touching charts edges?

**Comment by danielgindi** [comment]
Thanks I'll look into it!
@PhilJay are you aware of such an issue?

**Comment by PhilJay** [comment]
I just tried in the example app and was unable to reproduce.
Could you describe your setup?

**Comment by danielgindi** [comment]
I found it! Fixed!

iOS: https://github.com/danielgindi/ios-charts/commit/48e8a994edb581c0cea18784b6f4a324626ce5f1
Android: https://github.com/PhilJay/MPAndroidChart/pull/544

**Comment by danielgindi** [comment]
It happend while zooming, but only in 1 frame out of ~20. It was a rounding issue. the X label's x is transformed through the matrix to pixel value, becomes `365.00000000006`, and the `contentRect` ends on `365`.

**Comment by fiftycy** [comment]
Yeah it was at very certain zoom level. I saw it very randomly !! keep up the good work
