### ISSUE TITLE
ChartData.removeEntryByXIndex removes the wrong entry

### ISSUE THREAD

**Issue by dorsoft** [danielgindi/ios-charts#182]
scenario: 
1. ChartData contains 1 dataset with 10 values (xIndex 0-9) 
2. Call ChartData.removeEntryByXIndex(xIndex:10, datasetIndex:0)
Expected result: no entry is removed and the method returns false
Actual result: the entry at xIndex 9 is removed, repeated method calls remove the last index (8,7,6...)

The fix:

public func removeEntryByXIndex(xIndex: Int, dataSetIndex: Int) -> Bool
 {
      if (dataSetIndex >= _dataSets.count)
      {
          return false
      }
    
 var entry = _dataSets[dataSetIndex].entryForXIndex(xIndex)
   
  if (entry?.xIndex != xIndex) {
      return false
  }

  return removeEntry(entry, dataSetIndex: dataSetIndex)
}

**Comment by danielgindi** [comment]
How exactly does constraining `dataSetIndex` solve this issue?... If at all, you would want to constrain the `xIndex`. But that is already done by check for the right `xIndex` in case that it does not exist and we got the closest one.

**Comment by dorsoft** [comment]
I've added:
if (entry?.xIndex != xIndex) {
return false
}

**Comment by dorsoft** [comment]
sorry for not mentioning it

**Comment by danielgindi** [comment]
@dorsoft Oh now it makes sense. But shouldn't you check for nil first?

**Comment by dorsoft** [comment]
you are right

if (entry == nil || entry?.xIndex != xIndex) {
return false
}

**Comment by danielgindi** [comment]
@dorsoft Actually - my bad! It's Swift. It will check the optional for you when using an `if`. Your previous post was correct :)

**Comment by danielgindi** [comment]
@dorsoft Do you want to open a PR? I'm not in front of Mac. Please format it according to the surrounding coding style and have a clean commit/PR :)

**Comment by dorsoft** [comment]
Done

**Comment by danielgindi** [comment]
SOl

**Comment by danielgindi** [comment]
https://github.com/danielgindi/ios-charts/pull/185
