### ISSUE TITLE
Having the area below a line graph be gradient layer instead of background color

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#186]
Is it possible to have the area underneath a line chart to be a gradient layer as opposed to just a solid color? We were also wondering if on a line chart if we could add a drop shadow below the line.  Thanks!

**Comment by danielgindi** [comment]
@BrandonShega Set the `backgroundColor` to `UIColor.transparentColor` and `opaque` to `false`

**Comment by BrandonShega** [comment]
But won't that just leave it entirely transparent rather than fading from a color to transparent?

**Comment by danielgindi** [comment]
@BrandonShega The background gradient is your job. You can even put your girlfriend's face there if you want. Put whatever you want behind the chart.

**Comment by BrandonShega** [comment]
No, no, I don't mean behind the chart, I just mean the area below the actual line graph. It's hard to explain here are some images that maybe will help.

Gradient Example:
![gradient](https://cloud.githubusercontent.com/assets/1090748/8485840/9d10b828-20ce-11e5-9a9a-9bf2c90b9baf.png)

Shadow Example:
![shadow](https://cloud.githubusercontent.com/assets/1090748/8485842/a0d8900c-20ce-11e5-89b9-bb35e137d29c.png)

**Comment by danielgindi** [comment]
@BrandonShega You mean the fill color. That's not supported yet, but it's planned.

**Comment by BrandonShega** [comment]
Ok great, thank you so much! Loving the library, I added drop shadow to the circles and lines for line graph, I'll have to make a pull request here some day.

**Comment by Halkyonbird** [comment]
Nice library, but really it would be cool to add fill color gradient support!

**Comment by IcyTexx** [comment]
It would be awesome if this got added.

**Comment by IcyTexx** [comment]
It would be awesome if this got added to the project.

**Comment by danielgindi** [comment]
Yes friends, this happened :-)

**Comment by rubenwardy** [comment]
For future readers, this is the fill property on LineDataSets (sorry for bumping, this is the only result I found)

Swift

```swift
datset.fill = ChartFill.fill(withColor: color.withAlphaComponent(0.8))
```

Objective C

```objectivec
dataset.fill = [ChartFill fillWithColor:[color colorWithAlphaComponent:0.8]];
```

**Comment by davigr** [comment]
How do you create gradient? I used approach below and it's not working. It's filling the whole view with gradient and nothing show

func setGradientBackground() {
        let colorTop =  UIColor(red: 255.0/255.0, green: 149.0/255.0, blue: 0.0/255.0, alpha: 1.0).cgColor
        let colorBottom = UIColor(red: 255.0/255.0, green: 94.0/255.0, blue: 58.0/255.0, alpha: 1.0).cgColor
        
        let gradientLayer = CAGradientLayer()
        gradientLayer.colors = [ colorTop, colorBottom]
        gradientLayer.locations = [ 0.0, 1.0]
        gradientLayer.frame = lineChartView.bounds
        
        lineChartView.layer.addSublayer(gradientLayer)
    }

**Comment by timotiuserick** [comment]
is it added yet ?
need it so much :(

**Comment by davigr** [comment]
@timotiuserick 
` //setting fill gradient color
        let coloTop = UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 0.8).cgColor
        let colorBottom = UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 0.1).cgColor
        let gradientColors = [coloTop, colorBottom] as CFArray // Colors of the gradient
        let colorLocations:[CGFloat] = [0.7, 0.0] // Positioning of the gradient
        let gradient = CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations) // Gradient Object
        lineChartDataSet.fill = Fill.fillWithLinearGradient(gradient!, angle: 90.0) // Set the Gradient
        lineChartDataSet.drawFilledEnabled = true // Draw the Gradient`

**Comment by timotiuserick** [comment]
@davigr wow Thank you so much!!

**Comment by abhiccc5** [comment]
let gradientColors = [UIColor(red: 141, green: 133, blue: 220, alpha: 0), UIColor(red: 230, green: 155, blue: 210, alpha: 0)] as CFArray // Colors of the gradient
        let colorLocations:[CGFloat] = [1.0, 0.0] // Positioning of the gradient
        let gradient = CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)
        line1.fill = Fill.fillWithLinearGradient(gradient!, angle: 90.0) // Set the Gradient
        line1.drawFilledEnabled = true /

this is not working!

**Comment by davigr** [comment]
Hey @abhiccc5 
Check it out my chart view with all configs
https://github.com/davigr/BLEDemo/blob/master/BLEDemo/Application/Details/RSSIChartView.swift

There are 2 methods that sets gradients 'getGradientFilling', 'setGradientBackground'

**Comment by abhiccc5** [comment]
// Setting fill gradient color
        let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 0.8).cgColor
        let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 0.1).cgColor
        // Colors of the gradient
        let gradientColors = [coloTop, colorBottom] as CFArray
        // Positioning of the gradient
        let colorLocations: [CGFloat] = [0.7, 0.0]
        // Gradient Object
let gradient = CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
        line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
        line1.drawFilledEnabled = true

Got it working correctly! Thanks to @davigr 👍

**Comment by Aanchal96** [comment]
@BrandonShega Hey! Can you please help me in adding the drop shadow under the line and circles as shown in the pictures you shared.

**Comment by abhiccc5** [comment]
Hey @Aanchal96 , use my code to set shadow under the line and circles:-

func setChart(dataPoints: [String], values: [Double]) {
        mChart.noDataText = "No data available!"
        for i in 0..<values.count {
            print("chart point : \(values[i])")
            let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(dataEntry)
        }
        let line1 = LineChartDataSet(values: dataEntries, label: "Units Consumed")
        line1.colors = [NSUIColor.blue]
        line1.mode = .cubicBezier
        line1.cubicIntensity = 0.2

        let gradient = getGradientFilling()
        line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
        line1.drawFilledEnabled = true

        let data = LineChartData()
        data.addDataSet(line1)
        mChart.data = data
        mChart.setScaleEnabled(false)
        mChart.animate(xAxisDuration: 1.5)
        mChart.drawGridBackgroundEnabled = false
        mChart.xAxis.drawAxisLineEnabled = false
        mChart.xAxis.drawGridLinesEnabled = false
        mChart.leftAxis.drawAxisLineEnabled = false
        mChart.leftAxis.drawGridLinesEnabled = false
        mChart.rightAxis.drawAxisLineEnabled = false
        mChart.rightAxis.drawGridLinesEnabled = false
        mChart.legend.enabled = false
        mChart.xAxis.enabled = false
        mChart.leftAxis.enabled = false
        mChart.rightAxis.enabled = false
        mChart.xAxis.drawLabelsEnabled = false
        
    }
  
 
    /// Creating gradient for filling space under the line chart
    private func getGradientFilling() -> CGGradient {
        // Setting fill gradient color
        let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 1).cgColor
        let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 1).cgColor
        // Colors of the gradient
        let gradientColors = [coloTop, colorBottom] as CFArray
        // Positioning of the gradient
        let colorLocations: [CGFloat] = [0.7, 0.0]
        // Gradient Object
        return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
    }

**Comment by abhiccc5** [comment]
Hey @Aanchal96 , use this code snippet to get shadow under lines and circles in your chart.

`func setChart(dataPoints: [String], values: [Double]) {
        mChart.noDataText = "No data available!"
        for i in 0..<values.count {
            print("chart point : \(values[i])")
            let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(dataEntry)
        }
        let line1 = LineChartDataSet(values: dataEntries, label: "Units Consumed")
        line1.colors = [NSUIColor.blue]
        line1.mode = .cubicBezier
        line1.cubicIntensity = 0.2

        let gradient = getGradientFilling()
        line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
        line1.drawFilledEnabled = true

        let data = LineChartData()
        data.addDataSet(line1)
        mChart.data = data
        mChart.setScaleEnabled(false)
        mChart.animate(xAxisDuration: 1.5)
        mChart.drawGridBackgroundEnabled = false
        mChart.xAxis.drawAxisLineEnabled = false
        mChart.xAxis.drawGridLinesEnabled = false
        mChart.leftAxis.drawAxisLineEnabled = false
        mChart.leftAxis.drawGridLinesEnabled = false
        mChart.rightAxis.drawAxisLineEnabled = false
        mChart.rightAxis.drawGridLinesEnabled = false
        mChart.legend.enabled = false
        mChart.xAxis.enabled = false
        mChart.leftAxis.enabled = false
        mChart.rightAxis.enabled = false
        mChart.xAxis.drawLabelsEnabled = false
        
    }
    
    func myinit(){
        progressBar.transform = progressBar.transform.scaledBy(x: 1, y: 3)
        
        mChart.noDataText = "No data available!"
        mChart.chartDescription?.text = "Energy Consumption"
        //yyyy-mm-dd
        getChartData(acct_id: "381201000", startDate: "2018-08-08", endDate: "2018-08-10")
        
    }
    
  
    
    /// Creating gradient for filling space under the line chart
    private func getGradientFilling() -> CGGradient {
        // Setting fill gradient color
        let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 1).cgColor
        let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 1).cgColor
        // Colors of the gradient
        let gradientColors = [coloTop, colorBottom] as CFArray
        // Positioning of the gradient
        let colorLocations: [CGFloat] = [0.7, 0.0]
        // Gradient Object
        return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
    }`

**Comment by abhiccc5** [comment]
Hey @Aanchal96 , use this code snippet to get shadow under the line and circles in your graph.

   `func setChart(dataPoints: [String], values: [Double]) {
        mChart.noDataText = "No data available!"
        for i in 0..<values.count {
            print("chart point : \(values[i])")
            let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(dataEntry)
        }
        let line1 = LineChartDataSet(values: dataEntries, label: "Units Consumed")
        line1.colors = [NSUIColor.blue]
        line1.mode = .cubicBezier
        line1.cubicIntensity = 0.2

        let gradient = getGradientFilling()
        line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
        line1.drawFilledEnabled = true

        let data = LineChartData()
        data.addDataSet(line1)
        mChart.data = data
        mChart.setScaleEnabled(false)
        mChart.animate(xAxisDuration: 1.5)
        mChart.drawGridBackgroundEnabled = false
        mChart.xAxis.drawAxisLineEnabled = false
        mChart.xAxis.drawGridLinesEnabled = false
        mChart.leftAxis.drawAxisLineEnabled = false
        mChart.leftAxis.drawGridLinesEnabled = false
        mChart.rightAxis.drawAxisLineEnabled = false
        mChart.rightAxis.drawGridLinesEnabled = false
        mChart.legend.enabled = false
        mChart.xAxis.enabled = false
        mChart.leftAxis.enabled = false
        mChart.rightAxis.enabled = false
        mChart.xAxis.drawLabelsEnabled = false
        
    }
   
    /// Creating gradient for filling space under the line chart
    private func getGradientFilling() -> CGGradient {
        // Setting fill gradient color
        let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 1).cgColor
        let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 1).cgColor
        // Colors of the gradient
        let gradientColors = [coloTop, colorBottom] as CFArray
        // Positioning of the gradient
        let colorLocations: [CGFloat] = [0.7, 0.0]
        // Gradient Object
        return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
    }`

**Comment by abhiccc5** [comment]
Hey @Aanchal96 , use this code snippet to get shadow under the line and circles in your graph.

```func setChart(dataPoints: [String], values: [Double]) {
mChart.noDataText = "No data available!"
for i in 0..<values.count {
print("chart point : (values[i])")
let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
dataEntries.append(dataEntry)
}
let line1 = LineChartDataSet(values: dataEntries, label: "Units Consumed")
line1.colors = [NSUIColor.blue]
line1.mode = .cubicBezier
line1.cubicIntensity = 0.2

    let gradient = getGradientFilling()
    line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
    line1.drawFilledEnabled = true

    let data = LineChartData()
    data.addDataSet(line1)
    mChart.data = data
    mChart.setScaleEnabled(false)
    mChart.animate(xAxisDuration: 1.5)
    mChart.drawGridBackgroundEnabled = false
    mChart.xAxis.drawAxisLineEnabled = false
    mChart.xAxis.drawGridLinesEnabled = false
    mChart.leftAxis.drawAxisLineEnabled = false
    mChart.leftAxis.drawGridLinesEnabled = false
    mChart.rightAxis.drawAxisLineEnabled = false
    mChart.rightAxis.drawGridLinesEnabled = false
    mChart.legend.enabled = false
    mChart.xAxis.enabled = false
    mChart.leftAxis.enabled = false
    mChart.rightAxis.enabled = false
    mChart.xAxis.drawLabelsEnabled = false
    
}

/// Creating gradient for filling space under the line chart
private func getGradientFilling() -> CGGradient {
    // Setting fill gradient color
    let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 1).cgColor
    let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 1).cgColor
    // Colors of the gradient
    let gradientColors = [coloTop, colorBottom] as CFArray
    // Positioning of the gradient
    let colorLocations: [CGFloat] = [0.7, 0.0]
    // Gradient Object
    return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
}```

**Comment by abhiccc5** [comment]
Hey @Aanchal96 , use this code snippet to get shadow under the line and circles in your graph.

```

func setChart(dataPoints: [String], values: [Double]) {
mChart.noDataText = "No data available!"
for i in 0..<values.count {
print("chart point : (values[i])")
let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
dataEntries.append(dataEntry)
}
let line1 = LineChartDataSet(values: dataEntries, label: "Units Consumed")
line1.colors = [NSUIColor.blue]
line1.mode = .cubicBezier
line1.cubicIntensity = 0.2

    let gradient = getGradientFilling()
    line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
    line1.drawFilledEnabled = true

    let data = LineChartData()
    data.addDataSet(line1)
    mChart.data = data
    mChart.setScaleEnabled(false)
    mChart.animate(xAxisDuration: 1.5)
    mChart.drawGridBackgroundEnabled = false
    mChart.xAxis.drawAxisLineEnabled = false
    mChart.xAxis.drawGridLinesEnabled = false
    mChart.leftAxis.drawAxisLineEnabled = false
    mChart.leftAxis.drawGridLinesEnabled = false
    mChart.rightAxis.drawAxisLineEnabled = false
    mChart.rightAxis.drawGridLinesEnabled = false
    mChart.legend.enabled = false
    mChart.xAxis.enabled = false
    mChart.leftAxis.enabled = false
    mChart.rightAxis.enabled = false
    mChart.xAxis.drawLabelsEnabled = false
    
}

/// Creating gradient for filling space under the line chart
private func getGradientFilling() -> CGGradient {
    // Setting fill gradient color
    let coloTop = UIColor(red: 141/255, green: 133/255, blue: 220/255, alpha: 1).cgColor
    let colorBottom = UIColor(red: 230/255, green: 155/255, blue: 210/255, alpha: 1).cgColor
    // Colors of the gradient
    let gradientColors = [coloTop, colorBottom] as CFArray
    // Positioning of the gradient
    let colorLocations: [CGFloat] = [0.7, 0.0]
    // Gradient Object
    return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
}

```

**Comment by cluelessoodles** [comment]
I have a line chart and have added a linear gradient fill below the line that goes from white to light purple using the suggested code in this post. The line chart view has a dark purple background color. It seems that my fill gradient is not opaque and instead is showing a semi-transparent over the purple background as evidenced here with the top of the line chart showing a shade of purple instead of white. Here's a photo - https://imgur.com/a/Khi3jqz

How can I make this gradient totally opaque?

Here's my code so far:
// Create Gradient for fill under the line
private func getGradientFilling() -> CGGradient {
    // Setting fill gradient
    let colorTop = UIColor.white.cgColor
    let colorBottom = UIColor.lightPlum.cgColor
    //Colors of the gradient
    let gradientColors = [colorTop, colorBottom] as CFArray
    // Positioning of the gradient
    let colorLocations: [CGFloat] = [0.5, 0.0]
    // Gradient Object
    return CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations)!
}

func setupChartView(values: [Double]) {
    chartView.noDataText = "No data available"
    for i in 0..<values.count {
        print("chart point : \(values[i])")
        let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
        dataEntries.append(dataEntry)
    }
    let line1 = LineChartDataSet(values: dataEntries, label: nil)
    line1.colors = [NSUIColor.white]
    line1.mode = .cubicBezier
    line1.drawCirclesEnabled = false
    line1.drawHorizontalHighlightIndicatorEnabled = false
    line1.drawVerticalHighlightIndicatorEnabled = false
    line1.cubicIntensity = 0.2
    line1.lineWidth = 2.0
    line1.valueTextColor = UIColor.white
    line1.valueFont = UIFont.systemFont(ofSize: 16.0)
    
    let gradient = getGradientFilling()
    line1.fill = Fill.fillWithLinearGradient(gradient, angle: 90.0)
    line1.drawFilledEnabled = true
    
    let data = LineChartData()
    data.addDataSet(line1)
    chartView.data = data
    chartView.setScaleEnabled(false)
    chartView.drawGridBackgroundEnabled = false
    chartView.legend.enabled = false
    chartView.minOffset = 0
    chartView.backgroundColor = UIColor.plum
    chartView.isOpaque = true
  
    chartView.xAxis.drawAxisLineEnabled = false
    chartView.xAxis.gridColor = #colorLiteral(red: 0.7215686275, green: 0.5764705882, blue: 0.7568627451, alpha: 1)
    chartView.xAxis.gridLineWidth = 0.75
    chartView.xAxis.drawGridLinesEnabled = true
    chartView.xAxis.granularity = 1.5
    chartView.xAxis.enabled = true
    chartView.xAxis.drawLabelsEnabled = false
    
    chartView.leftAxis.drawAxisLineEnabled = false
    chartView.leftAxis.drawGridLinesEnabled = false
    chartView.leftAxis.enabled = false
    
    chartView.rightAxis.drawAxisLineEnabled = false
    chartView.rightAxis.drawGridLinesEnabled = false
    chartView.rightAxis.enabled = false
}

**Comment by cerupcat** [comment]
@abhishekgautam101 is this supposed to create a drop shadow? I copied your code but it justs created a basic gradient - not a drop shadow. Are drop shadows supported?

**Comment by pradweep** [comment]
@danielgindi Hi daniel I need some help regarding the filling gradient color for the linecharts. I am struggling hard to how to fill gradient colors for the different data sets as shown in the below screenshot. Can you please provide me the resolution asap.
![Screenshot 2020-05-30 at 10 03 21 PM](https://user-images.githubusercontent.com/29473144/83334077-a9d64080-a2c1-11ea-84fd-ca52d96815ac.png)

**Comment by dattatrayParthenon** [comment]
@pradweep you got any solution to your problem?
