### ISSUE TITLE
Highlight multiple values

### ISSUE THREAD

**Issue by mpullman** [danielgindi/ios-charts#187]
Would it be possible to be able to highlight more than one value and have the delegate return an array of highlighted values?

**Comment by liuxuan30** [comment]
I have done this for radar chart. Highlight all values for the same xIndex. you have do the customization yourself, as I don't think there is a plan to add this feature recently?

**Comment by mpullman** [comment]
OK thanks, thought someone else might have already looked into it. Will take a look myself.
