### ISSUE TITLE
Library not loaded: @rpath/Charts.framework/Charts

### ISSUE THREAD

**Issue by carlosandresSanchez** [danielgindi/ios-charts#196]
Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/mobile/Containers/Bundle/Application/D054D8D8-EF3A-41E6-8861-59CB7D26E8E4/Weex.app/Weex
  Reason: image not found
  Dyld Version: 353.12

**Comment by danielgindi** [comment]
You should follow the instructions in the README carefully.
