### ISSUE TITLE
Don't draw zero value label

### ISSUE THREAD

**Issue by liebeskind** [danielgindi/ios-charts#197]
Any know a way to not draw the value labels that are 'zero' in a horizontal bar graph?

**Comment by danielgindi** [comment]
`NSNumberFormatter` is a very strong factory.

**Comment by danielgindi** [comment]
Meaning you can set `zeroSymbol` to `""`, which by default is `"0"`
https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSNumberFormatter_Class/index.html#//apple_ref/occ/instp/NSNumberFormatter/zeroSymbol

*Or*, make a subclass of `NSNumberFormatter`, and format the numbers however you like.

**Comment by liebeskind** [comment]
Brilliant!  That worked.  Thanks Daniel.  For others that are interested in doing something similar, here is my fairly simple NSNumberFormatter subclass.

    class NoStyleFormatter: NSNumberFormatter {
        required init(coder aDecoder: NSCoder) {
            super.init(coder: aDecoder)
        }
    
        override init() {
            super.init()
            self.numberStyle = .NoStyle
            self.zeroSymbol = ""
        }
    
        // Swift 1.2 or above
        static let sharedInstance = NoStyleFormatter()
    }

**Comment by danielgindi** [comment]
Man that's over-complex.
Just do:
```
var noZeroFormatter = NSNumberFormatter()
noZeroFormatter.zeroSymbol = ""
```

**Comment by danielgindi** [comment]
You can subclass - but for changes that you don't have properties for. Luckily you have properties for anything you can dream about...
