### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by sureshkw** [danielgindi/ios-charts#2]
Hi,

Firstly great initiative.  I've been looking for a good charting library for sometime now. Highly appreciated. I tried testing this today and getting the above error. I'm trying this in Xcode Version 6.3 (6D520o). 

It is happening at two files in the library. I'm posting the final error message for both of them 

```
While emitting IR SIL function @_TFC6Charts21CombinedChartRenderer15createRenderersfS0_FT_T_ for 'createRenderers' at /ios-charts/Charts/Classes/Renderers/CombinedChartRenderer.swift:50:14

While emitting IR SIL function @_TFC6Charts19ChartLegendRenderer12renderLegendfS0_FT7contextCSo9CGContext6legendGSQCS_11ChartLegend__T_ for 'renderLegend' at /ios-charts/Charts/Classes/Renderers/ChartLegendRenderer.swift:104:12

```

Can you let me know how to get rid of those ?

Tried : 

1. When I comment out the switch cases in the respective functions (createRenderers, renderLegend) it compiles fine. Although I hardly think it's a solution.

**Comment by PhilJay** [comment]
I tried applying a quick fix.
I think it has something to do with using the `?` instead of the `!`.

In case it doesn't work now, try avoiding the `?` whenever possible.

**Comment by sureshkw** [comment]
Thank you PhilJay.

**Comment by danielgindi** [comment]
Well actually sometimes the '?' is necessary if you want to avoid a 'nil' check, as '!' unwraps and assumes there's a value, but the '?' is an optional.

For me of course it compiled well, but Xcode currently crashes sometimes during compilation of Swift, which is what you are experiencing.
It is expected to be fixed when Swift 1.2 is final... 
I hope so at least.

**Comment by danielgindi** [comment]
I'm training currently but will try to reproduce the crash when I come back. The iPhone can't run Xcode... yet

**Comment by danielgindi** [comment]
Compilations seem to pass through fine in latest Xcode with Phil's fix
