### ISSUE TITLE
Charts stuttering when reloaded

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#201]
Hello,

So I don't know if I'm just doing this wrong or what but I can not figure this out.  I had a quick question though is there a method for the iOS version like the Android `invalidate()`? 

Anyways, the problem I am running into is I have 8 cells in a collection view with a chart in every one, and I have tried everything under the sun to get the chart to not stutter.

These are the scenarios I have seen:
The chart still has the data when it is made, so it flashes on the screen and then animates.
The chart has another cell's old chart and then flashes on the screen before the new one animates.

Is there a way to just have the graph redraw with new data without having the chart just drawn first and then animated? I have tried hiding the chart and then displaying right before animation but it seems like it is already drawn and then animates, causing it to look like it is stuttering.

Thanks!

**Comment by danielgindi** [comment]
Have you tried `setNeedsDisplay`?

**Comment by BrandonShega** [comment]
Do I do this when I change the data or before the graph is drawn?

**Comment by BrandonShega** [comment]
If I override `prepareForReuse` in the cell, is it possible to wipe out all data for the graph or something like that?
