### ISSUE TITLE
Issue while displaying the chart (HorizontalBarChartView)

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#202]
I am trying to implement chart functionality using iOS-charts. 
I tried with the ChartsDemo example. It compiled successfully. and could run it on device too.

I followed all the steps from README file. 
I repeated it number of times in last 3 days. But I am still struggling with the integration. 
I am not getting if I am missing something while integration.

After errorless integration I am getting console log as "Unknown class HorizontalBarChartView in Interface Builder file."

I created single view application using Xcode 6.4
Following are some of the screenshots of my Xcode. Please help me with the successful integration.

![screen shot 2015-07-10 at 5 10 55 pm](https://cloud.githubusercontent.com/assets/3005149/8617975/01b2c092-2727-11e5-91f3-6e65019c37bc.png)

![screen shot 2015-07-10 at 5 14 01 pm](https://cloud.githubusercontent.com/assets/3005149/8618050/d5c79948-2727-11e5-90e5-b48945c6061b.png)

![screen shot 2015-07-10 at 5 14 34 pm](https://cloud.githubusercontent.com/assets/3005149/8618051/d87203cc-2727-11e5-95dc-eadd5e0aa62f.png)

In GraphViewController I have copied and used code from HorizontalBarChartViewController.h and .m 
as it is.

![screen shot 2015-07-10 at 5 15 00 pm](https://cloud.githubusercontent.com/assets/3005149/8618053/e03ea3b2-2727-11e5-979d-b64e9d1761b0.png)

![screen shot 2015-07-10 at 5 16 16 pm](https://cloud.githubusercontent.com/assets/3005149/8618054/e2ffae70-2727-11e5-98c8-8d4c2426258e.png)

**Comment by wganeshb** [comment]
This is first time I am asking question on github. I don't know how to use github for communication. please forgive me if it is irrelevant.

**Comment by wganeshb** [comment]
This is first time I am asking question on github. I don't know how to use github for communication. Please forgive me if the question is irrelevant.

**Comment by Bautistax** [comment]
the compiler doesn't know where is HorizontalBarChartView because you changed the name from the original class name "HorizontalBarChartView" to "GraphViewController"
And make sure the class name is defined on one of the ViewController as GraphViewController

**Comment by wganeshb** [comment]
@Bautistax Thanks.
Actually I haven't changed the class name from "HorizontalBarChartView" to "GraphViewController". The pointer to "HorizontalBarChartView" is "chartView" and it is declared as property inside class "GraphViewController".

**Comment by danielgindi** [comment]
Try Charts.HorizontalBarChartView

**Comment by wganeshb** [comment]
@danielgindi Thanks.

Sorry But I didn't get the you. how to use Charts.HorizontalBarChartView. Can you please elaborate it

**Comment by danielgindi** [comment]
@wganeshb You're missing the namespace

**Comment by liuxuan30** [comment]
1. check build settings for embed content contains swift code, define module, and make sure your module name is correct.
2. I think you add wrong @import for swift to Objective-C. There should be no bridging header file, instead, it looks like "{module name}-Swift.h", BY default (you can check it in swift compiler - code generation). the bridging header file is for swift to import Objective-C code, BY default.
3. the Objective-C generated interface header file is  generated by Xcode automatically. Once you can compile and import it, you should be able to use swift class.

**Comment by wganeshb** [comment]
@liuxuan30 Thanks, You are right. now I changed the import to "DemoCharts-Swift.h". The build is successful without error. But still I am getting log as "Unknown class HorizontalBarChartView in Interface Builder file."

**Comment by danielgindi** [comment]
I've already said that you are missing a namespace. The charts are namespaced under Charts.

**Comment by wganeshb** [comment]
@danielgindi Thanks,  now it is not not giving any error or console log. 

But somehow not showing the output. 
I am only trying HorizontalBarChartView for now. 

I cross checked all the connections and still working on if I am missing anything. 

Thanks.. :smile:

**Comment by wganeshb** [comment]
Thanks a lot for this great chart library. 
This is the most interactive and good looking chart library for the iOS platform. Giving me the what exactly I was looking for. :smile: 

I tried to integrate this library almost for the 4 days in my objectiveC project. But every time missing something. Sorry for the trouble.

@danielgindi already mentioned the usage steps in readme file. they are pretty straight forward. I read them again and again and again made the same mistakes. Finally successfully integrated the Charts in ObjectiveC project. 

I would like to share the steps again that I went through. 
Steps -
1) Create single view app with language ObjectiveC.
2) Go to, PROJECT -> Build Settings -> 
     Search the term packaging. Under packaging select Defines Module to YES. As shown below.
![screen shot 2015-07-15 at 6 40 51 pm](https://cloud.githubusercontent.com/assets/3005149/8699194/6c22c80c-2b21-11e5-85cf-5578ddee0b51.png)

3) Go to, TARGETS -> Build Settings -> 
    Search the term packaging. Under packaging set 'Product Module Name' and 'Product Name' to    
    project name. In this case Testing. As shown below.
![screen shot 2015-07-15 at 6 51 05 pm](https://cloud.githubusercontent.com/assets/3005149/8699337/7d58d11a-2b22-11e5-88b9-a763ddee8f49.png)

4) Go to, TARGETS -> Build Settings -> 
    Search the term Embedded. Under 'Build Options' set 'Embedded Content Contains Swift Code' to 
    YES. As shown below.

![screen shot 2015-07-15 at 7 05 36 pm](https://cloud.githubusercontent.com/assets/3005149/8699636/900cb072-2b24-11e5-9c04-888c2b039d98.png)

5) Add new swift file to project with same name as project target name or project name. Here in this case 'Testing' As shown below.
![screen shot 2015-07-15 at 6 52 42 pm](https://cloud.githubusercontent.com/assets/3005149/8699781/8d854840-2b25-11e5-9af8-9ea633a0955d.png)

  On file create Xcode will Show popup as shown below. Select YES. It will create the bridging header files for project.
![screen shot 2015-07-15 at 7 19 59 pm](https://cloud.githubusercontent.com/assets/3005149/8699941/a1d0fe88-2b26-11e5-98c0-96c4cf5f1f67.png)

6) Add all file and folder from Charts folder to the Projects root file. 
![screen shot 2015-07-15 at 7 25 04 pm](https://cloud.githubusercontent.com/assets/3005149/8700068/63229a92-2b27-11e5-85d1-13fb62ee71ad.png)

7) Add copied Charts.xcodeproj to project using option 'Add files to project_name' As shown below.
![screen shot 2015-07-15 at 7 26 59 pm](https://cloud.githubusercontent.com/assets/3005149/8700178/0e87407c-2b28-11e5-85a0-84dd40922c9a.png)

On adding the Xcode will look like below screen shot.
![screen shot 2015-07-15 at 7 32 25 pm](https://cloud.githubusercontent.com/assets/3005149/8700269/70b6d1ae-2b28-11e5-8228-7ca598272796.png)

8) Go to, TARGETS -> General
    Press + under the option 'Embedded binaries'. Select Charts.framework. Add it to the project.
    As shown.
![screen shot 2015-07-15 at 7 34 51 pm](https://cloud.githubusercontent.com/assets/3005149/8700362/017d1fd6-2b29-11e5-9491-7ba32e860e06.png)

These are some of the mandatory steps. In order to avoid the 'File not found' like other compile time errors.

Follow the objectiveC example Demos provided by the @danielgindi, the project owner. These demos are really best example covering all the charts.

Thank you once again. :+1:
