### ISSUE TITLE
Array index out of range when removing entries from DataSet

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#203]
Is there a specific reason why I am getting `fatal error: Array index out of range:` with this code?

```objc
for (int i = 0; i < [self.currentBarChartDataSet entryCount]; i++) {
        
        [self.currentBarChartDataSet removeEntryWithXIndex:i];
//        [self.pastBarChartDataSet removeEntryWithXIndex:i];
        
}
```

I'm basically trying to remove all data from the bar chart in `prepareForReuse` in a `UICollectionViewCell` so that the chart isn't visible when the collection view is reloaded.

If I log the count, it is 7 and the loop is running 7 times.

**Comment by BrandonShega** [comment]
Ok I changed my code to this because I realized what I was doing wrong before, but it's still crashing with the same error

```objc
    NSInteger count = [self.currentBarChartDataSet entryCount];
    
    for (int i = 0; i < count; i++) {
        
        [self.currentBarChartDataSet removeEntryWithXIndex:0];
//        [self.pastBarChartDataSet removeEntryWithXIndex:i];
        
    }
```

**Comment by BrandonShega** [comment]
It's crashing on this line #395 in ChartDataSet.swift
`calcMinMax(start: _lastStart, end: _lastEnd)`

**Comment by danielgindi** [comment]
Call notifyDataSetChanged() after done changing the data

**Comment by BrandonShega** [comment]
It doesn't even let me get that far, it's crashing before it even moves over the line where the entry is removed.
