### ISSUE TITLE
Can I use this library in an objective-c project targeting iOS 7 & 8?

### ISSUE THREAD

**Issue by xdf103** [danielgindi/ios-charts#206]
I really like this project. Can I use this library in an objective-c project targeting iOS 7 & 8? If yes, how to set it up? I am using Xcode 6.3.2 

Regards,
Frank

**Comment by liuxuan30** [comment]
yes you can. read README

**Comment by xdf103** [comment]
I drag all the swift files to the project. When I compile, there are many Swift Compiler Error, e.g. "Use of unresolved identifier CGFloat", "Use of undeclared type UIColor". Is there anything else that I need to do after dragging the swift files?

**Comment by liuxuan30** [comment]
I have met this too. Check if you miss `import UIKit` Sometimes @danielgindi forget to add it.

Paste code will help.

**Comment by kscorpio** [comment]
i compile chartsdemo with device 5s ios 7.1 ,it remind: need a recent enough viersion of ios

when i compile in simulator ios 8.1 ,proterty 'shadowColorSameAsCandle ' not found on object of type 'CandlerChartDataSet * '

**Comment by kscorpio** [comment]
if the demo in release 2.1 does not support ios 7.1?

**Comment by kscorpio** [comment]
i changed the target 8.0 to 7.0 
Desktop/ios-charts-master/ChartsDemo/Classes/Components/BalloonMarker.swift:16:8: Module file's minimum deployment target is ios8.0 v8.0: 

Library/Developer/Xcode/DerivedData/ChartsDemo-hgbdlbkgurqiigcqlbovqsnignai/Build/Products/Debug-iphonesimulator/Charts.framework/Modules/Charts.swiftmodule/x86_64.swiftmodule

Is this means the library doesn't support 7.1??

**Comment by liuxuan30** [comment]
It supports iOS 7, but you only need the swift files if it is based on 7.0. 

For iOS 8, you can use the binary framework, swift files is not a must.

Again, read README and #108, it explains well I think.

**Comment by xdf103** [comment]
Thanks @liuxuan30 ! It works for iOS7.0 after I added "import UIKit" to all the swift files.

**Comment by liuxuan30** [comment]
@xdf103 you are welcome. However, you should not add `import UIKit` for every file I think... only a few are missing.

**Comment by liuxuan30** [comment]
close this if you no longer have such issue.
