### ISSUE TITLE
Horizontal bar chart in combined bar chart.

### ISSUE THREAD

**Issue by codeHatcher** [danielgindi/ios-charts#210]
I looked in the docs as well as the MPAndroid Stackoverflow but couldn't find it. Is there a way to add a horizontal bar chart to a combined chart? I see a way to add a vertical bar chart only.

**Comment by liuxuan30** [comment]
I don't think it makes sense for a combined chart to have a honrizontal bar chart... the xAxis and yAxis totally reversed. What information do you want to send for such a chart?

**Comment by codeHatcher** [comment]
I'm interested in a horizontal bar chart with a horizontal line chart actually.
Is there a way to render a chart and then just rotate the whole thing?

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Mon, Jul 13, 2015 at 8:59 PM, Xuan <notifications@github.com> wrote:
I don't think it makes sense for a combined chart to have a honrizontal bar
chart... the xAxis and yAxis totally reversed. What information do you want to
send for such a chart?

—
Reply to this email directly or view it on GitHub
[https://github.com/danielgindi/ios-charts/issues/210#issuecomment-121102319] .[https://github.com/notifications/beacon/AFHNVsOkzZX1QtweqkWw2x-74blzdEm5ks5odFZkgaJpZM4FXoEn.gif]

**Comment by liuxuan30** [comment]
Well I don't think current scheme supports this. However, a 'honrizontal line chart' is harder to understand, right? I don't see such a chart in real life. 

Technically, it is possible to do so. I think once #194 is carried out, it can achieve your goals much easier. #194 will no longer distinguish xAxis and yAxis rendering logic, they share the same math to render. Currently, xAxis is using xIndex, which means the distance is equal on xAxis.

If you just want to rotate the whole chart, that's quite easy. However, the labels will also be rotated, you have to take care of them. You have to understand how the transformer and the CTM works, then you are good to go.

**Comment by codeHatcher** [comment]
Thanks for your help, I found another library I think I can use but if that doesn't work I think rotating the whole chart should be just fine for now.

**Comment by liuxuan30** [comment]
do you mind share what's the library?
