### ISSUE TITLE
[BUG]negative values rendering +highlight rect rendering not correct for stacked bar + stacked horizontal bar chart

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#212]
It looks like if the dataSet contains negative values for stacked bar + stacked horizontal bar chart, it cannot render correctly.

It's very easy to reproduce, just change the values inside the demo to negative.

I am not sure if you are aware of this, either we need to define how to render and highlight the stacked bar chart + stacked horizontal bar chart for negative values.
![negabarbug](https://cloud.githubusercontent.com/assets/4375169/8669146/91739fa6-2a44-11e5-8c68-5056de50059c.png)

**Comment by danielgindi** [comment]
What version are you using? Because we fixed that already

**Comment by liuxuan30** [comment]
I believe it's the latest code? I just sync yesterday.

**Comment by liuxuan30** [comment]
are you saying https://github.com/danielgindi/ios-charts/commit/ade153a54aa2fe20e2bba0f62df5952ad74019fc?
If that is the case, then I think it is not fixed... at least for pure negative values. The rendering and highlight both go wrong.
