### ISSUE TITLE
Crash on device - iOS 8.3

### ISSUE THREAD

**Issue by carrchr** [danielgindi/ios-charts#216]
Just updated our fork of ios-charts with the latest commits to master and we're experiencing a crash when running on a device with iOS 8.3 or iOS 8.4
Does not occur on 8.2 or on iOS 8.4 Simulator
Getting an `EXC_BAD_ACCESS` consistently with Xcode breaking at line 21 in `LineRadarChartDataSet.swift`

![screen shot 2015-07-15 at 11 44 46 am](https://cloud.githubusercontent.com/assets/1752939/8703339/83c24ad2-2aea-11e5-9d28-d066f19acbd3.png)

```
public class LineRadarChartDataSet: BarLineScatterCandleChartDataSet
{
    public var fillColor = UIColor(red: 140.0/255.0, green: 234.0/255.0, blue: 255.0/255.0, alpha: 1.0)
    public var fillAlpha = CGFloat(0.33)   //  <--- CRASH HERE??  -->
    private var _lineWidth = CGFloat(1.0)
    public var drawFilledEnabled = false
    
    /// line width of the chart (min = 0.2, max = 10)
    /// :default: 1
    public var lineWidth: CGFloat
    {
```

Moving up the stack trace to my code Xcode claims to be here:
![screen shot 2015-07-15 at 11 46 39 am](https://cloud.githubusercontent.com/assets/1752939/8703417/f9d1dd6e-2aea-11e5-91e6-e41562fc670a.png)
![screen shot 2015-07-15 at 12 15 32 pm](https://cloud.githubusercontent.com/assets/1752939/8703469/3c7d6a3e-2aeb-11e5-91d6-06c3b873f540.png)

I've run the ChartDemo project and it appears fine.

**Comment by carrchr** [comment]
I realize that our modifications could somehow be causing this crash, since the Demo project still appears to work fine but the fact that it does not crash on iOS 8.2 makes me wonder if it is a Swift bug...

**Comment by danielgindi** [comment]
There's no reason to crash there. You could be using a Beta version of
Xcode,
Or just need to make a Clean Build.

**Comment by carrchr** [comment]
Using Xcode 6.4 (6E35b) on Mac OS X 10.10.4
However, doing a full Clean Build (including deleting the Derived Data folder,) has gotten rid of the crash. Oh, Swift....

**Comment by liuxuan30** [comment]
I have met crash after init().. clean build also helps.
