### ISSUE TITLE
Prebuilt Frameworks & Tagged Releases

### ISSUE THREAD

**Issue by msanders** [danielgindi/ios-charts#217]
It would be nice if ios-charts had prebuilt frameworks attached to each GitHub release. This would [speed up building](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) via Carthage by quite a bit, since it automatically downloads those if they exist instead of building from scratch each time. Right now ios-charts is the lengthiest part of our build process; this would shave off a few minutes and would be much appreciated. Shouldn't be too hard to do manually, but can also be done automatically via Travis's [tagged releases](http://docs.travis-ci.com/user/deployment/releases/). Thanks again for the great library!

**Comment by danielgindi** [comment]
Actually I'm not sure if it is possible for Swift frameworks, as those frameworks are limited already (cannot be embedded in pre iOS-8). 
But I will look into it!

**Comment by msanders** [comment]
Carthage is only supported for iOS 8 and above, so that shouldn't be an issue. For iOS 7, files can still be dragged in (presumably as a submodule). Carthage itself includes a framework written in Swift, so you can see an example of it [here](https://github.com/Carthage/Carthage/releases).

**Comment by msanders** [comment]
Also see: [Quick](https://github.com/Quick/Quick/releases) & [Nimble](https://github.com/Quick/Nimble/releases)

**Comment by danielgindi** [comment]
So, basically all we need is to build the framework binaries, pack them in `Charts.framework.zip` and attach to a release, and then you and Carthage are happy? :-)

**Comment by danielgindi** [comment]
Ok so I've tried - but Xcode does not have an option for archiving frameworks the way Carthage wants. It can only build it as part of a greater project, and I really don't intend to go and pick up the binaries manually after compiling for each combination...

**Comment by petester42** [comment]
Carthage can spit out a zip file for you. Its fairly simple `carthage archive` I believe. I could look into it sometime. I am mainly using carthage right now.

**Comment by petester42** [comment]
This can be achieved by running `carthage build --no-skip-current && carthage archive Charts`

**Comment by danielgindi** [comment]
Note that I've built the `2.1.4a` binaries into the `2.1.4` release, since Carthage does not support letters after version numbers.
