### ISSUE TITLE
Is there guidance to beginner to use this?

### ISSUE THREAD

**Issue by sicaboy** [danielgindi/ios-charts#220]
Is there guidance for beginner to use this?

Could anybody do a pod repository for it so it can be loaded via pod.

Another request is could you write a How To Use for swift developers?

**Comment by sicaboy** [comment]
I searched pod,
-> ios-charts (0.0.1)
   Charts library for iOS
   pod 'ios-charts', '~> 0.0.1'
   - Homepage: https://github.com/egymgmbh/ios-charts
   - Source:   https://github.com/egymgmbh/ios-charts.git
   - Versions: 0.0.1 [master repo]

But however it should be the same with this repository

**Comment by liuxuan30** [comment]
perhaps long time no sync. why don't you use github's version?

For swift developers, the chart library is already in swift. It's easy for swift people to understand I think. Though the demo is in Objective-C. But a language is not an obstacle for you to read and understand.

**Comment by danielgindi** [comment]
1. There's the demo
2. Just read
3. The repo under "egymgmbh" is an old fork, not synced. Use the main repo. The pod points to the main repo.
