### ISSUE TITLE
How to setup up y-axis with min, max value and a fixed step between the grid lines?

### ISSUE THREAD

**Issue by SvenMuc** [danielgindi/ios-charts#227]
Hi,
I'm just in the learning phase of using ios-charts. I like to change the x-axis grid to fixed values.
My plotted y-values are just int numbers like 1, 2, 3,..., 10. Nevertheless the left y-axis shows values like 6.3, 9.1, etc., depending on my zoom level.
The second question is, how to setup the x-axis in order to show the labels 1,5,10,15,....40?

Is there any way to influence the step size like e.g. in Excel?

```swift
// zoom y-axis to min/max value
lineChart.leftAxis.customAxisMin = max(0.0, lineChart.data!.yMin - 1.0)
lineChart.leftAxis.customAxisMax = min(10.0, lineChart.data!.yMax + 1.0)
lineChart.leftAxis.startAtZeroEnabled = false
```

**Chart (min = 6.0 and max = 10.0):**
![linechartview](https://cloud.githubusercontent.com/assets/13385716/8755816/fb4f30e4-2ccd-11e5-990d-abd6fb7ecd3c.png)

The arrangement strongly depends on the min and max value.

**Chart (min = 3.0 and max = 10.0):**
![bildschirmfoto 2015-07-17 um 22 13 16](https://cloud.githubusercontent.com/assets/13385716/8756271/5855653a-2cd1-11e5-85de-b8799a07b8e4.png)

Thanks for your support.

**Comment by SvenMuc** [comment]
I identified that something goes wrong in the function `internal func computeAxisValues(#min: Double, max: Double)` in the class `ChartYAxisRenderer`. But I do not understand the source code. The function is called 5 times. 

What are the following lines exactly doing?
```swift
var rawInterval = range / Double(labelCount)
var interval = ChartUtils.roundToNextSignificant(number: Double(rawInterval))
var intervalMagnitude = pow(10.0, round(log10(interval)))
var intervalSigDigit = (interval / intervalMagnitude)
```

**Comment by danielgindi** [comment]
You can specify `customAxisMin`/`customAxisMax` to whatever values you want

**Comment by SvenMuc** [comment]
What do you mean with whatever values you want? Are these values ignored?

**Comment by danielgindi** [comment]
It means that you specify the minimum/maximum for the Y axis like you want. I'm kind of short on time right now but I wanted to give you an answer anyway, so you should just look at the axis features, or look at the demos :-)

**Comment by danielgindi** [comment]
If I have the time later I'll try to give you a more detailed answer

**Comment by SvenMuc** [comment]
Hi,
I solved the issue by analysing your source code. I forgot to set the `labelCount`.

```swift
            lineChart.leftAxis.customAxisMin = max(0.0, lineChart.data!.yMin - 1.0)
            lineChart.leftAxis.customAxisMax = min(10.0, lineChart.data!.yMax + 1.0)
            lineChart.leftAxis.labelCount = Int(lineChart.leftAxis.customAxisMax - lineChart.leftAxis.customAxisMin)
            lineChart.leftAxis.startAtZeroEnabled = false
```

**Comment by ramkrishna880** [comment]
My issue is that few cases y axis labels are not showing. (for bar and line graphs)

please help me to resolve this.

**Comment by sheetal-hemrom** [comment]
@ramkrishna880 setLabelsToSkip(0) in your Axis

**Comment by pranavBiz2Credit** [comment]
@danielgindi cant seem to access `customAxisMin`/`customAxisMax`for combined charts. Is there a way to fixate on the maximum and minimum values for Y-axis in Combined Chart?

**Comment by pranavBiz2Credit** [comment]
Hi again never mind figured this out.. 

`axisMaximum`/`axisMinimum` did the trick. 

Such a marvellous plugin. You have no idea how easy you guys have made life for us developers.

**A Massive Thank you!!**

**Comment by haozhouxu** [comment]
you can set axis : MinValue="0" in xaml
![image](https://user-images.githubusercontent.com/10582221/42807570-c1d28caa-89e3-11e8-9065-d15455150104.png)

**Comment by AwaisFayyaz** [comment]
Hi, Can any body tell me how to specify fixed intervals for y axis. I am using positive negative bar chart. 
charts 3.1.1

like 1.1, 1.3, 1.5 in the attached image

Thanks
![how to intervals](https://user-images.githubusercontent.com/11820112/45999367-e4d0ab80-c0be-11e8-8085-e68e135b2c4f.png)

**Comment by dawson86** [comment]
> You can specify `customAxisMin`/`customAxisMax` to whatever values you want

Hi Daniel will these properties also work for Bar chart?

**Comment by jayrawat** [comment]
@pranavBiz2Credit can you provide code for how you set max, min & no of labels in combined chart by using axisMaximum/axisMinimum? I need to not use automatic calculation & set no of labels based on data set
