### ISSUE TITLE
ChartYAxis valueFormatter NSFormatter instead of NSNumberFormatter

### ISSUE THREAD

**Issue by eliotfowler** [danielgindi/ios-charts#228]
Once you have the data you need to place the y-axis labels on the line in order, why do you need the value formatter be a NSNumberFormatter as opposed to just a NSFormatter. The reason I ask is I'm trying to plot times and I'd like to be able to show it in MM:SS format instead of minute.fraction format.

The same could be true with the labels placed above/below the data points.

**Comment by danielgindi** [comment]
Y values are number, hence `NSNumberFormatter`, which accepts numbers. If you want to print time, then subclass `NSNumberFormatter`, parse the time decimal and output a string.

**Comment by mathiasgithub** [comment]
It would be great to support other formatter types because subclassing NSNumberFormatter and overriding    
```
 func stringFromNumber(number: NSNumber) -> String? 
```
is a bit awkward if you're creating a new formatter type in that function to for example parse dates.

**Comment by liuxuan30** [comment]
@mathiasgithub  but y axis is meant to be numbers, right? I don't know if the y axis is about dates, how do you draw the charts? What's the meaning? Any examples?

**Comment by mathiasgithub** [comment]
@liuxuan30 here's one of the formatters I would love to be able to use:

´´´
    static var dateComponentsFormatter: NSDateComponentsFormatter {
        let dateComponentsFormatter = NSDateComponentsFormatter()
        dateComponentsFormatter.allowedUnits = [.Minute, .Second]
        dateComponentsFormatter.collapsesLargestUnit = true
        dateComponentsFormatter.zeroFormattingBehavior = .Pad
        return dateComponentsFormatter
    }
´´´
I use it to convert seconds (Int) to a string with the format MM:SS

I think there's a lot of value in being able to represent the values on the y axis in any way might want. NSNumberFormatter limits that.

NSDateComponentsFormatter inherits from NSFormatter

**Comment by liuxuan30** [comment]
I see. It will calculate the y axis range to determine how we draw the chart. We cannot change it to NSFormatter, since it does not provide a default implementation for converting to double values. We could provide one, but seems like it requires a decent work on it, without a high priority. If you want this support, you are more than welcome to file a PR :)

**Comment by mathiasgithub** [comment]
Thank you! No problem, I understand. I’ll see what I can do with that PR

Cheers
