### ISSUE TITLE
Podspec 3 months old

### ISSUE THREAD

**Issue by MatthewCawley** [danielgindi/ios-charts#231]
Could someone please update the pod spec?

Thanks

**Comment by danielgindi** [comment]
Soon. We're are tying up some tiny bits and releasing a version. In the meanwhile you can set it up to sync to latest commit instead of latest version

**Comment by MatthewCawley** [comment]
Brilliant, didn't know you could do it directly to a commit :)

Thanks

**Comment by danielgindi** [comment]
No problem :-)
