### ISSUE TITLE
How to draw Line segments in one Line Chart.

### ISSUE THREAD

**Issue by zxhfirefox** [danielgindi/ios-charts#235]
I have a question about how to draw one data set which some data entry has no value, I find this answer on [stackoverflow](http://stackoverflow.com/questions/30259955/ios-charts-null-data-point-do-not-show-on-chart).
But, I find that if we omit the values, the line still is one line, my question here is can I draw line segments instead of one line ? or I need to do it by myself ?

**Comment by zxhfirefox** [comment]
I think out a solution.
I draw multiple data sets, each one have one segment for it.

**Comment by zxhfirefox** [comment]
But this one may have  performance problem if we have too much line segments.

**Comment by danielgindi** [comment]
It should have similar performance. In a standard line chart, if you have "segments" then they are different data sets.

**Comment by liuxuan30** [comment]
@danielgindi can the rules be applied for combined chart? e.g. at a xIndex: 5, it has a bar data, but no line data, and the line should be cut.

**Comment by danielgindi** [comment]
Performance of two 50 points datasets shoul be the same as one 100 points
dataset (Add an extra CPU op or two for the for-loops)
So don't worry about it.

Unless you actually encounter or measure a performance problem, do not
worry about it.
>
>

**Comment by liuxuan30** [comment]
How about `In a standard line chart, if you have "segments" then they are different data sets.` for comebined chart? Can it apply to combined chart?

**Comment by danielgindi** [comment]
Why not? :)

‏בתאריך יום רביעי, 22 ביולי 2015, Xuan <notifications@github.com> כתב:
