### ISSUE TITLE
*** Announcements ***

### ISSUE THREAD

**Issue by danielgindi** [danielgindi/ios-charts#236]
So you've probably felt that I wasn't paying too much attention in the last few days.
Fear not, as I've not forsaken you...

I am getting married in two weeks exactly, which keeps me more and more busy as we get closer to it. Here and then I try to answer questions and issues, and maybe make a fix or two, but I don't have a lot of time on my hand right now.

We are planning on making a version release now, but of course this version actually has lots of changes and new features compared to previous release version, and we have to make sure everything works correctly.

I also have a few pending PRs, which I plan to review as soon as possible, which probably means after the wedding but could possibly be in a free night, if I'll have any of those.

----
*Swift 2.0* will probably be have a final release real soon, so in order to push it to pod users I'll make another release with a minor version change. Anyone not moving immediately to Xcode 7.0 will be able to just sync to a previous version without a hassle.

----

*Funny thing:*
I am receiving more and more emails from people demanding me to show them how to use the library, how to solve specific problems in their apps (like reading BT signals) and even writing them whole apps. Keep those coming, I love a good laugh! :-) 

*One more thing:*
I want to thank a few people (especially @liuxuan30) who are paying attention to the beginners and helping out those who need help.  :+1:

**Comment by mythodeia** [comment]
@danielgindi wish you a lifetime of happiness. :+1: 
thanks for your contribution to the Open Source community

**Comment by mpullman** [comment]
Thanks for creating this library :)
All the best!

**Comment by liuxuan30** [comment]
Thanks @danielgindi for your words!

Congratulations, Best wishes to you and your family, it's a big thing! 

I love this library so much and I have been working on shifting my old chart library to yours, that's why you see I have been digging more and more about the charts, filing bugs, PRs, asking questions...

Enjoy the wedding and honeymoon:) But don't enjoy for too long, because we are waiting for you to this project :-)

**Comment by katopz** [comment]
Congrats! 

Poor me I found this repos too late, I wrote my own messy Swift graph [for my app](https://itunes.apple.com/us/app/eminer/id986395501) 
already and it pretty pain when I try to make it responsive! 

Looking forward to try yours. It look promising! :D

Cheers!

**Comment by SvenMuc** [comment]
Wish you and your family all the best! Enjoy the time!

**Comment by BrandonShega** [comment]
Congratulations and thank you for your contributions.  This library is amazing!

**Comment by danielgindi** [comment]
Thank you my friends! The big day is coming...

And we have two releases - 2.1.1 that wraps up lots of features+improvements+bugfixes since 2.1.0, and 2.1.2 that improves Highlights and Stacked bars specifically.

**Comment by danielgindi** [comment]
We just passed 4000 stars!

**Comment by gjpc** [comment]
Gratz on the stars, and the wedding, Daniel.

**Comment by toriaezunama** [comment]
Congratulations on getting married. And the 4000 stars :)

**Comment by mcooksey** [comment]
Congratulations @danielgindi and thanks for the great library!

**Comment by yas375** [comment]
Congrats with the wedding!

**Comment by carrchr** [comment]
I'm glad we're providing you with cheap entertainment. Thanks for your work on this library and good luck with your wedding.

**Comment by danielgindi** [comment]
Thank you all for your blessings!
I'm a married man now... A very tired married man, but I'm going to do some catching up here before starting vacations etc :-)

**Comment by liuxuan30** [comment]
When you start your honeymoon?
