### ISSUE TITLE
Demo Project: In BalloonMarker.swift : "Error: No such module 'charts' " XCode 6.4 

### ISSUE THREAD

**Issue by DarvishKamalia** [danielgindi/ios-charts#237]
Just downloaded the library and tried compiling the demo project, ran into this error. I tried including the library in my project as per the instructions in the README, but I get the same problem.

**Comment by liuxuan30** [comment]
Can you provide more information? The demo project should be working anyway. There could be many reasons for Error: No such module 'charts'... you can search through the closed issues for possible reasons.

**Comment by DarvishKamalia** [comment]
Yeah that's what I thought. Since the demo project doesn't work, it's most likely a problem with my setup. However, I cannot think of anything I changed. I tried clean, and deleting the DerivedData folder. I will look at the closed issues.

**Comment by DarvishKamalia** [comment]
Alright so I fixed it. I tried a bunch of things together, and I'm not sure what did it. First, I moved the "Charts" folder into the "ChartsDemo" folder. Then I added ($SRCROOT) to the runpath search paths in the "linking" section in the build settings. Finally, I removed and re-added Charts in the "Target Dependencies" section in the build phases.

**Comment by DarvishKamalia** [comment]
I can confirm that adding ($SRCROOT) to the runpath search paths fixed it.

**Comment by liuxuan30** [comment]
I never played with ($SRCROOT) on my side, all defaults. Looks like you customized a lot of things...

**Comment by DarvishKamalia** [comment]
Haha yeah it looks like a one-off thing.

**Comment by tirendus** [comment]
Adding ($SRCROOT) to runpath search paths definitely fixes this problem, thank you very much for creating this issue.

**Comment by JackLeeMing** [comment]
you should copy the library to your project's dir and the pull the Charts.xcodeproj to your project . use "Embedded Binaries" to include the framework
