### ISSUE TITLE
Charts/Charts.h file not found

### ISSUE THREAD

**Issue by kotarofujita** [danielgindi/ios-charts#24]
Everytime I try to archive in Ad Hoc mode, it gives me this error. I added this as an embedded framework. I tried to mirror the ChartDemo settings as much as possible. Does anyone else get this and if so, how did you resolve this.

Thx in advance.

**Comment by baryon** [comment]
import swift from Objective-C, use
     
@import Charts;

**Comment by danielgindi** [comment]
Thanks @baryon!

**Comment by hackjie** [comment]
@baryon hello, @import Charts; where to put this code
