### ISSUE TITLE
Swift2 upgrade problem "Redundant conformance of 'ChartDataEntry' to protocol 'Equatable'"

### ISSUE THREAD

**Issue by bakierbas** [danielgindi/ios-charts#241]
Swift 2 problem after upgrade

![ekran resmi 2015-07-24 16 47 33](https://cloud.githubusercontent.com/assets/13076428/8875900/df763686-3224-11e5-989f-a1f2d927df40.png)

**Comment by danielgindi** [comment]
Are you using the swift-2.0 branch?
>
>

**Comment by bakierbas** [comment]
yes i am using that

**Comment by cianiandreadev** [comment]
I have the same problem. I'm using the swift-2.0 branch too.

**Comment by danielgindi** [comment]
Swift-2.0 branch is now synced to Xcode 7 beta 4. Please reset your clone to the latest commit.

**Comment by bakierbas** [comment]
Thanks problem resolved!

**Comment by cianiandreadev** [comment]
Thank you!
