### ISSUE TITLE
Can't find anything like "isWordWrapEnabled" in PieChart

### ISSUE THREAD

**Issue by sarvaiyac** [danielgindi/ios-charts#244]
Hi,

I have a gallery of charts and data changes dynamically. So sometimes there are just two values in pie chart and sometimes more than 10. Now I tried to find something related to word wrap but this setting is only in other charts. I have followed some issues. I found the isWordWrapEnabled in other renderers not in PieChartRenderer. Can you give me idea how can I make this possible ? Am I missing something or still that thing is left to implement ?

Thank You,
Chintan.

**Comment by liuxuan30** [comment]
If you tried to search it, you will see:
```Swift
    /// if set to true, word wrapping the labels will be enabled.
    /// word wrapping is done using (value width * labelWidth)
    /// NOTE: currently supports all charts except pie/radar/horizontal-bar
    public var wordWrapEnabled = false
    
    /// :returns true if word wrapping the labels is enabled
    public var isWordWrapEnabled: Bool { return wordWrapEnabled }
```
I don't know if the coming release will support them.

**Comment by sarvaiyac** [comment]
Hi liuxuan30,

Thank You.

**Comment by danielgindi** [comment]
It is planned, but we have a lot on our plate :-)
