### ISSUE TITLE
double vision in the chart

### ISSUE THREAD

**Issue by kscorpio** [danielgindi/ios-charts#245]
Why does the chart have double vision
[1](http://c.picphotos.baidu.com/album/s%3D900%3Bq%3D90/sign=7b7d4928912bd40746c7dffd4bb2ef6c/c8ea15ce36d3d539c459d8c33c87e950352ab04e.jpg)

[2](http://f.picphotos.baidu.com/album/s%3D900%3Bq%3D90/sign=b2080a14be99a9013f3557362dae7b46/8d5494eef01f3a2980cd03ce9f25bc315c607cad.jpg)

**Comment by kscorpio** [comment]
maybe the reason is in xib files  ，the linechartview  backgrou color is default （no color）

**Comment by danielgindi** [comment]
The screenshots are 403.

**Comment by kscorpio** [comment]
http://f.picphotos.baidu.com/album/s%3D900%3Bq%3D90/sign=b2080a14be99a9013f3557362dae7b46/8d5494eef01f3a2980cd03ce9f25bc315c607cad.jpg

http://c.picphotos.baidu.com/album/s%3D900%3Bq%3D90/sign=7b7d4928912bd40746c7dffd4bb2ef6c/c8ea15ce36d3d539c459d8c33c87e950352ab04e.jpg

**Comment by mythodeia** [comment]
403 again

**Comment by kscorpio** [comment]
http://i.imgur.com/A0WIVHC.png

**Comment by kscorpio** [comment]
http://i.imgur.com/x6HIJSS.png

**Comment by danielgindi** [comment]
Man you messed something up real good! Maybe your
`opaque`/`backgroundColor` properties are wrong, or you initialized too
many instances if the chart in one view, or many other things.

Take a step back, create a new view and start from there.

The other option is to post a "working" project so that the good people of
"Charts" can help you investigate.
>
>

**Comment by kscorpio** [comment]
it s the  backgroundColor, i set it as default transparent,.
why the transparent backgroud lead to this?

**Comment by danielgindi** [comment]
Try to set opaque=NO. And read a little bit about it in Apple's docs :)
>
>

**Comment by kscorpio** [comment]
thanks  ,I understand
