### ISSUE TITLE
Disable HorizontalHighlightIndicator on LineChart.

### ISSUE THREAD

**Issue by zxhfirefox** [danielgindi/ios-charts#249]
I found if I want to disable HorizontalHighlightIndicator in Line Chart, I need to subclass LineChartRenderer and override drawHighlighted method.

But on Android Library, there is a method called setDrawHorizontalHighlightIndicator on LineScatterCandleRadarDataSet which is super class of LineChartDatSet, using this method can disable the horizontal highlight indicator. In iOS, we don't have LineScatterCandleRadarDataSet in the class hierarchy.

Do you plan to add this feature in future ? or if I am wrong, please tell me.

**Comment by danielgindi** [comment]
I missed this feature which was introduces in 2.1.1, thanks for noticing

**Comment by amycheong19** [comment]
Hi, may I know if HorizontalHighlightIndicator has been implemented?
