### ISSUE TITLE
2.1.2 Not Yet in CocoaPods Master Repo

### ISSUE THREAD

**Issue by davecom** [danielgindi/ios-charts#251]
It's still on 2.1.0.  Someone needs to do the push to trunk...

**Comment by danielgindi** [comment]
@petester42 You are the one with permissions to the pod right?

**Comment by petester42** [comment]
Yep. I can push the update. I tried adding you a while back as an owner but you were not registered on trunk. If you want to be added as an owner you can follow the instructions [here](https://guides.cocoapods.org/making/getting-setup-with-trunk.html) and I'll add you.

**Comment by petester42** [comment]
For future reference if anyone need the most recent version of the pod but it is not in the trunk. They can define use the following to specify the version in their Podfile. 
`pod 'Charts', :git => 'https://github.com/danielgindi/ios-charts', :tag => '2.1.2'`

**Comment by danielgindi** [comment]
I got registered

**Comment by petester42** [comment]
Pushed and added you. Also fixed the podspec. You will see a PR shortly :wink:
