### ISSUE TITLE
Real time graph - X-axis moving?

### ISSUE THREAD

**Issue by ajaybhat1987** [danielgindi/ios-charts#255]
Hi,
Firstly, kudos for team and for the great work in building the wonderful library. 
I would like to know if there is a way to use this library to plot a real time moving x-axis. 
Similar to inbuilt app "voice memos". Is there a way to customize current library for drawing such movable axis (real time)?

**Comment by danielgindi** [comment]
Yes, just add entries when you want :-)

**Comment by ajaybhat1987** [comment]
With help of (addEntry: ). I am only able to add the values whenever needed. How can I dynamically "move the x -axis" with each frame.
