### ISSUE TITLE
How to add point dynamicly

### ISSUE THREAD

**Issue by kscorpio** [danielgindi/ios-charts#257]
i test to add point

      ChartDataEntry * entry=[[ChartDataEntry alloc] initWithValue:index xIndex:index];
      index+=1;
       [self.scaleView.data addEntry:entry dataSetIndex:0];

1 where is the fault in the code 
2  log out  and in dataset the xIndex just can be an int type

**Comment by danielgindi** [comment]
Call `notifyDataSetChanged`. You might also want to "moveToX..."

**Comment by kscorpio** [comment]
[self.scaleView.data addEntry:entry dataSetIndex:0];
what should i pass to `dataSet ： para` ?
1 pass in the last point in the line?
2 Or pass in the the line number in all lines? (i find in `datasets`, there are many `dataset`) 

I pass in 0, i suppose there is just one line in the chart

**Comment by kscorpio** [comment]
the code does not work well ， it cann‘t add point dynamly ， and it lead the yAxis confusion。
Maybe i use the api in error， Is there a demo which show the useage of the dynamic chart？？
    
      ChartDataEntry * entry=[[ChartDataEntry alloc] initWithValue:index xIndex:index];
      index+=1;
      [self.scaleView.data addEntry:entry dataSetIndex:0];

**Comment by kscorpio** [comment]
3 which object could do notifyDataSetChanged?  ChartDataSet instance or LineChartView instance
4 how to set xValues
    
       ChartDataSet * ds=self.scaleView.data.dataSets[0];
       NSInteger xIndex= ds.valueCount;
       ChartDataEntry * entry=[[ChartDataEntry alloc] initWithValue:index xIndex:xIndex];
       [ds addEntry:entry];
       [ds notifyDataSetChanged];
    
//    [self.scaleView.data addEntry:entry dataSetIndex:0];
//    [self.scaleView notifyDataSetChanged];

**Comment by kscorpio** [comment]
//! Y
           ChartDataSet * currentDataSet=self.scaleView.data.dataSets[0];
           NSInteger xIndex= currentDataSet.valueCount;
           ChartDataEntry * entry=[[ChartDataEntry alloc] initWithValue:yVal xIndex:xIndex];
           [currentDataSet addEntry:entry];
           //! X
           NSArray * xVal=_scaleView.data.xValsObjc;
           double lastX=[xVal.lastObject doubleValue];
           lastX +=0.1;
           [_scaleView.data addXValue:[NSString stringWithFormat:@"%f",lastX]];
    
           //!
           [self.scaleView notifyDataSetChanged];
           [self.scaleView moveViewToX:xIndex+1];

scene 1: before and zoom actions
when add new point to chart ,all the points are in the chart, the line does not move

scene 2: after zoom in or zoom out
when add new point to chart ,the line can move.
a new pooint add from right ,and one or more points (which has exitst in line) will disappear to left

scene 2 is which i want ,how to fix scene 1?
