### ISSUE TITLE
moveViewToX

### ISSUE THREAD

**Issue by donaldkingdt** [danielgindi/ios-charts#258]
Hi,

I'm trying to set the chat to scroll to last value in data set X using moveViewToX(entries.count) but this doesn't seem to move to the last value. Any Ideas?

Cheers

**Comment by danielgindi** [comment]
You are passing an invalid index

**Comment by donaldkingdt** [comment]
My data set has up to 1100 data points, i want to move to the last index. Shouldn't this be the right value? if not, how can i get it?

**Comment by danielgindi** [comment]
1099

**Comment by donaldkingdt** [comment]
How is that about? pls explain

**Comment by danielgindi** [comment]
The first item is at 0

**Comment by donaldkingdt** [comment]
Exactly my point. The last item should be at lastItem.count right?

**Comment by danielgindi** [comment]
No. If you have two items, and first one is `0`, then the second one is `1`. Which means that you cannot pass `2` for the last item of two, but `1`.

**Comment by donaldkingdt** [comment]
self.chartView.setVisibleXRangeMaximum(20)
self.chartView.moveViewToX(self.measurementEntries.count - 1)

does this look right?

**Comment by donaldkingdt** [comment]
Fixed. Had to call self.chartView.moveViewToX(self.measurementEntries.count - 1) in ViewDidAppear().

Cheers Daniel

**Comment by yas375** [comment]
Had to do similar thing in `viewDidAppear` as well. It results in weird jump to the most recent values. But if I do this in `viewWillAppear` then I get the wrong position with partly blank graph.

Happy to share more details about the issue if needed.

**Comment by NicolasLourenco** [comment]
I've the same issue.
I have 28 points and I show only 4 in a view.
I want to show (in the first time) the last point of my dataSet. But with this method, I've a blank space a the right of my last point. Any idea?

```[_lineChartView moveViewToX:_lineChartView.data.yValCount-1];
[_lineChartView zoom:7 scaleY:0 x:0 y:0];```

**Comment by daisoreanu** [comment]
the thing is from what I noticed that you will get another plotted value to the right side, also you should change the order of the lines from:
`[_lineChartView moveViewToX:_lineChartView.data.yValCount-1];
[_lineChartView zoom:7 scaleY:0 x:0 y:0];`

to:  

`[_lineChartView zoom:7 scaleY:0 x:0 y:0];
[_lineChartView moveViewToX:_lineChartView.data.yValCount-1];`
