### ISSUE TITLE
Another Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#260]
Today I was trying to upgrade to 2.1.2 from 2.1.0. When I tried to build, it throws:
Command failed due to signal: Segmentation fault: 11
```
1.	While emitting IR for source file /Users/xuan/Development/Charts/BDPLineChartView.swift
2.	While emitting class metadata for 'BDPLineChartView' at /Users/xuan/Development/Charts/BDPLineChartView.swift:12:8
```
It directs me to a function `getHighlightByTouchPoint` in BDPLineChartView. Below code works good in 2.1.0, I am not sure what goes wrong. I simply subclass LineChartView and override this function.
```Swift
    public override func getHighlightByTouchPoint(var pt: CGPoint) -> ChartHighlight?
    {
        //judge is point in chart
        if (viewPortHandler.contentRect.origin.x > pt.x) {
            return nil
        } else {
            return super.getHighlightByTouchPoint(pt)
        }
    }
```

**Comment by danielgindi** [comment]
It's just not defined as "var" anymore...

**Comment by liuxuan30** [comment]
maybe a silly mistake, but I don't get it yet... what var? I just try to add a small check before call super. The compiler don't complain it but throw segmentation fault while building...

**Comment by liuxuan30** [comment]
Oh lord, I finally realize you are saying the 'var' in the parameters.... I didn't ever see it for the whole time.
