### ISSUE TITLE
drawValuesForWholeStackEnabled deprecated?

### ISSUE THREAD

**Issue by zacjordaan** [danielgindi/ios-charts#261]
Hi Daniel

First, thank you for an incredible framework. I think your work is outstanding.

I've been successfuly using your *BarChartView* for a while but after refreshing the source today I've found that *drawValuesForWholeStackEnabled* is no longer recognised/implemented. Is that by design?

Rgds
Zac

**Comment by danielgindi** [comment]
Yes, it has been deprecated, as it does not make sense to have stacked data and not draw it...
We had that property in the past when stacked data were partially supported, but now with full support that property is not needed anymore.

**Comment by zacjordaan** [comment]
Ah, I understand. Thanks for the super-quick response; much appreciated.
