### ISSUE TITLE
Real-time Charts

### ISSUE THREAD

**Issue by AllenConquest** [danielgindi/ios-charts#263]
Is it possible to create a LineChart that is continuously updated as data is loaded every 5 seconds, with the chart smoothly scrolling to the left as new data points are plotted?

**Comment by ajaybhat1987** [comment]
Don't we have a sample for real time graphs in iOS which is similar to that used in Android Charts (RealtimeLineChartActivity)
 - Like
https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java

**Comment by kscorpio** [comment]
but how to change the yaxis max value, and in project when i add point to line , it compress the line in x direction, so the point in view is become more and  more, can it move to left dynamicly?

**Comment by kscorpio** [comment]
Why nobody solve this question

**Comment by pplavetzki** [comment]
Try removing the entry at the beginning of the dataset each time you add a new entry:

data.removeEntryByXIndex(0, dataSetIndex: 0)

This creates kind of a push and pop.  Not sure this will meet your needs as this kinda makes the graph choppy.

**Comment by liuxuan30** [comment]
Closing -- if you have updates, feel free to reopen it

**Comment by chris-gunawardena** [comment]
Also `self.lineChartView.setVisibleXRange(minXRange: CGFloat(1), maxXRange: CGFloat(50))` with 
`self.lineChartView.moveViewToX(CGFloat(i))` worked for me.
