### ISSUE TITLE
Crash on one entry point in charts

### ISSUE THREAD

**Issue by amycheong19** [danielgindi/ios-charts#265]
Hi all, I noticed when there is ok one entry point for the chart and it crash with error: (EXC_BAD_INSTRUCTION) at

    public override var highestVisibleXIndex: Int
    {
        var step = CGFloat(_data.dataSetCount)
        var div = (step <= 1.0) ? 1.0 : step + (_data as! BarChartData).groupSpace
        
        var pt = CGPoint(x: _viewPortHandler.contentRight, y: _viewPortHandler.contentBottom)
        getTransformer(ChartYAxis.AxisDependency.Left).pixelToValue(&pt)
        
        ////>>>> crash at this line >>>>>
        return Int((pt.x >= CGFloat(chartXMax)) ? CGFloat(chartXMax) / div : (pt.x / div))
     }

I found out that the point end up display (nan, nan) thus the error. Is there a precaution or workaround for this?

**Comment by liuxuan30** [comment]
you have to give more information why it is (nan,nan). I met such issues from time to time, and I found it's my fault to feed invalid numbers like nan, like divide 0.

Usually it is your duty to make sure all the data you passed through is valid.

**Comment by amycheong19** [comment]
It only happen when I have one entry point for the graph. Before the line method "getTransformer" my pt. returns (356, 10), after that pt becomes (nan, nan) 
I can assure my value pass in are double values combined chart

**Comment by liuxuan30** [comment]
only one entry point should not be the problem. What's the dataSet code so we can test?

**Comment by danielgindi** [comment]
Please state the version you are using, and show the dataset that crashes.

**Comment by danielgindi** [comment]
I do not experience any crash with 1 bar. There was a random crash with zero bars which was just fixed.
The last response from @amycheong19 was 23 days ago so I'm assuming he is not experiencing this either.

**Comment by mlorenzeCDS** [comment]
I have the same crash when the set has all values with the same value (zeros, ones, etc)

**Comment by liuxuan30** [comment]
@mlorenzeCDS what chart and what data can we  reproduce?

**Comment by mlorenzeCDS** [comment]
I found the solution. The problem was when the dataset has all values equals to zero.
I had to update the class ChartDataSet.swift (specially the method calcMinMax setting the yMax var with -DBL_MIN)

Thanks!

**Comment by liuxuan30** [comment]
@danielgindi are you aware of this zero issue?
