### ISSUE TITLE
Library not found while building application through distribution certificate

### ISSUE THREAD

**Issue by Maheshkmrao** [danielgindi/ios-charts#266]
Hi Daniel,

While debguging with developer certificate the application is working fine in the device(iPad/iPhone ios version 8.0 and 8.4).

I am facing an issue while building the application through the distribution certificate and gives the error as :- library not found.
![screen shot 2015-08-03 at 10 35 37 pm](https://cloud.githubusercontent.com/assets/7520858/9042996/01b9143a-3a30-11e5-88df-8482902630b0.png)

Please let us know the issue.

Thanks

**Comment by danielgindi** [comment]
Please go over the instructions in the README

**Comment by liuxuan30** [comment]
There are many posts already, like https://github.com/danielgindi/ios-charts/issues/240

try search and many answers

**Comment by Maheshkmrao** [comment]
Daniel - 

We have verified the instructions in README and tried all those steps. However, its' working with Developer certificate on device, but nor with Distribution certificate. We have tried with other distribution certificate. But, still not working for them as well. So, do we need to revoke the distribution certificate as mentioned by  liuxuan30? 

Please suggest your thoughts.

**Comment by liuxuan30** [comment]
Based on your log, my problem is not yours, because my footprint was
```
Library not loaded: @rpath/libswiftCore.dylib
```
Yours is
```
Library not loaded: @rpath/Charts.framework/Charts
```
Apparently the ios-charts is not bundled in your app. You could start from here.

Quote from #240
```
If you are building as a Framework, and have not dragged the code to the project, then it must be added as an Embedded framework. Otherwise the compiler does not actually embed the framework's code in the project - assuming it is available in the OS like any other framework - and will crash on runtime when it cannot load the library.
```

**Comment by rameshyadavmuddika** [comment]
Hi Daniel-

We hav fixed this issue by following steps:-

As read me we have followed each and every step but before building archive we need to do couple of steps as follows:-

We need have hav a new provision profile built with wild character as (com.XXX.*).

We need add this profile in build settings of project and we need to open the charts.xcodeprj and we need to change the bundle Id to (com.xxx.Charts) and include the provisioning profile and have the cer included

After this clean and build the app which is working fine now.

Thanks
Ramesh

**Comment by rameshyadavmuddika** [comment]
Provision with bundle id created for wild character as above because charts also should be mapped to thoes profiles

**Comment by liuxuan30** [comment]
So the reason is the charts.xcodeprj does not match your provisioning file and cert? I think this should be addressed in README @danielgindi

**Comment by rameshyadavmuddika** [comment]
Yeah your right @liuxuan30 that's why application is unable to compile the charts.framework while archiving the build.

**Comment by petester42** [comment]
is this resolved?

**Comment by danielgindi** [comment]
I'm not sure how much we can do about this in an automatic fashion. I'm going to try to set the code-signing distribution to Automatic, see if this helps.
I guess this is an issue with all frameworks, and I wonder why Xcode does not know to build the framework with the parent project's cert. Strange.

**Comment by liuxuan30** [comment]
@danielgindi for the in-house distribution, we can do nothing but generate a new one.

**Comment by danielgindi** [comment]
So they always require generating certificates for Frameworks? Seems a bit strange as AppStore distributions work fine without special certificates

**Comment by danielgindi** [comment]
So they always require generating certificates for Frameworks? Seems a bit strange as AppStore distributions work fine without special certificates

**Comment by liuxuan30** [comment]
I am not sure if it will affect AppStore distribution. But for in-house distribution, if the cert lacks the 'OU' attribute, it crashes for sure.

**Comment by wganeshb** [comment]
Is this issue resolved. 
I am also facing the similar issue.
I can use development provisioning to run the app on device. 
But it just can't archive the app using distribution profile. I get this warning whenever I validate the build.

![succeed with warning](https://cloud.githubusercontent.com/assets/3005149/10422404/a24aa3c2-70d7-11e5-8fa2-17a8560dfc6d.png)

**Comment by danielgindi** [comment]
This warning is OK. You can proceed.

‏בתאריך יום שני, 12 באוקטובר 2015, Ganesh <notifications@github.com> כתב:

**Comment by wganeshb** [comment]
I proceed with warning. Submission is completed with warning as shown below. 

![screen shot 2015-10-12 at 1 48 11 pm](https://cloud.githubusercontent.com/assets/3005149/10423987/da1b2752-70e8-11e5-9e0a-7a6fd3d92fcc.png)

**Comment by danielgindi** [comment]
It just means that they don't analyse IPAs of a few megabytes on the fly.
You'll see the results in iTunes Connect

**Comment by wganeshb** [comment]
Thank you @danielgindi.
It is showing up on itunesconnect for beta testing..
