### ISSUE TITLE
pod not support iOS 7.0 ???

### ISSUE THREAD

**Issue by 79144876** [danielgindi/ios-charts#27]
s.ios.deployment_target = "8.0"

[!] The platform of the target `Pods` (iOS 7.0) is not compatible with `Charts (2.0.9)` which has a minimum requirement of iOS 8.0.

**Comment by danielgindi** [comment]
Swift frameworks cannot be compiled on iOS 7, you'll have to drag the Swift files to your project. 
This is in the readme, you should really read it.
