### ISSUE TITLE
Highlight Doest'n work properly on UIPageViewController in LineChart.

### ISSUE THREAD

**Issue by garfiaslopez** [danielgindi/ios-charts#275]
When i touch the graph for highlight the value, my view is changed to the next viewcontroller of my UIPageViewController.

The view can't handle the graph highlight event or something like that. this happen me when i update to the version 2.1.2  .

![img_0381](https://cloud.githubusercontent.com/assets/10682365/9075171/3e1825c2-3ad7-11e5-8edb-49d41d45b306.PNG)

I have to downgrade the version to 2.1.0 for the highlight in graph works properly.

**Comment by danielgindi** [comment]
I don't exactly understand what you are experiencing.
Is tapping to highlight causing your pagecontroller to scroll? That shouldn't happen...
Or are you trying to move the finger around in order to change the highlight?

**Comment by garfiaslopez** [comment]
I try to move my finger around the graph to change the highlight position and this causes that the uipageviewcontroller change to the next view.
The tap to highlight works fine, but when i move my finger the page changes.

**Comment by danielgindi** [comment]
If course it does. You need to disable the continuous highlight feature, as you can't expect two different swiping behaviours to not collide.
