### ISSUE TITLE
ios-charts different plotting activity than MKAndroidChart

### ISSUE THREAD

**Issue by nlabhart** [danielgindi/ios-charts#276]
Please see the attached screenshots for a visual of what is happening. The data set is coming back the from the same source, and is the same data.  The data is plotting correctly on the Android implementation (MKAndroidChart), but is not plotting correctly using ios-charts. Is there an obviously setting or view property that I did not set? If you need to see code, I can certainly post it. 

ANDROID (Correct Version)
![android](https://cloud.githubusercontent.com/assets/3129166/9077550/1bcc6d16-3af5-11e5-9262-af7ad73e4f3e.png)

IOS (Incorrect plotting)
![ios](https://cloud.githubusercontent.com/assets/3129166/9077551/1bdf80d6-3af5-11e5-9c3e-105681e27d52.PNG)

**Comment by liuxuan30** [comment]
I think the ios version of chart is rendered correctly, but its origin point is higher then android. Double check your chart view's frame on iOS.

**Comment by nlabhart** [comment]
Does it play nice with auto layout in iOS? The frame doesn't change in the
code, but it does have auto layout attached to it.

On Tue, Aug 4, 2015 at 10:57 PM, Xuan <notifications@github.com> wrote:

> I think the ios version of chart is rendered correctly, but its origin
> point is higher then android. Double check your chart view's frame on iOS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-127840037>
> .
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by nlabhart** [comment]
@liuxuan30 the data I am pulling matches what is in Android (70K, 110K).
This was the first indicator that there was a problem. Also, the frame
doesn't change. It is set in a Xib, and loaded without changing the frame.
However, there is auto layout constraints attached to it. Could this cause
a problem?

On Tue, Aug 4, 2015 at 11:12 PM, Noah Labhart <noah@touchtap.io> wrote:

> Does it play nice with auto layout in iOS? The frame doesn't change in the
> code, but it does have auto layout attached to it.
>
> On Tue, Aug 4, 2015 at 10:57 PM, Xuan <notifications@github.com> wrote:
>
>> I think the ios version of chart is rendered correctly, but its origin
>> point is higher then android. Double check your chart view's frame on iOS.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-127840037>
>> .
>>
>
>
>
> --
>
> Sincerely,
>
> Noah Labhart
> noah@touchtap.io
> 817-988-5253
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by liuxuan30** [comment]
It should never be the case that if you feed the data in range [70K,110K] and it draws at the wrong position like [90K,110K], at least not on my side... It's a serious bug and I just cannot believe it right now. You might need to provide the dataSet code and we can try.

For the frame, you can check and compare before/after the autolayout engine calculate the frame. I would suggest start from debugging the frame.

What you can try is after the autolayout engine finalized the frame, you start creatign the dataSet and feed the chart.

**Comment by danielgindi** [comment]
To me it seems that your problem is the `NSNumberFormatter` is not configured similarly.

**Comment by danielgindi** [comment]
You may also want to check if your auto-layout constraints stick to margins or not. Because those "margins" can confuse and cause you to add extra spacing - or have negative extra spacing.

**Comment by nlabhart** [comment]
The NumberFormatter for the Y Axis is a separate issue. I'll check the
auto-layout constraints to see if that is what is causing the problem. And
I'll check the frame before and after the constraints are applied - I
suspect that is where the issue is, but I'm not sure how to fix it.

On Wed, Aug 5, 2015 at 3:27 AM, Daniel Cohen Gindi <notifications@github.com
> wrote:

> You may also want to check if your auto-layout constraints stick to
> margins or not. Because those "margins" can confuse and cause you to add
> extra spacing - or have negative extra spacing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-127913328>
> .
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by liuxuan30** [comment]
@nlabhart I also guess it's autolayout problem, yesterday I met one. Configuring chart view in viewDidLoad and viewDidAppear has slight different. The one in viewDidAppear is not correct. But it it's not my code, so I have to wait for other people to fix.

**Comment by nlabhart** [comment]
Xuan - is there a function similar to the invalidate() function on
MKAndroidChart? Is the only option setNeedsDisplay?

On Wed, Aug 5, 2015 at 8:45 PM, Xuan <notifications@github.com> wrote:

> @nlabhart <https://github.com/nlabhart> I also guess it's autolayout
> problem, yesterday I met one. Configuring chart view in viewDidLoad and
> viewDidAppear has slight different. The one in viewDidAppear is not
> correct. But it it's not my code, so I have to wait for other people to fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128207443>
> .
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by danielgindi** [comment]
setNeedsDisplay IS invalidate()

‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <notifications@github.com>
כתב:

> Xuan - is there a function similar to the invalidate() function on
> MKAndroidChart? Is the only option setNeedsDisplay?
>
> On Wed, Aug 5, 2015 at 8:45 PM, Xuan <notifications@github.com

**Comment by nlabhart** [comment]
That is good to know!

What I have found out is that changing the option setZeroEnabled for the
yAxis only changes the yAxis, and not the data. So I need to redraw the
data somehow. Perhaps setNeedsDisplay is the answer.

On Thu, Aug 6, 2015 at 7:03 AM, Daniel Cohen Gindi <notifications@github.com
> wrote:

> setNeedsDisplay IS invalidate()
>
> ‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <notifications@github.com>
> כתב:
>
> > Xuan - is there a function similar to the invalidate() function on
> > MKAndroidChart? Is the only option setNeedsDisplay?
> >
> > On Wed, Aug 5, 2015 at 8:45 PM, Xuan <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > @nlabhart <https://github.com/nlabhart> I also guess it's autolayout
> > > problem, yesterday I met one. Configuring chart view in viewDidLoad and
> > > viewDidAppear has slight different. The one in viewDidAppear is not
> > > correct. But it it's not my code, so I have to wait for other people to
> > fix.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128207443
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> > Sincerely,
> >
> > Noah Labhart
> > noah@touchtap.io <javascript:_e(%7B%7D,'cvml','noah@touchtap.io');>
> > 817-988-5253
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128341740
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128343264>
> .
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by danielgindi** [comment]
Yes it is. In most functions that work on the data, the chart can't know
about the changes, so you have to tell it.
Sometimes it involves calling "notifyDataSetChanged", sometimes a render is
enough

‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <notifications@github.com>
כתב:

> That is good to know!
>
> What I have found out is that changing the option setZeroEnabled for the
> yAxis only changes the yAxis, and not the data. So I need to redraw the
> data somehow. Perhaps setNeedsDisplay is the answer.
>
> On Thu, Aug 6, 2015 at 7:03 AM, Daniel Cohen Gindi <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > wrote:
>
> > setNeedsDisplay IS invalidate()
> >
> > ‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > כתב:
> >
> > > Xuan - is there a function similar to the invalidate() function on
> > > MKAndroidChart? Is the only option setNeedsDisplay?
> > >
> > > On Wed, Aug 5, 2015 at 8:45 PM, Xuan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com

**Comment by nlabhart** [comment]
Figured it out, without setNeedsDisplay or notifyDataHasChanged.

There are two Y axis's in the LineChart I am using - leftAxis and
rightAxis.  I had disabled the rightAxis from starting at zero
(startAtZeroEnabled = NO), and disabled the leftAxis entirely (enabled =
NO). However, I tried to set the startAtZeroEnabled on BOTH the left and
right axis - and it started charting properly. So despite the leftAxis
being disabled, the startAtZeroEnabled setting applied.

Thanks for the help!

On Thu, Aug 6, 2015 at 7:07 AM, Daniel Cohen Gindi <notifications@github.com
> wrote:

> Yes it is. In most functions that work on the data, the chart can't know
> about the changes, so you have to tell it.
> Sometimes it involves calling "notifyDataSetChanged", sometimes a render is
> enough
>
> ‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <notifications@github.com>
> כתב:
>
> > That is good to know!
> >
> > What I have found out is that changing the option setZeroEnabled for the
> > yAxis only changes the yAxis, and not the data. So I need to redraw the
> > data somehow. Perhaps setNeedsDisplay is the answer.
> >
> > On Thu, Aug 6, 2015 at 7:03 AM, Daniel Cohen Gindi <
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > wrote:
> >
> > > setNeedsDisplay IS invalidate()
> > >
> > > ‏בתאריך יום חמישי, 6 באוגוסט 2015, Noah Labhart <
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > כתב:
> > >
> > > > Xuan - is there a function similar to the invalidate() function on
> > > > MKAndroidChart? Is the only option setNeedsDisplay?
> > > >
> > > > On Wed, Aug 5, 2015 at 8:45 PM, Xuan <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > @nlabhart <https://github.com/nlabhart> I also guess it's
> autolayout
> > > > > problem, yesterday I met one. Configuring chart view in viewDidLoad
> > and
> > > > > viewDidAppear has slight different. The one in viewDidAppear is not
> > > > > correct. But it it's not my code, so I have to wait for other
> people
> > to
> > > > fix.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128207443
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > Sincerely,
> > > >
> > > > Noah Labhart
> > > > noah@touchtap.io <javascript:_e(%7B%7D,'cvml','noah@touchtap.io');>
> > <javascript:_e(%7B%7D,'cvml','noah@touchtap.io
> > <javascript:_e(%7B%7D,'cvml','noah@touchtap.io');>');>
> > > > 817-988-5253
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128341740
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128343264
> > >
> > > .
> > >
> >
> >
> >
> > --
> >
> > Sincerely,
> >
> > Noah Labhart
> > noah@touchtap.io <javascript:_e(%7B%7D,'cvml','noah@touchtap.io');>
> > 817-988-5253
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128343544
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/276#issuecomment-128343708>
> .
>



-- 

Sincerely,

Noah Labhart
noah@touchtap.io
817-988-5253

**Comment by liuxuan30** [comment]
Have you set your dataSet.axisDependency accordingly? By default it's left. but if you disable leftAxis and enable rightAxis, it should render wrongly I think. startAtZeroEnabled will only affect how the axis range is calculated. if you only have positive data, it's ok to leave it as 'YES' on both axis.

**Comment by nlabhart** [comment]
Hi @danielgindi would it be possible for you to remove my email address references from your comments? :)
