### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by gkaimakas** [danielgindi/ios-charts#277]
Hello,

this is a great framework, been using it on Android and it is totally awesome! Can you please publish it on Cocoapods so it can be easier to use?

P.S. It is really easy to publish a project on Cocoapods

**Comment by danielgindi** [comment]
Man it's already on...

**Comment by gkaimakas** [comment]
Oh, didn't check cocoapods for it. Sorry.

Please update your README.md so that the support is clear.

Thanks

2015-08-05 18:01 GMT+03:00 Daniel Cohen Gindi <notifications@github.com>:

> Man it's already on...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielgindi/ios-charts/issues/277#issuecomment-128027332>
> .
>



-- 
Γιώργος
