### ISSUE TITLE
Allow to align the Legend!

### ISSUE THREAD

**Issue by hxdev** [danielgindi/ios-charts#279]
I've create a BarChart with two BarChartDataSet.
Here is my init for the Legend:

        ChartLegend* legend = barChart.legend;
        [legend setCustomWithColors:@[UIColorFromRGB(0xD3370A),UIColorFromRGB(0xFFFFFF)] labels:@[@"Data1",@"Data2"]];
        legend.position = ChartLegendPositionRightOfChartInside;
        legend.direction = ChartLegendDirectionLeftToRight;
        legend.xEntrySpace = 15.f;
        legend.yEntrySpace = 0.f;
        legend.form = ChartLegendFormSquare;
        legend.formSize = 9.0;
        legend.font = [UIFont systemFontOfSize:11.f];
        legend.textColor = [UIColor whiteColor];
        [legend setYOffset:-15];

The legend will display like this:

    [icon] Data1
    [icon] Data2

How can I align the Legend to Left to Right? Like this

    [icon] Data1    [icon] Data2

Thank!

**Comment by liuxuan30** [comment]
I think as long as you set the position to ChartLegendPositionRight, it will render vertically, to save space. You either use bottom position, or customize ChartLegendRenderer to whatever you like.

**Comment by hxdev** [comment]
Thanks for your support :) I'll try with the ChartLegendRenderer

**Comment by NathanMrtns** [comment]
@hxdev Did you find a solution ?

**Comment by MarcosiOSdev** [comment]
Today this attribute doesnt exist. 
Does anyone know how to do ?

  legend.direction = ChartLegendDirectionLeftToRight;

**Comment by ABridoux** [comment]
In case of someone ends up here like me. To set the legend position:

```swift
chartView.legend.horizontalAlignment = .left
chartView.legend.verticalAlignment = .top
```
