### ISSUE TITLE
UISwipeGestureRecognizer

### ISSUE THREAD

**Issue by elifsimit** [danielgindi/ios-charts#28]
How can I use UISwipeGestureRecognizer on chartView? I wrote some code but it didn't work. 

- (void)viewDidLoad
{
	UISwipeGestureRecognizer *swipeRight = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(slideToRightWithGestureRecognizer:)];
	swipeRight.direction = UISwipeGestureRecognizerDirectionRight;
	
	[_chartView addGestureRecognizer:swipeRight];
}

-(void)slideToRightWithGestureRecognizer:(UISwipeGestureRecognizer *)gestureRecognizer{
	NSLog(@"here");
}

**Comment by danielgindi** [comment]
There was a problem specifically in a PieChart/RadarChart, where after a gesture was cancelled, touches were not restored. That was fixed in the latest commit.

Other than that, `UIGestureRecognizer`s should work, as most gestures are already handled by native `UIGestureRecognizer`s. 
You may want to loop the `gestureRecognizers` array of the view, and modify their properties to allow correctly playing with other conflicting gesture recognizers.

**Comment by inix** [comment]
@elifsimit 
 
hi, I have similar scenario with you,that,I disable Y axis scale,but I can not scroll tableview in the chart.
I just do a simple hack,that if chart disable Y axis scale,enable UITableView vertically scrolling.

```
		if !self.isScaleYEnabled {
			_outerScrollView?.nsuiIsScrollEnabled = true
		} else {
			_outerScrollView?.nsuiIsScrollEnabled = false
		}
```
in func `@objc fileprivate func panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)`
of `BarLineChartViewBase.swift` file

diff:
```
@@ -688,7 +688,11 @@ open class BarLineChartViewBase: ChartViewBase, BarLineScatterCandleBubbleChartD
                     if _outerScrollView !== nil
                     {
                         // Prevent the parent scroll view from scrolling
-                        _outerScrollView?.nsuiIsScrollEnabled = false
+                                               if !self.isScaleYEnabled {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = true
+                                               } else {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = false
+                                               }
                     }
                 }
                 
```
