### ISSUE TITLE
installing with cocoapods

### ISSUE THREAD

**Issue by peteclark3** [danielgindi/ios-charts#283]
Hi, I've read the various issues on this topic but haven't found a solution.  Closest I came was issue #87 but still didn't see a solution other than "read the instructions" which I swear I did a couple of times.. I apologize.

I simply added to my Podfile: pod 'ios-charts'

then did a pod install / pod update .. 

all seems good from a building perspective, but when I try to "import Charts" at the top of my swift file I get a compiler error, "No such module 'Charts'" .. similarly if I remove that and just try to add a BarChartView, e.g.  @IBOutlet weak var barChartView: BarChartView! , I get "use of undeclared type BarChartView"  

Is there a step I am missing for the cocoapods installation?  Tried multiple project cleans, stop and start xcode..

**Comment by xrolfex** [comment]
You may need to make sure that you are using frameworks in cocoa pods.

**Comment by peteclark3** [comment]
I was.. (I am) - gave up and installed via tutorial here: http://www.appcoda.com/ios-charts-api-tutorial/

**Comment by khanxc** [comment]
![screen shot 2016-01-28 at 6 35 07 pm] Other framework in pod are working, trying to make Charts work for hours but no progress. Guidance needed
(https://cloud.githubusercontent.com/assets/5825355/12645103/b7a84646-c5ed-11e5-9afe-b0c2090c71b4.png)
Podfile:
```Swift
 platform :ios, '8.0'
use_frameworks!
target 'AppName' do

pod 'Alamofire', '~> 3.0'
pod 'Charts'

end

**Comment by jhmacdon** [comment]
I am having the same issue

**Comment by danielgindi** [comment]
You may want to post an Issue on the Issues page of CocoaPods. Or try to install it manually...

**Comment by apprisingapps** [comment]
It looks as if you are using Swift.  If you are using Swift 3, you may need consider adding the following to your pod file.
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

**Comment by H-Sha** [comment]
It worked for me - please try the following in your Podfile

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'AppName' do
pod 'Alamofire', '~> 4.3.0'
pod 'Charts'
end

**Comment by elchris78** [comment]
I've been dealing with the same problem since 2 days ago, with no success so far though!
I'm trying to make this work with cocoapod, tried your solution @H-Sha but not a positive result.
Heres my problem:
![screen shot 2017-02-21 at 1 50 11 pm](https://cloud.githubusercontent.com/assets/20014863/23182028/bcfe7e8a-f83c-11e6-9903-50d38a1476c9.png)

**Comment by petester42** [comment]
Seems like you added all the files to your project? Please open another issue if you haven't figured it out. This is something wrong with your setup and isn't related with this issue

**Comment by TheTiger13** [comment]
Following steps worked for me:

1. install via cocoapods by using `pod 'Charts'`
2. Now if you will try to write anything related to charts it will not read that file or class. So for this GoTo -> General -> Linked Frameworks and Libraries -> Click on `+` button and add `Charts.framework`. 
3. Go to your class where you want to use this. `import Charts` and now you will be able to use this framework without any error.

**Comment by petester42** [comment]
@TheTiger13 this defeats the point of cocoa pods. After doing `pod install` all your dépensiers should automatically be linked in your project. If that is not that case you have configured something wrong in your pod file.

**Comment by TheTiger13** [comment]
I just took a new sample project and installed  `pod 'Charts'` without doing anything extra. (Xcode 9.3, Swift 4.1).
