### ISSUE TITLE
ios-charts for swift 2.0 cannot compile on XCode7 beta 5 - self.dynamicType.allocWithZone(zone) issue

### ISSUE THREAD

**Issue by iksiphone** [danielgindi/ios-charts#287]
Hi

Thank you for your hard word and fantastic ios-charts.

I noted that the latest ios-charts for swift 2.0 cannot compile on XCode7 beta 5 due to the following issue.
The self.dynamicType.allocWithZone(zone) produce the following error:
'allocWithZone' is unavailable in Swift: use object initializers instead

There are a couple of error occurrences.
1- ChartDataEntry.swift
2- ChartDataSet.swift

// MARK: NSCopying

public func copyWithZone(zone: NSZone) -> AnyObject
{

    let copy = self.dynamicType.allocWithZone(zone) as ChartDataSet
    -------
    --------
    return copy
}
I would love finding the trick on my own but.. :-(

Kind Regards,
Patrick

**Comment by AJ9** [comment]
Great work, please merge!

**Comment by danielgindi** [comment]
Merged
