### ISSUE TITLE
saveToCameraRoll strange behavior

### ISSUE THREAD

**Issue by sniis84** [danielgindi/ios-charts#288]
I have a ViewController with a UIView which I use for my lineChart.
Using saveToCameraRoll I don't a proper save of the plot in my Photos but the lineChart result to be cut on the right a bottom edges.
Any possible solution?
![ios simulator screen shot 08 ago 2015 13 10 23](https://cloud.githubusercontent.com/assets/9617798/9150246/e0b74b1a-3dce-11e5-9612-a2cd59972b2c.png)
![ios simulator screen shot 08 ago 2015 13 10 36](https://cloud.githubusercontent.com/assets/9617798/9150247/e0e41fd2-3dce-11e5-9057-7fb532be57ce.png)

**Comment by petester42** [comment]
Did you try to pinch out. The photos app tries to fit the picture to the whole screen. I could "reproduce" it  but pinching to zoom out shows the full image. The image seems right. Hopefully that helps.

Zoomed In:
![zoomed-in](https://cloud.githubusercontent.com/assets/296718/9189046/6912b61e-3fb1-11e5-9add-182de6f16176.png)

Pinched Out:
![pinched-out](https://cloud.githubusercontent.com/assets/296718/9189064/79bbd6f8-3fb1-11e5-8e00-f4379f876f45.png)

**Comment by sniis84** [comment]
wow, that's true.
Thanks so much!
