### ISSUE TITLE
Release Version 2.1.3 on CocoaPods

### ISSUE THREAD

**Issue by sgade** [danielgindi/ios-charts#289]
I noticed the current release [v2.1.3](https://github.com/danielgindi/ios-charts/releases/tag/v2.1.3), although tagged, is not available on CocoaPods.
I think the problem is that the [PodSpec](https://github.com/danielgindi/ios-charts/blob/master/Charts.podspec#L3) is not up to date.

Would be great to use 2.1.3 as it has some nice fixes.

**Comment by petester42** [comment]
fixed. enjoy :smile:

**Comment by sgade** [comment]
Cocoapods.org seems to have some issues right now so I can't see the update but thanks for the effort. :+1:
