### ISSUE TITLE
ChartMarker don't draw

### ISSUE THREAD

**Issue by noais** [danielgindi/ios-charts#293]
With out embedded binaries, using directly the swift files. On the class ChartMarker the method refreshContent is not called.

I found where is the problem on the class ChartViewBase in the func drawMarkers the var drawMarkers is false. I don't know why, but if I remove this var works nicely. 

I'm using the same example code class BalloonMarker.

**Comment by liuxuan30** [comment]
First, in my code, it is true by default.
/// if set to true, the marker is drawn when a value is clicked
    public var drawMarkers = true

Second, it's a public variable, so you can define its value after you created your chartView like `chartView.drawMarkers = true`

**Comment by noais** [comment]
I forced to be true and now works. I suppose by default it was true because is set to true.

Is possible use drawMarkers with Highligh disable? I don't want to see the orange crossed line to see the marker.

**Comment by danielgindi** [comment]
Yes it is, and you can control the visibility of the highlight lines too
