### ISSUE TITLE
lowestVisibleXIndex never gets zero after zooming out

### ISSUE THREAD

**Issue by alinoz77** [danielgindi/ios-charts#294]
This problem is encountered with a LineChartView.

The problem is the float precision, after zooming in and out the lowestVisibleXIndex will 99% of the time return 1 when the chart is completely zoomed out.

Here is the code form BarLineChartViewBase.swift :
```
/// Returns the lowest x-index (value on the x-axis) that is still visible on he chart.
    public var lowestVisibleXIndex: Int
    {
        var pt = CGPoint(x: viewPortHandler.contentLeft, y: viewPortHandler.contentBottom)
        getTransformer(.Left).pixelToValue(&pt)
        return (pt.x <= 0.0) ? 0 : Int(pt.x + 1.0)
    }
```

pt.x will never be 0.0 but it will be something like 0.000000000001 and the index returned will be 1

**Comment by danielgindi** [comment]
This is not the case anymore... Closing!
