### ISSUE TITLE
it has this problem "'#' has been removed from Swift" in many places

### ISSUE THREAD

**Issue by zhuohongxiao** [danielgindi/ios-charts#296]
I put your files in objective-c's project. 
When i compile it Xcode 7.0 beta4. it has this problem  '#' has been removed from Swift; double up ' * *' to make the argument label the same as the parameter name.
Xcode tell me delete '#' to fix it. but it has 185 places. I think it isn't a good choice to fix.
Does anybody have advices? Thank You!!

**Comment by danielgindi** [comment]
please use the `swift-2.0` branch
