### ISSUE TITLE
xcode 6.4 , Swift 1.2 build fail

### ISSUE THREAD

**Issue by mxyzptl** [danielgindi/ios-charts#298]
I would like use IOS-Chart in my Swift project, but i got some fails when I build project. (I'm beginer :-) )

What i did:

1) Create swift project (Empty)
2) Copy Charts.xcodeproj file from Finder to the project folder
3) Add Embeded Binaries (Charts.framework) (red)
4) Build project Cmd+B
5) I got fails (Attachments)

<img width="862" alt="kepernyofoto 2015-08-12 - 22 15 34" src="https://cloud.githubusercontent.com/assets/13771963/9236687/7f783b7c-4146-11e5-9c6b-2d3d77008843.png">
<img width="189" alt="kepernyofoto 2015-08-12 - 22 13 48" src="https://cloud.githubusercontent.com/assets/13771963/9236688/7f7d3262-4146-11e5-993d-b2445125ed1a.png">

**Comment by danielgindi** [comment]
I think you are using the swift-2.0 branch. Swift 2.0 is Xcode 7.
