### ISSUE TITLE
Axis titles?

### ISSUE THREAD

**Issue by timgshi** [danielgindi/ios-charts#299]
Is there a way to define labels for the titles of axes? I'd like to use them to state the units of the y-axis.

For example I'd like a label drawn to the left of the number labels on the y-axis that says "hits / minute" to tell the user the units of the graph.

**Comment by yas375** [comment]
Override `NSNumberFormatter` to returns string as you need. And then set it to the axis:

```objective-c
self.chartView.leftAxis.valueFormatter = [MyCustomNumberFormatter new];
```

**Comment by danielgindi** [comment]
Duplicate https://github.com/danielgindi/ios-charts/issues/35

**Comment by timgshi** [comment]
Sorry, that's not what I meant. I'm talking about titles for the axes, to present unit information. 

Check out the chart below for an example:

![chart](http://pandas-xlsxwriter-charts.readthedocs.org/en/latest/_images/chart_grouped_column_farms.png)

It has the axis titles "Farms" and "Total Produce". Is there any way to create labels like that in ios-charts?

**Comment by yas375** [comment]
Well, then it's indeed a duplicate of #35. Might make sense to add your voice there ;)

**Comment by DJ-Glock** [comment]
> Subclass `NSNumberFormatter` to return strings as you need. And then pass it to the axis:
> 
> ```objc
> self.chartView.leftAxis.valueFormatter = [MyCustomNumberFormatter new];
> ```

I have spent a lot of time to find yAxis property. Did not even think that it can be called "left axis". Thank you! Your comment saved me a lot of time...
