### ISSUE TITLE
Trying to compile demo code，but tons of compiler errors

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#3]
I just synced latest code and tries to run the demo, but I get tons of compiler errors. What configuration I need to set for compiling your demo code?

**Comment by danielgindi** [comment]
In the README it specifies Swift 1.2, Xcode 6.3

**Comment by liuxuan30** [comment]
@danielgindi  I do recommend you consider using Objective-C, not Swift.

**Comment by danielgindi** [comment]
Using ObjC for what?

**Comment by danielgindi** [comment]
And... What is your recommendation based on? :-)

Swift is a new language yes, and I *chose* to write the library in it. Nobody force my hand.

Swift has major performance gains, and is compatible with ObjC. Most of my libraries are written in ObjC so you can see I have nothing against it. Event the ChartsDemo project is written in ObjC.

So... ?

**Comment by wbish** [comment]
It is unfortunate you are using the swift syntax introduced in Xcode 6.3 as it is still in beta. Any apps that actually want to use your library are SOL until 6.3 gets out of beta.

**Comment by danielgindi** [comment]
It's fine by me, as this library has only been online for a few days, and
should considered beta for at least a few days...

Anyway, Swift 1.2 is a must if you want to fully cooperate with ObjC.

‏בתאריך יום שישי, 27 במרץ 2015, William Bishop <notifications@github.com>
כתב:

**Comment by wbish** [comment]
Sounds good. Thanks for your work -- looks cool and I look forward to using it in the future.

**Comment by emartynov** [comment]
I see a lot of warning like `'var' parameters are deprecated and will be removed in Swift 3`. Can I somehow disable it?

**Comment by danielgindi** [comment]
You can try to compile the *latest* code - on the *latest* Xcode.
