### ISSUE TITLE
Pinch zoom release triggers pan

### ISSUE THREAD

**Issue by AlBirdie** [danielgindi/ios-charts#30]
When you zoom in on a chart using a pinch gesture, the charts are sometimes being panned to a different position once the pinch gesture has ended. 
You can, for instance, check the CandleStickChart in your demo project. Other chart types show this as well, though.

**Comment by turkenh** [comment]
Using pods and needs to get this change too, it is not there yet I think. Is there an expected time to release a Pod version including this?

**Comment by turkenh** [comment]
Any way, using 
"pod 'Charts', :head"
did the trick:) 
Working perfectly, thank you very much for the fix...
