### ISSUE TITLE
Possible regression because of recent `startAtZeroEnabled` changes

### ISSUE THREAD

**Issue by yas375** [danielgindi/ios-charts#300]
Without any changes to my code here is what I get if I use this library from 2177f7d

![2015-08-13_1639](https://cloud.githubusercontent.com/assets/217368/9264313/d6a3f48e-41d9-11e5-81be-88d997f5edeb.png)

And here is what I'm getting from current master (2068a5c):

![2015-08-13_1633](https://cloud.githubusercontent.com/assets/217368/9264330/fe68c878-41d9-11e5-879d-eeeb5d3ba882.png)
*(Note `-15` in the left axis and extra space)*

I guess it might be related to recent changes around `startAtZeroEnabled`. In my code I don't this property.

Here are some chart params I set which might be useful to know for debugging the issue:

```objective-c
self.chartView.drawGridBackgroundEnabled = NO;
self.chartView.doubleTapToZoomEnabled = NO;
self.chartView.pinchZoomEnabled = YES;
self.chartView.scaleYEnabled = NO;

self.chartView.legend.form = ChartLegendFormCircle;

self.chartView.xAxis.drawGridLinesEnabled = NO;
self.chartView.xAxis.avoidFirstLastClippingEnabled = YES;
self.chartView.xAxis.labelPosition = XAxisLabelPositionBottom;

self.chartView.rightAxis.enabled = NO;
```

```objective-c
ChartDataEntry *dataEntry = [[ChartDataEntry alloc] initWithValue:value xIndex:index];
```

```objective-c
LineChartDataSet *dataSet = [[LineChartDataSet alloc] initWithYVals:values label:@"bar"];

dataSet.lineWidth = 2.0;
dataSet.drawFilledEnabled = YES;
dataSet.circleRadius = 4.0;
dataSet.drawValuesEnabled = NO;
dataSet.drawHighlightIndicators = NO;
```

**Comment by danielgindi** [comment]
`startAtZeroEnabled` is meant for positive values, when you want to see the *0* point in the axis. It normalizes the axis.
But when you have negative values, we can't just ignore them, they need to be visible.
The new behaviour is the correct one. If you don't want negative values to be visible you can either remove them, or set a custom y axis minimum to 0.

**Comment by liuxuan30** [comment]
I am curious, @yas375 your data only has positive values (first screenshot), but it calculated a negative _yAxisMinimum in second screenshot?

**Comment by danielgindi** [comment]
Well I assumed he has -15 somewhere in his dataset, that is out of the visible range...

**Comment by liuxuan30** [comment]
Yes, in the screenshot I don't see any negative. Need @yas375 to double check.

**Comment by yas375** [comment]
Thanks for the quick feedback!

I don't have any negative data entries:

```
ChartDataSet, label: Bar, 27 entries:
ChartDataEntry, xIndex: 0, value 103.0
ChartDataEntry, xIndex: 1, value 134.0
ChartDataEntry, xIndex: 3, value 202.0
ChartDataEntry, xIndex: 4, value 237.0
ChartDataEntry, xIndex: 7, value 131.0
ChartDataEntry, xIndex: 9, value 114.0
ChartDataEntry, xIndex: 10, value 238.0
ChartDataEntry, xIndex: 11, value 184.0
ChartDataEntry, xIndex: 12, value 274.0
ChartDataEntry, xIndex: 13, value 149.0
ChartDataEntry, xIndex: 14, value 203.0
ChartDataEntry, xIndex: 17, value 134.0
ChartDataEntry, xIndex: 18, value 81.0
ChartDataEntry, xIndex: 19, value 253.0
ChartDataEntry, xIndex: 20, value 250.0
ChartDataEntry, xIndex: 51, value 230.0
ChartDataEntry, xIndex: 52, value 214.0
ChartDataEntry, xIndex: 54, value 116.0
ChartDataEntry, xIndex: 55, value 260.0
ChartDataEntry, xIndex: 56, value 163.0
ChartDataEntry, xIndex: 57, value 234.0
ChartDataEntry, xIndex: 58, value 91.0
ChartDataEntry, xIndex: 59, value 207.0
ChartDataEntry, xIndex: 60, value 92.0
ChartDataEntry, xIndex: 64, value 92.0
ChartDataEntry, xIndex: 65, value 132.0
ChartDataEntry, xIndex: 76, value 12.0
```

And I have 77 values for xAxis and I believe you can use any strings there.
Let me know guys if you can't reproduce the issue with this data and I can try to make a sample project.

Thanks again!

**Comment by yas375** [comment]
Also I've verified locally that 67cb278ee2 makes the difference. Without this commit it works as it was before (my first screenshot).

**Comment by danielgindi** [comment]
Then it must mean that in your case, for some reason, `axisMinimum` is less than zero when the decision to not start at zero is made in the code. Somewhere there in https://github.com/danielgindi/ios-charts/commit/67cb278ee24b5631fce1d3ca3d1603194924f0f7... Do you mind debugging it a little? Or giving a small project demonstrating the problem?

**Comment by alinoz77** [comment]
The -15 value comes form the chart bottomSpaceLeft. 
Without the 67cb278 change the _leftAxis.axisMinimum was set to zero even if you didn't set the leftAxis.customAxisMin.
Now with this change the value is not set to zero and the default is going to use the value calculated in the BarLineChartViewBase.swift  at line 324:

```
        _leftAxis.axisMinimum = !isnan(_leftAxis.customAxisMin) ? _leftAxis.customAxisMin : (minLeft - bottomSpaceLeft)
```

Don't know the complete library to well so I can not decide if the bottomSpaceLeft is really needed, but maybe Daniel can have a look and decide.

**Comment by danielgindi** [comment]
Oh I got it. It's something I missed. bottom spacing is not needed when
starting at zero

‏בתאריך יום שני, 17 באוגוסט 2015, alinoz77 <notifications@github.com> כתב:

**Comment by danielgindi** [comment]
Will fix it soon

‏בתאריך יום שני, 17 באוגוסט 2015, Daniel Cohen Gindi <danielgindi@gmail.com>
כתב:

**Comment by yas375** [comment]
Thanks a lot!
