### ISSUE TITLE
Unknown class _TtC6Charts12BarChartView in Interface Builder file.

### ISSUE THREAD

**Issue by longxianlin** [danielgindi/ios-charts#301]
I copy all class folder to project folder。 and drag them to project fold， no copy，create group， to project。

build is ok
when run， have subject problem

**Comment by danielgindi** [comment]
Thats not the name of the class. When copying the sources manually, the "Charts" namespace does not exist.

**Comment by niksdgr8** [comment]
I am facing the same problem.Can you assist me on how to solve this?

**Comment by danielgindi** [comment]
Have you read my response? When copying the files instead of using as a Framework, you have to specify just `BarChartView`, **not** `Charts.BarChartView`!

**Comment by niksdgr8** [comment]
I am using BarChartView everywhere.
I have created a sample project where it is working fine. But when I am trying to integrate this with my existing project, it is giving this error.

**Comment by danielgindi** [comment]
Look closely and use the correct class name for your situation.

**Comment by ZetrixWeb-iOS** [comment]
![screen shot 2016-10-08 at 12 53 26 pm](https://cloud.githubusercontent.com/assets/7457258/19211269/40c4ec92-8d56-11e6-9073-fd8b2c84f818.png)
![screen shot 2016-10-08 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/7457258/19211273/484d9d42-8d56-11e6-97b8-a04b5e35891d.png)
Same issues.

**Comment by liuxuan30** [comment]
you are using it in XIB? did you change module to Charts?
