### ISSUE TITLE
MyProject-Swift.h header not found when embedding framework into ObjectiveC project

### ISSUE THREAD

**Issue by edulpn** [danielgindi/ios-charts#303]
I tried following the usage guidelines on the README for ObjectiveC projects several times and it never creates the "-Swift.h" header file so I can import.

I do as follows:

1 - Drag the Charts.xcodeproj to my project
![screen shot 2015-08-14 at 3 54 33 pm](https://cloud.githubusercontent.com/assets/4682317/9281758/c316a8a2-429d-11e5-9b10-6640213d02c9.png)

(Cmd + B -> Build Successful)

2 - Go to your target's settings, hit the "+" under the "Embedded Binaries" section, and select the Charts.framework
![screen shot 2015-08-14 at 4 04 02 pm](https://cloud.githubusercontent.com/assets/4682317/9281803/24c34664-429e-11e5-83ea-4d30adfbaabe.png)

(Cmd + B -> Build Successful) This should do step 3 of the Guide

(Since it's a ObjectiveC project, I jump to step 5)
5 - Under "Build Options", mark "Embedded Content Contains Swift Code"
![screen shot 2015-08-14 at 3 56 20 pm](https://cloud.githubusercontent.com/assets/4682317/9281863/babb170a-429e-11e5-8593-603c7413aae7.png)

(Cmd + B -> Build Successful) After this build I think my "-Swift.h" header file should be already generated, so we should be good, right?!

Alright, so by now I should be able to do a simple `#import "NewChartDemo-Swift.h"`, but then:
![screen shot 2015-08-14 at 3 56 55 pm](https://cloud.githubusercontent.com/assets/4682317/9281921/16673e4e-429f-11e5-95f5-a41320d7ebd3.png)

Am I missing something? I wasn't able to achieve the expected results in any of my several tries, looked up StackOverflow for other people having trouble importing Swift Frameworks into ObjectiveC projects and none of the work arounds work for me.

**Comment by polonel** [comment]
I'm fighting this same issue. +1

**Comment by danielgindi** [comment]
Sometimes the -Swift.h header is not created until you manually create a Swift file in your project.
And sometimes you just don't know how to name it correctly...
In your case it is definitely `import "NewChartDemo-Swift.h"`, so I'm guessing that Xcode wants you to manually create a .swift file for it to start creating the -Swift.h file.

So here's what you should do:
1. Remove *Charts* from your project, along with any "NewChartDemo-Swift.h" imports
2. Right click and add a new Swift file
3. Build (a successful build)
4. Import the "NewChartDemo-Swift.h" in one of your files
5. Build again, to make sure it works
6. Add *Charts* back

**Comment by edulpn** [comment]
Got XCode to generate de -Swift.h file, but the only mapped class was my manually created Swift class

![screen shot 2015-08-17 at 10 33 45 am](https://cloud.githubusercontent.com/assets/4682317/9305925/7521b7b0-44cb-11e5-82ee-e248805137b3.png)

What else should I try? What are the steps to import Charts source code into the project, like the iOS7 approach?

**Comment by danielgindi** [comment]
Are you importing the sources manually? Did you make sure that all the files are in your *target*?

**Comment by edulpn** [comment]
First approach I tried was importing/dragging the .xcodeproj file into my project, thought it'd be a good start, but in the future I'll need to support iOS7 when using Charts in an actual app. I'll make sure everything belong to my target and try again. Or is this only applicable to importing the sources manually?

**Comment by edulpn** [comment]
Wow! I think I got it working...

![screen shot 2015-08-17 at 10 45 42 am](https://cloud.githubusercontent.com/assets/4682317/9306198/1e21ece4-44cd-11e5-8402-e1a640a6c202.png)

This time I right-clicked my project -> Add files to... Then selected the whole folder, instead of the .xcodeproj file, like this

![screen shot 2015-08-17 at 10 46 49 am](https://cloud.githubusercontent.com/assets/4682317/9306230/56443c3a-44cd-11e5-8eb0-bec7ee5f3594.png)

Now it looks like I can use Charts classes on my ObjectiveC project. I'll keep the post updated.

**Comment by edulpn** [comment]
Yeah, it does work for me and people from my team. So, for anyone who should face the same issue in the future, add files to project selecting the whole folder (in the picture above) instead of dragging the .xcodeproj file worked for me.

![screen shot 2015-08-17 at 10 56 58 am](https://cloud.githubusercontent.com/assets/4682317/9306494/146e50be-44cf-11e5-885c-ace68337c06e.png)

**Comment by danielgindi** [comment]
Or guys, just read the README. It specifically says that for iOS 7 you should add the .swift files, not the framework!

**Comment by edulpn** [comment]
And by the way, AWESOME library @danielgindi , you're getting a dinner + beer sometime soon :)

**Comment by danielgindi** [comment]
Thanks :-)

**Comment by edulpn** [comment]
Ah, this was for iOS 8... I'll try iOS 7 later.

**Comment by danielgindi** [comment]
iOS7 is what you finally did...

**Comment by edulpn** [comment]
Gotcha... Thanks for the help!

**Comment by acegreen** [comment]
Why does this NewChartDemo-Swift.h go? and do we need it. I have a swift project and a bridging header. but can't do # import "NewChartDemo-Swift.h". I took it out and in my swift file did import Charts. 

PS I'm on iOS and added this as a embedded framework as per instructions

**Comment by liuxuan30** [comment]
${Your project name}-Swift.h is for objc based project to use swift code I remember. It is generated by XCode, to translate swift code to a header file for objc to import. If you don't need to use swift in objc project, you don't need it. As you can see you are simply a swift project, everything is swift.

**Comment by acegreen** [comment]
@liuxuan30 Ah crap. I got rattled by this without reading that ITS FOR AN OBJECTIVE-C PROJECT!!!

Though I'm left with one issue still

<img width="1259" alt="screen shot 2015-09-07 at 10 15 42 pm" src="https://cloud.githubusercontent.com/assets/10794609/9725028/088a604a-55ae-11e5-8852-a94256481225.png">

**Comment by liuxuan30** [comment]
then it goes to swift :-) Check how your 'object' is declared.

**Comment by acegreen** [comment]
@liuxuan30 to be honest, I'm not yet familiar with Charts library. The error is in the "ChartSelectionDetail" file

**Comment by acegreen** [comment]
I have a feeling this is a bug in Xcode 7 beta 6

**Comment by liuxuan30** [comment]
@acegreen try stackoverflow. or create a new issue with details, current info cannot tell what's wrong. To me it's more like a swift compiler error. should be easy resovled on SO

**Comment by inix** [comment]
I also have this issue for a fresh object-C project import framework followed by README, as @danielgindi said, you need first create a dummy swift file into an Object-C project,then Xcode will prompt a dialog that it will create needed briaged file for you,like follow image.  
![qq20161103-0](https://cloud.githubusercontent.com/assets/2264291/19959388/6739e194-a1e1-11e6-8611-4c6721856332.png)

**Comment by inix** [comment]
I also have this issue for a fresh object-C project import framework followed by README, as @danielgindi said, you need first create a dummy swift file into an Object-C project,then Xcode will prompt a dialog that it will create needed briaged file for you,like follow image.
![qq20161103-0](https://cloud.githubusercontent.com/assets/2264291/19959402/7d87d906-a1e1-11e6-9f29-c7d73077848c.png)

Thank for this excellent chart solution. 
I hope this will help you!

**Comment by venkatesh4446** [comment]
I have framework using bridge file created in sample framework project and i import same bridge file in another project.So i will import same bridge file in framework project and sample project means what happen?
