### ISSUE TITLE
Zero valued slices overlap

### ISSUE THREAD

**Issue by christosc** [danielgindi/ios-charts#305]
Hi,
I'm trying to use ios-charts to show some pie charts.  Some of the values of the pie are zero and they seem to overlap one another.  For example

![screen shot 2015-08-17 at 10 34 33 am](https://cloud.githubusercontent.com/assets/120986/9300186/0615dbde-44cc-11e5-972a-50f5b7e4f830.png)

Slices B and C, which have values 0, are completely indistinguishable.  Is there some way to have such zero-valued labels not shown on the pie, while leaving them on the legend?  I've found a way to achieve this by tweaking PieChartRenderer.swift, but I wondered If there's some better way. 

Thank you very much for your work and for any help.

**Comment by alinoz77** [comment]
The simple solution is to filter your input array and remove the zero values and add a custom legend. 

```
yourChart.legend.setCustom(colors: [UIColor.redColor(), UIColor.greenColor(), UIColor.blueColor(), UIColor.blackColor()], labels: ["A", "B", "C", "D"])
```

**Comment by christosc** [comment]
That worked great!
Thank you very much for your help!
