### ISSUE TITLE
Line Chart Line is not drawing properly for the large yValues

### ISSUE THREAD

**Issue by faizandedia** [danielgindi/ios-charts#307]
I tried to integrate line chart but it seems it is not drawing it properly for the large yValues see the attached screenshot. see the screenshot. for small values it works fine.

<img width="348" alt="screen shot 2015-08-19 at 9 22 17 am" src="https://cloud.githubusercontent.com/assets/185690/9349285/b86c6e40-4654-11e5-9b49-8e825d721947.png">

**Comment by liuxuan30** [comment]
You need to provide the data sets so we can try reproduce. From the screenshot we can't tell what's wrong.

**Comment by faizandedia** [comment]
Here is the data I have 

		LineChartView *chartView = view.chartView;
        NSMutableArray *xVals = [[NSMutableArray alloc] initWithObjects:@“Jun“,@”Jul”,@“Aug”, nil];
        
        
        NSMutableArray *yVals = [[NSMutableArray alloc] init];
        [yVals addObject:[[ChartDataEntry alloc] initWithValue:12238 xIndex:0]];
        [yVals addObject:[[ChartDataEntry alloc] initWithValue:14022 xIndex:1]];
        [yVals addObject:[[ChartDataEntry alloc] initWithValue:9286 xIndex:2]];
        
       
        LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithYVals:yVals label:@"DataSet 1"];
        
        set1.lineWidth = 3.0;
        set1.circleRadius = 7.0;
        [set1 setColor:[UIColor whiteColor]];
        [set1 setCircleColor:[UIColor whiteColor]];
        set1.circleHoleColor = [UIColor colorWithRed:0 green:155/255.0f blue:223/255.0f alpha:1.0];
        set1.drawCircleHoleEnabled = true;
        set1.drawValuesEnabled = false;
        set1.drawFilledEnabled = false;
        
        NSMutableArray *dataSets = [[NSMutableArray alloc] init];
        [dataSets addObject:set1];
        
    
        LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
        chartView.data = data;

**Comment by liuxuan30** [comment]
giving the value 9286, 12238, 14022, I think your distance on y axis is fine. Have you looked at what's the yAxis range?

**Comment by faizandedia** [comment]
I set the values for customAxisMin and Max, still giving the same result:

        double maxValue = MAX([value1 doubleValue], [value2 doubleValue]);
        maxValue = MAX(maxValue, [value3 doubleValue]);
        
        double minValue = MIN([value1 doubleValue], [value2 doubleValue]);
        minValue = MIN(minValue, [value3 doubleValue]);
    
        chartView.leftAxis.customAxisMax = maxValue;
        chartView.leftAxis.customAxisMin = minValue;
        chartView.leftAxis.startAtZeroEnabled = false;

**Comment by liuxuan30** [comment]
should be your setup problem, I don't have trouble with customAxisMax. 
What's the order of calling chartView.data = yourData and chartView.leftAxis.customAxisMax = maxValue?
Have you tried to call `notifyDataSetChanged`?

**Comment by faizandedia** [comment]
I tried to do that as well, still same output. Here is the full sample code

LineChartView *chartView = view.chartView;
    NSMutableArray *xVals = [[NSMutableArray alloc] initWithObjects:@“Jun“,@”Jul”,@“Aug”, nil];


    NSMutableArray *yVals = [[NSMutableArray alloc] init];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:12238 xIndex:0]];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:14022 xIndex:1]];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:9286 xIndex:2]];

LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithYVals:yVals label:@"DataSet 1"];
        
        set1.lineWidth = 3.0;
        set1.circleRadius = 7.0;
        [set1 setColor:[UIColor whiteColor]];
        [set1 setCircleColor:[UIColor whiteColor]];
        set1.circleHoleColor = [UIColor colorWithRed:0 green:155/255.0f blue:223/255.0f alpha:1.0];
        set1.drawCircleHoleEnabled = true;
        set1.drawValuesEnabled = false;
        set1.drawFilledEnabled = false;
        
        NSMutableArray *dataSets = [[NSMutableArray alloc] init];
        [dataSets addObject:set1];
        
        double maxValue = MAX([value1 doubleValue], [value2 doubleValue]);
        maxValue = MAX(maxValue, [value3 doubleValue]);
        
        double minValue = MIN([value1 doubleValue], [value2 doubleValue]);
        minValue = MIN(minValue, [value3 doubleValue]);
    
        chartView.leftAxis.customAxisMax = maxValue;
        chartView.leftAxis.customAxisMin = minValue;
        chartView.leftAxis.startAtZeroEnabled = false;
        
        LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
        chartView.data = data;
        [chartView notifyDataSetChanged];

**Comment by faizandedia** [comment]
The issue is fixed, somehow view was clipping the line from maxValue, I added extra margin in maxValue so It can be inside the view.

 chartView.leftAxis.customAxisMax = maxValue + 500; // margin

Thanks for the help.. :)
