### ISSUE TITLE
Ability to disable legends completely

### ISSUE THREAD

**Issue by deepumukundan** [danielgindi/ios-charts#312]
I could not find a method/setting that would allow to disable the legend completely and reuse the area available for the legend for the chart view itself. Suppose I have a 100 x 100 view and set it as a pie chart view, the legend takes up space on the bottom (default setting). If I mask off the legend somehow since I did not find an api for that (using clear color) the area still shows up empty (the chart is on the upper ~80-90% of the view it seems. Is there a way to completely disable the legend and show the chart in the center of the view?
<img width="185" alt="screen shot 2015-08-23 at 10 34 56 am" src="https://cloud.githubusercontent.com/assets/1459484/9429387/3cd1d676-4983-11e5-9d5e-1ac6e730fce3.png">

**Comment by liuxuan30** [comment]
I remember setting `ChartLegend.enabled = false;` will not calculate the space? Anway, take a look at `calculateOffsets()` in `PieRadarChartViewBase`, it calculates the space there. You should be able to change it.

**Comment by deepumukundan** [comment]
Whoa! That did it. I poured over each and every property of ChartLegend, but should have just looked at the super class. Thanks @liuxuan30
Closing issue!

**Comment by Ged2323** [comment]
This also works.

ChartLegend *l = _chartView.legend;
    l.enabled = false;
