### ISSUE TITLE
how to place the Y axis label at the bottom of the chart?

### ISSUE THREAD

**Issue by whatya** [danielgindi/ios-charts#314]
how to place the Y axis label at the bottom of the chart?

**Comment by liuxuan30** [comment]
take a look at renderAxisLabels and YAxisLabelPosition. There is only two options:
        case OutsideChart
        case InsideChart
I guess you have to override `public override func renderAxisLabels`

**Comment by whatya** [comment]
i was wrong, i mean how to put the X axis values at the bottom of the chart

**Comment by liuxuan30** [comment]
It's the same.. each axis has its own renderAxisLabels implementations. BTW, the x axis values are already at the bottom. I don't get it.
