### ISSUE TITLE
iOS Chart Y-Axis High Limit

### ISSUE THREAD

**Issue by amycheong19** [danielgindi/ios-charts#317]
I'm having a set of volume for example: 1- 10 but the Y-Axis bar top is 1000 which I have no idea why it expand that much. Is there something need to be set? Why there is a lot of space on top>=?
<img width="554" alt="screen shot 2015-08-25 at 9 50 02 pm" src="https://cloud.githubusercontent.com/assets/9781961/9468444/3c0a4906-4b74-11e5-90b2-05ede457f5d2.png">

Here is the chart settings.
    
     bottomCombinedChartView.descriptionText = ""
        bottomCombinedChartView.noDataTextDescription = ""
        bottomCombinedChartView.noDataText = "Loading chart..."

        bottomCombinedChartView.highlightEnabled = true
        bottomCombinedChartView.dragEnabled = true
        
        bottomCombinedChartView.pinchZoomEnabled = true
        bottomCombinedChartView.doubleTapToZoomEnabled = true
        bottomCombinedChartView.drawGridBackgroundEnabled = false
        
        bottomCombinedChartView.rightAxis.enabled = true
        bottomCombinedChartView.leftAxis.enabled = false
        bottomCombinedChartView.drawBarShadowEnabled = false
        bottomCombinedChartView.legend.enabled = false        
        bottomCombinedChartView.setViewPortOffsets(left: 0, top: 0, right: 0, bottom: 0)
        
    var yAxis: ChartYAxis = bottomCombinedChartView.rightAxis
        yAxis.startAtZeroEnabled = false
        yAxis.labelPosition = .InsideChart
        yAxis.drawAxisLineEnabled = false

**Comment by liuxuan30** [comment]
If you did nothing, it will calculate the y axis range depending on your data values' range. Double check if you have some values that is abnormally large but not shows up.

On the other hand, you could use yAxis.customAxisMax to set the max value.

**Comment by noais** [comment]
Maybe this alteration can help you: #382

**Comment by noais** [comment]
#388

**Comment by danielgindi** [comment]
Please check to see if the problem still persists with the latest version.
