### ISSUE TITLE
Animated moveViewToX()

### ISSUE THREAD

**Issue by tomastiminskas** [danielgindi/ios-charts#318]
I think it's not an issue but I couldn't find a solution so maybe you can help me. 

I implemented ios-charts on a swift application I am working on and composed a graph to show some information. The graph has set setVisibleXRangeMaximum(9.0) but has more than 30 values, so the user can scroll on the graph.

I could center the selected bar on the screen when the user tap on some of the graph bars, but I can't animate it. I am using moveViewToX() method to move to an specific index. Is there a way to do the same as "moveViewToX()" does but animated?

**Comment by danielgindi** [comment]
Duplicate #189

**Comment by danielgindi** [comment]
I thought that this was a duplicate of #189, but it's a different kind of animation. It should actually be pretty easy to implement

**Comment by tomastiminskas** [comment]
Thanks a lot Daniel. Waiting for the implementation of moveViewToX() with animation.

**Comment by tomastiminskas** [comment]
Daniel, have you been able to add this feature to the library? Thanks in advance

**Comment by kexoth** [comment]
:+1:

**Comment by idenjoe** [comment]
Are you planning to add this feature soon?? Thanks.

**Comment by liuxuan30** [comment]
really this is carried out :)
