### ISSUE TITLE
Bug: Xcode 7 beta 5: dyld: Library not loaded: @rpath/Charts.framework/Charts

### ISSUE THREAD

**Issue by gaborvadasz** [danielgindi/ios-charts#326]
Hello,

The charts works in simulator perfectly, but when I build for device, and starting app, I receive the following error in console:

dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/mobile/Containers/Bundle/Application/92EF72C5-C1C2-4551-94E6-28BE32ED57F4/My.app/My App
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/92EF72C5-C1C2-4551-94E6-28BE32ED57F4/My.app/Frameworks/Charts.framework/Charts: mmap() error 1 at address=0x00280000, size=0x00130000 segment=__TEXT in Segment::map() mapping /private/var/mobile/Containers/Bundle/Application/92EF72C5-C1C2-4551-94E6-28BE32ED57F4/My.app/Frameworks/Charts.framework/Charts

iOS 8, Swift 2 branch, full swift project, xcode 7

How can I fix it?

Thanks,
Gabor

**Comment by danielgindi** [comment]
Please search the issues for similar issues
