### ISSUE TITLE
UIPanGestureRecognizer causes index out of bounds crash

### ISSUE THREAD

**Issue by steprescott** [danielgindi/ios-charts#327]
A tester has came back to me saying that when they stress test the double tap gesture of a chart it causes a crash.

I have been able to reproduce this issue and when it crashes the below exception is logged.
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[UIPanGestureRecognizer locationOfTouch:inView:]: index (0) beyond bounds (0).'
```
From looking at your Classes I can see that only the `BarLineChartViewBase` has a `UIPanGestureRecognizer `.

A potential fix to avoid this crash is to check for the number of touches before processing the gesture.

I have modified the first line in the `panGestureRecognized` method of the `BarLineChartViewBase` Class to 
```
if (recognizer.state == UIGestureRecognizerState.Began && recognizer.numberOfTouches() > 0)
```

**Comment by danielgindi** [comment]
Will work on a fix soon. Actually numberOfTouches will ALWAYS be > 0, when the state is "began", or when another finger is added. I guess this is caused in a state of END or CANCEL.

**Comment by danielgindi** [comment]
Or maybe it is related to this: http://stackoverflow.com/questions/12066821/pan-gesture-is-crashing-while-taking-the-location-of-touch-in-view-in-ios

**Comment by danielgindi** [comment]
After further research - it seems like `UIPanGestureRecognizer` is indeed unstable under stress testing. Causing 0 touches when it has a minimum of 1. Could be a bug in iOS 8 or something. Anyway I'll add a fix.
