### ISSUE TITLE
Can I implement this kind of chart with this library?

### ISSUE THREAD

**Issue by sacrious** [danielgindi/ios-charts#328]
![graficospresion](https://cloud.githubusercontent.com/assets/11412726/9562473/aac118d2-4e32-11e5-94c6-611b5ef18e21.PNG)

Thank you for your support

**Comment by liuxuan30** [comment]
Of cause you can using this library, as long as how it works. Simply rewrite drawDataSets and drawData

**Comment by sacrious** [comment]
hello, thank u...How can I change xAxis value by sending an array? is it possible?

**Comment by liuxuan30** [comment]
I am not sure what's your question. xAxis will display the text whatever you give.

**Comment by liuxuan30** [comment]
Closing, feel free to reopen it for more questions
