### ISSUE TITLE
Extending lines between data points when zoomed and panning

### ISSUE THREAD

**Issue by micnguyen** [danielgindi/ios-charts#330]
Hi,

I've implemented a "time-series" graph by basically creating a chartview with lots of intervals (where each interval is 1 minute) ie: there is a data point at interval 1 and interval 61 if they are 1 hour apart.

I've noticed when I zoom into some points and panned across that the line connecting 2 data points will extend out beyond the limits of the start/end points of the line even if the data-points have disappeared form the view port.

I have made a recording of the bug in action: http://gfycat.com/SarcasticCarefreeGalapagostortoise

**Comment by liuxuan30** [comment]
Did you modify `drawLinear` or `drawCubic`? If not, could you help debugging it? Should be an issue that if the interval is wider than screen width, it cannot find proper data point to connect and leads to weird behaviour.

**Comment by kwoylie** [comment]
Hey,

I have fixed the issue, I haven't checked it into github, since I'm not too sure what the ramifications are. But below is the description of my fix:

<b>BEFORE:</b>
<b>drawLinear</b> function was getting chart entries that is inside the bounds of the view by doing the following:
<code>
```swift
internal func drawLinear(#context: CGContext, dataSet: LineChartDataSet, entries: [ChartDataEntry]) {
        ...
        var entryFrom = dataSet.entryForXIndex(_minX)
        var entryTo = dataSet.entryForXIndex(_maxX)
        ....
}
```
</code>
<b>AFTER:</b>
So I added the follow functions to <b>ChartDataSet</b> class to give me the entry before the first visible entry and the entry after the last visible entry.

<code>
```swift
public func entryForBeforeXIndex(x: Int) -> ChartDataEntry?
{
        var index = self.entryIndex(xIndex: x)
        if (index > -1)
        {
            return _yVals[max(0,index-1)];
        }
        return nil
}
    
public func entryForAfterXIndex(x: Int) -> ChartDataEntry?
{
        var index = self.entryIndex(xIndex: x)
        if (index > -1)
        {
            
            return _yVals[min(index+1, _yVals.count-1)];
        }
        return nil
}
```
</code>
Then I changed the drawLinear function to this instead:
<code>
```swift
internal func drawLinear(#context: CGContext, dataSet: LineChartDataSet, entries: [ChartDataEntry]) {
        ...
        var entryFrom = dataSet.entryForBeforeXIndex(_minX)
        var entryTo = dataSet.entryForAfterXIndex(_maxX)
        ....
}
```
</code>

It'll be great, if you guys can apply the changes the library if it doesn't break anything else.

**Comment by liuxuan30** [comment]
@micnguyen try it out! @kwoylie you could raise a PR and let @danielgindi has a review.

**Comment by micnguyen** [comment]
@liuxuan30 @kwoylie fix does indeed fix this issue as well as #130. The core problem at hand is when the viewport changes, the data points no longer exist and there is funny rendering issues that come with that. Admittedly, this does come at a performance hit as it's looking at a much larger range of values, but the hit is temporarily worth the frequent and visible visual glitch.

**Comment by liuxuan30** [comment]
I saw this in my project :( today Seems we need a enhancement.

**Comment by danielgindi** [comment]
Well I don't see this anymore, so I guess we fixed it in a commit somewhere :-)
