### ISSUE TITLE
how can i disable the doubles? i only need the chat show int data

### ISSUE THREAD

**Issue by whatya** [danielgindi/ios-charts#332]
thanks!!

**Comment by AlBirdie** [comment]
Numberformatters are your friend.

**Comment by whatya** [comment]
whats the api? my project was written in object-c, so i mix swift, its hard for me to see the api

**Comment by AlBirdie** [comment]
There's a valueFormatter property on the ChartYAxis.

**Comment by whatya** [comment]
thank you so much

**Comment by AlBirdie** [comment]
You are very welcome. In case that that solved your issue, please close this issue.

**Comment by Losering** [comment]
@whatya Can you show  the code?
