### ISSUE TITLE
Adding Large number of data points -- addEntry()

### ISSUE THREAD

**Issue by ajaybhat1987** [danielgindi/ios-charts#333]
My requirement is to draw/plot real time graph.

I am using Remote I/O units and apple accelerate framework to extract raw audio sample and perform FFT for frequency analysis.  (approx with around 44100 data packets /sec or LESS )

Can I use ios-charts with such huge amount of real time data flowing? 
What is the best way possible to display huge number of audio samples per second in graph UI. (SImilar to other graph engines).  Please help.
Can it be possible similar to https://www.youtube.com/watch?v=DOwCKfRdn5k

Thank you,
Ajay

**Comment by liuxuan30** [comment]
I think you could, but the performance is what I worried. I tried ~1000 data points in one chart, works great. Not sure how many entries you would have in one chart?

**Comment by ajaybhat1987** [comment]
@liuxuan30  The graph seems to get clumsy and slow.. I am not able to test for more than ~ 1000 data points in an average.. Can you suggest if i am doing it right -
I am calling the method " - (void)addEntry:(ChartDataEntry * __nonnull)e dataSetIndex:(NSInteger)dataSetIndex;" multiple times after giving a short delay.. Is it the right way? Any reference for this to work this out... 
Thank you, Ajay

**Comment by liuxuan30** [comment]
Sorry pal I haven't tried addEntry like your case. You need to try on your side. You could use addEntry, but I am wondering if each adding will cause a re-render and slow you down.

**Comment by liuxuan30** [comment]
@ajaybhat1987 have you tried it?

**Comment by liuxuan30** [comment]
Closing - feel free to reopen if any problem
