### ISSUE TITLE
For CandleStickChart, how can I limit according to the count of candles

### ISSUE THREAD

**Issue by YariZhang** [danielgindi/ios-charts#334]
Suppose it has 200 candles, but I just need to show some of them when it started, for example, 60, but not all of them, and I want to limit the width of the candle, what should I do? Thank you!

![image](https://cloud.githubusercontent.com/assets/11606388/9578318/4f3f9a52-501b-11e5-8a7a-e228a16275b7.png)

**Comment by AlBirdie** [comment]
Has this been solved by #348 as well then? If so, please close the issue. Thanks.

**Comment by AlBirdie** [comment]
Cheers mate! :)
