### ISSUE TITLE
Position Pie Chart over the View

### ISSUE THREAD

**Issue by pezzetti** [danielgindi/ios-charts#337]
how i can change the pie chart position on the view? My legend isn't showing correct, look at the image

Thank you
<img width="372" alt="piechart" src="https://cloud.githubusercontent.com/assets/6005103/9607021/23a9d5ce-509d-11e5-9512-dba830d735d0.png">

**Comment by liuxuan30** [comment]
You could move your chart view to anywhere you like by setting it's center. For the legend, there are too many reasons for not showing correctly... I suggest you take a look at the ChartsDemo pie chart view controller code. and the ChartLegend code to understand how it is displayed.
