### ISSUE TITLE
IBInspectable support?

### ISSUE THREAD

**Issue by garnett** [danielgindi/ios-charts#34]
There are a lot simple properties (like BOOLs for configuring lineChart) that can be easily tweaked from interface builder. 

http://nshipster.com/ibinspectable-ibdesignable/

What do you think? I can submit a pull-request if the idea works for you.

**Comment by garnett** [comment]
UPD: looking at the code it would be not so easy:) Because a lot of properties have custom getters/setters

**Comment by danielgindi** [comment]
It's easy to make it IBDesignable, but it won't help you see actual data as the DataSet is set separately...

**Comment by garnett** [comment]
@danielgindi but I'm speaking about IBInspectable, it will allow to tweak graph properties from Interface BUilder

**Comment by danielgindi** [comment]
IBInspectable and IBDesignable are the two parts of the same thing. 
Again, it will not allow you to define a dataset and see the changes

**Comment by davecom** [comment]
Daniel,
We're not necessarily talking about the data set - just general look & feel properties of the graph.  It would be much more convenient to be able to manipulate them in IB instead of having to dig into the (you must admit) fairly massive API.
