### ISSUE TITLE
Multiple line Chart, same view

### ISSUE THREAD

**Issue by djbennyj** [danielgindi/ios-charts#340]
Hello, and thanks for his awesome library.

I would liike to know if it it possible to display 2 line charts at the same time.

I have a game, with 3 difficulty level, and on the stat page, i would like to display 3 lines, for each level of difficulty.

On xAxis would days, and on Yaxis the average score.

With 1 line for each difficulty level.

Is that possible?

ps : I managed to do what i want for 1 line, butcant figure out how to deal with the others.
<img width="358" alt="screen shot 2015-09-04 at 6 39 24 pm" src="https://cloud.githubusercontent.com/assets/14123979/9680786/5396c640-5334-11e5-93a9-f790e7639e0b.png">

Thanks  a lot for your help.

Ben

**Comment by JackLeeMing** [comment]
you can do that , just set datasets , you can set a Array but they use same xAxis

**Comment by danielgindi** [comment]
As @JackLeeMing said - just add multiple DataSets. Instead of passing a `dataSet` argument to your Data object, pass a `dataSets` argument (plural).
