### ISSUE TITLE
HELP : some problem never met about iOS-charts

### ISSUE THREAD

**Issue by lizan402** [danielgindi/ios-charts#341]
![Uploading 屏幕快照 2015-09-06 下午8.42.03.png…]()
I run my  progress  on  iPhone4s , it  works successfully
 ,but with 10  faults.
Faults  like :
1. Unknown type name 'LineChartView'
2.Property with 'retain (or strong)' attribute must be of object type
as shown in the figure;

**Comment by danielgindi** [comment]
Make sure that the framework is compiling correctly before using it.  
Follow the instructions in the README, and then compile.  
Only after that - add the charts to your view. If you are using as an Embedded Framework, then you will need to use the namespace (`Charts.LineChartView`).

**Comment by lizan402** [comment]
I have  follow your  step(usage)  to  compile.  but  it won't  show  fault  at  simulator. only on  real iPhone.
and   Under   the class  using  this framework  is selected, it  will  be  10  error. but when  other  class  is   selected  , it  won't.  that's  very  weird.  Werther  there is  error, it always  run  successfully.  

My progress  is based on  Object-C.   "Charts.LineChartView  "  you said  is Swift's   grammar?

looking forward your  answer.

**Comment by liuxuan30** [comment]
You have to be clear what are the errors, iOS version, etc. only on real iPhone you mean archive or just debugging? There's not enough info.

If you are objc project on iOS 7, make sure you set up your project for swift correctly, checkout https://github.com/danielgindi/ios-charts/issues/270

**Comment by danielgindi** [comment]
Please follow the README to the point. Read carefully. The instructions are pretty simple.

If you are still having trouble, then post examples of your problem so the people trying to help can diagnose it. 

Feel free to re-open if the issue was not resolved yet.
