### ISSUE TITLE
Swift-2.0 Branch Error

### ISSUE THREAD

**Issue by acegreen** [danielgindi/ios-charts#344]
I'm getting the following issue:

This is happening in the "ChartSelectionDetail" file

Some are saying its an Xcode bug. 

- Xcode 7 beta 6
- Embedded framework method

<img width="1259" alt="screen shot 2015-09-07 at 10 15 42 pm" src="https://cloud.githubusercontent.com/assets/10794609/9725337/19eefcde-55b2-11e5-834c-f63e4223f8d9.png">

**Comment by acegreen** [comment]
More info on this:

Straight from the logs:

/Users/AceGreen/Dropbox/iOS/Xcode Projects/StockSwipe/Charts/Classes/Utils/ChartSelectionDetail.swift:76:19: error: ambiguous use of 'dataSet'
        if (object!.dataSet !== _dataSet)
                  ^
/Users/AceGreen/Dropbox/iOS/Xcode Projects/StockSwipe/Charts/Classes/Utils/ChartSelectionDetail.swift:47:16: note: found this candidate
    public var dataSet: ChartDataSet?
               ^
Charts.ChartSelectionDetail:7:13: note: found this candidate
  @objc var dataSet: ChartDataSet? { get }
            ^

**Comment by liuxuan30** [comment]
I am with latest Xcode 6, not seeing this.... Tried clean & rebuild?

**Comment by acegreen** [comment]
Update: Added the same instance of the library (copied from my project where it gives me the error) to a test project and it works. 

Something in my project is causing a clash

**Comment by acegreen** [comment]
Issue Resolved:

The variable above seems to clash somewhere, changing it from private to normal, solves the problem

    var dataSet: ChartDataSet?
    {
        return _dataSet
    }

**Comment by hooman96** [comment]
Can we convert the syntax with Xcode Beta?

**Comment by 931743010** [comment]
convert the syntax with Xcode7，there have five syntax can‘t be fixed

**Comment by nikhil-pagalguy** [comment]
I am still getting this error "/Users/Niks/Music/smartbanking1/Charts/Classes/Utils/ChartSelectionDetail.swift:76:19: Ambiguous use of 'dataSet'"

I am using latest master branch (yesterday). XCode 7.0. Please help.... Tried everything. Even removing public from function does not help......

**Comment by danielgindi** [comment]
I assume you have dragged `Charts`' files into your project. Please remove them all, and copy the fresh files to your project.

**Comment by nikhil-pagalguy** [comment]
hey dan, thanks for quick reply. I have dragged 'Charts' module to project and added 'Charts.framework' into embedded binaries for my target. Are you suggesting that I delete that module and copy all files inside module to my project itself?

**Comment by danielgindi** [comment]
No, I just thought that your problem may be *because* of dragging the files themselves, and maybe a file missing or not up to date.

Can you create a simple project that demonstrates the compilation problem? Because we are not seeing this.

**Comment by nikhil-pagalguy** [comment]
Hey Dan, I created seperate project but this error does not occur there. So, I think its messing with one of the variable in my project only. I have mulitple libraries like Restkit, AFNetworking and Shinobi Charts along with ios charts. I will try to remove all and then may be try to add them again. But do you have any idea why this error occurs only in new xCode 7 and swift 2? I have been your excellent library for about year now and it worked great for me. but this little thing has caused me about 24 hours now. Let me know....

**Comment by danielgindi** [comment]
I have no idea, as there is not problem actually. It can be a bug in Xcode
7... It can be that you need to clean up the "derived data" folder
