### ISSUE TITLE
Pie chart is getting drawn again and again on rotation in iOS 

### ISSUE THREAD

**Issue by harshcs** [danielgindi/ios-charts#346]
I am rotating the pie chart and it keeps adding the new state without removing the earlier one. Thus, resulting in Overlapping. Please let me know why is happening??
<img width="304" alt="screen shot 2015-09-08 at 10 56 10 am" src="https://cloud.githubusercontent.com/assets/1318176/9727061/546311f0-5618-11e5-92e3-4253b5f8dfe6.png">

**Comment by danielgindi** [comment]
You've given a transparent `backgroundColor`, while `opaque` is set to `YES`. You have a conflict. You should look at the documentation of `UIView`.
