### ISSUE TITLE
[BUG] highlighted bar animation on Y Axis for all bar charts is wrong and not same speed

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#349]
Easy to reproduce:
1. simply navigate to stacked bar chart in ChartsDemo
2. highlight the top bar or bottom bar, or the middle one
3. click options and choose animate Y, and watch the animation
You will see the highlighted bar's rect animation is not correct, and the timing is not the same too. The highlighted bar should be same speed as the background bar's speed

Update:
This bug happens on stacked horizontal bar chart, normal bar chart, all bar charts type, as long as we have highlighted the bar.

**Comment by liuxuan30** [comment]
For the speed issue, I change `y2 = (ranges?.last?.to ?? 0.0) * Double(_animator.PhaseY)` to `y2 = (ranges?.last?.to ?? 0.0) * Double(1)` will solve it, though I am not quite clear why.

**Comment by danielgindi** [comment]
Well I see the problem, but your suggestion does not solve it.
Interesting bug... Looking into this
