### ISSUE TITLE
adding cross platform feature

### ISSUE THREAD

**Issue by hooman96** [danielgindi/ios-charts#350]
Can we add cross platform feature to this project? great and useful charts

**Comment by liuxuan30** [comment]
what you mean by cross platform feature?

**Comment by hooman96** [comment]
cross platform means that we can add frameworks that make it possible to deploy these charts on both iOS and android!

**Comment by danielgindi** [comment]
This is already cross platform

**Comment by liuxuan30** [comment]
You can look at REAMDME and it indeed tells you there is android portion.

**Comment by AlBirdie** [comment]
Literally the very first sentence of the project description (which you can find on the starting page of ios-charts) states this!
Amazing, really...

**Comment by AlBirdie** [comment]
I guess this can be closed then.
So much clutter in the bug reports here...

**Comment by danielgindi** [comment]
Yes it's a lot of clutter. My personal life stole some time from Charts ;-)
I'll do some order here soon, along with some bug fixes a features
