### ISSUE TITLE
drawFillEnabled in line chart bug?

### ISSUE THREAD

**Issue by ekhall** [danielgindi/ios-charts#351]
![img_1182](https://cloud.githubusercontent.com/assets/1452508/9748169/d05fa0ec-5650-11e5-9b6c-f82f5beac775.PNG)

I presume this is not the correct fill pattern for drawFilledEnabled?

**Comment by liuxuan30** [comment]
Do you have the data set code, so we can use it in ChartsDemo and reproduce? I think there is bug, but I don't see it when all valus are positive.

**Comment by ekhall** [comment]
I didn’t save it Daniel - I’m sorry. But I avoided it by turning off cubic.

**Comment by liuxuan30** [comment]
@ekhall , then for the linear filling, any problem?

**Comment by ekhall** [comment]
So far no - it works great!

**Comment by liuxuan30** [comment]
Then closing. I don't see draw cubic filling has problem. And if you could help provide the data sample, reopen it and we will look into it.
