### ISSUE TITLE
Using Embedded Binaries giving build failed error in xcode 7 ?

### ISSUE THREAD

**Issue by 34tm4n** [danielgindi/ios-charts#354]
I am using the framework for iOS 8 using swift 2.0 in Xcode 7 beta 4 but when in add Charts.framework in Embedded Binaries and build then it gives me build failed dialogue without prompting to any error window.

**Comment by petester42** [comment]
You need to update Xcode. In the beta versions of Xcode the language has change quite a bit version to version. Currently I believe that the library will work with beta 6 and gm.
