### ISSUE TITLE
Unable to run a demo

### ISSUE THREAD

**Issue by Borntofly** [danielgindi/ios-charts#356]
I am trying to run a demo and xcode does not start simulator after i press "RUN". As you can see on screenshot it only building the code with success.
Any ideas why i am not able to run it?

![233f1033-6e5d-445d-83e9-4800c0ead6d6](https://cloud.githubusercontent.com/assets/6824258/9812051/11d293be-587b-11e5-9776-fbad54b229c8.png)

**Comment by bobdami** [comment]
I have the same problem.

**Comment by danielgindi** [comment]
You have selected to run "Charts" which is the framework, instead of
"ChartsDemo"...
>
>
It's in the upper left corner of Xcode

**Comment by Borntofly** [comment]
Thank you, guys!

**Comment by AmberKCopper** [comment]
it shows errors..
First it coudlnt find CGFloat..i fixed it with import UIKit, then whole lot of errors FbSnapshotTests etc..
