### ISSUE TITLE
Module is not extensible

### ISSUE THREAD

**Issue by iheart2code** [danielgindi/ios-charts#357]
I do not have a suggested solution for this issue, but the Swift module is not nearly as extensible as the Java counterpart. In Java, you can create a subclass of a chart renderer and take advantage of internal/protected methods & properties to create a custom chart renderer. This does not appear to be the case with the Swift module.

I was trying to create a bar chart with rounded corners on the bars. I needed to subclass BarChartRenderer, but was unable to do so without moving the ios-charts source code into my app's module.

Is there a way to accomplish a similar level of API-parity with the Java counterpart while at the same time allowing for extensibility? Perhaps take advantage of protocols or something.

**Comment by danielgindi** [comment]
"protected" methods are not available in Swift. For some reason Apple think
that it's not a use case...

Maybe a post on the appropriate Swift forum will change something...

**Comment by petester42** [comment]
I would suggest maybe writing an extension to `BarChartRenderer` and override the methods you want to change. Maybe worth a try.

**Comment by martinnormark** [comment]
You cannot override methods from extensions:

> Extensions can add new functionality to a type, but they cannot override existing functionality.
Source: [Docs, first note](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Extensions.html#//apple_ref/doc/uid/TP40014097-CH24-ID151)

**Comment by danielgindi** [comment]
@martinnormark it is not an extension but a module...

**Comment by martinnormark** [comment]
Yes, I was just replying to @petester42 's suggestion.

**Comment by petester42** [comment]
There is a distinction though. If the property or function comes from the subclass then its fine. 

```
extension UIViewController {
    /// doesn't work
    override var title: String? {
        get {
            return "Cool"
        } set(new) {
            
        }
    }
}

class VC: UIViewController { }

extension VC {
    /// works
    override var title: String? {
        get {
            return "Cool"
        } set {

        }
    }
}
```

I thought it might work since `BarChartRenderer` since it is a subclass of `ChartDataRendererBase` but I haven't tried it.

**Comment by petester42** [comment]
@danielgindi I believe this kind of issue could be solved if the renderers were protocol oriented and not subclasses. Then the charts could then take any object that adheres to lets say `RenderProtocol` and make it easier for other to modify the rendering.

**Comment by martinnormark** [comment]
@petester42 Should work it seems. Then you only need to subclass the [`BarChartView`](https://github.com/danielgindi/ios-charts/blob/master/Charts/Classes/Charts/BarChartView.swift#L33) class, since that instantiates the renderer and there's no way to configure from the outside which renderer class it will use.

**Comment by danielgindi** [comment]
I think, maybe, we should try turning into `public` the important methods that deserve to be `protected` or are `protected` in the android counterpart.

https://developer.apple.com/swift/blog/?id=11

**Comment by danielgindi** [comment]
I think that maybe things that are "protected" in the Java counterpart, should be public here, but prefixed with an underscore, so the developer/user can know whether he/she is supposed to access it or not.
I don't get why Apple has decided that there is no use case for "protected". I guess it just made their life easier to optimize to C-level performance, when they know that they can't expect "dynamic" subclassing of stuff that was supposed to be "sealed".

**Comment by broncha** [comment]
+1 I am working on a custom renderer but I cannot access the animator

**Comment by simonmcl** [comment]
+1 Trying to add a gradient to the Cubic Line chart, can't get at the drawCubicFill method. Means i'm going to have to throw anyway cocoapods and import manually so I can modify it.

**Comment by broncha** [comment]
Bumped again. I need to assign a custom highlighter to a custom chart, derived from bubble chart. And cant access `_highlighter` neither extend `ChartHighlighter`

**Comment by danielgindi** [comment]
Yes this will be address soon

**Comment by broncha** [comment]
:+1:

**Comment by broncha** [comment]
how do you suggest I do it for now?

**Comment by iheart2code** [comment]
@broncha you're going to need to bring the source code into your project and modify the files directly.

**Comment by iheart2code** [comment]
@danielgindi perhaps take a loot at the Protocol-Oriented Programming video from WWDC 2015 for inspiration here.

https://developer.apple.com/videos/play/wwdc2015-408/

**Comment by iheart2code** [comment]
The more I look at this library from a Swift/extensibility perspective, the more I realize that what I am asking is probably out of the scope of what this library intends, since it is supposed to be a direct port of a Java counterpart.

**Comment by petester42** [comment]
As long as the API for the library remains similar to the Java version then it would be fine. Changes also go both ways. If you add something good to iOS charts then there is is a good chance it makes its way to Java version and vice versa. Don't let it discourage you from implementing something cool for this library. 

You can try to give protocol oriented programming for the ChartHighlighter a shot and see if it's feasible.

**Comment by broncha** [comment]
About the custom highlighter part, I had to copy the entire `ChartHighlighter` and modified `getHighlight`.
Then introduce new `_highlight` property in my custom chart `initialize` . Of course this new `_highlight` was not accessed by the chart library. So I also had to override `getHighlightByTouchPoint` in my custom chart to use the new `_highlight`.

**Comment by liuxuan30** [comment]
@broncha It seems you could  replaced the _highlighter in initialize(), then you don't have to override getHighlightByTouchPoint if no more actions to take?

**Comment by iheart2code** [comment]
@petester42 took your advice. Please let me know if I went in the right direction with that.

**Comment by liuxuan30** [comment]
another quesiton, shall we make initialize() to public rather than internal? I saw some people want to replace the renderer, but they cannot override initialize() outside of the library:http://stackoverflow.com/questions/33994223/fetching-current-x-position-when-graph-is-set-to-scroll-in-ios-charts/34011274?noredirect=1#comment55831925_34011274

**Comment by martinnormark** [comment]
That's exactly what I intend to do. Subclass an existing renderer, and override methods. Then pass that renderer to the chart view.

Perhaps you could define your own renderer af initialize, by setting a public property instead?

**Comment by liuxuan30** [comment]
I am using the source files, so have no trouble of override internal stuff. But seems lots of people are sub classing outside of the library.

**Comment by danielgindi** [comment]
Moving to protocol oriented - will cause problem with keeping cross-platform API. Instead, everything in the renderers is now completely public :-)

**Comment by martinnormark** [comment]
Excellent :+1: 

Any idea when you'll cut a new release?

**Comment by danielgindi** [comment]
Probably around a day.

Just checking for any incompatibilities that I can find with the Android API, as this is the time to fix them, along with the other structural changes that were done (and also for critical bugs that must be included in this version)

**Comment by jenjia** [comment]
@martinnormark how do you pass the your custom renderer to the chartView?
