### ISSUE TITLE
Xcode 7.0 and Swift 2.0 issue

### ISSUE THREAD

**Issue by j259liu** [danielgindi/ios-charts#358]
I just upgraded my xcode to 7.0beta and swift 2.0. Really counldn't figure out how to link the project to the charts framework. In xcode 6.0, I use the "embedded binaries" and simply linking the charts frame to my project. How do I do this in xcode 7?

**Comment by liuxuan30** [comment]
I think pretty the same steps except that you need to use swift-2.0 branch or convert your swift code by Xcode 7.
