### ISSUE TITLE
Two different-scale axis support for different data sets

### ISSUE THREAD

**Issue by garnett** [danielgindi/ios-charts#36]
I have two datasets, yellow and green and want to have two distinct Y axis for them. Is that possible?
![2015-04-19 00-50-51 lifts rimmer sk last -1](https://cloud.githubusercontent.com/assets/829783/7217346/48cc6170-e62e-11e4-81ee-329f68568c1f.png)

**Comment by danielgindi** [comment]
For the complex questions, you could always ask @PhilJay :-)

**Comment by danielgindi** [comment]
You should ask these on MPAndroidChart repo!

**Comment by vineethvijayan** [comment]
@garnett were you able to find a solution?

**Comment by danielgindi** [comment]
There are other options:
1. Using the rightAxis
2. Overlaying a chart on another chart. While stripping one chart of all of its lines etc.

**Comment by vineethvijayan** [comment]
![screen_shot_2015-10-12_at_10_49_34_am](https://cloud.githubusercontent.com/assets/6049347/10422015/cbb5e934-70d1-11e5-829c-e5c857c34df4.png)

Will it be possible something like this?

**Comment by danielgindi** [comment]
Maybe in the future, it shouldn't be too hard to implement.
But it's not on our plate right now, we have bigger things planned

‏בתאריך יום שני, 12 באוקטובר 2015, vineethvijayan <notifications@github.com>
כתב:

**Comment by vineethvijayan** [comment]
Thanks @danielgindi, you have done a great job with this charts. 
I wish there was some feature like this :(
Anyways thanks a lot 

https://github.com/i-schuetz/SwiftCharts
has my required feature, but I have already integrated ios-charts.
