### ISSUE TITLE
Xcode 10 beta & Swift 4.2 support

### ISSUE THREAD

**Issue by MaddyCoder** [danielgindi/ios-charts#3623]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Tried running my app which has charts library integrated on Xcode 10.  

## What did you expect to happen?

ℹ I expected charts library to run on Xcode10.  

## What happened instead?

ℹ Got Compiler error.  

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:**Xcode 10 beta
**Swift version:** 4.2
**Platform(s) running Charts:** iPad
**macOS version running Xcode:**

**Comment by misuqian** [comment]
same
