### ISSUE TITLE
Sequencing of legend titles

### ISSUE THREAD

**Issue by kaustubh-kabra** [danielgindi/ios-charts#363]
Will it be possible to provide sequencing options to legends ?
![screen shot 2015-09-14 at 10 41 39 pm](https://cloud.githubusercontent.com/assets/642690/9866815/4adf27dc-5b35-11e5-961d-9f07e93d5786.png)
The bottom strip needs to be in Pn sequence, where n is ascending order of numbers. Currently they are random.

**Comment by danielgindi** [comment]
The legend entries are actually ordered, by the order that you've put it in.

You have another option, if you do not want to sort your datasets: Just set custom legend entries.

**Comment by chennuruashok** [comment]
how it can possible if i want to set all the red coloured legends on left side and remaining coloured legends on right side
