### ISSUE TITLE
Marker frame adjustment according to bounds

### ISSUE THREAD

**Issue by kaustubh-kabra** [danielgindi/ios-charts#364]
I am showing values on a standard graph, which has minimum origin defined. The Chartview is added as a subview on UISplitViewController. As a result, the marker view which appears on click of a point close to X axis is getting cut. Screenshot-
![screen shot 2015-09-14 at 10 57 11 pm](https://cloud.githubusercontent.com/assets/642690/9866873/24853ecc-5b36-11e5-9a38-c779108b413c.png)
Any suggestion to fix this behaviour ?

**Comment by liuxuan30** [comment]
have you tried find out which view is responsible for clipping, the chart view, or your super view?

**Comment by kaustubh-kabra** [comment]
I want the marker view to be on top of any underlying subviews. Still better, if it can sense the bounds of chart view and align content/arrow location such that no clipping happens - similar to way iOS presents UIPopupViewController.

Thanks for the quick reply !

**Comment by liuxuan30** [comment]
I checked that `drawMarkers(context: context!)` will not be clipped, it's not another view. Do you set any maskToBounds in your super views?

**Comment by kaustubh-kabra** [comment]
Nothing explicitly set for maskToBounds to any views in this controller.

**Comment by liuxuan30** [comment]
Well I guess you need to debug then. Just walk through you super views and see who's frame your marker view got clipped out of the frame.

**Comment by liuxuan30** [comment]
BTW, you need to check how you draw the text as well.

**Comment by kaustubh-kabra** [comment]
ok thanks, will check and update this thread later.

**Comment by kaustubh-kabra** [comment]
As per your suggestion, I tried setting masksToBounds and clipsToBounds to NO for all superviews in hierarchy of chart view.

UIView *thisView = self.chartView; //this is reference to my line chart view
    do{
        thisView.clipsToBounds = NO;
        thisView.layer.masksToBounds = NO;
        thisView = v.superview;
    } while(thisView != nil);

Issue still persists. Any insights ?

**Comment by liuxuan30** [comment]
If no view clips your marker, have you checked how you draw the text. I looked at your screenshot, the text is first not left aligned? You may check here too.

**Comment by liuxuan30** [comment]
@kaustubh-kabra any updates?

**Comment by liuxuan30** [comment]
Closing - I guess you solved the problem? Welcome to post answer here

**Comment by gsolanki1509** [comment]
@kk-code how do you set values to Marker View before showing them on click of chart?
