### ISSUE TITLE
How to achieve 0 spacing between bars?

### ISSUE THREAD

**Issue by kexoth** [danielgindi/ios-charts#365]
I want to make a bar chart with 0 space between the bars, but couldn't manage to do that so far.

![simulator screen shot sep 16 2015 6 23 37 am](https://cloud.githubusercontent.com/assets/883816/9896385/81fbbaa8-5c3b-11e5-9c55-03f5c2b72139.png)

This is my current code for that matter:

        self.chartView.delegate = self
        self.chartView.descriptionText = ""
        self.chartView.noDataTextDescription = "No data to show at the moment."
        self.chartView.scaleYEnabled = false
         
        self.chartView.leftAxis.customAxisMin = 0
        self.chartView.leftAxis.customAxisMax = 100
        self.chartView.leftAxis.labelCount = 10
        self.chartView.leftAxis.startAtZeroEnabled = true
        
        let yNumbersFormatter = NSNumberFormatter()
        yNumbersFormatter.allowsFloats = false
        yNumbersFormatter.positiveSuffix = "%"
        self.chartView.leftAxis.valueFormatter = yNumbersFormatter
        self.chartView.leftAxis.labelFont = UIFont(name: "HelveticaNeue-Light", size: 8)!
        
        self.chartView.xAxis.labelPosition = ChartXAxis.XAxisLabelPosition.Bottom
        self.chartView.xAxis.spaceBetweenLabels = 0
        self.chartView.xAxis.drawGridLinesEnabled = false
        
        self.chartView.rightAxis.enabled = false
                
        let xValues = [String](count: 100, repeatedValue: "")

        var onValues = [BarChartDataEntry]()
        var offValues = [BarChartDataEntry]()
        
        for i in 0..<100 {
            
            let entry = BarChartDataEntry(value: Double(index), xIndex: index, data: nil)
            
            if random() % 2 == 1 {
                
                onValues.append(entry)
            }
            else {
                
                offValues.append(entry)
            }
        }
        
        let onDataSet = BarChartDataSet(yVals: onValues, label: "ON")
        onDataSet.barSpace = 0
        onDataSet.colors = [UIColor.greenColor()]
        onDataSet.drawValuesEnabled = false
        
        let offDataSet = BarChartDataSet(yVals: offValues, label: "OFF")
        offDataSet.barSpace = 0
        offDataSet.colors = [UIColor.grayColor()]
        offDataSet.drawValuesEnabled = false
        
        let data = BarChartData(xVals: xValues, dataSets: [onDataSet, offDataSet])
        data.groupSpace = 0
        self.chartView.data = data

No matter how I arrange the bars, only if I have gray after green I get the desired effect.

The code is with Swift 2.0 & I'm using your swift-2.0 branch.

**Comment by liuxuan30** [comment]
Seems the space is there because some of your green bars are missing, and ios-charts need to make a place holder for every bar, even it is not there.

**Comment by kexoth** [comment]
@liuxuan30 but there shouldn't be any bars missing missing, take a look at the code, I have a range `0..<100`, `yValue` & `xIndex` have the same value while iterating in the range.

**Comment by liuxuan30** [comment]
Here's the thing:
you have two dataSets, which means every xIndex should have two bars; however you add bars randomly into each dataSet exclusively, which means each xIndex would only have 1 bar, and the other is missing, but the space is reserved.

**Comment by kexoth** [comment]
@liuxuan30 I'm sorry, but now I understand my mistake :disappointed_relieved:

Apparently I did it the wrong way trying to cover with 2 datasets. But then what will be the correct approach to achieve it? 

Should I put them all in the same dataset & create an array of colors for each item & assign it to the dataset & then customize the legend to follow that convention?

**Comment by liuxuan30** [comment]
@kexoth it first depends on what you want your chart looks like. 1 dataSet means one bar, remember that first. Puting more than one y value inside one dataSet will gives you a stacked bar chart.

For those spacing issues, if ios-charts does not support it yet, then you may need to override the renderer to get what you want, but this will get complicated and requires you understand how the bars is positioned and rendered.

**Comment by kexoth** [comment]
I managed to achieve the mentioned with 1 dataSet, assigned it an array of colors for every entry & created a custom labels & colors for the legend. 

Thanks anyway, I'll close the thread :v:
