### ISSUE TITLE
Multiple axis - line charts drawing

### ISSUE THREAD

**Issue by ajaybhat1987** [danielgindi/ios-charts#366]
Hi,
I am trying to draw accelerometer data with 3 axis - X, Y, Z. Similar to the one shown in image.
I am unable to plot them in real time, (1 data point/sec for each axis).
tried to use addentry() method and I feel there is a bug here as only 1 axis moves and the other  2 axis just remain static.

Please help me fix this or provide a better approach to solve it.
![Uploading 3axis.png…]()
Unable to attach images.

Regards,
Ajay

**Comment by danielgindi** [comment]
1. There's no image attached ("Unable to attach images"). Read your on post!
2. I do not see where your trouble is. You can control "moving" the chart on both axis. It does not move automatically with addEntry.
