### ISSUE TITLE
I upgraded my UXcode 7,I can't use charts framework.

### ISSUE THREAD

**Issue by NEOCHIU** [danielgindi/ios-charts#378]
Help me, I just upgraded my UXcode 7 today , I can't use charts framework.

**Comment by AlBirdie** [comment]
"Xcode 6.3 / Swift 1.2 (Swift 2.0 for Xcode 7 beta is available currently on the swift-2.0 branch)"

**Comment by NEOCHIU** [comment]
Oh~no,I guess i will have to wait for the update charts framework. 

thanks!

**Comment by AlBirdie** [comment]
You can use the Swift 2.0 branch today.
For the record, please close issues that don't need further discussion. Helps to keep the project tidy. :)

**Comment by AlonShm** [comment]
When is it going to be merged to master?

**Comment by danielgindi** [comment]
Use the `swift-2.0` branch. It will be merged soon.

**Comment by liuxuan30** [comment]
@danielgindi, I use Xcode 7 converter to convert my code first, it's working so far. what's the difference in swift 2.0 branch and DIY convertion?
