### ISSUE TITLE
Installing ios-charts in an existing project

### ISSUE THREAD

**Issue by dddppp** [danielgindi/ios-charts#379]
Dear All,

Thank you for creating this awesome project. I run the demo and is great. I would like to take it to the next step and integrate it in my custom project. What are the steps I need to do? Would anyone be able to help me?

I have tried the following but was not successful:

- copy the Charts target from the demo project to mine
- link the framework 

However I get the following error:

      dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/mobile/Containers/Bundle/Application/0C7EC6DC-94B6-4205-8E71-0F704B2A7523/ChartIn.app/ChartIn
  Reason: image not found

Also it says that the *ChartsDemo-Swift.h* is not found.

Any help would be greatly appreciated. Thanks

**Comment by liuxuan30** [comment]
ChartsDemo-Swift.h will be built by Xcode automatically. Try search closed issues, there are a lot of this.

**Comment by dddppp** [comment]
Hello, in one of the post @danielgindi says "Read the instructions again.". Where can I find them? Sorry to ask this.

**Comment by danielgindi** [comment]
@dddppp It's in the README
