### ISSUE TITLE
Charts running on Simulator only 

### ISSUE THREAD

**Issue by MohamedElzohirey** [danielgindi/ios-charts#381]
Charts running on Simulator only and nothing appear on real iPad.
Any idea?

**Comment by yas375** [comment]
Probably something wrong with setup. It works well in [our app](https://itunes.apple.com/us/app/carezone-organize-health-information/id829841726?mt=8) on all devices including iPads. Could you please provide a sample project showing the issue?

**Comment by liuxuan30** [comment]
you need to debug it first. With this info we can tell nothing.

**Comment by MohamedElzohirey** [comment]
@liuxuan30  yes I know...I just wa asking if there is any special setup that may cause this.
@yas375  good idea to have sample project. I will prepare and send to you.

Thank you guys for your fast response :)

**Comment by liuxuan30** [comment]
@MohamedElzohirey  It's more like you need to debug on your real iPad first and then check if the archives works on your iPad as well. What I can guess is, if it works in debug mode but not release mode, the chart library is not bundled when archiving.
