### ISSUE TITLE
Add ios-charts to existing project in XCode 7

### ISSUE THREAD

**Issue by patreu22** [danielgindi/ios-charts#383]
Hello,

I'm trying to add ios-charts to an existing Swift project in XCode 7 for iOS9 but I'm not able to make it work. Does anybody has a detailed instruction to do that? 

Regards, Patrick

**Comment by yas375** [comment]
There is swift-2.0 branch you can use with Xcode 7. This is what I do and it works well! It's probably [going](https://github.com/danielgindi/ios-charts/pull/360#issuecomment-140892358) to be merged into master very soon! :)

**Comment by patreu22** [comment]
But how do I add it to the project? 
I dragged the whole folder to my project, but that didn't worked :(

Thx for your help! :)

**Comment by yas375** [comment]
@patreu22 there is [an instruction in readme](https://github.com/danielgindi/ios-charts#usage). It's the same for current `master` and `swift-2.0`.

**Comment by patreu22** [comment]
Oh now I got the problem. First time I used the wrong branch, second time the wrong instruction. But you saved my night with that hint, thank you very much! :)

**Comment by yas375** [comment]
You are welcome :)
