### ISSUE TITLE
StackedBarChart in horizontal manner

### ISSUE THREAD

**Issue by nitin8** [danielgindi/ios-charts#384]
I have a situation where I need to show a horizontal bar chart but in stacked bar chart manner.
Any suggestion or help ??

**Comment by yas375** [comment]
You can do this!

[Here](https://gist.github.com/yas375/5cb7e42ba1669f50f93b) I've slightly modified [NegativeStackedBarChartViewController.m](https://github.com/danielgindi/ios-charts/blob/master/ChartsDemo/Classes/Demos/NegativeStackedBarChartViewController.m) from ChartdDemo and here you go:

![2015-09-18_0909](https://cloud.githubusercontent.com/assets/217368/9964501/81234f5a-5de5-11e5-9fee-5177da18d46c.png)

Good luck!

**Comment by nitin8** [comment]
Thanks :)
