### ISSUE TITLE
POLL: Appointing some assitance

### ISSUE THREAD

**Issue by danielgindi** [danielgindi/ios-charts#385]
Hello friends!

As you can see, the library grows very popular and with it there are a lot of "help" requests or bug reports, and a lot of clutter is being created in the *issues* section if I take my eyes off of this for 2 days.

I want to appoint someone with the proper permissions to the repo to help with maintaining it.

Requirements are:

1. Must be responsible
2. Friendly, to be able to communicate well with users of the issues section
3. Fluent in Swift
4. Experienced developer
5. Able to make responsible decisions regarding PRs. *(Yes I know it's a duplicate of 1, but it's a tricky business)*
6. Prioritize compatibility with the Android lib interface, functionality and version numbering.

I have my own thoughts on this, but I wanted to hear from you!  
Also if someone is suggesting himself - that's great too :-)

GO!

**Comment by liuxuan30** [comment]
item 6 is quite a strict requirement:) 

How many hours per day/week you think is needed? And, a single person or a team?

**Comment by danielgindi** [comment]
@liuxuan30 yes it is, but that was the whole point to begin with :-) What happens to most people is they have to create a cross-platform app, and start looking for charting libraries. Now they have functionalities that exist on one platform and lack on the other, and they have to learn two different APIs and then figure out how the hell to do what they did with the other one.

So I'd like to keep it compatible. It does not mean that you need to translate every line of code the you commit or accept; It means that you need to consider "how will this be implemented in Android? will it still conform to the standards of the library on both platforms or should this PR be rewritten?.."

I also do not require any strict schedule! It's volunteer work from all of us :-)

And this world is filled with single people. It is just that some of them are able to work as a team. The people working on this repo (or any repo) should be able to work as a team.

**Comment by liuxuan30** [comment]
Guess I can continue my way to help. Know nothing about Android/Java

**Comment by danielgindi** [comment]
@liuxuan30 I have just given you access to the repo. Feel free to manage the issues section :-)

**Comment by danielgindi** [comment]
I think that there are a lot of noise in the form of duplicate issues

**Comment by petester42** [comment]
There is indeed a lot of noise in issue. I'd be glad to help where I can.

**Comment by danielgindi** [comment]
@petester42 I'm adding you too as a collaborator.

In the next few days I'll take the time to review the PRs that still exist, and review the bugs that were reported, and cleanup as much as I can.

You guys helping with the issues - are a big help!
