### ISSUE TITLE
Can't change X-axis label color

### ISSUE THREAD

**Issue by codeHatcher** [danielgindi/ios-charts#387]
I'm trying to change the x-axis label but am unable to do it. Any idea if this is implemented? It's the same thing he is trying to do here. https://github.com/PhilJay/MPAndroidChart/issues/319

**Comment by codeHatcher** [comment]
I'm an idiot, nvm. It was approximately `xAxis.labelTextColor = UIColor.whiteColor()`

**Comment by codeHatcher** [comment]
Actually, i'm not an idiot. It was pretty different from the Android docs such that it took me a few minutes to figure out.
**Android:**

```java
XLabels label = chart.getXLabels();
label.setTextColor(getResources().getColor(android.R.color.white));
```
**iOS:**

```swift
var xAxis = chartView.xAxis
xAxis.labelTextColor = UIColor.whiteColor()
```

**Comment by danielgindi** [comment]
The android docs are not up to date... there's no `getXLabels` function in the android library anymore!

**Comment by codeHatcher** [comment]
ahh, ic ic

**Comment by JoeSerb** [comment]
Hi,
I'm trying to change color of y-axis label, but I can't find method for this. Is it possible to change color of y axis label?
Thank you for your framework and for your help!!!!

**Comment by JoeSerb** [comment]
I found solution:
        self.graphTwo.leftAxis.labelTextColor = UIColor.whiteColor()
        self.graphTwo.rightAxis.labelTextColor = UIColor.whiteColor()
Thank you....

**Comment by anishparajuli555** [comment]
@danielgindi @codeHatcher  Is there a way to change the background color instead of text color?

**Comment by amish-infosys** [comment]
What if I want to change text color of specific labels on y axis/x axis ?  Is there any way ?

Thanks

**Comment by t0nyak** [comment]
I've also the same problem as @amish-infosys. I need to color/bold label of concrete x axis when its value is tapped. However, I just find the way of setting color for every label of x axis, not just for one.

Any idea on this?

Thanks
