### ISSUE TITLE
ios-charts Integration problem

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#389]
HI,

I got error when I imported charts project in my project,Please help how to integrated the ios-charts in my project.

**Comment by yas375** [comment]
Did you follow the steps described in README? What error do you get?

**Comment by unnamedd** [comment]
@smilydronavalli please, follow the steps on README and everything will be ok. If you have any other question, call us!

**Comment by smilydronavalli** [comment]
Hi,

Now its working

Thanks for your help!!!

**Comment by smilydronavalli** [comment]
i tried ti integrate charts in xcode 7.1 but i am getting error at xctest (cannot load  underlying module for xctest)
