### ISSUE TITLE
Swift-2.0 branch runtime crashes after distributed on the TestFlight

### ISSUE THREAD

**Issue by reeyan** [danielgindi/ios-charts#390]
First of all thanks for the wonderful framework.
I have been using this framework since April and before to migrate swift-2.0 branch for to distribute using Xcode 7, there was no issue however after I switched and distributed for internal testing App just got crash as soon as try to open the view.
Funny thing is that there is no issue if I build from Xcode. 
Do I need specific configuration on Xcode before to upload iTunes connect for swift2.0?
I'm using cocoapods however adding Charts project into my project have the same issue.
Crash log in the Xcode organizer doesn't give any clue.

**Comment by reeyan** [comment]
For your information, I have tried with master branch however issue still persist.

**Comment by liuxuan30** [comment]
sounds like a common issue other people had, the chart library is not bundled, could you try more? Like gather the device logs.

**Comment by reeyan** [comment]
Hi Thanks for your comment.
I found the issue and solution. Short answer is that please turn Swift Optimization to "None" otherwise you will have an exception at the very last line of the code below.
Seems like there is Swift optimization bug in the Swift compiler.


public class CombinedChartView: BarLineChartViewBase
{
    /// the fill-formatter used for determining the position of the fill-line
    internal var _fillFormatter: ChartFillFormatter!
    
    /// enum that allows to specify the order in which the different data objects for the combined-chart are drawn
    @objc
    public enum CombinedChartDrawOrder: Int
    {
        case Bar
        case Bubble
        case Line
        case Candle
        case Scatter
    }
    
    public override func initialize()
    {
        super.initialize()
        
        _fillFormatter = BarLineChartFillFormatter(chart: self)

Charts was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by danielgindi** [comment]
Please file a bugreport to apple (bugreport.apple.com) about the optimization failure.
The optimization probably fails with the very specific combination of your code + Charts.framework.
It happens that the Swift compiler has bugs...

Also - you can try different optimization levels.
