### ISSUE TITLE
bar chart with gradient

### ISSUE THREAD

**Issue by vigyanhoon** [danielgindi/ios-charts#398]
Hi,

Does this support two or more gradient color for bars?

Thanks.

**Comment by liuxuan30** [comment]
What you mean for the gradient color for bars? It has fill color first; and you can customize the color for each dataSet

**Comment by vigyanhoon** [comment]
I have a requirement to create a graph like this:

![screen shot 2015-09-21 at 6 11 06 pm](https://cloud.githubusercontent.com/assets/8503526/9991965/4619776e-608c-11e5-8358-559b02de49ef.png)

**Comment by liuxuan30** [comment]
hmm, it seems you need to implement the gradient layer by yourself. ios-charts does not support this right now.

But for the line chart, we already support the filling - check out `drawLinearFill` and enable it with `dataSet.isDrawFilledEnabled`

**Comment by throb** [comment]
Do you have any example code for the gradient fill on the line chart?  I cannot seem to reproduce it in Swift.  Thank you so  much!

**Comment by tejas-ardeshna** [comment]
Any update on this? Still no gradient layer for Barcharts?

**Comment by liuxuan30** [comment]
not yet. Busy with Chart 3.0

**Comment by Egor1219** [comment]
hi
I would like to know hot to make Line Chart(gradient fill)

**Comment by Moa131** [comment]
@Egor1219 
Hi, you can do this with for example like this :

`        let chartDataSet = LineChartDataSet(values: %%YOUR DATA ENTRIES %%, label: "Temperature")
        // Gradient
        let gradientColors = [UIColor.red.cgColor, UIColor.clear.cgColor] as CFArray // Colors of the gradient
        let colorLocations:[CGFloat] = [0.5, 0.0] // Positioning of the gradient
        let gradient = CGGradient.init(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: gradientColors, locations: colorLocations) // Gradient Object
        chartDataSet.fill = Fill.fillWithLinearGradient(gradient!, angle: 90.0) // Set the Gradient
        chartDataSet.drawFilledEnabled = true // Draw the Gradient
        
        
        chartDataSet.drawCubicEnabled = true
        chartDataSet.cubicIntensity = 0.09`

**Comment by abhiccc5** [comment]
I have created a video tutorial for this task. Kindly refer to my video.

https://www.youtube.com/watch?v=zT6zMyYpkXM&t=13s

**Comment by WangZhongyong** [comment]
@vigyanhoon 
Hi! Have you found the solution for BarChartView gradientColors?and coding by Objective-C

**Comment by vigyanhoon** [comment]
Its pretty old issue. I have now moved to front end dev.

**Comment by lexuanquynh** [comment]
no one help me?
