### ISSUE TITLE
Swift 2.0 branch not found

### ISSUE THREAD

**Issue by Mazorati** [danielgindi/ios-charts#399]
Hello.

I try to install with cocoapods on my swift 2.0 ios app.
pod 'Charts', :git => 'https://github.com/danielgindi/ios-charts.git', :branch => 'swift-2.0'

It gives an error:

```
Analyzing dependencies
Pre-downloading: `Charts` from `https://github.com/danielgindi/ios-charts.git`, branch `swift-2.0`

[!] Error installing Charts
[!] /usr/bin/git clone https://github.com/danielgindi/ios-charts.git /var/folders/79/yg8j5fr1489c7nnjvjbw_jzc0000gn/T/d20150920-10002-y5rvpb --single-branch --depth 1 --branch swift-2.0

Cloning into '/var/folders/79/yg8j5fr1489c7nnjvjbw_jzc0000gn/T/d20150920-10002-y5rvpb'...
warning: Could not find remote branch swift-2.0 to clone.
fatal: Remote branch swift-2.0 not found in upstream origin
```

**Comment by danielgindi** [comment]
The `swift-2.0` is merged into main, since the current Xcode version is 7. You should download the final version of Xcode from the AppStore, and switch to the master branch.
NOTE: There's no version release yet, so if using CocoaPods you'll need to sync to latest commit, not latest version.
