### ISSUE TITLE
Cocoapod

### ISSUE THREAD

**Issue by ZhenyuRipple** [danielgindi/ios-charts#4]
Hi,

Can you tell me why this project is not in the CocoaPod spec?

**Comment by danielgindi** [comment]
Well, it's simple. It's because I didn't write a CocoaPod spec for it.  
I do not use CocoaPod. You are welcome to add a CP spec!

**Comment by ZhenyuRipple** [comment]
Thanks for the super clear answer ;)

I will try to add it!

**Comment by danielgindi** [comment]
Great! Let me know through a PR
