### ISSUE TITLE
How to show time values in horizontal Bar chart?

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#402]
Can I show graph y value as hh:mm:ss format? As usual I am initializing the BarChartDataSet with BarChartDataEntry value array. I am passing the y values array which consists time in seconds.

**Comment by wganeshb** [comment]
Got the answer.
https://github.com/danielgindi/ios-charts/issues/228

Thanks

**Comment by wganeshb** [comment]
I just subclassed NSNumberFormatter. And override 
- stringFromNumber: function. It worked for me.

**Comment by yas375** [comment]
I guess this issue can be closed.
