### ISSUE TITLE
Xcode 7 and iOS 9 Support (Deployment Target iOS 7.0)

### ISSUE THREAD

**Issue by sagarcool89** [danielgindi/ios-charts#404]
Dear Author,

My Project deployment target is iOS 7.0. I have integrated ios-charts as per your guidelines (README). I am getting following error while building the project. Please find the attached screenshot.

Can you please help me out to resolve this?

Thanks, Sagar.

![screen shot 2015-09-21 at 6 55 08 pm](https://cloud.githubusercontent.com/assets/4920892/9993218/33ed7a88-6094-11e5-9554-d0cc10bdc2d7.png)

**Comment by AlBirdie** [comment]
So you did drag the .Swift files into your project?

**Comment by danielgindi** [comment]
As the error said, Embedded Frameworks are not supported in iOS 7.0. You should **read** the README. It says you should drag the files to your project.
