### ISSUE TITLE
How to draw a line only for the 5th value of dataset along x axis?

### ISSUE THREAD

**Issue by LekhaPai** [danielgindi/ios-charts#409]
x axis i have defined for time intervals.I need to specify a interval line only when 5th values from  y axis is drawn.I have tried with setLabelstoSkip(),.With this method it draws line for the first value of y and then keeps on plotting the  interval lines.How to avoid it?

**Comment by liuxuan30** [comment]
I am not quite clear about what is interval line here? Grid line or else? setLabelstoSkip has some description:
`Sets the number of labels that should be skipped on the axis before the next label is drawn. 
    This will disable the feature that automatically calculates an adequate space between the axis labels and set the number of labels to be skipped to the fixed number provided by this method. 
     Call `resetLabelsToSkip(...)` to re-enable automatic calculation.
`

**Comment by danielgindi** [comment]
No response for so long, I guess he figures this out...
