### ISSUE TITLE
Two graphs overlaying each other

### ISSUE THREAD

**Issue by amycheong19** [danielgindi/ios-charts#41]
Hi, may I know is there are way for me to overlay line graph above a candle stick graph with synchronise xy axis. I tried to put the same values to each graphs and positioned them starts from zero but the axis are not tally (you can see the candlestick 185 is lower than line graph's 180 y-axis.

Thanks

![ios simulator screen shot 22 apr 2015 1 26 14 pm](https://cloud.githubusercontent.com/assets/9781961/7267792/325bf6d6-e8f3-11e4-97c5-b7f349a19088.png)

**Comment by danielgindi** [comment]
You should really ask these questions in the MPAndroidChart repo, as there's much more knowledge there on the advanced stuff :-)

**Comment by amycheong19** [comment]
Thanks. I will try my luck there. :)
