### ISSUE TITLE
Unit tests? ;)

### ISSUE THREAD

**Issue by yas375** [danielgindi/ios-charts#414]
How about adding some unit tests to the project? ;) Would be nice to have view snapshot tests. This should be useful in cases when someone finds some bug in rendering. We can write a unit test which will capture how it looks like. It will reduce possible regressions in future since a lot of people are using different parts of the library (different chart types) and can fix an issue in one chart, but it will cause an issue for another one.

I'm happy to volunteer to set up test environment :) If you are ok with that, then do you have any preferences on frameworks to use?

I'd like to try to use Quick, Nimble, and Nimble-Snapshots. I haven't worked with these libs yet because we have testing set up in Obj-C at work. But these libs look promising. We can see Artsy is [using](https://github.com/artsy/eidolon/blob/426116c94386ff26c824bbaf9647f4b7d9f9ada9/Podfile#L66-L68) them as well. Should be good :)

**Comment by danielgindi** [comment]
That's a great idea!
I'll be happy to merge that in! Looking forward to see what you've done with it...

**Comment by yas375** [comment]
Will do it soon then! :+1:

**Comment by danielgindi** [comment]
:+1:

**Comment by danielgindi** [comment]
Ok so now its deployed and working wonderfully, we only need to add more tests :)
