### ISSUE TITLE
Excessive Printing to Console

### ISSUE THREAD

**Issue by petester42** [danielgindi/ios-charts#417]
I don't know if this is a recent change or what but this [line](https://github.com/danielgindi/ios-charts/blob/436ee924ab0bdbee4a5b85d910f992399687d3dc/Charts/Classes/Charts/ChartViewBase.swift#L193) causes a print if the array for y values is empty.

This seems excessive. If the developer when through the trouble of setting a `ChartData` then they should be aware of what data it holds. 

Thoughts?

**Comment by danielgindi** [comment]
It's actually there from the first version... But I don't see the problem. It notifies you that something is wrong there. I think maybe a `nil` check is sufficient.
Problem is mainly with newbies forgetting to add datasets to their data object...

**Comment by petester42** [comment]
Ya for normal imperative use that is fine but I have created a `ReactiveCocoa` extension which expects the `ChartData` to not be nil since it shouldn't really be. Since `ChartViewBase` has an optional `data` I need to assign it a value so I just initialize an empty `ChartData` as can be seen below. This causes the printing to happen. Having only the nil check should be sufficient.

```
extension ChartViewBase {
    
    private struct Associated {
        static var data: UInt8 = 0
    }
    
    public var rac_data: MutableProperty<ChartData> {
        return associatedProperty(self, key: &Associated.data, initial: { self.data ?? ChartData() }, setter: { self.data = $0 })
    }
}
```

**Comment by liuxuan30** [comment]
shall we disable the printing for release mode?

**Comment by petester42** [comment]
Using `print` doesn't get printed in the device console like `NSLog` does so it shouldn't matter.

**Comment by liuxuan30** [comment]
alright, main concern is too much print will cause performance drop

**Comment by danielgindi** [comment]
This is not Android lol ;-)
>
>

**Comment by liuxuan30** [comment]
seems we should check the y values. There is a case in #577, x values empty, bar data entries empty, and combined chart continues drawing and crash.
