### ISSUE TITLE
CGContextAddLineToPoint no current point. 

### ISSUE THREAD

**Issue by yuravake** [danielgindi/ios-charts#419]
When drawing LineChart i have a lot of warnings in console "CGContextAddLineToPoint: no current point." and  "CGContextClosePath: no current point."

So i  think, that LineChartRenderer missing CGPathMoveToPoint line at 234 or so, but can't figure out how to make it work... %)

**Comment by liuxuan30** [comment]
can we reproduce it with ChartsDemo? I don't see it in my project. 
Also, what line chart type you are using, cubic or linear, and have you enabled `dataSet.isDrawFilledEnabled`

**Comment by yuravake** [comment]
i managed to get same error in ChartsDemo when i changed LineChartDataSet in LineChart1ViewController to follows : 
    [set1 setColor:[UIColor blackColor]];
    set1.lineWidth = 3.0;
    set1.fillAlpha = 1;
    set1.fillColor = [UIColor blackColor];
    set1.drawCubicEnabled = YES;
    set1.drawFilledEnabled = YES;
    set1.drawCirclesEnabled = NO;
    set1.drawValuesEnabled = NO;

**Comment by liuxuan30** [comment]
I see it with:
```Swift
    set1.drawCubicEnabled = YES;
    set1.drawFilledEnabled = YES;
```
function: `internal func drawCubicFill`
```Swift
234        CGContextAddLineToPoint(context, pt1.x, pt1.y)
235        CGContextAddLineToPoint(context, pt2.x, pt2.y)
```
CGContextAddLineToPoint is causing it. Only drawCubic has the problem, you can use drawLinear right now.
I am not sure what's the reason yet...

**Comment by yuravake** [comment]
so, the graph actually draws correctly...its just console messages...

**Comment by liuxuan30** [comment]
Find out more:
It's related with the animation:
phaseX is 0 at first if you turned on animate X, so it calculates the size to be 0:
`let size = Int(ceil(CGFloat(maxx - minx) * phaseX + CGFloat(minx)))`, if you turn off animate X, drawCubic is also fine.

**Comment by yuravake** [comment]
Yes, without X animation all good, thanks.

**Comment by danielgindi** [comment]
@liuxuan30 thanks for narrowing the case :-)

**Comment by liuxuan30** [comment]
@danielgindi I would help to fix, but drawLinear and drawCubic is a little complicated to find out the proper solution :( still learning when having some chances
