### ISSUE TITLE
How to add custom text to the diagram

### ISSUE THREAD

**Issue by SvenMuc** [danielgindi/ios-charts#421]
Hi,
I'm currently trying to adde  custom text within the bar chart diagram. What's the best way to do so?
Are there already some internal functions available?

Thanks for you support
Sven

**Comment by liuxuan30** [comment]
It depends what text you want to add and where. There is labels, values text, and `ChartMarker` to let you display some custom text when you tap the bar; of cause you could write your own code to display the chart markers when the chart is loaded.

**Comment by SvenMuc** [comment]
I'd like to plot three histograms into one diagram and add a text field (description) above each bar chart. It is just a label which I'd like to position at any place in the diagram.

I saw a function called  '''drawExtras''' . Is that the right place to add custom drawings?

**Comment by liuxuan30** [comment]
Technically, as long as you know how it works, you can draw whatever you like on the canvas. Just keep it easy for you to maintain if any version upgrade;

There is legend, chart marker, here for you. But looks like you need to override and calculate the right position. For ultimate flexibility, I would consider create a chart marker; Anyway, just pick one you feel comfortable to use.
