### ISSUE TITLE
ScatterChartRenderer - create a custom shape

### ISSUE THREAD

**Issue by y-k-r** [danielgindi/ios-charts#423]
Hi,

I've been trying to create a custom shape and nothing is being rendered on screen.
I've created a simple CGPath? and started to debug and i've noticed that:
                CGContextTranslateCTM(context, -point.x, -point.y)
might be wrong, and the right transformation should be
                CGContextTranslateCTM(context, point.x, point.y)
Can you confirm/correct me wrong?

Thanks

**Comment by danielgindi** [comment]
Did you create the path around [0,0]?
Does it work for you when flipping the negative translations?
