### ISSUE TITLE
Error Swift 2 - ChartViewBase.swift

### ISSUE THREAD

**Issue by belen89** [danielgindi/ios-charts#428]
Hi guys! I'm having an error with ChartViewBase class (the Swift 2 version) 

This line: 
layer.renderInOptionalContext(context) is using the "renderInOptionalContext" which is deprecated. 

I replaced it with: 
layer.renderInContext(context!) and now is working fine, but I don't know if I'm missing something. 

Thanks!

**Comment by petester42** [comment]
`renderInOptionalContext` can't be deprecated since it's a function I created that which basically does `renderInContext(context!)` but without force unwrapping. 

What is the error you are seeing exactly.

**Comment by danielgindi** [comment]
You haven't imported an important file. It's missing from your project, which is why this function is missing from your project. Please make sure you've imported the project fully.
