### ISSUE TITLE
Custom ChartXAxisValueFormatter not Being Called with Data containing NSObjects

### ISSUE THREAD

**Issue by someoneAnyone** [danielgindi/ios-charts#429]
Hi! I'm experimenting with this framework and its really cool, but I've having some trouble figuring out some things... My goal is to re-create a D3 chart as seen below.
![d3chart](https://cloud.githubusercontent.com/assets/438049/10139400/b3eb5da4-65d0-11e5-88ab-6393e5c5c19f.png)

I'm using the ```CombinedChartView``` and in my test code, I'm generating an array of dates.

 ```swift
        var dateArray: [NSObject] = []
        for _ in 0..<20 {
            let aRandomInt = Double(Int.randomRange(100000...200000))  // returns a random number within the given range.
            // dateArray.append("\(aRandomInt)") // Works. My formatter code is called.
             dateArray.append(NSDate(timeIntervalSinceNow: -aRandomInt)) // Does not work. Formatter code isn't called.
            // dateArray.append(NSDate(timeIntervalSinceNow: -aRandomInt).description) // Works. My formatter code is called.
        }
        let data = CombinedChartData(xVals: dateArray)
        data.lineData = generateLineData(dateArray.count)
        
```

later I configure my custom formatter..

```swift
    func configureBottomAxis(bottomAxis: ChartXAxis) {
        bottomAxis.labelPosition = .Bottom
        bottomAxis.labelTextColor = UIColor.whiteColor()
        bottomAxis.drawGridLinesEnabled = false
        bottomAxis.valueFormatter = MyFormatter()
    }
```

```swift

class MyFormatter: NSObject, ChartXAxisValueFormatter {
    
    override init() {
        super.init()
    }
    
    @objc func stringForXValue(index: Int, original: String, viewPortHandler: ChartViewPortHandler) -> String {
        print("stringForXValue:\(index) original: \(original), viewPortHandler:\(viewPortHandler)" )
        
        return "modified: \(original)"
    }
    
}
```
But as you can see from code comments above, if I pass in an object ```MyFormatter()``` is never called. It only happens if I pass in a string. Is this intentional? Am I approaching this the wrong way? Is there another method I can use to get the object?

Thanks!

**Comment by liuxuan30** [comment]
adding some break points should help you figure out. I cannot offer much help here, I think the code is fine.. must be something wrong somewhere else.

**Comment by someoneAnyone** [comment]
Even with the change (removing NSObject), It doesn't get called when I place an object like NSdatecomponents into the xAxis array.

**Comment by danielgindi** [comment]
@someoneAnyone you cannot pass `NSDateComponents` to the xAxis array.

You can only pass `String`s or `nil`s. In ObjC you can pass `NSString` or `NSNull`, which is why you can pass an `NSObject` - for translating between objc's "nullable" type to a real nullable type of Swift.

I really hope that in the next Swift version we will be able to specify that a specific function is not available in Swift, but only in ObjC. This way we'll hide the ObjC bridges from Swift consumers.

**Comment by someoneAnyone** [comment]
Ok, one way I got around this was by passing a time interval as a string then using the custom formatter to turn into a date string. But I'm having  a hard time keeping the x-axis sync to line data.... Any tips on how to do that in the combined chart view? As you can seen the image above I'm trying to get a time series type visual going. here is where I'm at with it now...

![simulator-screen-shot-sep-30_-2015_-1 56 00-pm](https://cloud.githubusercontent.com/assets/438049/10225309/47135fbc-6830-11e5-8d2c-06361792ca72.png)
