### ISSUE TITLE
Any chance of porting this to OSX?

### ISSUE THREAD

**Issue by crewshin** [danielgindi/ios-charts#43]
Any chance of porting this to OSX?

**Comment by danielgindi** [comment]
Well I am not planning to use this on OS X anytime soon, but if you are willing to do it - that would be great!
If I'm not missing anything, we just need typealiases for UIKit types. Everything else is same API as iOS.

**Comment by danielgindi** [comment]
Of course you would need to write an OS X app and test that it's behaving there :-)

**Comment by danielgindi** [comment]
I guess there's no interest there. I will close this in a day of two if nobody wants to help with this. (Help means porting using typealiases, possibly handle mouse event in addition to touches, and testing to that it actually works)

**Comment by crewshin** [comment]
Oh there is interest, trust me. I mean basically there is one option for OSX right now (core plot) and it's an old crotchety bastard. 

Although I'd LOVE to, I personally don't have the time to learn this entire framework's inner workings enough to do this on top of everything else I have going on at the moment. I was hoping someone that knew it's internals would be able to bang it out real fast. I mean it shouldn't be too much work.

**Comment by danielgindi** [comment]
Okay then :)
We'll leave it open for a while!

I personally don't have the time right now but it really shouldn't be too much work... May be this will be your contribution to the project, who know ;)

**Comment by Fab1n** [comment]
I like the project and porting it to OSX will be done... Maybe I will do some work soon

**Comment by crewshin** [comment]
That would be fantastic @Fab1n ! I'm helping start up a company and even though I'd love to help port this, time has not been my friend lately.

**Comment by liuxuan30** [comment]
@crewshin same as you. God I wish I have 48 hours a day.

**Comment by klaas** [comment]
+1 OS X support would be more than awesome.

**Comment by danielgindi** [comment]
@Fab1n any news on this?

**Comment by Fab1n** [comment]
@danielgindi sorry, not yet. I didn't need it really until now, but when I need it, I will convert it. 
Otherwise, what about the others here? It should not be much pain to convert it to OSX... Just work on it, submit a pull request

**Comment by pblen** [comment]
danielgindib, would like to understand the effort.  Could you point me to where the changes need to be made.  thx.

**Comment by petester42** [comment]
If it was just making type alias for bridging it would be easy but there is an extensive use of gesture recognizers which don't have an equivalent for OS X. There is also some use of CADisplayLink which doesn't exist either but from what I read can be done. 

It's not as simple as everyone here makes it seem. You can try it out and maybe help us since I don't usually make things for OS X.

**Comment by liuxuan30** [comment]
And the coordinate system is different on OS X and iOS I remember?

**Comment by danielgindi** [comment]
IF the coordinate system is different, it could be solved by changing the
affine matrix of the view on init...

**Comment by whatsthebeef** [comment]
Can the gesture recognizers not be implemented in stages?

**Comment by petester42** [comment]
There is no 1 to 1 mapping of iOS gesture recognizers to OS X gesture recognizers. Some don't exist at all so those would need to be created for OS X or disabled all together. When I tried this out last that is where I stopped.

**Comment by whatsthebeef** [comment]
I have limited knowledge of the library but some of my colleagues use it quit extensively on an iOS app and I'm working on the OSX port. I therefore have some time to invest if it is feasible to make is OSX compliant and I'm interested in your thoughts of how we might go about it.

* For gestures can we not just begin with a simple scroll which I guess can be mapped to an OSX gesture recognizer and switch the other gestures on/off according to the platform?
* If we followed this approach and given the work you have already done how long do you think it might take?

**Comment by petester42** [comment]
Probably a couple days. Don't know if I kept my work on the OS X version. If you could look into the gesture stuff that would be great. The NS* to UI* conversion is really easy with typaliases so dont worry about that.

**Comment by whatsthebeef** [comment]
Okay so I did a little research and this is what I came up with.

**UI* to NS* conversion**
* For the simpler classes (UIColor, UIFont etc.) we should just be able to use typealiases (as suggested by @petester42)
* For the more complicated classes (NSImage etc.) it's less clear and probably needs to be approached on a class by class basis.
* For classes that are missing methods, we could use typealiases and categories to add the missing methods.
* The typealiases could either specify a new class name to be used in both platforms or just point from UI* to NS* in OSX.

**UIView**
* It's not clear to me what the consequences are of typealiasing UIView and other classes high up the hierarchy. But we can just try it out I guess.

**Gestures**
* Gestures that overlap (Tap, DoubleTap) could possibly be typealiased and we can use categories to apply the correct action according to the platform if it needs it.
* Gestures that don't overlap (Pinch, Drag) can be stubbed out in the platform that doesn't used them.

**Coordinates**
* Because the NSView and UIView have different origins for the coordinates we will need to use a affline transformation (as suggested by @danielgindi) or something similar.

Any thoughts?

**Comment by pixelspark** [comment]
After a few hours:

<img width="592" alt="naamloos" src="https://cloud.githubusercontent.com/assets/181337/13089462/f985df62-d4f0-11e5-9733-8eebb4c63d6d.png">

Will upload my fork soon after clean-up.

**Comment by pixelspark** [comment]
https://github.com/danielgindi/ios-charts/pull/759

**Comment by liuxuan30** [comment]
awesome work :) only a few hours?

**Comment by whatsthebeef** [comment]
@pixelspark Have you implemented all the charts and/or any of the 'gestures'?

I have the line chart working and was working on gestures for it but if you are further a long I will bin my code and just work on yours.

**Comment by pixelspark** [comment]
@liuxuan30 yes, the find/replace bit of UI to NS/UI was actually easy. The difficult bits were the UIImage specific features ([this project](https://github.com/BigZaphod/Chameleon/tree/master/UIKit/Classes) came in handy to find how they could be implemented) and implementing CADisplayLink for OSX (there is no such thing so I simply made it into a 60fps timer - could perhaps also use CVDisplayLink in the future).

**Comment by pixelspark** [comment]
I've also implemented gestures by the way, however they need some more work. Tapping (clicking) and dragging works, haven't tried the others. OSX does not provide an NSPinchGestureRecognizer so that one won't work for sure.

**Comment by crewshin** [comment]
Thanks for putting time into this guys! I'm sure free time is hard to come by for everyone in here.

**Comment by danielgindi** [comment]
@pixelspark thank you so much for you efforts!

**Comment by danielgindi** [comment]
I've done some improvements. There are still some limitations to the gesture recognizers:

1. "magnification" recognizer has no way to tell the angle, as it does not share information about the trackpad touches...
2. There are issues with  `velocity`, but no way to resolve those in current version of the OSX SDK. The `NSGestureRecognizer` api is really lacking, and there's no way to handle the trackpad touched here. I would have written my own rotation gesture recognizer - I did so on the Android side, with velocity and eveything. But as it's impossible to effectively subclass the `NSGestureRecognizer` - it's not use.

**Comment by danielgindi** [comment]
I have implemented `CVDisplayLink` for OSX. The animations look smoother now.

Funny thing - CVDisplayLink is meant specifically for OpenGL, which makes me want to go back and try again to move all the drawing to OpenGL. But that's a project for another time :-)

**Comment by pixelspark** [comment]
Looks great, Daniel! Thanks so much for fixing up these last things. I have pulled your branch into an OS X application that draws some charts and gestures + animations seem to work smoothly :+1:

**Comment by danielgindi** [comment]
@petester42 feel free to merge that in when you feel it is ready!

**Comment by danielgindi** [comment]
I think we need some comments in the docs about this, explaining current limitations (touch gestures).
