### ISSUE TITLE
Glitch while scrolling

### ISSUE THREAD

**Issue by AlexEdunov** [danielgindi/ios-charts#430]
I have line chart view. Sometimes when I scroll it and the scale is changing I see glitch like this: https://youtu.be/HybGwFSQDjQ

**Comment by liuxuan30** [comment]
would you be able to break it when it glitch, seems like the lowestVisibleXIndex is not correct? so there will be a blank space on the left?

**Comment by AlexEdunov** [comment]
The problem went away when I set a fixed width of left axis

        leftAxis.maxWidth = 100.f;
        leftAxis.minWidth = 100.f;

**Comment by danielgindi** [comment]
Can you provide sample data for it?
Not happening in the demo...

I suspect that your leftAxis is actually trying to change size while scrolling, because of the visible data range changing. This is normal behaviour, except that the axis width changes seem too radical in your video!

**Comment by AlexEdunov** [comment]
https://github.com/AlexEdunov/ios-charts/tree/feature/issue_430

**Comment by sochalewski** [comment]
I'd like to reopen the issue. The same is happening to me almost every single move.

Screencast recorded: https://dl.dropboxusercontent.com/u/5765015/glitch.mov

Here is my setup:
`chartView.scaleYEnabled = false
chartView.scaleXEnabled = false
chartView.pinchZoomEnabled = false
chartView.doubleTapToZoomEnabled = false
chartView.xAxis.drawGridLinesEnabled = false
chartView.leftAxis.customAxisMin = 0.0
chartView.autoScaleMinMaxEnabled = false
chartView.leftAxis.drawGridLinesEnabled = false
chartView.rightAxis.enabled = false
chartView.legend.form = .Circle`

**Comment by sochalewski** [comment]
@AlexEdunov I investigated and it's broken when `drawFilledEnabled` is true. Could it be fixed easily?
