### ISSUE TITLE
Error: Can't build demo project with XCode Version 6.4 (6E35b)

### ISSUE THREAD

**Issue by AntiMoron** [danielgindi/ios-charts#431]
/Users/gaoboyuan/Downloads/ios-charts-master/Charts/Classes/Utils/UIGraphics+Extensions.swift

**Comment by danielgindi** [comment]
Of  course you can't. It's an old Xcode. Read the README. Xcode 7 is required.

**Comment by danielgindi** [comment]
Of  course you can't. It's an old Xcode. Read the README. Xcode 7 is required.

**Comment by AntiMoron** [comment]
Oh I didn't notice it. 
Sry.
