### ISSUE TITLE
dyld_fatal_error

### ISSUE THREAD

**Issue by emaddoma** [danielgindi/ios-charts#434]
I've read the instructions carefully and attempting to run on my device crashes with this error.  My project is Swift 2, XCode 7.

**Comment by yas375** [comment]
Please provide more detailed explanation of the error.

**Comment by emaddoma** [comment]
I wish I could - that's all the console says.  I had originally missed the bit about embedding the framework in the Embedded Binaries section (I had it in Linked Frameworks only) and got the image missing error.  I then added it to Embedded Binaries and now I'm getting this useless error.

**Comment by yas375** [comment]
Could you reproduce it on a sample project so we can take a look? In a project I'm working on now I'm also using the latest version of the library added manually to my project. It works fine. So I guess there is something wrong with the setup...

**Comment by emaddoma** [comment]
I'm sorry, I had added another framework shortly before yours and hadn't run on the device.  It was not yours.  Thanks for your time anyway.

**Comment by yas375** [comment]
No problem!
