### ISSUE TITLE
RadarChart (spider web chart) issue 

### ISSUE THREAD

**Issue by ergihervi** [danielgindi/ios-charts#435]
I build the demo app and select the Radar chart, the app froze and nothing happened. I tried to build it my self but same problem. The rest of the charts works.

I'm using swift 2 by the way.
![simulator screen shot 01 10 2015 17 49 06](https://cloud.githubusercontent.com/assets/14208368/10235789/3b3decb8-6865-11e5-826e-1b3794ba8f13.png)

**Comment by danielgindi** [comment]
There was a bug a few commits back. Pull the latest commit.
