### ISSUE TITLE
Label lines with different style, larger and not for all lines in grid

### ISSUE THREAD

**Issue by iangmaia** [danielgindi/ios-charts#439]
I was searching some way to achieve the following: have a grid on a line chart that has axis labels, but not for all grid lines. Also, would it be possible to have a slightly different style for these label grid lines (like different width) and make it a bit bigger than the chart borders?
This is the effect:
![screen shot 2015-10-02 at 16 16 33](https://cloud.githubusercontent.com/assets/2152244/10248642/23a1335a-6921-11e5-8bfa-9af72744fd95.png)

Thanks!

**Comment by liuxuan30** [comment]
fir the visual effect, I guess you need to override the drawing the gird lines. Take a look at `renderGridLines` and `renderAxisLine` in axis renderer files and other useful methods.

Some custimzations works for you but not others, so it's better for you to override correspoinding methods to get what you want. With a good code base, it's easy for you to figure out how to do it.
