### ISSUE TITLE
Use of undeclared type 'CGFloat'

### ISSUE THREAD

**Issue by msanders** [danielgindi/ios-charts#44]
Has anyone had any luck getting this to compile for an iOS 7 project? I tried the suggested approach (copying all .swift files to your project), but I'm getting lots of compiler errors from what look to be missing UIKit imports:

```
ios-charts/Charts/Classes/Data/ScatterChartData.swift:19:43: Use of undeclared type 'CGFloat'; did you mean to use 'CGFloat'?
ios-charts/Charts/Classes/Data/ScatterChartData.swift:21:19: Use of unresolved identifier 'CGFloat'
ios-charts/Charts/Classes/Data/BarChartData.swift:18:31: Use of unresolved identifier 'CGFloat'
ios-charts/Charts/Classes/Data/BarChartData.swift:21:28: Use of undeclared type 'CGFloat'; did you mean to use 'CGFloat'?
```

Any idea what's going wrong? I'm using Xcode 6.3.1.

**Comment by danielgindi** [comment]
There are several people who already did... But try to add an import to
UIKit and let me know

**Comment by vishw3** [comment]
Import UIKit will work i tried it few days back

**Comment by danielgindi** [comment]
In do not experience that- so if one of you wants to make a pull request
for iOS 7 compilations with the proper UIKit imports that would be great!

‏בתאריך יום חמישי, 23 באפריל 2015, Vishwas NG <notifications@github.com>
כתב:

**Comment by vishw3** [comment]
ya i wanted to support for iOS 7 so i just copied swift file in to my project and worked around every thing works fine if UIKit is imported to all shift headers

**Comment by vishw3** [comment]
hi i have created example project to run on iOS 7 tested on simulator and working fine look into it
https://github.com/vishw3/IOSChart-IOS-7.0-Support/tree/master

**Comment by danielgindi** [comment]
Merged :-)

**Comment by zhijunsheng** [comment]
I cloned yesterday. Don't understand why I had to manually add "import UIKit" for swift files dragged in. I'm using Xcode 7.3.1 and my own project is an ObjC one. What did I miss?

**Comment by kaleevans** [comment]
I've had the same issue as zhijunsheng. Objective-c project still having this issue.

I am trying the importing swift files method as I had issues just importing the framework with the bridging header.

**Comment by balkarov** [comment]
I have this problem too
