### ISSUE TITLE
Custom Y Axis entries with String values

### ISSUE THREAD

**Issue by hipwelljo** [danielgindi/ios-charts#441]
Is there a way to specify custom label entries for the Y axis? In my case, I need to label the y axis with labels that are letters of the alphabet A-Z. Labeling them 0-25 isn't appropriate. How can I use custom String entries for the y axis?

**Comment by baumatron** [comment]
You can implement a NSNumberFormatter and assign it to your chart view's leftAxis.valueFormatter property.

**Comment by shivang2902** [comment]
You can find help from this issue https://github.com/danielgindi/Charts/issues/943
