### ISSUE TITLE
xcode 7 issue? -  non-existent file for the CFBundleExecutable key

### ISSUE THREAD

**Issue by vamsi80us** [danielgindi/ios-charts#442]
Runs fine on the device but submit to app store does not succeed. Please help.

This is the error message I get after app submission using xcode / itunes connect:
------------
Invalid Bundle - Info.plist of “AppName.app/Charts/ChartsTV” specifies a non-existent file for the CFBundleExecutable key...

Invalid Bundle - Info.plist of “AppName.app/Charts/Supporting Files” specifies a non-existent file for the CFBundleExecutable key...

Once these issues have been corrected, you can then redeliver the corrected binary.
--------------

**Comment by danielgindi** [comment]
Just remove the ChartsTV target from the project and you'll be fine
