### ISSUE TITLE
Demo project is not working 

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#443]
Hi,
demo project is not working properly.I got the following errors

1.cannot override  anon-failableintializer.
2.Consecutive statements on a line separated by :.

I got above errors.

Please help how to rectify these errors.

Thanks
Smily

**Comment by liuxuan30** [comment]
may be it's your setup problem, it works fine on my side. You need to google or search SO for it. Seems your Xocde is out of date? master has been merged with swift 2.0

**Comment by petester42** [comment]
Because of your number 1 I would say you are not using Xcode 7
