### ISSUE TITLE
Candle Stick not filled make the stick and the gridline show within the candle

### ISSUE THREAD

**Issue by iangmaia** [danielgindi/ios-charts#444]
See the picture below:

![screen shot 2015-10-05 at 15 01 53](https://cloud.githubusercontent.com/assets/2152244/10281045/13be8f34-6b72-11e5-9b05-3032f27bc81d.png)

The stick line is seen within the candle, because it isn't being filled. There should be a way to configure only the border of the candle and still have the body solid.

One way to fix this would be to have stick border color / body color properties, so we could set a solid body color independently of the border color.

**Comment by iangmaia** [comment]
By the way, this could be fixed with a custom renderer as well, but the private properties on CandleStickChartRenderer makes a bit hard to extend it -- maybe making this renderer a bit easier to be extended is also a good idea.

**Comment by danielgindi** [comment]
That has been fixed a week or two ago :-)
