### ISSUE TITLE
Make _chart in CombinedChartRenderer internal

### ISSUE THREAD

**Issue by AlBirdie** [danielgindi/ios-charts#446]
Hi guys, 

would it be possible to change the _chart property in the CombinedChartRenderer from private, to internal?

That would assist extendability a lot. I'm constantly forgetting to change this once I've updated to the new master branch.

Cheers!

**Comment by danielgindi** [comment]
No problem make a PR and I can merge it quickly using a message in the
Telegram bot ;)

‏בתאריך יום שני, 5 באוקטובר 2015, AlBirdie <notifications@github.com> כתב:

**Comment by AlBirdie** [comment]
Awesome! ETA tomorrow morning! :+1:

**Comment by AlBirdie** [comment]
Sorry, couldn't make it yet. But this is on my to do list monday morning!
