### ISSUE TITLE
Can we show title of Axis?

### ISSUE THREAD

**Issue by bravevu** [danielgindi/ios-charts#447]
Example, xAxis with title is Month, labels are Jan, Feb, Mar..., can we show Month below Jan, Feb... or at right of December?

**Comment by iangmaia** [comment]
You can create an array of strings with the formatted months and use it in the xVals constructor parameter (e.g. ChartData(xVals:monthsXValues dataSets:[dataSet]))

**Comment by solidcell** [comment]
I believe @bravevu is saying that he'd like to display the label `"Month"` below the months.  So a label that describes what the axis is.  Not the individual values for x-positions.

**Comment by danielgindi** [comment]
https://github.com/danielgindi/ios-charts/issues/61
