### ISSUE TITLE
bar width

### ISSUE THREAD

**Issue by vigyanhoon** [danielgindi/ios-charts#448]
Is there any way we can control space between two dataset bars for graph having large width and only one or two x values? I can change bar width via barspace but not space between bars. 

Basically I want to modify bar width only to have smaller width bars than bars with giant width taking entire chart view width.

Following is the graph with two datasets array having only one index each.
![screen shot 2015-10-06 at 12 25 02 pm](https://cloud.githubusercontent.com/assets/8503526/10301980/86fcc368-6c25-11e5-9c77-ed6aa6ed622f.png)

**Comment by vigyanhoon** [comment]
I dont want my graph to look like following hence changing bar width using barSpace property on datasets.

![screen shot 2015-10-06 at 12 31 54 pm](https://cloud.githubusercontent.com/assets/8503526/10302065/5e0dd8ce-6c26-11e5-9d16-5f0910066562.png)

Thanks.

**Comment by danielgindi** [comment]
From the docs:
> space indicator between the bars in percentage of the whole width of one value (0.15 == 15% of bar width)

If the whole space for a bar is 100%, then a `barSpace` of 0.15 means that 15% of it will be space, and 75% is for the bar.

The sizes are in percentages as there is no absolute size of the bar on the view. It depends of how many bars you try to fit in the viewport.

**Comment by niksdgr8** [comment]
I understand that by setting barspace I get width of bar but how to set space of bar from which it gets barspace?

**Comment by liuxuan30** [comment]
@niksdgr8 be more clear, you are like rapping :) space of bar is barspace?

**Comment by tejas-ardeshna** [comment]
@danielgindi  @liuxuan30 Is it possible to fix bar width and bar space will adjust accordingly to number of bars?

**Comment by liuxuan30** [comment]
not sure what you mean. But they work fine right now..?

**Comment by tejas-ardeshna** [comment]
@liuxuan30  Nop man I just set data.barWidth = 20.0 and now each bar is covering whole graph view. All I want to fix size bar for a different number of bars.

**Comment by liuxuan30** [comment]
You set a big bar width and it is wider for sure..
I am still not clear for "fix size bar for a different number of bars". The more bars you have, the thinner for each bar. You should check the code to see how bar width is used.

**Comment by mushtaque87** [comment]
I want a fixed bar with ... i dont want dynamic bar width.. Like if i have one bar or 10 bar .. The size should be same not dynamically change .. It looks odd when you have 1 or 2 bars ... the bar looks fat ... where as when you have more then 5 - 6 bar they looks fine .. So for less bar say 1 or 2 bar how to make bar with fixed and also they should not be very far away .. it should be close to each other and also looks fixed sizes

**Comment by preetirani** [comment]
@vigyanhoon  How did you managed to get fixed bar width via bar space ??

**Comment by wooodypan** [comment]
@preetirani Do you mean set the bar in fixed width, no matter how many data ? I just found the solution:
``` objc
// the code is in BarChartViewController.m (BarChartViewController.swift)
        _chartView.data = data;
        [_chartView setVisibleXRangeMaximum:10];
```
