### ISSUE TITLE
chartView does't overlay with dark color highlighted value in bar chart 

### ISSUE THREAD

**Issue by cooler333** [danielgindi/ios-charts#449]
```swift
let chartHighlight = ChartHighlight(xIndex: 0, dataSetIndex: 0, stackIndex: 0)
strongSelf.chartView.highlightValue(highlight: chartHighlight, callDelegate: true)
```
when bar was selected by tap all works well, but when select from code, overlay do not drown as expected

**Comment by danielgindi** [comment]
What do you see drawn instead?

**Comment by cooler333** [comment]
Nothing. ChartView call highlight delegate method. But does not draw overlay for bar section. Color stay same


Wednesday 7 October 2015 09:55 +0300 from Daniel Cohen Gindi  <notifications@github.com>:

**Comment by danielgindi** [comment]
There may be a missing setNeedsDisplay call. I'll look into it. In the mean
time, try to add a setNeedsDisplay call.

**Comment by danielgindi** [comment]
Well I couldn't reproduce this problem. I'm guessing your Highlight object is not configured well

**Comment by danielgindi** [comment]
If it's not a stacked bar chart, set stackIndex to -1

**Comment by cooler333** [comment]
@danielgindi i can't highlight segment on stacked bar chart without ChartRange param. But all methods which return correct ChartRange are Internal func. 

    let entry = dataSet.entryForXIndex(_xIndex)
    let point = chartView.getPosition(entry!, axis: dataSet.axisDependency)
    let chartHighlight = chartView.getHighlightByTouchPoint(point)
    chartView.highlightValue(highlight: chartHighlight, callDelegate: true)

the code above doesn't allow to change yVal. Always return last(top) segment from ChartDataEntry

**Comment by cooler333** [comment]
The problem in range.

    let chartHighlight = ChartHighlight(xIndex: _xIndex, dataSetIndex: 0, stackIndex: _yIndex, range: ChartRange(from: ???, to: ???))

if range exist (in internal func called by gesture recogniser) chart is highlighted, but if I pass nil range nothing happens.

**Comment by cooler333** [comment]
fixed:

    let entry = dataSet.entryForXIndex(_xIndex) as! BarChartDataEntry

    let x = Double(_xIndex)

    var y = 0.0
    for (var i = 0; i <= _yIndex; i++) {
        y += entry.values![i]
    }

    let pixel = chartView.getPixelForValue(x, y: y, axis: dataSet.axisDependency)
    let chartHighlight = chartView.getHighlightByTouchPoint(pixel)
    chartView.highlightValue(highlight: chartHighlight, callDelegate: true)

    // _xIndex, _yIndex - private property

**Comment by danielgindi** [comment]
@PhilJay It seems like the `stackIndex` is not used at all when drawing highlights  for stacked bar, but the range property. It is only used for determining a boolean of `isStacked`... Are you planning on "fixing" this or should the users rely on the range instead?

**Comment by liuxuan30** [comment]
@danielgindi I just answered a question yesterday, to use stackIndex -1 to highlight the whole bar, instead of the segments. Is this valid?

**Comment by raghunath44** [comment]
I want to show yValue in AnotherBarChart.This is my Code:
-(void)setUpAnotherBarViewOptions:(BarChartView *)anotherBarChart
{
    
    anotherBarChart.descriptionText = @"";
    anotherBarChart.noDataTextDescription = @"You need to provide data for the chart.";
    
    anotherBarChart.maxVisibleValueCount = 60;
    anotherBarChart.pinchZoomEnabled = NO;
    anotherBarChart.drawBarShadowEnabled = NO;
    anotherBarChart.drawGridBackgroundEnabled = NO;
    
    ChartXAxis *xAxis = anotherBarChart.xAxis;
    xAxis.labelPosition = XAxisLabelPositionBottom;
    xAxis.spaceBetweenLabels = 0.0;
    xAxis.drawGridLinesEnabled = NO;
    
    
    ChartLegend *legend = anotherBarChart.legend;
    legend.position = ChartLegendPositionBelowChartCenter;
    legend.font = [UIFont fontWithName:@"HelveticaNeue-Light" size:14.f];
    
    anotherBarChart.leftAxis.drawGridLinesEnabled = NO;
    anotherBarChart.rightAxis.drawGridLinesEnabled = NO;
    anotherBarChart.leftAxis.enabled = NO;
    anotherBarChart.rightAxis.enabled = NO;
    
    anotherBarChart.legend.enabled = YES;    
}
