### ISSUE TITLE
Provide callbacks on ChartViewDelegate to better handle dragging, touch, etc

### ISSUE THREAD

**Issue by iangmaia** [danielgindi/ios-charts#451]
Since the chart already has GestureRecognizers (making it hard to add our own), there could be callback methods in the "should*" fashion to pass to the delegate the touched Point and to let the delegate allow or not the chart to pan.
This is useful, for instance, if I want to draw something on the chart as the user drags his finger over it instead of panning the chart.

It is possible to achieve the same having a container view with touchesBegan, touchesMoved, etc and using the "dragEnabled" property and the isInBounds methods, but having it in the delegate would be cleaner, more natural and flexible.

**Comment by danielgindi** [comment]
You don't have to do all of that. You just add your own gesture recognizers in addition to whatever is in the chart.
We don't add custom APIs for anything that is supported natively by iOS.
