### ISSUE TITLE
how to update the ios-charts in existing projects.

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#452]
Hello. 

I am using ios-charts in project. Recently I have upgraded yosemite to capitan. Also switch from Xcode 6.4 to Xcode 7.0. The on opening the project it asked to update the latest swift. Also it is showing random errors. The ios-charts was perfectly integrated in Xcode 6.4.
 Do I need to change any extra things while with Xcode 7. Is this the known issue. I have been struggling with this issue since last 3 days. please help.

I tried many different ways to solve the issue. The issues are random.
1) I replaced in project with new Charts.xcodeproj. Also added and updated any missing files from class folder. But its not working for me.
2) It shows systemConfiguration.framework not found.

**Comment by petester42** [comment]
What kind of errors are you seeing?

**Comment by wganeshb** [comment]
Thanks @petester42 .  

I have already integrated ios-charts with the Xcode 6.4 It worked fine. I opened the same project with Xcode 7. It force me to went through following processes. 

![screen shot 2015-10-07 at 10 45 54 am](https://cloud.githubusercontent.com/assets/3005149/10329723/916f229c-6ce2-11e5-9cd1-d081780679f8.png)

![screen shot 2015-10-07 at 10 46 16 am](https://cloud.githubusercontent.com/assets/3005149/10329727/9e58d69c-6ce2-11e5-9eca-0b88059f71b7.png)

Then I updated the Charts.xcodeproj and merged the new latest 'Class' folder with my project. But it is showing following error.

Target specifies product type 'com.apple.product-type.application.watchapp', but there's no such product type for the 'watchsimulator' platform

**Comment by danielgindi** [comment]
You are using an old version of Charts. The newer version uses Swift 2.0.

**Comment by wganeshb** [comment]
Thanks for reply. 
I downloaded the latest master. Removed the Charts.xcodeproj from existing project. And again dragged the Charts.xcodeproj from latest master ios-charts. It doesn't work for me. 

Am I missing anything, any step. 
I am struggling with this since last three days. Please help me out.

**Comment by danielgindi** [comment]
What doesn't work? You HAVE to elaborate. We're not telepathies.

**Comment by wganeshb** [comment]
Sorry I couldn't reply. The problem is solved. I was missing something. The Xcode was just not reflecting the changes by dragging the Charts.xcodeproj.

I completely removed the library cleaned the project. And freshly integrated it again with fresh project. It successfully got added. Now it is working just fine.

Thank you very much.
