### ISSUE TITLE
problems using autoScaleMinMaxEnabled 

### ISSUE THREAD

**Issue by tila77** [danielgindi/ios-charts#453]
Hello,
I try to auto scale the y-axis for an LineChart. If I set the option autoScaleMinMaxEnabled, followed by an notifyDataSetChanged no auto scale occurs.

Also toggeling autoScaleMinMaxEnabled in ChartsDemo seems not to work. Is there a special trick?

Many thanks! - Tini

**Comment by danielgindi** [comment]
You see the auto-scale in action when scrolling the chart sideways. It scales the Y axis depending on the data that is in the visible area.

**Comment by tila77** [comment]
Hello Daniel,

I don't know what I'm doing wrong. Using the ChartDemo-App I have the following behavior:

- LineChart (LineChart1ViewController) - If I change the data range the y-axis don't scale
- BarChartViewController - If I change the data range the y-axis scale - also after toggeling the property toggleAutoScaleMinMax

Also in my own application I have an unexpected behavior - adding a dataset with values 900 +/- 10 the y-axis has a range of 0 .. 1000. Do I have a wrong understanding? I suggest the behavior is, that after setting toggleAutoScaleMinMax the y-axis will have a range such as 800 ... 900.

I'm very impressed of the charts created by using ios-charts - so I want to use these library!

Thanks for help! - Tino
