### ISSUE TITLE
swift 1.2 branch

### ISSUE THREAD

**Issue by vineethvijayan** [danielgindi/ios-charts#459]
What is the branch having swift 1.2?

what should be the pod code that we should use?

**Comment by liuxuan30** [comment]
you can check the old commits before swift 2.0 merged into master, or check out release tags to find a proper release. No branch for swift 1.2 now. Also, you should use Xcode 7 for many reasons.

**Comment by vineethvijayan** [comment]
i think 2.3.1 is the tag, but how to write the pod code?

Sorry I am very new to iOS

**Comment by yas375** [comment]
@vineethvijayan I would encourage you to use the latest tool. Especially if you are new. Use the latest version of Xcode available on the AppStore. It support Swift 2.0. And the same version of Swift is used by the library. Then follow instructions from readme how to add the library to your project.

**Comment by liuxuan30** [comment]
@vineethvijayan as @yas375 said, it's the best deal for you to get started using latest software and tools. Plus the library is continuing improving, bugs and features will be added, and only added based on swift 2.0.
