### ISSUE TITLE
chart is scrolling to top when reach maxScaleY and try zoom in again

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#463]
Steps to reproduce, using ChartsDemo:
for normal bar chart:
```Swift
[_chartView.viewPortHandler setMaximumScaleY:3.0];
```
for horizontal bar chart:
```Swift
// which is a little confusing, it means the x axis for horizontal bar chart
[_chartView.viewPortHandler setMaximumScaleY:3.0]; 
```
First reach the max scale level, scroll the chart to the middle, and try zoom in again, it actually starts a scrolling to top, which at first seems zooming.

@noais I guess it's introduced in https://github.com/danielgindi/ios-charts/pull/388?

**Comment by noais** [comment]
@liuxuan30 yes you right this happens on all charts. 
I put this gift http://imgur.com/chYcHLV to explain the issue. 

It's hard to fix this issue and the worst part is to not have time to fix him 😓

**Comment by iangmaia** [comment]
Isn't that the same as  #437?
I've sent a pull request that seems to have fixed the issue but it hasn't been reviewed yet.

**Comment by liuxuan30** [comment]
@iangmaia I don't see it on maxScaleX, only scaleY. Your PR #438 seems only to fix the x axis, while I don't have this problem on x axis. Could you clarify?

**Comment by iangmaia** [comment]
@liuxuan30 Yes, you're right. I've added now scaleY handling as well.
I think I took the assumption that they were also always gonna be changed together (which is my case and it seemed to fix the issue).

**Comment by iangmaia** [comment]
@liuxuan30 Actually, I've played around with it a bit more and I realized it fixes only when pinchZoom is enabled. When it is disabled, unfortunately it is still there.

**Comment by liuxuan30** [comment]
@iangmaia thanks, but why can't it be applied when pinchZoom disabled?

**Comment by danielgindi** [comment]
I have merge that PR, and made some fixes. Now it works properly
