### ISSUE TITLE
Feature : initial display of the graph

### ISSUE THREAD

**Issue by Begoodi** [danielgindi/ios-charts#468]
Hi Daniel,

A useful feature would be to choose, for a bargraph, the starting index of the graph.
Something like "barchartview.startViewIndex", so the bargraph is directly displayed at this position with animated features enabled.

Thanks

**Comment by danielgindi** [comment]
I don't quite understand what do you mean here...

**Comment by petester42** [comment]
Lets say you have a chart with all days of the month then I think he wants to set the current day index and it move to that point automatically when the chart is loaded.

That's what I got from it.

**Comment by Begoodi** [comment]
Yes pettester42, that's it.
Today the chart is automatically loaded showing day 1, and then I have to make a move to day 20 for example. So the user sees the first load, and then he sees the move.
I would like to directly show the graph on day 20 for example.

**Comment by liuxuan30** [comment]
There is already some people asking for this, like  moveViewToX() and Animated better, like  #450, #318

**Comment by danielgindi** [comment]
Now that there's much more control of the viewport - including animated move and zoom - I think we got this covered!
