### ISSUE TITLE
Y-Axis values "stick together" occasionally

### ISSUE THREAD

**Issue by amycheong19** [danielgindi/ios-charts#469]
Sorry for the bad titles. Please see the image for better understanding.
The YAxis values is off ("stick together") and it will only recover when user tap on the chart.
This happens on Android version as well.

Here is the settings I used for the chart. Hope it helps.

        combinedChartView.pinchZoomEnabled = true
        combinedChartView.drawGridBackgroundEnabled = false
        combinedChartView.doubleTapToZoomEnabled = false
        
        combinedChartView.rightAxis.enabled = true
        combinedChartView.leftAxis.enabled = false
        combinedChartView.legend.enabled = false
        combinedChartView.drawBarShadowEnabled = false
        
        combinedChartView.setViewPortOffsets(left: 0, top: 0, right: 0, bottom: 20)
        
        let yAxis: ChartYAxis = combinedChartView.rightAxis
        yAxis.startAtZeroEnabled = false
        yAxis.labelPosition = .InsideChart
        yAxis.drawAxisLineEnabled = false
        yAxis.labelTextColor = COLOR_GREY
        yAxis.axisLineColor = COLOR_GREY
        yAxis.gridColor = COLOR_GREY_AA
        
        let yAxisFormatter = NSNumberFormatter()
        yAxisFormatter.maximumFractionDigits = 3
        yAxis.valueFormatter = yAxisFormatter

<img width="480" alt="screen shot 2015-10-13 at 8 28 44 pm" src="https://cloud.githubusercontent.com/assets/9781961/10454720/6277adae-71e9-11e5-8ad5-089dc4f1c831.png">

**Comment by danielgindi** [comment]
@PhilJay

**Comment by PhilJay** [comment]
What happens if you out-comment this line: `combinedChartView.setViewPortOffsets(left: 0, top: 0, right: 0, bottom: 20)`?

**Comment by amycheong19** [comment]
combinedChartView.setViewPortOffsets(left: 0, top: 0, right: 0, bottom: 20) 
wont fixed the issue but 
managed to solve it by setting it after the data is being drew and chart.notifyDataSetChanged().

**Comment by danielgindi** [comment]
Does this still happen?

**Comment by danielgindi** [comment]
I don't see this happening using your code. I'm assuming this is closed. Feel free to re-open with a fuller code-sample if you are still experiencing this.
