### ISSUE TITLE
Pinch to Zoom is not being disabled properly.

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#470]
We are turning off the pinch to zoom by the following code:

`self.barChartView.pinchZoomEnabled = NO;`

But we are still able to pinch zoom, this has only been happening recently after the latest update to charts, is there something else we need to do to disable it?

**Comment by danielgindi** [comment]
pinchZoomEnabled is only one way to zoom. There are also per axis zoom options which you need to turn off- and it has always been there...

**Comment by GABHISEKBUNTY** [comment]
```
 self.barChart?.doubleTapToZoomEnabled = false
 self.barChart?.pinchZoomEnabled = false
 barChart.dragEnabled = false
```


I have tried out the above things but still user is able to zoom the bar chart. Can you please suggest the code to disable X & Y scaling individually.

**Comment by zanesc** [comment]
@GABHISEKBUNTY after having the same issue i found the option to disable all zooming:

`self.barChart?.setScaleEnabled(false)`

**Comment by joaocamargo** [comment]
@zanesc  You saved my day! Tks

**Comment by tscholze** [comment]
Could it, that this fix does not longer work in Charts v4?
