### ISSUE TITLE
Problem with marker in Swift

### ISSUE THREAD

**Issue by m0rt3nlund** [danielgindi/ios-charts#472]
Hi!

I am getting an error saying **Cannot assign a value of type 'BalloonMarker' to a value of type 'ChartMarker?'**

BalloonMarker is the same as the Balloon marker in the demo.

Code:
``` swift
let marker:BalloonMarker = BalloonMarker(color: UIColor.redColor(), font: UIFont(name: "Roboto", size: 15)!, insets: UIEdgeInsets(top: 8.0, left: 8.0, bottom: 8.0, right: 8.0))
marker.minimumSize = CGSizeMake(80.0, 40.0)
            
//Line with error
cell.chart.marker = marker
```

Is this a bug?

**Comment by m0rt3nlund** [comment]
Problem was that I had created a subclass of ChartMarker... Sorry for this issue.

**Comment by channak** [comment]
Hi could you provide your working code? I am also facing the same problem.
