### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by rajasagashe** [danielgindi/ios-charts#473]
Hello,

Occasionally when open up my xcode project with the charts framework. I get this error message:

<unknown>:0: error: no such file or directory: '/Users/Documents/"Project Name"/Classes/Utils/UIGraphics+Extensions.swift'
<unknown>:0: error: no such file or directory: '/Users/Documents/"Project Name"/Classes/Utils/CALayer+Extensions.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

The only way I can seem to make it go is by removing the charts xcode project and then adding it back again. Do you know why this may be happening?

**Comment by danielgindi** [comment]
Maybe your source control mixes up version of your project file.

Anyway, from the latest commits, those two files do not exist anymore and are not used anymore.

**Comment by rajasagashe** [comment]
ok gotcha! thanks for the fast response!
