### ISSUE TITLE
compiling for iPhone4s gives error like #344

### ISSUE THREAD

**Issue by Stay-in-Touch** [danielgindi/ios-charts#475]
ambiguous use of dataset
Is ios-chart supposed to work with 4s? It works beautifully with iPhone 6 in the simulator but I get this error when I start to test on other phones.

    public override func isEqual(object: AnyObject?) -> Bool
    {
        if (object === nil)
        {
            return false
        }
        
        if (!object!.isKindOfClass(self.dynamicType))
        {
            return false
        }
        
        if (object!.value != _value)
        {
            return false
        }
        
        if (object!.dataSetIndex != _dataSetIndex)
        {
            return false
        }
        
        if (object!.dataSet !== _dataSet)  // error is here
        {
            return false
        }
        
        return true
    }
}

JOhn

**Comment by liuxuan30** [comment]
It has nothing to do with hardware model so far, only iOS version. Upgrade your ios-charts to swift 2.0 and Xcode 7 and try again. #344 is fixed in https://github.com/danielgindi/ios-charts/commit/da0877b7259c2a892ed7d0744d33a190c0707d77
