### ISSUE TITLE
Can't install app due to non matching architecture.

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#476]
I have integrated the ios-charts. It worked fine on iphone6+.
Now testing app on iPhone5 (ios 9.0.2). 

following are build setting for project and target.

![screen shot 2015-10-15 at 1 15 24 pm](https://cloud.githubusercontent.com/assets/3005149/10507616/5a96e148-733f-11e5-80a6-03114c083836.png)

But I am getting this error. 

![screen shot 2015-10-15 at 1 13 19 pm](https://cloud.githubusercontent.com/assets/3005149/10507649/8bd6c44e-733f-11e5-9f6a-67f3c6bda995.png)

I am not getting any clue. Has anybody got any suggestions please.

**Comment by danielgindi** [comment]
Check your app's plist

**Comment by wganeshb** [comment]
Thanks @danielgindi ,
Yes it solved my problem. 
armv7 was not included in app's plist file.
