### ISSUE TITLE
Zombie exception

### ISSUE THREAD

**Issue by 931743010** [danielgindi/ios-charts#477]
only one number 
            [yVals1 addObject:[[ChartDataEntry alloc] initWithValue:0 xIndex:j]];

Int(pt.x) exception
BarLineChartViewBase---public var highestVisibleXIndex: Int---Int(pt.x)

**Comment by liuxuan30** [comment]
mate, you need to provide more info so we can help you. With this I can say nothing

**Comment by AntiMoron** [comment]
There's an error while doing casting.
just 
[yVals1 addObject:[[BarChartDataEntry alloc] initWithValue:0 xIndex:j]];

I think this is a casting bug.

**Comment by 931743010** [comment]
[yVals1 addObject:[[ChartDataEntry alloc] initWithValue:0 xIndex:j]];
not a casting bug;when server give me one number ;{11:00, 0}
and the andriod version is ok
when my yVals1 only have one number  and this number is 0;  will have exception
Int(pt.x) exception
exception-site   BarLineChartViewBase---public var highestVisibleXIndex: Int---Int(pt.x)

**Comment by 931743010** [comment]
when  initWithValue:0  and just one number ; use the LineChartView  the pt.x will be {nan,nan}, then will exception.

**Comment by liuxuan30** [comment]
Can you reproduce it with ChartsDemo code? I don't quite understand your words

Give the full dataSet and reproduce it with ChartsDemo

**Comment by AntiMoron** [comment]
此贴其实可以中文。

**Comment by 931743010** [comment]
- - 我看 demo是好的， 我再试试

**Comment by 931743010** [comment]
谁知道如何把
![7dec0ddc-eda8-4712-bdf0-fa4241f83040](https://cloud.githubusercontent.com/assets/9315727/10660590/9f6d60a8-78da-11e5-83e4-c1d84f7239bf.png)    里面的日期  竖起来显示呢 如下图
![default](https://cloud.githubusercontent.com/assets/9315727/10660619/d4a24aea-78da-11e5-9a43-ba3777463d68.png)

**Comment by 931743010** [comment]
还有  就是柱状图上  x轴显示的 数字是double  能不能 只显示整数，如何做呢

**Comment by liuxuan30** [comment]
1. use valueFormatter and other available formatters
2. the text rotation is a little complicated, but you could try with CoreGraphics, you can override the renderer

I guess it's better to write in English, as more people can help you.

**Comment by AntiMoron** [comment]
@liuxuan30  :+1: 

0. Inherit ```ChartXAxisRenderer ``` and override ```renderAxisLabels ```
1. Inherit ```LineChartView``` and  override its ```initialize``` function to reset the ```xAxisRenderer``` ;-)

**Comment by 931743010** [comment]
The key is I only know a  little about swift，just know about Object-C,my project is write with Object-C. if you have some times off and this is easy for you .  Can you write a demo for me,thanks.

**Comment by liuxuan30** [comment]
I tried rotate the label a little but no luck yet, seems I missed something there..

**Comment by 931743010** [comment]
Look forward to this function；
i have another question ：
all number Type is int ，but the Axis Display the type of double； is there any Method to display int。
i dont want to Modify the danielgindi/ios-charts.

**Comment by 931743010** [comment]
![img_0182](https://cloud.githubusercontent.com/assets/9315727/10683509/527595b8-7975-11e5-98f4-615f21ea4d0e.PNG)

**Comment by 931743010** [comment]
Removal of the decimal number in the X axis of the table
