### ISSUE TITLE
PieChart chartValueSelected don't return the good entry

### ISSUE THREAD

**Issue by AmandineDB** [danielgindi/ios-charts#48]
Hello, 

on the function for Pie chart
-(void)chartValueSelected:(ChartViewBase * __nonnull)chartView entry:(ChartDataEntry * __nonnull)entry dataSetIndex:(NSInteger)dataSetIndex highlight:(ChartHighlight * __nonnull)highlight

the entry is not good and dataSetIndex is set to 0

could you explained me what i must do for getting the good entry?

Have a good day

Amandine

**Comment by danielgindi** [comment]
Then entry is good. You are probably looking for xIndex, not dataSetIndex.
