### ISSUE TITLE
Using image as marker in the chart

### ISSUE THREAD

**Issue by orlanczyk** [danielgindi/ios-charts#483]
Hi i am trying to find a way to make a data set that each of the markers will be an image instead of the default points or circles, is there a way to do it?

**Comment by liuxuan30** [comment]
sure, there is already an UIImage property there:
```Swift
public class ChartMarker: ChartComponentBase
{
    /// The marker image to render
    public var image: UIImage?
```

**Comment by orlanczyk** [comment]
Can you provide an example I can't find any in the documentation and I couldn't understand your explanation.

Thanks,
Gal

**Comment by liuxuan30** [comment]
I am saying ChartMarker already has image property. I have post the code and point out the function in my answer that you need look at.

**Comment by orlanczyk** [comment]
i want to make a graph like this where 1 set will be a regular line and the other will be another indicator with pills for example if my x axis is the time i will have a series of times i need to take a pill.
i don't need the marker to show image when it is selected i need a complete set of data values to show images instead of default circle/dot.
i really appreciate any help.

screenshot:
![screen shot 2015-10-26 at 08 20 49](https://cloud.githubusercontent.com/assets/6908583/10722715/d4ea4dfc-7bbb-11e5-8493-37cf9cd99eca.png)

**Comment by liuxuan30** [comment]
answered in #506

**Comment by vinhqn** [comment]
Hi.
i want draw or using  property image same attachment file. help me. Thanks
<img width="69" alt="screen shot 2017-09-27 at 3 45 46 pm" src="https://user-images.githubusercontent.com/8424069/30904120-2d8db490-a39b-11e7-8f3a-1c882b343905.png">

**Comment by NallapatiMalleswari** [comment]
Any one found solution for custom marker Image.
i want to add custom marker like in the bellow picture , anyone can help me. Thanks

![screen shot 2017-10-31 at 3 20 08 pm](https://user-images.githubusercontent.com/31246172/32217813-2023564c-be4f-11e7-88d3-fa638e825dc3.png)

**Comment by waleedmahmood** [comment]
I don't know if anyone still looking for a solution. Here is an example:

```
let entries = stride(from: 0.0, to: Double(10), by: 1.0).map { (i) -> ChartDataEntry in
            return ChartDataEntry(x: i+0.25, y: Double(55), icon: UIImage.init(named: "YourImageName"))
        }
```

I am using scatter plot, just create your data entries with an image name, and Charts will plot it for you automatically, depending on icon size of your file.

🥳
