### ISSUE TITLE
Positioning using screen points instead of xIndex

### ISSUE THREAD

**Issue by alessandroorru** [danielgindi/ios-charts#487]
Is it possible to scroll to a portion of the graph defined by a rect (or offset) in terms of screen points instead of data points?
I would like to position the viewport in a similar fashion of what I can do with a UIScrollView using the `scrollToRect`/`scrollToOffset` method. 
The only scroll method I found is `moveViewToX(xIndex: Int)` but it needs data point, not screen points.

**Comment by liuxuan30** [comment]
Are you talking about #226?
