### ISSUE TITLE
inner web lines missing. 

### ISSUE THREAD

**Issue by hosokawa-gh** [danielgindi/ios-charts#490]
I have a question about the Radar chart in ChartsDemo. 
As you can see from the picture that I have attached, there are some inner web lines that are missing. 
(I have not done any additional work after git clone)
<img width="244" alt="ng" src="https://cloud.githubusercontent.com/assets/13192100/10630243/5fb4581a-7810-11e5-9c31-20fd0594f15a.png">

I would like to show lines in blue in the attached picture. 
<img width="244" alt="desire" src="https://cloud.githubusercontent.com/assets/13192100/10630242/5fb3f38e-7810-11e5-971b-105b8cb514fa.png">

Could you give me advice how to do it ?

Thanks.

**Comment by danielgindi** [comment]
It's a bug with the default `skipWebLineCount`. Set it to `0` and it will be fine.
It you are not working with pods then you can just pull the latest code changes.
This has been fixed 20 minutes ago by @PhilJay, https://github.com/danielgindi/ios-charts/commit/46fd83942da8f572989dbee9d88eb8152baeb1d0

**Comment by PhilJay** [comment]
The thing with this is it totally looks like a bug if you have an uneven number of web lines. But yes, as Daniel mentioned it's not a bug, just a "badly placed" default value of skip = 1.

**Comment by hosokawa-gh** [comment]
Thanks.
