### ISSUE TITLE
About method setCircleColor & setCircleHoleColor

### ISSUE THREAD

**Issue by kscorpio** [danielgindi/ios-charts#491]
setCircleColor:  
 setCircleHoleColor:   

 No visible @interface for 'ChartDataSet' declares the selector 'setCircleColor:'

**Comment by liuxuan30** [comment]
Because only LineChartDataSet has circleColor

**Comment by GayatriNagarkar** [comment]
I am using Charts 3.0 and drawn a line chart.
I have set setCircleHoleColor for LineChartDataSet and it is not working.
Is there any change for same, as in previous version it was working correctly?

Any help would be appreciable.
Thank you in advance!

**Comment by GayatriNagarkar** [comment]
I got the solution! :)
Found newly added method setCircleHoleRadius.

It's working as expected now.
Thank you. :)
