### ISSUE TITLE
Background color and floats on Y axis.

### ISSUE THREAD

**Issue by tomkowz** [danielgindi/ios-charts#495]
Hey, I'm trying to understand the library (iOS). I try to draw simple chart for forecast and have few problems:

- I cannot change background color. Don't really know which value I should modify. The background is still white. View in storyboard has transparent background.
- Values on Y axis are floating numbers instead of ints.
- How to disable showing X and Y axis when selecting some value on a chart?

Thank you in advance

**Comment by liuxuan30** [comment]
1. use UIView.backgroundColor
2. use yAxis.valueFormatter (+ forceLabelsEnabled + labelCount if you need to avoid duplicated int because 2.1 and 2.3 will be 2) read computeAxisValues carefully
3. use drawLabelsEnabled properly when you highlight or have your own customization
If you are trying to understand, read each class's properties first.

**Comment by danielgindi** [comment]
@tomkowz set `UIView.opaque` to `false` if you want the chart to have a `UIColor.clearColor` as its `backgroundColor`. Otherwise the transparent background will be drawn as a black color.

**Comment by tomkowz** [comment]
Setting `opaque` to `false` and `backgroundColor` to `clearColor` was the first thing I did. And background is still white.

    [_chartView setViewPortOffsetsWithLeft:0 top:0 right:0 bottom:0];
    _chartView.descriptionText = @"";
    _chartView.noDataTextDescription = @"You need to provide data for the chart.";
    _chartView.xAxis.enabled = NO;
    _chartView.rightAxis.enabled = NO;
    _chartView.legend.enabled = NO;
    _chartView.opaque = NO;
    _chartView.backgroundColor = [UIColor clearColor];

**Comment by petester42** [comment]
Are you sure you are not talking about the `gridBackgroundColor`? I'm pretty sure that it isn't white by default but maybe try that.

**Comment by tomkowz** [comment]
You're right. `gridBackgroundColor` is what I need to use.
