### ISSUE TITLE
LineChart crashes if no entries

### ISSUE THREAD

**Issue by jwardle** [danielgindi/ios-charts#496]
Instead of showing the 'no data available' perspective of the chart, with version 2.1.5 of Charts the view now crashes when there are no data items to be shown...when the chart is instructed to draw the circles on the line (the no data available view shows correctly if drawCirclesEnabled = false).

LineChartRenderer.drawCircles() is the culprit, particularly the forced unwrap on the following line within drawCircles()

    let entryFrom = dataSet.entryForXIndex(_minX)!

This can be protected against by adjusting the test above this line to include a check for 0 data entries:

    if (!dataSet.isVisible || !dataSet.isDrawCirclesEnabled || dataSet.entryCount == 0)
     {
           continue
     }

**Comment by danielgindi** [comment]
Thanks!!! :-)
