### ISSUE TITLE
When i use ios-charts with swift ..

### ISSUE THREAD

**Issue by paneaktae** [danielgindi/ios-charts#50]
How i fix it?
![screen shot 2558-04-27 at 10 49 40 am](https://cloud.githubusercontent.com/assets/11417557/7341359/407726c4-eccb-11e4-9581-78106d4344a1.png)

**Comment by liuxuan30** [comment]
`LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithYVals:yVals label:@"DataSet 1"];` this is in demo code.

**Comment by saivenkatesh005** [comment]
i am also getting same problem can you please any one help me this issue and is there any sample swift project for iOS charts

**Comment by danielgindi** [comment]
The first argument is not named in this case, so it should be `LineChartDataSet(yVals, label: ...)`. Although it should be named. **Xcode knows how to automatically fix your call!**

I will change the function signatures soon so keep up with the updates and let xcode fix it back when necessary.

**Comment by danielgindi** [comment]
Actually never mind - the initializers always have the first argument named. I have absolutely no idea why you are getting that error.

**Comment by danielgindi** [comment]
Well, actually, I do. The compiler tells you that there's no initializer that accepts an `NSMutableArray`. It accepts a simple swift array, not an `NSMutableArray`.
