### ISSUE TITLE
StackedBar Chart highlighting complete single bar

### ISSUE THREAD

**Issue by NSri** [danielgindi/ios-charts#504]
I am using StackedBar Chart in iOS-Charts, I need to provide two functionality:

1) When user selects single bar I need to highlight complete Bar instead of specific stack index.
2) I need to show pop-up with complete value.
 How this can be achieved?

For highlighting I tried doing following but it's not working

let highlighter1: ChartHighlight = ChartHighlight(xIndex: dataSetIndex, dataSetIndex: 0, stackIndex: 0)
let highlighter2: ChartHighlight = ChartHighlight(xIndex: dataSetIndex, dataSetIndex: 0, stackIndex: 1)
let highlighter3: ChartHighlight = ChartHighlight(xIndex: dataSetIndex, dataSetIndex: 0, stackIndex: 2)

chartView.highlightValues([highlighter1, highlighter2, highlighter3])

this doesn't even highlight single bar.

if I give single value it works.

**Comment by liuxuan30** [comment]
1. using -1 for stackIndex will highlight the whole bar, is this what you want?
2. Take a look at ChartMarker, it can pop up a small HUD to display some text. Just try the ChartsDemo

**Comment by NSri** [comment]
Thanks :+1:  'ChartMarker' class helped.

**Comment by liuxuan30** [comment]
don't forget it can have image as well :)

**Comment by hardiiik** [comment]
For marker things, ChartMarker is perfect as per @liuxuan30 
But to highlight whole stacked bar, you can use this property of BarChartView, 
`chartView.setHighlightFullBarEnabled = true`
