### ISSUE TITLE
Making a line chart set with images on the chart

### ISSUE THREAD

**Issue by orlanczyk** [danielgindi/ios-charts#506]
i want to make a graph like this where 1 set will be a regular line and the other will be another indicator with pills for example if my x axis is the time i will have a series of times i need to take a pill.
i don't need the marker to show image when it is selected i need a complete set of data values to show images instead of default circle/dot. in short i need to create a series of images instead of the default dots/circles for a set of data.
i really appreciate any help.

screenshot:
![screen shot 2015-10-26 at 08 20 49](https://cloud.githubusercontent.com/assets/6908583/10733720/a49cf7ba-7c08-11e5-8f9b-8663cd061970.png)

**Comment by liuxuan30** [comment]
Then write your own code and logic  to add the image. The logic to calculate the position is already there. You simply write your own rendering method to draw the images instead of line dots

**Comment by orlanczyk** [comment]
Listen i really don't understand what you mean, could you please provide me with a little example...
where is the drawing method of the dots that i can override with my own drawing? i am really lost here and could really use your help...

**Comment by liuxuan30** [comment]
I have no time to provide code example. You should have the knowledge and skill to code right?

Where to draw the dot: search `private func drawCircles(context context: CGContext)`
This is where it draws the circle. walk through the logic to have a better idea and sub class of line chart view and override this method, to draw the image you want

**Comment by orlanczyk** [comment]
the drawCircles is in the renderer, i can't get it to subclass properly. i understand i can only switch the renderer of the chart and than it will draw the images but i can get it subclass from outside the library.
is there an example of subclassing the renderer properly? (the animator property doesnt get recognised)

**Comment by liuxuan30** [comment]
you have to sub class the chart view and replace the renderer with yours.

Take a look at how bar chart and line chart is sub classed from BarLineChartViewBase

**Comment by AlexanderKvamme** [comment]
Hey guys I am curious about this as well! All i wanna do is to fill a select few holes. Im very new to customizing libraries, and im wondering, is this possible to to do without manipulating the Charts files?  Im using Cocoapods and im wondering if i can do this with subclassing or if i gotta manually drag the Charts files over and then manipulate them :)
