### ISSUE TITLE
ComboChartView highlight

### ISSUE THREAD

**Issue by cooler333** [danielgindi/ios-charts#507]
I can't choose bar when use lines+bar dataSets

When i select bar, lines select too but bar only highlight.
I've mailed you demo with this issue.

Screenshots attached below:

![simulator screen shot 26 oct 2015 18 38 14](https://cloud.githubusercontent.com/assets/2772537/10733687/dfd4c30a-7c10-11e5-918f-e15f99f005b2.png)
![simulator screen shot 26 oct 2015 18 38 26](https://cloud.githubusercontent.com/assets/2772537/10733686/dfd4d44e-7c10-11e5-9b3b-fbf962df83e4.png)

**Comment by liuxuan30** [comment]
Don't mail privately; github has enough space to report problem and get response
You could look at the combined chart renderer and customize your own highlight rendering logic. The default highlight will highlight both line dots and the bars.
