### ISSUE TITLE
How to detect end of chart event?

### ISSUE THREAD

**Issue by orlanczyk** [danielgindi/ios-charts#508]
i am trying to detect end of chart, and couldn't find any event taking care of that.
i need to fetch data once the chart has reached the end and user kept dragging.
the problem is the current translated delegate is keeps getting called as long a the gesture keeps going.
could someone help me find a solution?

Thanks
Gal

**Comment by liuxuan30** [comment]
You can customize it a little bit I guess: try to find if the `highestVisibleIndex` has reach the max value and send a proper message to your delegate? Or there is no more space to scroll;

**Comment by liuxuan30** [comment]
closing - maybe this will be solved when native Realm support rolls out.

**Comment by krystianpaszek** [comment]
I'm also interested in that issue, detecting end of the chart would be useful.
