### ISSUE TITLE
How can I reset bargraph total width ?

### ISSUE THREAD

**Issue by Begoodi** [danielgindi/ios-charts#509]
Here is my case 

I have a bargraph with let's say 20 bars and only 10 visible with scroll option.
For any reason, I need to recalculate and redisplay it.
So I make barChartView.clear(), fetch new data, etc.

Now if the bargraph has only 5 values, the total width of the bargraph doesn't change and the bars are very thick (x4 in this case).
I would like the width of the bargraph to be not wider than the screen, as I have enough space to see it.

In other word, is there a method that would reset the graph better than with the clear() method ?

**Comment by liuxuan30** [comment]
I remember the default solution will show all your data at once. It is simple math: less bars, more bar width;
The bar will never wider than the screen unless you zoomed in a lot; if this is the case, simply add maxScaleX would solve your problem? BTW, there is `groupSpace` and `barSpace` to control the width.
