### ISSUE TITLE
Changing the specific data point (circle color) in Line Chart

### ISSUE THREAD

**Issue by rajatmohanty** [danielgindi/ios-charts#51]
In case of Line Chart, whenever user is tapping on the small circle(data point), a Popover is displaying to user and i want to change the color of this specific data point(small circle only) instead of color of whole line chart.

Is there any way to do this ?

**Comment by danielgindi** [comment]
The popover is part of the demo, not part of Charts.
So you can use whatever popover you want, and you can query the color from the dataset using the xIndex.
