### ISSUE TITLE
How in your chart on the basis of the modified？

### ISSUE THREAD

**Issue by Bogon** [danielgindi/ios-charts#510]
How in your chart on the basis of the modified, I will be able to get this effect: such as January, February, march, April sales are mapped onto the icon, but there is no results, march to achieve with implementation is in January and February, between February and April a line drawing? To provide a train of thought?

**Comment by liuxuan30** [comment]
have no idea what are you saying, an image could help a lot

**Comment by Bogon** [comment]
just like this
![img_0018](https://cloud.githubusercontent.com/assets/6748372/10752009/6a57248c-7cc0-11e5-9578-6f36d6425363.jpg)
