### ISSUE TITLE
Can't update library to 2.1.5 by cocoapods

### ISSUE THREAD

**Issue by AlexEdunov** [danielgindi/ios-charts#511]
I set up Podfile as following:

    pod 'Charts', '~> 2.1.5'

When I try to install pods I get following error:

	$ pod install
	
	Updating local specs repositories
	Analyzing dependencies
	[!] Unable to satisfy the following requirements:
	
	- `Charts (~> 2.1.5)` required by `Podfile`

Utility pod search also couldn't find latest version:

	$ pod search Charts
	
	-> Charts (2.1.4)
   	ios-charts is a powerful & easy to use chart library for iOS
   	pod 'Charts', '~> 2.1.4'
   	- Homepage: https://github.com/danielgindi/ios-charts
   	- Source:   https://github.com/danielgindi/ios-charts.git
   	- Versions: 2.1.4, 2.1.4a, 2.1.3, 2.1.2, 2.1.0, 2.0.9 [master repo]

Did you forget to update podspec?

Right now I use HEAD version, but it's not safe.

	pod 'Charts', :git => 'https://github.com/danielgindi/ios-charts.git', :commit => 'HEAD'

**Comment by danielgindi** [comment]
You know what - seems like I did forget it! silly me... I published it now, you may try again :-)
