### ISSUE TITLE
How to set position of description?

### ISSUE THREAD

**Issue by kiliankoe** [danielgindi/ios-charts#512]
Hi,

as far as I can tell MPAndroidChart [offers the option](http://stackoverflow.com/a/29149527/1843020) of setting the description position. Is this in any way possible with ios-charts? I can't find a way to do so.

Thanks!

**Comment by danielgindi** [comment]
Yeah, seems like I missed that feature... Added now :-)

**Comment by kiliankoe** [comment]
Awesome, thanks for the amazingly fast fix!
