### ISSUE TITLE
 This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.

### ISSUE THREAD

**Issue by dddppp** [danielgindi/ios-charts#514]
Hello,

I am running the iOS Charts library extensively on an App and I get the following message:

"This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
 Stack:(
	0   CoreFoundation                      0x0000000182884f74 <redacted> + 148
	1   libobjc.A.dylib                     0x000000019747bf80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182884ea4 <redacted> + 0
	3   Foundation                          0x000000018389e5d8 <redacted> + 88
	4   Foundation                          0x0000000183720a1c <redacted> + 36
	5   UIKit                               0x0000000187edf93c <redacted> + 64
	6   UIKit                               0x00000001886060ac <redacted> + 156
	7   UIKit                               0x0000000188605da0 <redacted> + 252
	8   UIKit                               0x00000001886060d8 <redacted> + 200
	9   UIKit                               0x0000000187ee0820 <redacted> + 100
	10  UIKit                               0x0000000187edf94c <redacted> + 80
	11  UIKit                               0x0000000187ee0454 <redacted> + 244
	12  UIKit                               0x000000018860677c <redacted> + 268
	13  UIKit                               0x00000001880ddfb0 <redacted> + 176
	14  UIKit                               0x0000000187dd701c <redacted> + 688
	15  QuartzCore                          0x00000001875ddf14 <redacted> + 148
	16  QuartzCore                          0x00000001875d8b20 <redacted> + 292
	17  QuartzCore                          0x00000001875d89e0 <redacted> + 32
	18  QuartzCore                          0x00000001875d807c <redacted> + 252
	19  QuartzCore                          0x00000001875d7dd0 <redacted> + 516
	20  QuartzCore                          0x0000000187606f48 <redacted> + 236
	21  libsystem_pthread.dylib             0x0000000197e8a1e8 <redacted> + 584
	22  libsystem_pthread.dylib             0x0000000197e89d60 <redacted> + 136
	23  libsystem_pthread.dylib             0x0000000197e89544 pthread_mutex_lock + 0
	24  libsystem_pthread.dylib             0x0000000197e89028 start_wqthread + 4
)"

I have zombie objects enabled as well as an "All Exceptions" breakpoint, no sign that is from my code so I assume is from iOS Charts. 

To fix this we need to modify the iso-charts library so it modifies the UI elements using dispatch on the main queue, see here:

http://stackoverflow.com/questions/28302019/getting-a-this-application-is-modifying-the-autolayout-engine-error

**Comment by petester42** [comment]
You application is doing something not on the main thread. As far as I know there is no autolayout code in this library.

**Comment by liuxuan30** [comment]
@petester42  +1, it's your code problem, not this library

**Comment by bocalexandru** [comment]
I receive the same error, only here it references the Charts:

`This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
 Stack:(
	0   CoreFoundation                      0x0000000182252dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001818b7f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182252cf8 <redacted> + 0
	3   Foundation                          0x0000000182d03b2c <redacted> + 88
	4   Foundation                          0x0000000182b84c3c <redacted> + 36
	5   UIKit                               0x00000001873a2bc4 <redacted> + 532
	6   UIKit                               0x00000001873b0678 <redacted> + 1784
	7   Charts                              0x0000000100bbaff8 _TFC6Charts26ChartXAxisRendererBarChart10drawLabelsfT7contextCSo9CGContext3posV12CoreGraphics7CGFloat6anchorVSC7CGPoint_T_ + 8104
	8   Charts                              0x0000000100baf8fc _TFC6Charts18ChartXAxisRenderer16renderAxisLabelsfT7contextCSo9CGContext_T_ + 1720
	9   Charts                              0x0000000100b09ac8 _TFC6Charts20BarLineChartViewBase8drawRectfVSC6CGRectT_ + 9548
	10  Charts                              0x0000000100b09fb8 _TToFC6Charts20BarLineChartViewBase8drawRectfVSC6CGRectT_ + 120
	11  UIKit                               0x0000000187432678 <redacted> + 368
	12  QuartzCore                          0x0000000184d66228 <redacted> + 260
	13  QuartzCore                          0x0000000184d508ac <redacted> + 2432
	14  QuartzCore                          0x0000000184e68360 <redacted> + 52
	15  QuartzCore                          0x0000000184d4fa88 <redacted> + 1368
	16  QuartzCore                          0x0000000184d317a8 <redacted> + 228
	17  QuartzCore                          0x0000000184d31494 <redacted> + 44
	18  QuartzCore                          0x0000000184d30ab8 <redacted> + 252
	19  QuartzCore                          0x0000000184d30818 <redacted> + 500
	20  QuartzCore                          0x0000000184d5fbcc <redacted> + 236
	21  libsystem_pthread.dylib             0x0000000181eb61e0 <redacted> + 584
	22  libsystem_pthread.dylib             0x0000000181eb5d58 <redacted> + 136
	23  libsystem_pthread.dylib             0x0000000181eb553c pthread_mutex_lock + 0
	24  libsystem_pthread.dylib             0x0000000181eb5020 start_wqthread + 4
)`

I have checked and double checked all the calls to the library to not call from any other thread thah the main one!

**Comment by petester42** [comment]
Our library contains no auto layout code. The problem is on your end. You are probably modifying the constraints of the view that contains the chart.
