### ISSUE TITLE
No 'setHighlightPerTapEnabled(boolean enabled)' in iosCharts?

### ISSUE THREAD

**Issue by jarp89** [danielgindi/ios-charts#515]
I can't find this method which exists in MPAndroidChart. Is it not implemented yet?

Thanks in advance.

**Comment by danielgindi** [comment]
It's a new feature which is implemented in both platforms. But it's not a method, it's a property.
In traditional languages there were always `get`/`set` pairs for properties, but in Swift there's an actual property.
If coding for ObjC, you *will* see an `setHighlightPerTapEnabled`, but in swift you won't.
