### ISSUE TITLE
Does ios-charts work for Mac Cocoa programming?

### ISSUE THREAD

**Issue by johnwheeler** [danielgindi/ios-charts#516]
Can these charts be embedded in a Mac OS X app or is core-plot the only game in town? I know this is probably a stupid question given the name of this project, but I am new to Mac development and am wondering if it would be hard to port these to working on Mac if they don't already.

Thanks,
John

**Comment by petester42** [comment]
As of right now no. There are certain complications with OS X due to the use of gesture recognizers.

**Comment by liuxuan30** [comment]
someone saying he will do the porting, but not yet. You can have a try :-)  there would be some differences on the gestures and other stuff, so a descent work is needed
