### ISSUE TITLE
Implementing Gestures

### ISSUE THREAD

**Issue by htran91** [danielgindi/ios-charts#519]
I'm having trouble implementing gestures to interact with my line chart. I am pretty new to swift programming but i know that you can highlight values using the chartValueSelected function. It appears as the mpandroidcharts has something that allows for gesture recognition when highlighting lines. Is there something in this port that does the same thing?

**Comment by liuxuan30** [comment]
gestures should be different on these platforms. It already has tap gesture and other gestures (pinch, pan) there. You can write your own gesture handler.

**Comment by danielgindi** [comment]
You should read about UIGestureRecognizers in iOS. It's a wonderful gesture
system.
>
>

**Comment by ashish1703** [comment]
Hi,

Well i am trying to add a tap gesture to the barchartView but not getting succeeded.
This the code which i am using:

UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(touch:)];
    [tap setNumberOfTapsRequired:1]; // Set your own number here
    [tap setDelegate:self]; // Add the <UIGestureRecognizerDelegate> protocol
    
    UILongPressGestureRecognizer *longTap = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(longTouch:)];
    [longTap setNumberOfTapsRequired:0]; // Set your own number here
    [longTap setMinimumPressDuration:1.0];
    [longTap setDelegate:self]; // Add the <UIGestureRecognizerDelegate> protocol
    [tap requireGestureRecognizerToFail:longTap];   // Priority long
    
    [self.barchartV addGestureRecognizer:tap];
    [self.barchartV addGestureRecognizer:longTap];

Nothing gets to the selector functions.

Please help..!!

**Comment by liuxuan30** [comment]
file a new issue if it's releated to the charts, or ask it on StackOverflow for technical quetions.
To me, seems bar chart already has tap gesture so some conflicts maybe. Ask on SO is much easier to get it answered.
