### ISSUE TITLE
When I used iOS-charts in iOS 7 project

### ISSUE THREAD

**Issue by LumiaSaki** [danielgindi/ios-charts#52]
I dragged all of .swift files into my project, then build the project, 400+ errors appeared, it seemed like the codes can't recognize UIKit, I had to add a line `import UIKit` manually in every .swift file.
Is there anything wrong in my steps?
BTW: This charts library is really powerful!

**Comment by danielgindi** [comment]
There was a problem when compiling for iOS 7. It's already fixed in a previous commit
