### ISSUE TITLE
no equal distance between points on x-axis

### ISSUE THREAD

**Issue by richarddigifit** [danielgindi/ios-charts#522]
I couldn't find if this is possible:

If I have, for example, 3 data-entries with time = 1,2 and 10
What I want is a line graph with distances between the points on the x-axis according to the time of the data entries. So that the distance between points 1 and 10 = 10x the distance between points 1 and 2.

But when I add these points to a LineChartView, I need to give them xIndex 0,1,2
and the distance between 1, 2 and 10 is equal everywhere.

Is it possible what I want or is this not a feature (yet)?

**Comment by liuxuan30** [comment]
I have asked for such a feature in #176 (#194 the same) a long time ago. But it needs lot of rewrite and even before start writing, we need to think about a lot of things... So it is a big change and no ETA yet. 

I suggest you workaround it buy inserting the rest xIndex but no y value provided

**Comment by cartmanguo** [comment]
@liuxuan30 你意思是ChartDataEntry初始化的时候value参数传0？
