### ISSUE TITLE
if I want to set the RadarLabel like this!

### ISSUE THREAD

**Issue by JasonSZL** [danielgindi/ios-charts#524]
if I want to set the RadarLabel like this!
    public override func renderAxisLabels(context context: CGContext)
    {
        if (!_xAxis.isEnabled || !_xAxis.isDrawLabelsEnabled)
        {
            return
        }
        
        let labelFont = _xAxis.labelFont
        let labelTextColor = _xAxis.labelTextColor
        let labelRotationAngleRadians = _xAxis.labelRotationAngle * ChartUtils.Math.FDEG2RAD
        let drawLabelAnchor = CGPoint(x: 0.5, y: 0.0)
        
        let sliceangle = _chart.sliceAngle
        
        // calculate the factor that is needed for transforming the value to pixels
        let factor = _chart.factor
        
        let center = _chart.centerOffsets
        
        let modulus = _xAxis.axisLabelModulus
        for var i = 0, count = _xAxis.values.count; i < count; i += modulus
        {
            let label = _xAxis.values[i]
            
            if (label == nil)
            {
                continue
            }
            if (_xAxis.labelPosition == .Top)
            {
                
            }
            let angle = (sliceangle * CGFloat(i) + _chart.rotationAngle) % 360.0
            
            
            let p = ChartUtils.getPosition(center: center, dist: CGFloat(_chart.yRange) * factor + _xAxis.labelRotatedWidth / 2.0, angle: angle)
            if(angle == 270){
                drawLabel(context: context, label: label!, xIndex: i, x: p.x, y: p.y - _xAxis.labelRotatedHeight / 2.0 - 100, attributes: [NSFontAttributeName: UIFont.systemFontOfSize(14), NSForegroundColorAttributeName: UIColor.greenColor()], anchor: drawLabelAnchor, angleRadians: labelRotationAngleRadians)

//            drawLabel(context: context, label: label!, xIndex: i, x: p.x, y: p.y - _xAxis.labelRotatedHeight / 2.0, attributes: [NSFontAttributeName: labelFont, NSForegroundColorAttributeName: labelTextColor], anchor: drawLabelAnchor, angleRadians: labelRotationAngleRadians)
            }else{
                
                drawLabel(context: context, label: label!, xIndex: i, x: p.x, y: p.y - _xAxis.labelRotatedHeight / 2.0, attributes: [NSFontAttributeName: labelFont, NSForegroundColorAttributeName: labelTextColor], anchor: drawLabelAnchor, angleRadians: labelRotationAngleRadians)
            }
            

        }
    }

the QUESTION is :+1: 
the  labelRotatedHeight  and the Label color is changed, but when the RadarView Rotating! the Label will be reDraw and the setting is Invalid. 

so where is the method of the label redraw and how could i setting?
 thank u very much!

**Comment by liuxuan30** [comment]
it's in drawRect: either figure out a way to dynamicly change your setting or disable the redrawLabels if you detect it's rotating, or just disable the rotate
```Swift
    public override func drawRect(rect: CGRect)
    {
        super.drawRect(rect)

        if (_dataNotSet)
        {
            return
        }
        
        let optionalContext = UIGraphicsGetCurrentContext()
        guard let context = optionalContext else { return }
        
        _xAxisRenderer?.renderAxisLabels(context: context)
```

**Comment by JasonSZL** [comment]
I want  when it Rotating and  the color and position of the TOP Label be changed only. but there have some Automatic calculation bothers me ,

**Comment by liuxuan30** [comment]
I guess you have to write your own logic for what you want. If something bothers you, just override the method and take what you need.

**Comment by JasonSZL** [comment]
thank u very much
