### ISSUE TITLE
My own app is crashed  and got error is fatal error: value failed to bridge from Swift type to a Objective-C type

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#525]
Hi,

I am assigning yaxis custom max and min values dynamically.When i gave values statically to the Line graph it works fine but when i gave values dynamically to the Line graph  the app crashes at the following point

" _xAxis.labelWidth = widthText.sizeWithAttributes([NSFontAttributeName: _xAxs.labelFont]).width"

Please suggest me why the app is crushed at this point.

Please help me its very urgent for me.

Thanks
Smily

**Comment by liuxuan30** [comment]
you have to give the crash log... looks like width is nan?

**Comment by liuxuan30** [comment]
close as no update. Reopen if you are able to reproduce.
