### ISSUE TITLE
Scale and displacement by code

### ISSUE THREAD

**Issue by mariovillamizar** [danielgindi/ios-charts#527]
Hi @danielgindi , thank you for this great library, it's amazing. I have a question. I have two charts, a chart below the other. I need to synchronize both charts. I mean, when a chart is displaced and/or scaled, the other chart should also do the same. It this possible? How can I do this?

**Comment by liuxuan30** [comment]
Definitely it's possible, but this will requires some addtional understanding how the scale and scroll works. 

There is a class called ChartViewPortHandler, and there are the methods you need to scale/scroll or even give your own matrix.

**Comment by mariovillamizar** [comment]
Hi again @liuxuan30 and @danielgindi. I managed to synchronize the two charts. Now the problem that I have is that the size of the charts changes when I zoom or scroll as the y-axis values change.

Example:

![simulator screen shot nov 4 2015 11 29 11 am copy](https://cloud.githubusercontent.com/assets/10704258/10944554/bac2863c-82e7-11e5-86d9-457e555603a0.png)

I need to synchronize the size of chart too. I need that the size of both charts is always the same. 

Example:

![simulator screen shot nov 4 2015 11 29 27 am copy](https://cloud.githubusercontent.com/assets/10704258/10944601/084172d8-82e8-11e5-97a9-9fe265398001.png)

**Comment by liuxuan30** [comment]
`1. the size of the charts changes when I zoom or scroll `
the size of the chart is controlled by the frame, right? Have you change it? The zoom/scroll will never change the frame. Not sure the meaning
`2. as the y-axis values change.`
the y-axis value will change, because you are zooming! Right? :)
