### ISSUE TITLE
Get the visible max and min yAxis values

### ISSUE THREAD

**Issue by mariovillamizar** [danielgindi/ios-charts#528]
Is possible to get the visibles max and min values of yAxis or the visible center value of yAxis?

**Comment by liuxuan30** [comment]
There is {highest/lowest}VisibleXIndex, so it is possible to get the value you want.
but the values on the y axis may be a little tricky, because it's calculated with some algorithm

**Comment by mariovillamizar** [comment]
Yes @liuxuan30. I was trying to get a formula and eventually achieve an approximation, but can sometimes fails.

**Comment by liuxuan30** [comment]
the formula is in computeAxis

**Comment by liuxuan30** [comment]
close as no update
