### ISSUE TITLE
BalloonMarker shows float number with many digits after '.'

### ISSUE THREAD

**Issue by bravevu** [danielgindi/ios-charts#529]
Function: refreshContent in BalloonMarker needs change to highlight: ChartHighlight. entry.value.description shows many digits of float number.

**Comment by liuxuan30** [comment]
don't you use a formatter?

**Comment by bravevu** [comment]
Yes, I can fix for myself. But I only note, let others know it.

**Comment by liuxuan30** [comment]
Yes, thanks! The balloonMarker is a demo I guess, so not implementing a lot features in it.
