### ISSUE TITLE
Highlight a label in xAxis

### ISSUE THREAD

**Issue by mats-claassen** [danielgindi/ios-charts#530]
Hi, I am trying to draw a line chart where one entry is highlighted. I can get the circle to be different to the others but I did not find a way to have different fonts and colors for the labels in the xAxis. I mean having all labels with one font but the selected label with another font.
Is there a way to do this? I tried using attributed strings but that did not work either.

**Comment by liuxuan30** [comment]
You can trigger another drawLabels, get which label you need to highlight and feed your own colors, fonts etc. when highlighting. It is not designed to do so for now.

**Comment by jibax** [comment]
Hi @mats-claassen Did you managed the set a different font for the labels?

**Comment by liuxuan30** [comment]
so some details:
xAxis has font and color property called `labelFont` and `labelTextColor` you can set it from there.
If you want to set different font, then you may have to customize yourself - take a look at 
`internal func drawLabels(context context: CGContext, pos: CGFloat, anchor: CGPoint)`, and override it with your own implementation.

**Comment by mats-claassen** [comment]
@thang2410199 I ended up using [my fork](https://github.com/xmartlabs/ios-charts) which I changed to fit my particular needs. Not sure it will be useful for you. It is almost 3 years old as well.
