### ISSUE TITLE
Legend at bottom of graph show on more than one line.

### ISSUE THREAD

**Issue by bravevu** [danielgindi/ios-charts#532]
I draw graph having 7 data sets, use ChartLegendPositionBelowChartCenter for position of legend. Because legend length is so long, can't show all in one line, I want to show in 2 lines. How can we do it?

**Comment by liuxuan30** [comment]
I guess you might want to custimze it? I remember we don't support the wrapping lines right now?

My workaround is I had my own legend implementation and put it in a scroll view. I once suggest @danielgindi to put the legend in a scroll view.

**Comment by danielgindi** [comment]
If I remember correctly wrapping lines is supported

‏בתאריך יום חמישי, 5 בנובמבר 2015, Xuan <notifications@github.com> כתב:

**Comment by danielgindi** [comment]
Just set `legend.wordWrapEnabled = true`

**Comment by cuddle-sujeet** [comment]
I have a stacked bar graph and want the labels in the legend to come below each other in a vertical stack
have used
           graphView.legend.maxSizePercent = 0.70
                graphView.legend.wordWrapEnabled = true
still doesnt work

**Comment by a-radwan** [comment]
Is it possible to trim the legend view , to be able to display limited number of  lines only , specific height or limited number of values.

**Comment by liuxuan30** [comment]
@a-radwan I guess not, take a look at ChartLegend
