### ISSUE TITLE
Line chart circle positions

### ISSUE THREAD

**Issue by martinnormark** [danielgindi/ios-charts#535]
The circles in a line chart doesn't position perfectly:
![screenshot 2015-11-05 22 37 45](https://cloud.githubusercontent.com/assets/67565/10982534/1c1856d8-840e-11e5-8d5b-98a5b54e800c.png)

I wonder if this is caused by `drawCubicEnabled`, I've tried tweaking `cubicIntensity` but it gets off already around ~0.15.

**Comment by liuxuan30** [comment]
Sorry for late reponse I was thinking someone could help on this.

Have you solved this or, confirmed as a bug and can be reduced using ChartsDemo?

**Comment by danielgindi** [comment]
This is how cubic lines work. The point of the value is not necessarily the highest or lowest point of the curve.
I'm not sure if we should even try to fix this...
@PhilJay thoughts?

**Comment by PhilJay** [comment]
This is not really an issue.
As Daniel mentioned this is just how cubic lines work. Of course we could change that (somehow), but it would eliminate the natural behaviour of cubic lines.

**Comment by augustinAJ** [comment]
@danielgindi  @PhilJay  Could please tell me how to solve this issue. According to my requirement the circles should end at the coordinates.

**Comment by danielgindi** [comment]
I'm afraid there's bot much we can do about it. That's how cubic lines work. That's by definition of the cubic function... See http://cdn-5.analyzemath.com/Graphing/cubic_graph_3.gif

**Comment by danielgindi** [comment]
Btw, you can try playing with `cubicIntensity`

**Comment by augustinAJ** [comment]
what does it do?

**Comment by danielgindi** [comment]
It controls the intensity of the cubic bezier.
