### ISSUE TITLE
Getting some interesting errors when trying to upload our project to ITC with the latest ios-charts.

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#538]
Hey everyone,

We're getting some strange issues when we try to upload to iTunesConnect something about Unsupported Architectures and I'm not quite sure how to fix it.

![pasted image at 2015_11_06 09_46 am](https://cloud.githubusercontent.com/assets/1090748/10999996/2ed7338e-846d-11e5-9da9-29db2e048aad.png)

**Comment by prithsharma** [comment]
@BrandonShega - how did you fix these?
