### ISSUE TITLE
Use LineChartView create chartview will not slide,  

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/ios-charts#540]
Use LineChartView create chartview will not slide, but after scaling up after can slide, at this time only can slip a little, can't slide to the end, how to solve

**Comment by liuxuan30** [comment]
line chart can only scroll when your data is out of screen - that's why we scroll right?
if you cannot slide to the end, you may want to provide the data code you use or a sample project so we can know. But to me, it seems the library itself is ok for this part

**Comment by shanyulaile** [comment]
Has been solved，thank you

**Comment by xchenLee** [comment]
if datas are too much, the line chart looks so bad, i think it should supply method to set scaleX when initial the chart ,then the chart can scroll and look good
