### ISSUE TITLE
Guidance on scrollable/pannable charts

### ISSUE THREAD

**Issue by trustyfrog** [danielgindi/ios-charts#543]
Can anyone provide an example of a chart that can be panned/scrolled along an axis, please?

**Comment by petester42** [comment]
The demo project has such examples.

**Comment by trustyfrog** [comment]
I went through them yesterday, but none let you scroll until you perform some other kind of action, like a zoom. 

I've event set the number of values to display but it still tries to show all of them.

I also checked the Android equivalent help but I couldn't find the equivalent.

**Comment by danielgindi** [comment]
By default the viewport is fully zoomed out. You can change the zoom programatically, and then the user could scroll.
