### ISSUE TITLE
App didn't started with Charts

### ISSUE THREAD

**Issue by ShadyRover** [danielgindi/ios-charts#546]
I add project Charts to Xcode 7, it has sucsessfuly running on Simulator, but when I distribute app and run on iphone, it shows splash screen and close without errors. When I remove Charts, app run OK

**Comment by petester42** [comment]
We need more details to help you. What is the error message.

**Comment by liuxuan30** [comment]
Another typical issue? Just search:)

**Comment by ShadyRover** [comment]
No errors message, I noticed that if run app from simulator but not debugger, the application is closed, as well as on the iPhone

**Comment by petester42** [comment]
Ok well. We need some sort of error report to be able to help you.

**Comment by ShadyRover** [comment]
How I can get deep log? Because, stacktrace when app close is clear

**Comment by petester42** [comment]
You can see some of the device's log when you plug it in and go to devices in Xcode. Probably google something like "see device log in Xcode"

**Comment by ShadyRover** [comment]
Okey, I find the log. It says: "Library not loaded /Charts.framework/Charts"

**Comment by petester42** [comment]
Ok good. Have you followed the installation methods mentioned in the readme? If so which one?

**Comment by ShadyRover** [comment]
I'm trying install via CocaPods, but I can't add framework to Embeded Binary or Linked Frameworks. When building project I get error: "Charts not found". I try add .xcodeproj to project, it builds succsessful, but I get crash(as in topic). When I add framework to Embedded Binaries, project didn't build, but I havn't get error

**Comment by petester42** [comment]
That's not how cocoapods works. You define your podfile and the do `pod install`. That's it. No other steps needed. Info on how cocoapods works can be found [here](https://cocoapods.org)

**Comment by ShadyRover** [comment]
I add Charts with Pods, but project not building (No such module 'Charts')

**Comment by petester42** [comment]
What does your podfile look like?

**Comment by ShadyRover** [comment]
```
use_frameworks!
pod 'Cartography'
pod 'Charts'```

**Comment by petester42** [comment]
That's looks fine. when you run `pod install` what happens.

**Comment by ShadyRover** [comment]
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11 (15A282b)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 03c5a5413149795cc09fcc63dda21ebf34adbb43
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Sber' do
pod 'Cartography'
pod 'Charts'

end

target 'SberTests' do

end

target 'SberUITests' do

end
```

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`A848AACE1BEFB0620038B734`>:Xcodeproj::Project::Object::PBXFileReference
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:91:in `set_target_xcconfig'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:25:in `block (2 levels) in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:43:in `block in integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:40:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:116:in `block in integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:750:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:747:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:112:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60files%27+for+%3CPBXFileReference+path%3D%60Pods%60+UUID%3D%60A848AACE1BEFB0620038B734%60%3E%3AXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

**Comment by ShadyRover** [comment]
I didn't find how resolve this issue, I reinstall CocoaPods two times. This issue happened on each project in Xcode

**Comment by petester42** [comment]
This is an issue with cocoapods or your setup. Open an issue with cocoapods if you are having problems. If you have iOS charts specific questions just open another issue.
