### ISSUE TITLE
CocoaPods can only install Charts with Version `2.1.3`

### ISSUE THREAD

**Issue by dogvscat** [danielgindi/ios-charts#547]
Readme shows there is a new version `2.1.6`,but when i use CocoaPods install it ,i get some errors, and `pod search Charts` only get version 2.1.3 . if i use version 2.1.3 , i will get some compile errors like "# has removed from swift, double up start start ....".

**Comment by petester42** [comment]
Just did this and got the right version. Maybe your cocoapods version is out of date or something.

**Comment by dogvscat** [comment]
Cocoapods version is 0.39.0 ,when i finished installing Charts,i just  import Charts in ViewController, but i will get errors ‘no such module Charts’, so what should i do ?

**Comment by petester42** [comment]
Try pod update. Maybe your podfile.lock has 2.1.3 in it.

**Comment by dogvscat** [comment]
@petester42  below is my podfile.lock.

PODS:
  - Charts (2.1.3)

DEPENDENCIES:
  - Charts

SPEC CHECKSUMS:
  Charts: 7af03baa4642bfde9745214daf109efac11977fe

COCOAPODS: 0.39.0

and  pod search charts ,i will get :

-> Charts (2.1.3)
   ios-charts is a powerful & easy to use chart library for iOS
   pod 'Charts', '~> 2.1.3'
   - Homepage: https://github.com/danielgindi/ios-charts
   - Source:   https://github.com/danielgindi/ios-charts.git
   - Versions: 2.1.3, 2.1.2, 2.1.0, 2.0.9 [master repo]

and pod update has no work for this.

**Comment by petester42** [comment]
I dont know how to help you. I have a project configured with 2.1.6 using cocoapods and it works fine.

**Comment by petester42** [comment]
This is what I get. Maybe you could upload your project to get help. Otherwise I have no idea.

<img width="567" alt="screen shot 2015-11-19 at 9 21 37 pm" src="https://cloud.githubusercontent.com/assets/296718/11290290/99eb7202-8f03-11e5-9f67-9536ec964231.png">

**Comment by dogvscat** [comment]
@petester42   pod search Alamofire, and i also just get version 2.0.0, but others can get version 3.0 and their cocoapods version is 0.38.0,so i think there must be something wrong with my cocoapods. Thanks for your help.

**Comment by petester42** [comment]
Ya that might be it. Good luck.

**Comment by dogvscat** [comment]
@petester42  `gem list cocoapods` i get 0.39.2 and 0.38.2, so i just `pod _0.38.2_ setup`to older version, and now `pod search Charts` can get the latest version 2.1.6, and maybe i also need `pod repo update`.
