### ISSUE TITLE
Charts over scrollview not scrolling in iPad only

### ISSUE THREAD

**Issue by rupammitra** [danielgindi/ios-charts#550]
Hi Daniel,

I have a scrollview over which I am having a view of scrollview's width and height and on top of these I am having the view over which the charts are gonna drawn. 

So the problem arouse only with iPad that when I am trying to scroll the charts its not scrolling whereas if I am long pressing the charts view and then dragging it slightly it starts scrolling. 

I have to do it everytime when I want to scroll the charts. Note that this problem only happens with iPad.

Any help is highly appreciated. Thanks.

**Comment by liuxuan30** [comment]
I guess it should be a conflict? Have you checked the delegate and which view catches the touch event?

**Comment by danielgindi** [comment]
It is a bit unclear what the view hierarchy is...
It sounds like a trick that the OS does for deciding which scrollview to scroll - but I haven't really bumped into something like this.

Can you try to explain it again?
