### ISSUE TITLE
Bar Chart view group in Swift

### ISSUE THREAD

**Issue by brytnvmg** [danielgindi/ios-charts#551]
Error : cannot invoke initializer for type with an argument list of type !!!    

   override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0]
        let unitsSold2 = [25.0, 2.0, 4.0, 10.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0]
        setChart(months, values: unitsSold, values2: unitsSold2)
    }

    func setChart(dataPoints: [String], values: [Double], values2: [Double]) {
        barChartView.noDataText = "You need to provide data for the chart."
        var dataEntries1: [BarChartDataEntry] = []
        var dataEntries2: [BarChartDataEntry] = []
        
        for i in 0..<dataPoints.count {
            let dataEntry1 = BarChartDataEntry(value: values[i], xIndex: i)
    
            let dataEntry2 = BarChartDataEntry(value: values2[i], xIndex: i)
            dataEntries1.append(dataEntry1)
            dataEntries2.append(dataEntry2)
        }

        let chartDataSet1 = BarChartDataSet(yVals: dataEntries1, label: "Units Sold")
        let chartDataSet2 = BarChartDataSet(yVals: dataEntries2, label: "Units Sold 2")
        var dataSet : [BarChartDataSet] = [BarChartDataSet]()
        dataSet.append(chartDataSet1)
        dataSet.append(chartDataSet2)

        let chartData = BarChartData(xVals: dataPoints, dataSet: dataSet) ->> 
        ->> Error : cannot invoke initializer for type with an argument list of type !!!
        

        chartData.groupSpace = 1
        barChartView.data = chartData
    }

**Comment by victors1681** [comment]
chage dataSet to dataSets  "Add S"
let chartData = BarChartData(xVals: dataPoints, dataSets: dataSet) ->> 
    ->> Error : cannot invoke initializer for type with an argument list of type !!!

**Comment by zhydanovajulia** [comment]
+1

**Comment by sangle-umesh** [comment]
let chartData = BarChartData()
        chartData.addDataSet(chartDataSet)
        barChartView.data = chartData

**Comment by Sikandarkhan** [comment]
>  let chartData = BarChartData()
>     chartData.addDataSet(chartDataSet)
>     barChartView.data = chartData

this worked for me.
