### ISSUE TITLE
Repetitions of y axis labels

### ISSUE THREAD

**Issue by vigyanhoon** [danielgindi/ios-charts#552]
Can we avoid this repetition when label count is set to six?

![screen shot 2015-11-16 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/8503526/11178130/a351c750-8c70-11e5-8c8b-497272ac5ebd.png)

**Comment by liuxuan30** [comment]
Well You only have one value named 1 and ask the axis to have 6 labels, then it will do 1/6 for each axis label. If you don't use decimal formatter, this is what you will have. #315 is talking about it.

@danielgindi You might want to take a look, people are asking about this more and more
