### ISSUE TITLE
Auto-adjusting graph scale on moving

### ISSUE THREAD

**Issue by gGololicic** [danielgindi/ios-charts#553]
When you set your graph to only show part of data at once with setVisibleXRangeMaximum graph y axis is not scaled for only current data on screen but for all data set. Would there be a possibility y axis could adapt only to current data on screen so it scales to the current data y range not to the whole data y range.

**Comment by AlBirdie** [comment]
autoScaleMinMax is what you are looking for.

e.g.:
[chart setAutoScaleMinMaxEnabled:YES]

**Comment by gGololicic** [comment]
Thank you very much. Awesome.
