### ISSUE TITLE
Problem uploading the archive.

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#556]
I previously integrated charts and uploaded the build successfully for beta testing on Xcode 7. It uploaded successfully.

 But recently I updated the appID and related provisioning profiles and tried to upload the build for beta testing. It gives error. I am using Xcode 7.1.1

![screen shot 2015-11-17 at 4 36 09 pm](https://cloud.githubusercontent.com/assets/3005149/11261596/1e5b2676-8e9c-11e5-95cf-42a714b08d7a.png)

**Comment by danielgindi** [comment]
Try to remove the Charts framework from your project (from the project navigator) and drag it back in - and then add it to the Embedded binaries section too, as stated in the README.

If you are compiling for iOS 7 - then *do not* add as a framework - take a look at the README.
