### ISSUE TITLE
can i add thiss？

### ISSUE THREAD

**Issue by Tomikes** [danielgindi/ios-charts#557]
http://e.hiphotos.baidu.com/zhidao/pic/item/0eb30f2442a7d9336cb79238af4bd11373f00159.jpg

I want to circle line on the graph into a square and a triangle ，for example, the shape of the above picture on the right, how to do it , the great God？

**Comment by Tomikes** [comment]
![2222](https://cloud.githubusercontent.com/assets/11148585/11262082/dda92eec-8eb5-11e5-8390-743ad9ecf9a3.png)

**Comment by liuxuan30** [comment]
The library does not support yet, but you could contribute, search darwCircles, and then you can add more shape following the same pattern.
