### ISSUE TITLE
iOS 7 && Xcode 7.1.1 build not success, 'Charts' Module no found

### ISSUE THREAD

**Issue by TeehomHub** [danielgindi/ios-charts#560]
iOS 7 && Xcode 7.1.1 build not success, 'Charts' Module no found

**Comment by danielgindi** [comment]
You should add the code to your project, not the framework. iOS 7 does not support dynamic frameworks.

**Comment by TeehomHub** [comment]
I already add the code to my project

**Comment by danielgindi** [comment]
So there shouldn't be any reference to "module" Charts, as it is part of
your module, which is your project.

‏בתאריך יום שישי, 20 בנובמבר 2015, TeehomHub <notifications@github.com> כתב:

**Comment by TeehomHub** [comment]
#if defined(__has_feature) && __has_feature(modules)
@import Charts;
@import CoreGraphics;
@import UIKit;
#endif

**Comment by danielgindi** [comment]
In which file do you see that reference?

‏בתאריך יום שישי, 20 בנובמבר 2015, TeehomHub <notifications@github.com> כתב:

**Comment by TeehomHub** [comment]
I found  [MyProjectName]-Swift  have this       
 #if defined(__has_feature) && __has_feature(modules)
@import Charts;
@import CoreGraphics;
@import UIKit;
#endif

**Comment by danielgindi** [comment]
So it's in your files... Try to remove it. You don't need it unless you set
your minimum deployment target to 8.0 and import Charts as a Framework

‏בתאריך יום שישי, 20 בנובמבר 2015, TeehomHub <notifications@github.com> כתב:

**Comment by TeehomHub** [comment]
if i remove the @import Charts ,the BalloonMarker is error,Can't find BalloonMarker

**Comment by TeehomHub** [comment]
the [MyProjectName]-Swift is copy your demo swift file,is right?

**Comment by danielgindi** [comment]
BalloonMarker is a part of the demo, not of the Charts framework. You can
copy it to your project safely :)

‏בתאריך יום שישי, 20 בנובמבר 2015, TeehomHub <notifications@github.com> כתב:

**Comment by TeehomHub** [comment]
if i add the  BalloonMarker, the BalloonMarker error in the swift  file

import Foundation
import UIKit;
import Charts;///error....

**Comment by danielgindi** [comment]
Again, remove the import.

‏בתאריך יום שישי, 20 בנובמבר 2015, TeehomHub <notifications@github.com> כתב:

**Comment by TeehomHub** [comment]
i remove the  import Charts,than the  [MyProjectName]-Swift is error ,
@interface BalloonMarker : ChartMarker  //error ... can't found ChartMarker

**Comment by TeehomHub** [comment]
can you write a sample for iOS 7

**Comment by liuxuan30** [comment]
If you are targeting iOS 7, you should drag the whole Charts files into your project. Don't copy the balloon marker first. Properly set your build settings, like define modules, product name.. etc. If you are not sure, google it. Make sure you are good to compile, and able to create chart views.

Balloon marker is not part of Chart framework, it's just a simple sub class of chartMarker, so if you want to use it, simply copy it into your project, just like what you have done for the Charts files.

**Comment by TeehomHub** [comment]
build iOS 7 && Xcode 7.1.1  is successful,but i did not use chart in the project.

**Comment by TeehomHub** [comment]
could you success build in iOS 7&& Xcode 7.1.1 and can use it successfully?

**Comment by liuxuan30** [comment]
Of cause, I need to support iOS 7. One thing at a step, don't mixup different issues.

**Comment by TeehomHub** [comment]
ok,i have successful build in iOS 7 and can use it successfully

**Comment by juandavidcruzs** [comment]
Can someone tell me how to compile in iOS 7. Which files should I copy. Which folder? What Build Phases or Embedded Libraries should I change? Thanks a  lot!

**Comment by liuxuan30** [comment]
drag all the swift source files into your project. Just treat them as .h + .m combined. But you need to turn on swift settings in build settings. Try google, there is a lot info

**Comment by TeehomHub** [comment]
you can add new swift file in the project，and then would tips you add bridge file，and you comfier.And Then You go to Setting -> Objective-C Generated Interface Header Name ,and set the file as project'sName-Swift.h .And Than Your #Import  project'sName-Swift.h at what you want use the Lib.

**Comment by TeehomHub** [comment]
And your drag all swift into Project,in first.
