### ISSUE TITLE
iOS-Charts not working on Jenkins

### ISSUE THREAD

**Issue by ankitthakur** [danielgindi/ios-charts#564]
While integrating the code on Jenkins. iOS-Charts framework is getting failed. As the bundle-id set in iOS-Charts is not compatible with Provisioning profile certificates. What are the other alternative to integrate iOS-Charts with Jenkins-CI and XCode.

**Comment by petester42** [comment]
Could you clarify your issue? Are you trying to build your app on Jenkins and charts is failing or just charts. Is there any error messages output. I have an idea of what the problem is but I need more details.

**Comment by dogvscat** [comment]
@ankitthakur  you can use Cocoapods to install `Charts`,pods will manage settings for you ,you just need import Charts in your project.

**Comment by danielgindi** [comment]
No response for 24 days...

**Comment by Yoncn** [comment]
iOS-Charts/Objective-C/Formatters/LargeValueFormatter.swift:8:8: error: no such module 'Charts'
import Charts
       ^

** BUILD FAILED **

failed when I use jenkins...

**Comment by petester42** [comment]
This could be a million things. We can’t help you with so little information.

**Comment by Yoncn** [comment]
maybe because of that Jenkins cannot build charts before build my project

**Comment by petester42** [comment]
There is problably something wrong with your project of your Jenkins setup because it builds for us both on ci and locally. If you don’t share any details about your setup and your project we really can’t help you.

**Comment by Yoncn** [comment]
![qq20181012-211550](https://user-images.githubusercontent.com/16697649/46871490-2a81c800-ce64-11e8-859e-9d055b26acfa.png)
I have drag charts to my project like this , then , I have not set any settings about charts in jenkins setup because I don't know how to set, could you please tell me that I should set what on my jenkins except my own project settings ? 
![qq20181012-212132](https://user-images.githubusercontent.com/16697649/46871752-d2979100-ce64-11e8-9a4d-d26942c0ed77.png)

**Comment by petester42** [comment]
There are no setting you need to put. It should just work. From the info that was given it looks right if the target is your app. I know nothing about Jenkins but maybe work Xcode version is wrong or your swift version is wrong.

**Comment by petester42** [comment]
As far as we’re concerned this isn’t an issue with our library since as you said it works on your device. Their must be something wrong with your Jenkins environment. For more Jenkins help you’re probably better going to check out stackoverflow.

**Comment by Yoncn** [comment]
ok, thanks for your hep
