### ISSUE TITLE
Using Charts library for real-time plotting

### ISSUE THREAD

**Issue by rforouzanfar** [danielgindi/ios-charts#565]
Hi Daniel,

Thanks a lot for this great API. 

I'm using Charts to plot ECG data points (versus time) in real-time and I have 100 data points coming from hardware per second. I'm saving the data in database and then plot them. Here is what I'm using to clear the chartview as well ECG voltages and times each time I'm reseting the graph:

[self.chartView clear];
[self.chartView notifyDataSetChanged];
[self.ecgVoltage removeAllObjects];
[self.ecgDate removeAllObjects];

Although I have changed the database from Core Data to Realm, I am still experiencing slow processing. Is there anything else I could do on the plotting end to save some extra processing? I'm drawing every 50 x-index, though I was wondering if there would be any way that I could assign x-index to some of my y-values as it seems to have a high CPU usage?

P.S. I thought of using custom min and max y values, as they should be refreshed due to possible noises

**Comment by liuxuan30** [comment]
Have you checked what functions took lots of time or the CG is slow? I guess you need to use timer to measure it.

**Comment by danielgindi** [comment]
You do not need to read the whole dataset for each frame rendering, and do not need to `clear`.

Just add the new entries (and drop old, unnecessary entries).
Then you could call `notifyDataSetChanged`

Btw - Realm support coming soon cross-platform, courtesy of Realm. :-)

**Comment by liuxuan30** [comment]
god, I just know Realm today and seems awesome. Seems time to rewrite my model? LOL

**Comment by AwaisFayyaz** [comment]
Hi Daniel, 

Thanks for the great library. Can you tell me if this kind of real time plotting is possible using your charts library? 

![demo](https://user-images.githubusercontent.com/11820112/45688626-5498e080-bb6b-11e8-97d0-1a17b6436e06.gif)

**Comment by thierryH91200** [comment]
do you want something like that?


[realtime.mov.zip](https://github.com/danielgindi/Charts/files/2392889/realtime.mov.zip)

**Comment by AwaisFayyaz** [comment]
@thierryH91200 My values can go positive as well as negative, as depicted in the attached gif.

**Comment by thierryH91200** [comment]
this is just  an example 


<img width="1788" alt="capture d ecran 2018-09-18 16 28 15" src="https://user-images.githubusercontent.com/6251463/45694600-e39ffb80-bb5f-11e8-80d7-8ffee3156123.png">

**Comment by kartiksharma007** [comment]
hi just wanted to ask if we in any way you can help as the data which we have is in a single array , so that means no x or y axis.

**Comment by kartiksharma007** [comment]
[data.json.zip](https://github.com/danielgindi/Charts/files/7942237/data.json.zip)
