### ISSUE TITLE
UIPanGesture blocked while zoomed out completely

### ISSUE THREAD

**Issue by Scrambles56** [danielgindi/ios-charts#566]
Hi Daniel, 

First up, I want to thank you for this library, as it has proved most useful with my current works. In my time using this library, I have come across a problem that I wanted to clear up, and find out whether it is intentional, or possible to change.

I have set up a Linechart view, with reasonably default settings. The problem is that I want to add a UIPanGestureRecognizer to the LineChartView, but the action associated to the gesture is not fired when the chart is zoomed all the way out. 

Thanks,
Matt

**Comment by liuxuan30** [comment]
The chart view itself contains two tap gestures and one pinch,  one pan gesture. I guess you need to provide your own handler, rather than adding a new one?

**Comment by danielgindi** [comment]
Well the thing is that when the pan gesture can interfere with scroll views, so we kind of "disable" it when there's nothing to pan.

I think you can still make this work - try to *not* specify the chart as the delegate for your new pan recognizer.
