### ISSUE TITLE
issue with Bar width 

### ISSUE THREAD

**Issue by narri007** [danielgindi/ios-charts#569]
Hi, i am using the bar charts in my project.  i have the data of 3 values to show in bar chart. Now the issue is the bar showing very big for less data. how to reduce the bar width for less data.

**Comment by liuxuan30** [comment]
dynamicly change `barSpace` can be used.

**Comment by shenyufei** [comment]
backSpace who belong to? DataSet? Or what? BarChart sometimes less and sometimes a lot, so there is no MaxWidth like similar? @liuxuan30     If not, can add a? should be very convenient

**Comment by liuxuan30** [comment]
it's in barChartDataSet. the idea is different, as the barSpace indicats between the bars in percentage of the whole width of one value (0.15 == 15% of bar width)
