### ISSUE TITLE
Cannot call getBarBounds from objective-c

### ISSUE THREAD

**Issue by adonaire-sage** [danielgindi/ios-charts#570]
This is not a bug but it is a problem for me because I cannot get the size of the bars in any other way.

The problem at hand is the impossibility of calling this one method because the swift implementation returns nil when no data set is found. Since CGRect in obj-c is not an object and cannot be set to nil, the method is not callable.

There is an easy workaround for this which is returning CGRectNull instead of nil. I am creating a pull request for this.

This behaviour is there since the first implementation of the method which is in this commit: 19165ddacb2bbac9db0a541fd92f86b294147c11

**Comment by liuxuan30** [comment]
well, if you need get the barRect, can you use protocols or add more functions to do so?
