### ISSUE TITLE
RadarChart animation

### ISSUE THREAD

**Issue by vidcina** [danielgindi/ios-charts#574]
Hi
I would like to add an animation on radarChart like data spreading on the spider web.
I used the method

radarChartView.animate(yAxisDuration: 1)

But there is nothing change after I called the method.
Would you please help me figure out what's going on?
I can animate other charts but not radarChart.

Thank you.

**Comment by danielgindi** [comment]
Well, animating the spider web is not supported yet unfortunately. But fortunately should be quite easy to implement ;-)

**Comment by vidcina** [comment]
Thanks for response!! I will find some time dig in this issue. Maybe I can support this feature.

**Comment by xanderbuck** [comment]
Any update on the ability to animate the RadarChartView? If not could you possibly point me in the right direction of how I would implement this? Thanks a bunch!
