### ISSUE TITLE
Question: Gesture Detection

### ISSUE THREAD

**Issue by nickfedoroff** [danielgindi/ios-charts#578]
How are touch events handled? The Android version has a `OnChartGestureListener`, but I don't see an equivalent for the Swift framework.

I want to un-highlight a line chart when dragging has stopped, among other things. Am I missing it?

Thanks

**Comment by liuxuan30** [comment]
iOS has gestures and their handlers.
check out 
```swift
    internal var _tapGestureRecognizer: UITapGestureRecognizer!
    internal var _doubleTapGestureRecognizer: UITapGestureRecognizer!
    #if !os(tvOS)
    internal var _pinchGestureRecognizer: UIPinchGestureRecognizer!
    #endif
    internal var _panGestureRecognizer: UIPanGestureRecognizer!
``` 
and their handlers, such as:
@objc private func panGestureRecognized(recognizer: UIPanGestureRecognizer)
(search other handlers)
