### ISSUE TITLE
How to remove background gridlines from Bar Chart

### ISSUE THREAD

**Issue by SpaceYatri** [danielgindi/ios-charts#579]
I am struggling to remove the background gridlines and X and Y axis  from my Bar Graph/Chart. Can you help me with that.

**Comment by alvesjtiago** [comment]
I believe what you are looking for is:
```
- drawAxisLineEnabled
- drawGridLinesEnabled
```

If you're using Objective-C just set these on the desired axis:
```
yAxis.drawAxisLineEnabled = NO;
yAxis.drawGridLinesEnabled = NO;
```
or if you're using Swift:
```
yAxis.drawAxisLineEnabled = false
yAxis.drawGridLinesEnabled = false
```

Hope it helps.

**Comment by SpaceYatri** [comment]
thanks

**Comment by hernanarber** [comment]
Awesome Thanks

**Comment by KiritVaghela** [comment]
How to change grid line color?

**Comment by Gurinderbatth** [comment]
Thanks

**Comment by Marwan-Mostafa7** [comment]
what about javafx ? plz

**Comment by bijancronin** [comment]
I'm using Swift 4 and I can't get rid of any of the grid lines.

I'm creating a LineChartView and customizing it as so:

`let lineChart: LineChartView = {`
`    let chart = LineChartView()`
`    chart.leftAxis.drawAxisLineEnabled = false`
`    chart.leftAxis.drawGridLinesEnabled = false`
`    chart.leftAxis.gridColor = NSUIColor.clear`
`    chart.xAxis.drawGridLinesEnabled = false`
`    chart.backgroundColor = .white`
`    chart.translatesAutoresizingMaskIntoConstraints = false`
`    return chart`
`}`

The chart the appears looks exactly like the default line chart without any customization.

**Comment by beraylik** [comment]
Here is how I did that

`lineChart.leftAxis.enabled = false`
`lineChart.rightAxis.enabled = false`
`lineChart.xAxis.enabled = false`

**Comment by laazer** [comment]
It seems you can't directly disable grid lines in swift 4. Workaround is just setting the grid color to clear so they won't be visible 

```
lineChart.xAxis.gridColor = .clear
lineChart.leftAxis.gridColor = .clear
lineChart.rightAxis.gridColor = .clear
```
