### ISSUE TITLE
Is there any inertia effect in the library?

### ISSUE THREAD

**Issue by XiaolongJin** [danielgindi/ios-charts#58]
When I drag line chart from left to right, the animation seems so angular, I wonder is there a inertia effect in the chart, just makes the dragging animation more smooth.
Thanks! Waiting for reply.

**Comment by danielgindi** [comment]
Now there is :-)

#3cb2bdf
#859bb14
#146bf0b

**Comment by LumiaSaki** [comment]
I have taken hours for finding this snippet code, thanks for saving my time!
