### ISSUE TITLE
Mixed Font Style for Line Chart of X-Axis

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#581]
I was wondering if the following was possible. Basically on the x-axis I have a set of dates with a string like
05 Sat
I wanted to do two things, one is to wrap the string so that the day number is on 1 line and weekday is on the next.
The next thing I wanted to do is see if I could make the first line a bigger font size then the second line. So basically 05 is larger than Sat

![image](https://cloud.githubusercontent.com/assets/280426/11461196/4c657cb4-96cc-11e5-822d-37818b5b46e8.png)

**Comment by liuxuan30** [comment]
x axis support wrapping already, but I am not 100% sure it can achieve your goals, just give a try first. 

using two font seems not supported yet. Since this is a little customization-oriented. You could override some methods and add new font size property to do so.
