### ISSUE TITLE
Getting question (?) mark while importing the library. How to get it resolved

### ISSUE THREAD

**Issue by SpaceYatri** [danielgindi/ios-charts#583]
I am getting a question mark while importing it in my project while its not coming when I am importing it in the same manner in the iosChartsDemo project. I am able to use all the functionality and compile successfully but can you help me understand the issue here and how to resolve it. 
![screen shot 2015-11-30 at 2 02 12 pm](https://cloud.githubusercontent.com/assets/16056119/11467108/03c79d34-976c-11e5-9914-e8bbcfe41307.png)

**Comment by petester42** [comment]
That just means those files have not been added to version control yet.
