### ISSUE TITLE
Is there a way to add arrows to highlight line?

### ISSUE THREAD

**Issue by JeremyVolkons** [danielgindi/ios-charts#584]
Hi, is it possible to add arrows indicating that highlight line can be moved? 

Like here:
![img_6418](https://cloud.githubusercontent.com/assets/16090930/11488067/fc16ed3a-97c3-11e5-9a70-23d13f0beb06.PNG)

**Comment by liuxuan30** [comment]
Of course you can. But you need to write your own code in drawHighlighted, or chart marker, or many other ways.
