### ISSUE TITLE
how to combine  chart  as follows

### ISSUE THREAD

**Issue by hengchengfei** [danielgindi/ios-charts#587]
**Top:  CombinedChartDrawOrder.Candle + CombinedChartDrawOrder.Line**
**Bottom:  BarChartData**

Their leftAxis and xAxis are different.
How to combine them in a chartView?

![6 pic](https://cloud.githubusercontent.com/assets/3182964/11554452/1070cd76-99d3-11e5-842a-6a1d24cdfe91.jpg)

**Comment by GMJD** [comment]
waiting

**Comment by liuxuan30** [comment]
It's your business logic to put two charts together and make sure they share the same x values and widths.
I would say you could use two chart views rather than only one.
