### ISSUE TITLE
Finger drawing (draw values into the chart with touch-gesture) implemented?

### ISSUE THREAD

**Issue by minuscorp** [danielgindi/ios-charts#589]
In the feature list of the library is present:
* Finger drawing (draw values into the chart with touch-gesture)

But I cannot find any clue of this feature in the library code or even in the example application so my question is if there's a way nowadays to accomplish this with the library.

Kind regards.

**Comment by liuxuan30** [comment]
I guess it does not support finger drawing? Where do you see it?

**Comment by minuscorp** [comment]
In the Readme of the project, under the Features section.

**Comment by petester42** [comment]
Hmm. You are indeed correct. I don't know if this is in this library yet. @danielgindi?

**Comment by petester42** [comment]
What would be your use case for this just for my curiosity?

**Comment by minuscorp** [comment]
I need the user to configure some power/speed mappings inside an electrical motor and the way to do it letting the user drawing that mapping would be really nice.

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by danielgindi** [comment]
Well this feature list is copied over from the Android counterpart, and I
guess that this relates to the old Android demo that listened to touch
events and added points in the touch points. So you can say that the
library supports with just 2-3 lines of code ;)

I never got the time to rewrite all the demos to reflect the whole set

‏בתאריך יום שישי, 4 בדצמבר 2015, Jorge <notifications@github.com> כתב:

> I need the user to configure some power/speed mappings inside an
> electrical motor and the way to do it letting the user drawing that mapping
> would be really nice.
>
> Jorge Revuelta Herrero
> Software Engineer
> BISITE Research Group
>
> > El 4 dic 2015, a las 15:13, Pierre-Marc Airoldi <
> notifications@github.com

**Comment by minuscorp** [comment]
So it's possible to do it with the library right now or not. I couldn't fine a way to do so...

If possible could you provide an example, or some clues, to allow me to implement this on my app?

Kind regards.

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by danielgindi** [comment]
Well I remember that there's a demo on the Android version so you could
just take a snippet from there and adjust the syntax for Swift.

Basically the work to be done is add the gesture recognizer, for each point
convert to chart coordinates, add an entry.

‏בתאריך יום שבת, 5 בדצמבר 2015, Jorge <notifications@github.com> כתב:

> So it's possible to do it with the library right now or not. I couldn't
> fine a way to do so...
>
> If possible could you provide an example, or some clues, to allow me to
> implement this on my app?
>
> Kind regards.
>
> Jorge Revuelta Herrero
> Software Engineer
> BISITE Research Group
>
> > El 5 dic 2015, a las 16:21, Daniel Cohen Gindi <notifications@github.com
