### ISSUE TITLE
Selective fill colors on LineChartView

### ISSUE THREAD

**Issue by borut-t** [danielgindi/ios-charts#591]
I cannot found a solution for selective value (area bellow chart, not line) fill on line chart view.

![Selective fill](http://shrani.si/f/1v/7g/1Wmu83l8/linechartselectivefill.png)

Is there anything like that implemented yet?

**Comment by liuxuan30** [comment]
Yes it is possible, as long as you get each closed path and fill it, but it seems not that easy. You have to do it on your own.

**Comment by borut-t** [comment]
@liuxuan30 Can you point me in the right direction where could I find this paths?

**Comment by liuxuan30** [comment]
Oh man, I'm afraid I cannot. It's quite complicated to figure out the right direction for filling different paths, especially thinking about negative + positive values
