### ISSUE TITLE
 Cannot load underlying module for 'XCTest' when i am using charts in xcode7.1

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#595]

**Comment by petester42** [comment]
See #599

**Comment by clinton-housingman** [comment]
This maybe a little late but what you have to do is:

Click on File > New > Target > iOS Unit Testing Bundle.

And then add your tests in there. This worked for me. The problem was that I didn't select create unit tests when I created my project. Hope this helps someone.
