### ISSUE TITLE
Charts pulled from cocoapods is still of version 2.1.3 and it has compile errors against Swift 2.0

### ISSUE THREAD

**Issue by xpacificsoda** [danielgindi/ios-charts#598]
As subjected. Please update the project in CocoaPods and make it compatible with Swift 2.0. Thanks.

**Comment by petester42** [comment]
It is at 2.1.6 on cocoapods and swift 2 compatible. There is a problem with your setup. Wrong version of cocoapods/Xcode?

**Comment by liuxuan30** [comment]
I believe @petester42 has the right answer
