### ISSUE TITLE
Myproject-swift.h  has not founded in my project why??

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#599]
I followed the  https://github.com/danielgindi/ios-charts/iss   but i got the following error
in swift file

<img width="962" alt="screen shot 2015-12-08 at 6 49 55 pm" src="https://cloud.githubusercontent.com/assets/14346725/11656614/6b960c86-9ddc-11e5-9504-f8e6916eb8f8.png">

After i delete this " import foundation" from swift file then it work fine.

then i drag the charts folder into my project then build the project

<img width="771" alt="screen shot 2015-12-08 at 6 53 01 pm" src="https://cloud.githubusercontent.com/assets/14346725/11656686/d5873886-9ddc-11e5-8135-101a3daa228c.png">
  i got the following error

Please help  me how to integrate MP-Charts into my project

**Comment by petester42** [comment]
Don't import the tests in you application. Only the classes folder

**Comment by petester42** [comment]
We should maybe consider remving iOS 7 support from the readme due to the many issues. If someone really knows what they are doing then they can easily get it to work but we would reduce this kind of issue.

**Comment by liuxuan30** [comment]
@petester42 I feel it should be there? People are learning or switching to swift because of this project :) and they maybe don't know the trick for iOS 7 & 8
