### ISSUE TITLE
xcode complains ChartsDemo-Swift.h can't be found

### ISSUE THREAD

**Issue by gnijuohz** [danielgindi/ios-charts#6]
When I try to build `ChartsDemo`, Xcode complains about `ChartsDemo-Swift.h` not being found in a few `.m` files whicj have `#import "ChartsDemo-Swift.h"` in them. 

I can't find the file anywhere in the project as well.

**Comment by danielgindi** [comment]
It's generated automatically by Xcode for bridging Swift to ObjC.
You should make sure that you are using a compatible version of Xcode, that
successfully compiles the Charts module, so that the header will be
available.

**Comment by gnijuohz** [comment]
Yeah that worked. I didn't compile the Charts module first. Thanks :)
