### ISSUE TITLE
dyld_fatal_error

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#60]
Xcode 6.3 and iOS 8.3 Deployment. 
Any help?

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/37604CDA-D682-424D-A215-8FC42D486884/PatientApp.app/Frameworks/Charts.framework/Charts
  Reason: image not found
(lldb)

![screen shot 2015-04-30 at 1 43 59 pm](https://cloud.githubusercontent.com/assets/12183139/7409357/35b61dfa-ef3f-11e4-800a-ca640fea1e0a.png)
![screen shot 2015-04-30 at 1 44 19 pm](https://cloud.githubusercontent.com/assets/12183139/7409358/35bd2834-ef3f-11e4-9e3c-8da3c4d29cdf.png)

**Comment by danielgindi** [comment]
Maybe try another one in the list when choosing the embedded library. Sometimes there are two options - one for it being under your project, one as itself... I don't know why. But maybe there lies solution to your problem.

And you might want to Clean & Build after re-adding the framework.

Please let us know if it solved your problem.

**Comment by BurhanMughal** [comment]
Thank you Danielgindi for your response, I tried your suggested solution but it didn't work. Still app is crashing. Waiting for quick reply.

**Comment by BurhanMughal** [comment]
Finally resolved my problem.

Here are the Steps:
1: Build Setting
2: Build Options
3:Under Build Options Mark Embedded Content Contains Swift Code YES.

4: Clean the Build and RUN.

Thanks.

**Comment by danielgindi** [comment]
Thank you - I'll add to the README!

**Comment by BurhanMughal** [comment]
You are most Welcome :)

**Comment by BurhanMughal** [comment]
Hey Denial I have another question, If you have some time ?

**Comment by BurhanMughal** [comment]
Can we change the TEXT position of PIE Chart, Currently I can only draw text in the slice, I want to draw text outside the slice. Is there any way to do it ?

**Comment by zakkhoyt** [comment]
@BurhanMughal, thanks for listing the fix. It saved lots of mad time.

**Comment by BurhanMughal** [comment]
You are most welcome @zakkhoyt

**Comment by iOSArchitect** [comment]
I am having weird issue in my Xcode when I turned the Embedded Content contains swift code to Yes and then tried running in the device got this error, please see the error in the snapshot.
And when set to NO that same old error dyld: Library not loaded: @rpath/libswiftCore.dylib

Your urgent help will be appreciated.


<img width="661" alt="screen shot 2015-12-22 at 12 11 00 pm" src="https://cloud.githubusercontent.com/assets/14069953/11951883/b828e0ea-a8a5-11e5-9644-b591e02f82c1.png">

**Comment by liuxuan30** [comment]
@iOSArchitect Do not post same issue in two different closed issues. We had answer it in the other one.

**Comment by JhonnyTawk** [comment]
I am having the same issue on Xcode(9.3) the only solution thats worked for me is to use Xcode(9.2)
that's the error I am getting :
**dyld: Library not loaded: .dylib
Referenced from: /Users/ziadtawk/Library/Developer/CoreSimulator/Devices/B0ECFE80-1882-4A5B-ADE8-D547298E92D1/data/Containers/Bundle/Application/8464DBFD-8ADC-4B93-BD5E-2872645BEAFF/Slybroadcast.app/Frameworks/Charts.framework/Charts
Reason: image not found**
