### ISSUE TITLE
Pie Chart only one Legend data is visible

### ISSUE THREAD

**Issue by TheEngineerz** [danielgindi/ios-charts#602]
![screen shot 2015-12-10 at 11 51 16 am](https://cloud.githubusercontent.com/assets/5149947/11708903/bba1e8c2-9f34-11e5-9c82-e2e0ab8f7b0b.png)

What i am doing wrong here is my code

    func createPieChart1(myview:UIView,y:Float){
        let  pieChart:PieChartView = PieChartView(frame: CGRectMake(0, CGFloat(y), (self.view.frame.width/1.5), (self.view.frame.width/1.5)))
        pieChart.center=CGPointMake(UIScreen.mainScreen().bounds.width/2, UIScreen.mainScreen().bounds.height/5)
        pieChart.descriptionText = ""
        pieChart.usePercentValuesEnabled = true
        pieChart.drawHoleEnabled=true
        pieChart.holeTransparent = true
        pieChart.rotationAngle = 0.0
        pieChart.rotationEnabled = true
        pieChart.legend.enabled = true
        pieChart.animate(xAxisDuration: 1.5, yAxisDuration: 1.5, easingOption: ChartEasingOption.EaseOutBack)
        myview.addSubview(pieChart)
        let  pcDatapoints = ["Present","Onleave","Absent"]
        let legend:ChartLegend = pieChart.legend
        legend.xEntrySpace = 7.0;
        legend.yEntrySpace = 0.0
        legend.yOffset = 0.0;
        legend.position = ChartLegend.ChartLegendPosition.AboveChartRight
        setPieChartData(pcDatapoints , values: pcData,pieChart:pieChart)
        
        
    }

**Comment by liuxuan30** [comment]
take a look at https://github.com/danielgindi/ios-charts/issues/518, seems the same.
Highlight: If I change the setCharts function to set the data after changing the colors it works fine. Best practice would be to create all your datasets first and only set the data after all the data is created.
