### ISSUE TITLE
Min and max number of horizontal lines

### ISSUE THREAD

**Issue by NicolasLourenco** [danielgindi/ios-charts#603]
Hello,
I don't know if exist. But if exist sorry for the issue, I don't have a good knowledge of the library at the moment.

If it doesn't exist, I think it will be fine to add this feature.

For example:
- I don't want more than 4 horizontal lines
- I don't want less than 2 horizontal lines

Thanks for reading.
Nicolas

**Comment by NicolasLourenco** [comment]
So, after a lot of research I find the solution:

```
[self.lineChartView.leftAxis setLabelCount:4];
    [self.lineChartView.leftYAxisRenderer computeAxisValuesWithMin:0 max:2000];
```

**Comment by liuxuan30** [comment]
You don't have to be this way. There already exists `cusomAxisMin/Max` property in `ChartYAxis`.
