### ISSUE TITLE
when BarChartView has no chart data availble, drag will lead crash.

### ISSUE THREAD

**Issue by liuhuan1991** [danielgindi/ios-charts#607]
the crash is at ChartHighlighter.swift file, crash message is **"EXC_BAD_INSTRUCTION(code=EXC_I386_INVOP,subcode=0x0)"** .
and the crash breakpoint at the method:

```
internal func getXIndex(x: Double) -> Int
    {
        // create an array of the touch-point
        var pt = CGPoint(x: x, y: 0.0)
        
        // take any transformer to determine the x-axis value
        _chart?.getTransformer(ChartYAxis.AxisDependency.Left).pixelToValue(&pt)
        
        return Int(round(pt.x))
    }
```

And I set ```_chartView.highlightPerTapEnabled = NO;
    _chartView.highlightPerDragEnabled = NO;```, the bug will fixed.

**Comment by liuxuan30** [comment]
If your bar chart has no data, it should display 'No chart data available. You need to provide data for the chart'. And it won't zoom or scroll, as exptected.
what's your data looks like? I tried with ChatsDemo, not seeting chart.data, it will not crash. Could you provide a data code snippet with ChartsDemo so we can reproduce it?

If your data is empty, but you actually did trigger getXIndex(), and the matrix will be a mess, so pixelToValue will calculates NaN and leads to crash. By default, it will not goes to getXIndex() or drawRect. So I will make a guess, you modified the code, right?

**Comment by liuhuan1991** [comment]
Modify and replace the method of BarChartViewController.m:
```
- (void)setDataCount:(int)count range:(double)range
{
    BarChartData *charData = [[BarChartData alloc] initWithXVals:@[] dataSets:@[]];
    _chartView.data = charData;
}
```
then, drag with BarChartView, it will be crash.

And if we set the *highlightPerTapEnabled* and *highlightPerDragEnabled* of  chartView as NO, the bug will fixed.

**Comment by liuxuan30** [comment]
Ah I see. Seems duplicated to #577
There is a PR #582 pending. You can use the code there to prevent the crash.
