### ISSUE TITLE
Y - Axis Values stick together

### ISSUE THREAD

**Issue by shakked** [danielgindi/ios-charts#608]
I saw someone else had this same problem but I'm unable to solve it:

![image](https://cloud.githubusercontent.com/assets/5383089/11768444/2b329e8a-a19b-11e5-978f-f4f93d50bdc6.png)
```
             cell.lineChartView.data = chartModel.loadData(datapoints, calendarUnit: calendarUnit) as! LineChartData
                if let lastValue =  chartModel.yVals.last?.value {
                    cell.topRightLabel.text = "\(lastValue)"
                } else {
                    cell.topRightLabel.text = "0"
                }

                cell.lineChartView.delegate = self
                cell.lineChartView.notifyDataSetChanged()
```

```
        gridBackgroundColor = UIColor.whiteColor()
        descriptionText = ""
        legend.enabled = false
        dragEnabled = false
        doubleTapToZoomEnabled = false
        pinchZoomEnabled = false
        autoScaleMinMaxEnabled = true
        rightAxis.enabled = false
        leftAxis.startAtZeroEnabled = false
        drawBordersEnabled = true
        borderColor = UIColor.lightGrayColor()
        xAxis.drawGridLinesEnabled = false
        xAxis.gridColor = UIColor.lightGrayColor()
        xAxis.labelPosition = .Bottom
```

**Comment by liuxuan30** [comment]
Can you try reproduce with ChartsDemo code so we can use it?
To me, the y axis label and grid lines are weird, but I cannot reproduce it.

**Comment by shakked** [comment]
The problem gets fixed when I highlight a value on the chart. I've tried calling all sorts of `setNeedsDisplay()` `notifyDataChanged` etc but still doesn't fix the issue

**Comment by liuxuan30** [comment]
if this is a bug, please use ChartsDemo and try to reproduce it, so we can try it on our side to lock down the issue.

**Comment by danielgindi** [comment]
It is probably some weird issue with left and right axis conflicting in some manner.
Please give a code sample so that we can reproduce it - and hopefully fix it :-)

**Comment by danielgindi** [comment]
Any news on this?

**Comment by shakked** [comment]
Sorry I haven't gotten a chance to reproduce it in the demo, I am still having the same issue. If it is something with conflicting axises, what do you suggest? I have the right axis hidden.

**Comment by danielgindi** [comment]
Code sample?... We need to know when this happens

**Comment by danielgindi** [comment]
If right axis is disabled then it is not a conflict. You may have changed the data without calling `notifyDataSetChanged()` so the axis was not calculated properly.
