### ISSUE TITLE
X axis names visibility (Rotation)

### ISSUE THREAD

**Issue by fiftycy** [danielgindi/ios-charts#61]
Hello there,

Am plotting 6 dates on x axis with format "dd/MM/yy" but the font size of each label doesn't auto shrink and it looks bad. Can i show these values rotated by 45 degrees or is anything similar to text autoshrink. 

If not these 2 features will be good for enhancements

Thanks,
Adam

**Comment by turkenh** [comment]
+1 from my side.
I was about to open an issue like this. 
X axis label visibility is problematic and a rotation possibility would be perfect.

**Comment by danielgindi** [comment]
We are already looking into this...

**Comment by BurhanMughal** [comment]
Any news regarding above mentioned issue/enhancement ?

**Comment by neverfollowr** [comment]
This would be helpful for long labels. Having the x-axis titles position on bottom/top doesnt work in this case. Having the labels at an angel in relation to the bar would be super help.
