### ISSUE TITLE
I put the deployment of XCODE target to 8.0 is an error, but change to 8.3 won't go wrong, what's the matter?

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/ios-charts#612]
![Uploading 屏幕快照 2015-12-15 下午4.55.55.png…]()
I put the deployment target of XCODE  to 8.0 is an error, but change to 8.2 won't go wrong, what's the matter?    Don't support under 8.2

**Comment by liuxuan30** [comment]
your screenshot is broken.

**Comment by shanyulaile** [comment]
![2015-12-15 4 55 55](https://cloud.githubusercontent.com/assets/11886729/11830617/db23edba-a3e1-11e5-8128-f60c84c2a85d.png)

**Comment by liuxuan30** [comment]
I am not sure, I checked the project setting, its targeting 8.0, not 8.2
Where do you get the library? pod, Carthage, or you compiled your own?

**Comment by shanyulaile** [comment]
I get the library from this web site by “download  zip”

**Comment by liuxuan30** [comment]
well.. You could download the source code and compile it on your own to try.

**Comment by shanyulaile** [comment]
Run the demo is also appear such problem. I want to ask is not another way to support the low version of the iOS? Specific how to implement, hope you can detailed say, thank you.

**Comment by liuxuan30** [comment]
@shanyulaile I ran the demo and no problem found on my side. You need to provide the exact steps to reproduce. I am running it on iOS 7. You should read REAME first and search.

**Comment by petester42** [comment]
Are you using the correct version of Xcode? You need to use at least Xcode 7 to compile this library.

**Comment by shanyulaile** [comment]
![2015-12-17 2 02 39](https://cloud.githubusercontent.com/assets/11886729/11862518/df1746e8-a4c6-11e5-9c78-7513e1acb654.png)
This is my version of Xcode

**Comment by liuxuan30** [comment]
should be no prolem. Still, you have to give more details..
Did you just open an untouched ChartsDemo project and broke immediatelly once you tried to run it? 
We can compile and run the demo perfectly with Xcode 7.0.

**Comment by danielgindi** [comment]
No response for 17 days? He probably figured out his problem already...
