### ISSUE TITLE
touchesEnded event in BarChartView not called

### ISSUE THREAD

**Issue by niklas22** [danielgindi/ios-charts#613]
Hello everyone!

I'm currently developing an iOS App which is using the Charts-framework.
I want to know when the user stops zooming or touching the chart.
But when i call the touchesBegin/Moved/Ended events, the touchesEnded event is not called.

I hope someone can help me with this issue! :-)

Kind regards

Niklas

**Comment by liuxuan30** [comment]
how do you setup your gesture and call touchesBegin/Moved/Ended events? 

The library already had some gestures in BarLineChartViewBase and its handlers like:
`@objc private func pinchGestureRecognized(recognizer: UIPinchGestureRecognizer)`
You can provide your own implementation, or add delegate method and call it when the gesture state is ended.

**Comment by farfromrefug** [comment]
@liuxuan30 i would like to re open that issue cause i can see this clearly happening. 
When using a ChartView i can see my views ```touchesEnded``` not being called.
I can see ```touchesBegan``` but no ```touchesEnded```.
I soon as touch another view it works.

It feels like you are canceling/preventing the touch from being propragated

**Comment by liuxuan30** [comment]
Have you checked the origin implementation? Are you providing yours or using the library's?

**Comment by farfromrefug** [comment]
what do you mean by origin implementation?
I do set breakpoint in touchesBegan from Charts and i do break there. 
Now that i think about it i think i know what's going on. You must have a longpress gesture that cancels touch end events.
I think about this because i do get the touch end events when i long press on the Charts view. Will run some tests

**Comment by liuxuan30** [comment]
What I mean is gesture handlers are private funcs, so if you use yours, it should be calling yours only..
The library seems not having a long press gesture. You can take a look at `BarLineChartViewBase`, it holds all the gesture handlers.

**Comment by farfromrefug** [comment]
@dtroupe18 can you make a PR?

**Comment by dtroupe18** [comment]
@farfromrefug I did. https://github.com/danielgindi/Charts/pull/3599 There is also this PR https://github.com/danielgindi/Charts/pull/3612
