### ISSUE TITLE
How to make the chart and the other chart with the same action

### ISSUE THREAD

**Issue by z404558** [danielgindi/ios-charts#615]
I have a CandleStickChart and a BarChart below it. When I make CandleStickChart zoom in or out or translate, I want BarChart do the same action.
Do you have a solution about this?

**Comment by liuxuan30** [comment]
you have to do it using delegate, and make sure they share the same x values otherwise the scrolling offset is different. There is one person asked this, you could search. Sorry I don't have time to do so.
