### ISSUE TITLE
Legend colors not correct

### ISSUE THREAD

**Issue by AndreasHeiberg** [danielgindi/ios-charts#617]
This is obviously a problem with my setup. Using the same code in the iOSChartsDemo project works as you would expect. But in my project it results in the bars being red and the legend being turquoise.

![Image of resulting chart](http://i.imgur.com/RJ0DUZj.png)

Really sorry waisting peoples time with this issue, but I don't see an obvious fix.

```
        heightChart.noDataText = "You need to provide data for the chart."
        heightChart.descriptionText = ""
        
        var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: values[i], xIndex: i)
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(yVals: dataEntries, label: "Units Sold")
        let chartData = BarChartData(xVals: months, dataSet: chartDataSet)
        heightChart.data = chartData
        
        chartDataSet.colors = [UIColor(red: 230/255, green: 0/255, blue: 0/255, alpha: 1)]
        
        heightChart.xAxis.labelPosition = .Bottom
        
        heightChart.backgroundColor = UIColor.clearColor()
        
        heightChart.animate(xAxisDuration: 2.0, yAxisDuration: 2.0, easingOption: .EaseInBounce)
```

**Comment by AndreasHeiberg** [comment]
My temporary fix is

```heightChart.legend.setCustom(colors: [UIColor(red: 230/255, green: 0/255, blue: 0/255, alpha: 1)], labels: ["Units Sold"])```

**Comment by liuxuan30** [comment]
Please use ChartsDemo and reproduce it, so we can know what happens. But you said it's fine, it's about your setup. You may want to look at ChartsDemo code and the source code.
