### ISSUE TITLE
yAxis label shows only when i touch the view

### ISSUE THREAD

**Issue by zhmiblog** [danielgindi/ios-charts#618]
I used the lineChartView to draw a line chart, But I run out an issue: My yAxis label doesn't show anyway with codes below, only when I touch it to highlight something, the label shows. how can I show it instantly at the beginning?

        lineChartView.descriptionText = ""
        lineChartView.gridBackgroundColor = UIColor.whiteColor()
        lineChartView.legend.enabled = true
        lineChartView.dragEnabled = false
        lineChartView.doubleTapToZoomEnabled = false
        lineChartView.pinchZoomEnabled = true
        lineChartView.autoScaleMinMaxEnabled = true
        
        lineChartView.rightAxis.enabled = false
        lineChartView.leftAxis.startAtZeroEnabled = false
        lineChartView.leftAxis.gridLineWidth = 0.1
        lineChartView.leftAxis.drawAxisLineEnabled = false
        lineChartView.leftAxis.drawLabelsEnabled = true
        lineChartView.xAxis.labelPosition = .Bottom
        lineChartView.xAxis.drawAxisLineEnabled = false

**Comment by zhmiblog** [comment]
Who can help me to solve this problem？Many Thanks......

**Comment by liuxuan30** [comment]
Can you reproduce it with ChartsDemo code?
It will show up by default because drawLabelsEnabled is true if you don't change it.

I do see you call lineChartView.leftAxis.drawLabelsEnabled = true, so what I can guess is, are you using leftAxis or rightAxis? By default it's left. Also, dataSet has a propety called axisDependency, have you changed it?

**Comment by zhmiblog** [comment]
@liuxuan30 , I tried ChartsDemo with replacing the chart-setting code，And the label didn't show either. In my code,I put all chart-setting work in a func, maybe you can run it in xcode simply if you kindly help to solve.For your question, I use leftAxis, and I didn't change dataSet's attribute axisDependency. 
code as below:

        func setChart(var dataPoints: [String],lineChartView: LineChartView, values: [Double],Date: String) {
            lineChartView.noDataText = "You need to provide data for the chart."
            var dataEntries: [ChartDataEntry] = [] 
            for i in 1..<dataPoints.count {
                let dataEntry = ChartDataEntry(value: values[i], xIndex: i)
                dataEntries.append(dataEntry)
            }
            dataPoints.removeFirst()
            let chartDataSet = LineChartDataSet(yVals: dataEntries, label: Date)
            let chartData = LineChartData(xVals: dataPoints, dataSet: chartDataSet)
            lineChartView.data = chartData

            chartDataSet.drawCircleHoleEnabled = true
            chartDataSet.drawValuesEnabled = false
            chartDataSet.drawFilledEnabled = false
            chartDataSet.drawCirclesEnabled = false
            chartDataSet.lineWidth = 1.0
            //        chartDataSet.colors = [UIColor.init(red: 74/255, green: 134/255, blue: 232/255, alpha: 1)]
            
            lineChartView.descriptionText = ""
            lineChartView.gridBackgroundColor = UIColor.whiteColor()
            lineChartView.legend.enabled = true
            lineChartView.dragEnabled = false
            lineChartView.doubleTapToZoomEnabled = false
            lineChartView.pinchZoomEnabled = true
            lineChartView.autoScaleMinMaxEnabled = true
            
            lineChartView.rightAxis.enabled = false
            lineChartView.leftAxis.gridLineWidth = 0.1
            lineChartView.leftAxis.startAtZeroEnabled = false
            lineChartView.leftAxis.drawAxisLineEnabled = false
            lineChartView.leftAxis.drawLabelsEnabled = true
            lineChartView.leftAxis.customAxisMax = Sigma.max(values)!
            lineChartView.leftAxis.customAxisMin = Sigma.min(values)!
            lineChartView.xAxis.labelPosition = .Bottom
            lineChartView.xAxis.drawGridLinesEnabled = false
            lineChartView.xAxis.drawAxisLineEnabled = false
            
            let ll = ChartLimitLine(limit: values[0], label: "zero line")
            ll.lineColor = UIColor.greenColor()
            ll.lineWidth = 1.0
            ll.labelPosition = .RightTop
            ll.valueFont = UIFont.boldSystemFontOfSize(10)
            lineChartView.leftAxis.addLimitLine(ll)
            
            
        }

**Comment by liuxuan30** [comment]
Would you please post the code you tried in ChartDemo that can reproduce? I don't have a swift one in my hand.

BTW, from you code, I suspect it's because you called lineChartView.data = chartData and then you start setting the chart. I would suggest put lineChartView.data = chartData into the last line.
Remember calling lineChartView.data = chartData at last, because the chart setting will impact the space calculating.

**Comment by zhmiblog** [comment]
@liuxuan30 as your advice，I put  lineChartView.data = chartData  on the tail，It worked. TTTTTThank   U, master!
BTW, Sigma.max(values)!  is  fetching the max value of an array with another library about math, Couse there is lots of math works in my project.

**Comment by liuxuan30** [comment]
NP :)
