### ISSUE TITLE
[Enhancement] avoidFirstLastClipping should keep the labels centered

### ISSUE THREAD

**Issue by danielbmarques** [danielgindi/ios-charts#619]
I think the `avoidFirstLastClipping` option should keep the labels centered, like this:
![simulator screen shot 20 de dez de 2015 19 36 05](https://cloud.githubusercontent.com/assets/15813674/11920294/faec6136-a751-11e5-88e2-96d2781e8163.png)

Instead of this:
![simulator screen shot 20 de dez de 2015 19 37 13](https://cloud.githubusercontent.com/assets/15813674/11920295/fee1d6ea-a751-11e5-961d-c9a1db43269e.png)

I can't see why anyone would prefer the last option, which is what happens right now.
This is what I'm doing to achieve what I want:
```swift
chartView.xAxis.avoidFirstLastClippingEnabled = false
let left = 10 + 3 * CGFloat(chartDataPoints.first!.characters.count)
let right = 10 + 3 * CGFloat(chartDataPoints.last!.characters.count)
chartView.setExtraOffsets(left: left, top: chartView.extraTopOffset, right: right, bottom: chartView.extraBottomOffset)
```

So my offsets are increased by three times the number of characters in the respective label.
This is working fine, but since there already is an `avoidFirstLastClipping` method, I think it should do all that for me. (Maybe by considering the width of the labels and increasing the offset by half of it?)

**Comment by danielgindi** [comment]
Seems to me like you are choosing a very specific value for your offsets.
And `avoidFirstLastClipping` is doing something very specific, which is *avoid being clipped*, by sliding the values even while scrolling the chart, which provides for smoother experience.

Not everyone wants the labels to bleed out of the content bounds, which can cause two labels being rendered on top of each other.

So, you have those `extraOffsets` for those kind of situations where you want to do something a little different :-)
