### ISSUE TITLE
Line chart crashes with a big float

### ISSUE THREAD

**Issue by turkenh** [danielgindi/ios-charts#62]
I am drawing line chart with one yVal = 657711616 and xVal="SomeText"
But app crashes at following line:

![screen shot 2015-05-02 at 3 59 26 am](https://cloud.githubusercontent.com/assets/9900707/7439400/165d4d36-f082-11e4-8fe6-c96a9677ede9.png)

Previously, just before I updated to recent commits, app was crashing  for same chart but with an error: 

Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathMoveToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 254.

**Comment by danielgindi** [comment]
It crashes because x/y are `NaN`, and `NaN` can't be cast to `Int`.
The question is - why is viewPortHandler full of `NaN`s?

Did you initialize with a null frame or something?

**Comment by danielgindi** [comment]
@PhilJay do you think we should move everything to work with `double`s? Seems like people have already exhausted all numeric possibilities with `float` ;-)

**Comment by PhilJay** [comment]
Yes I think we could.
It's gonna be significant effort, but doable :-)

**Comment by danielgindi** [comment]
It's just "ant work" as we say in Hebrew, just changing a lot of floats to
double, and of course float literals like 0.f to 0.0... Yeah a lot of work!

**Comment by turkenh** [comment]
Yes, I aggree that double would be better:)
But unfortunately I need a quick fix right now:(
So, I prepared a minimal working example with exactly same data. It draws the chart with a small float, i.e. 100 but crashes with the one that I mentioned above. 
Could you please check it and advise my about what am I doing wrong? or a workaround if this is really a bug?

https://github.com/turkenh/ios-chart-crash

Thanks...

**Comment by danielgindi** [comment]
For the next version we will be ready with Doubles instead of Floats, so that will be relatively soon...

**Comment by danielgindi** [comment]
@PhilJay are you going to move MPAndroidCharts to Double? Do you want my help?

**Comment by PhilJay** [comment]
Yes I am definitely planning on doing so, I just don't have the time right now. If you want to start this just let me know so that we don't start simultaneously :-)
