### ISSUE TITLE
Show % Percentage value with Legend data 

### ISSUE THREAD

**Issue by TheEngineerz** [danielgindi/ios-charts#621]
I want to show value like this 

![screen shot 2015-12-21 at 1 18 35 pm](https://cloud.githubusercontent.com/assets/5149947/11926322/a2ffca96-a7e5-11e5-9374-e8324a0b912c.png)

currently by default i have this kind of screen

![screen shot 2015-12-21 at 1 20 48 pm](https://cloud.githubusercontent.com/assets/5149947/11926344/c386d138-a7e5-11e5-853e-bca16cb3a560.png)

my code is like this

   let  pieChart:PieChartView = PieChartView(frame: CGRectMake(0, CGFloat(y), (self.view.frame.width/1.3), (self.view.frame.width/1.3)))
        pieChart.center=CGPointMake(UIScreen.mainScreen().bounds.width/2, UIScreen.mainScreen().bounds.height - (self.view.frame.width/1.6))
        pieChart.descriptionText = ".="
        pieChart.usePercentValuesEnabled = false
        pieChart.drawHoleEnabled=true
        pieChart.holeTransparent = true
        pieChart.rotationAngle = 0.0
        pieChart.rotationEnabled = true
        pieChart.legend.enabled = true
        pieChart.animate(xAxisDuration: 1.5, yAxisDuration: 1.5, easingOption: ChartEasingOption.EaseOutBack)
        myview.addSubview(pieChart)
        let  pcDatapoints = [pc2Labels[0] as! String,pc2Labels[1] as! String,pc2Labels[2] as! String,pc2Labels[3] as! String]
        let legend:ChartLegend = pieChart.legend
        legend.position = ChartLegend.ChartLegendPosition.RightOfChartInside

**Comment by liuxuan30** [comment]
you could change the source code or override it to whatever you like.
