### ISSUE TITLE
How to draw a LineChartDataSet skipping certain data points

### ISSUE THREAD

**Issue by dddppp** [danielgindi/ios-charts#622]
Hello,

below there is the method that I use to generateLineData. However I would like to skip the data points where the data.price value is different than INT16_MIN. 

Unfortunately there is no source code for " [[LineChartDataSet alloc] initWithYVals:entries label:@"Price"];". The code below does not seem to do the job as I believe passing a mutable array to the initWithYVals method is not the correct way to deal with this (there is no fixed enumeration on it so it would not know when a data point is missed).

What should I do to get the library to skip some data points?

    - (LineChartData *)generateLineData
        {
        LineChartData *d = [[LineChartData alloc] init];
        
        NSMutableArray *entries = [[NSMutableArray alloc] init];
        
        for (int index = 0; index < [self.data count]; index++)
        {
            MyData * data = [self.data objectAtIndex:index];
            if (data.price != INT16_MIN) {
                [entries addObject:[[ChartDataEntry alloc] initWithValue:data.price xIndex:index]];
            }
        }
        
        LineChartDataSet *set = [[LineChartDataSet alloc] initWithYVals:entries label:@"Price"];
        [set setColor:[UIColor colorWithRed:240/255.f green:238/255.f blue:70/255.f alpha:1.f]];
        //    set.lineWidth = 2.5;
        set.lineWidth = 1.0;
        [set setCircleRadius:1.0f];
        [set setCircleColor:[UIColor colorWithRed:240/255.f green:238/255.f blue:70/255.f alpha:1.f]];
        set.fillColor = [UIColor colorWithRed:240/255.f green:238/255.f blue:70/255.f alpha:1.f];
        set.drawCubicEnabled = YES;
        set.drawValuesEnabled = YES;
        set.valueFont = [UIFont systemFontOfSize:0.f];
        set.valueTextColor = [UIColor colorWithRed:240/255.f green:238/255.f blue:70/255.f alpha:1.f];
        // set.axisDependency = AxisDependencyLeft;
        
        [d addDataSet:set];
        return d;
    }

**Comment by liuxuan30** [comment]
you can just don't feed y value for the specific xIndex. It will pass it, and then connect the previous data to the next valid one.
e.g.
x: 0 1 2 3 4
y: 1    3 5 6
