### ISSUE TITLE
what's wrong with:_OBJC_CLASS_$__TtC6Charts13LineChartView

### ISSUE THREAD

**Issue by chenyangjun** [danielgindi/ios-charts#623]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$__TtC6Charts13LineChartView", referenced from:
      objc-class-ref in DashTypeSelectedVCViewController.o
ld: symbol(s) not found for architecture armv7

I used Swift in an ObjC project,has selected the Charts.framework under the "Embedded Binaries" section. 
depoloyment Target : 8.0
I am a novice,Thank you first.

**Comment by liuxuan30** [comment]
It's about saying your architecture, not Chart's library. Check your project setting about it first
Follow README carefully, and run ChartsDemo, it's helpful.
