### ISSUE TITLE
set width of highlight in pie

### ISSUE THREAD

**Issue by Kepedize** [danielgindi/ios-charts#625]
first of all - great Lib!

I did run into some trouble trying to set the width of the highlight that's added to the slice when it is touched.

I was able to work around by changing line 335 in PieChartRenderer to (new code in bold) :
let shift = set.selectionShift <B>/ 2</B>

is there a better way?

**Comment by liuxuan30** [comment]
I am not sure, what's your question, but why don't you just make selectionShift what you want?
like  `set.selectionShift  = set.selectionShift  / 2`

**Comment by Kepedize** [comment]
Thanks for taking the time to answer such a silly question, it was right in
front of me...
