### ISSUE TITLE
I want to know the project name - swift. h  class of how to generate

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/ios-charts#627]
I want to know  the following content  of  the project name - swift. h is how to generate, if it is to write  by oneself ,     how can I be sure " _TtC10ERPPRODUCT13BalloonMarker" ,thanks

SWIFT_CLASS("_TtC10ERPPRODUCT13BalloonMarker")
@interface BalloonMarker : ChartMarker
@property (nonatomic, strong) UIColor * __nullable color;
@property (nonatomic) CGSize arrowSize;
@property (nonatomic, strong) UIFont * __nullable font;
@property (nonatomic) UIEdgeInsets insets;
@property (nonatomic) CGSize minimumSize;
- (nonnull instancetype)initWithColor:(UIColor * __nonnull)color font:(UIFont * __nonnull)font insets:(UIEdgeInsets)insets OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize size;
- (void)drawWithContext:(CGContextRef __nonnull)context point:(CGPoint)point;
- (void)refreshContentWithEntry:(ChartDataEntry * __nonnull)entry highlight:(ChartHighlight * __nonnull)highlight;
@end

**Comment by liuxuan30** [comment]
This is done by Xcode, you don't have to write it. You just need to setup your project settings to enable swift and Objective-C hybrid.
