### ISSUE TITLE
Chart Line vanishes on pinch to zoom

### ISSUE THREAD

**Issue by caloon** [danielgindi/ios-charts#63]
I experienced that when you zoom in on a chart using a pinch gesture, the chart lines are sometimes vanishing (no chart lines displayed). The data source however still contains several values.

Has anyone else experienced this issue?

**Comment by danielgindi** [comment]
Can you record what you are experiencing? (Using iPhone Simulator, iTunes or whatever...)

It could be theoretically lines that are skipped since being out of the viewport anyway, but that shouldn't happen. So maybe floats that are too big? (We're planning to move to Doubles anyway... #62 )

**Comment by caloon** [comment]
Yes, recorded the screen of my iPhone using QuickTime Player. 
Find the video here: https://www.dropbox.com/s/kdxxqaauki6rcmo/LineChart%20vanishing.mov?dl=0

**Comment by danielgindi** [comment]
I can't make it happen the same way, it works flawlessly, except for one bug with Cubic lines which I'm fixing now.
Can you produce an example project?

**Comment by danielgindi** [comment]
Maybe try the latest fixes? I don't know if they affect you in some way, but it doesn't hurt to try!

**Comment by caloon** [comment]
I had the issue from the very first time I implemented it with my source data. A friend of mine (Testflight beta tests) reported the same issue. 

Please find my sample data attached, maybe you can use it to reproduce the issue: http://www.codeshare.io/zdFG9

**Comment by caloon** [comment]
I just recognized that the xIndex of the ChartDataEntries is not unique (see line 191). Might this be the source of the error?

**Comment by caloon** [comment]
Just tested the above. Making the xIndex a unique integer seems to improve the situation somewhat, however the chart lines still vanish in certain time intervals.

By the way - would be good if xIndex could be a Float or Double, this would make it more flexible for relative values (currently my chart is an approximation of the next integer value for a yVal).

**Comment by danielgindi** [comment]
A) I will test your code soon- it has nothing to do with the x indexes
B) x indexes shouldn't really be decimal as the distance between two
x-values should be equal. The values *should* be an approximation...

**Comment by danielgindi** [comment]
Well I can't test your code as I don't have the datasets and I sure am not
going to convert all those dates from println to NSDates :-)
Could you post a "working" sample project?

**Comment by caloon** [comment]
It seems as it is now solved: I applied the approximation to the yVals instead of the x indexes. The chart is now no longer vanishing.
Thanks for your helped.
