### ISSUE TITLE
Xcode7.1.1 contains error

### ISSUE THREAD

**Issue by Adrian0212** [danielgindi/ios-charts#633]
I down load project and run with Xcode 7.1.1 ，but it contains two error
I run this project with Xcode 7.0 no problem，I remember
![3bcd6afd-3080-4b2f-9764-688ec11f73e0](https://cloud.githubusercontent.com/assets/8456365/12031618/1c88e384-ae49-11e5-899e-e545591c5b66.png)

**Comment by liuxuan30** [comment]
I am Version 7.2 (7C68) Xcode and no such issues. and it reports bitcode_strip is not in PATH. So checkout if bitcode_strip is broken or missing. I would suggest do a 7.2 fresh install.
