### ISSUE TITLE
Not able to archive build : Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by pratik6554** [danielgindi/ios-charts#634]
Command failed due to signal: Segmentation fault: 11
in 

1) "ChartDataSet"
SwiftCodeGeneration normal arm64 /Users/pratik/Library/Developer/Xcode/DerivedData/ChartsDemo-fyabqwvvqygxxwbyrrudetsmskcu/Build/Intermediates/ArchiveIntermediates/ChartsDemo/IntermediateBuildFilesPath/Charts.build/Release-iphoneos/Charts-iOS.build/Objects-normal/arm64/ChartDataSet.bc

2) PieRadarChartViewBase
SwiftCodeGeneration normal arm64 /Users/pratik/Library/Developer/Xcode/DerivedData/ChartsDemo-fyabqwvvqygxxwbyrrudetsmskcu/Build/Intermediates/ArchiveIntermediates/ChartsDemo/IntermediateBuildFilesPath/Charts.build/Release-iphoneos/Charts-iOS.build/Objects-normal/arm64/PieRadarChartViewBase.bc

**Comment by liuxuan30** [comment]
Are you using ChartsDemo? You have to provide more details, like error log or back trace about this error. Currently, I don't see such issue on my side. The log can't tell anything can help narrow down the issue.

**Comment by pratik6554** [comment]
Yes. i am using ChartsDemo . Try to archive.

**Comment by pratik6554** [comment]
<img width="1111" alt="error" src="https://cloud.githubusercontent.com/assets/1791675/12033312/9f6c628c-ae47-11e5-8340-152759d73001.png">

**Comment by liuxuan30** [comment]
I am able to archive on my side without issues, Xcode 7.2.
Have you changed any project settings? This seems a very deep exception..

**Comment by pratik6554** [comment]
ohh.. i am on Xcode 7.1 beta 5.
Thanks will update :) :+1:

**Comment by pratik6554** [comment]
Able to archive on xcode 7.2 :) @liuxuan30  Thanks :)

**Comment by ShenLinPing** [comment]
i have a same problem,  thanks your issue
