### ISSUE TITLE
【StackedBarChartView】How to handle 0？

### ISSUE THREAD

**Issue by hh1myfei** [danielgindi/ios-charts#637]
hey:
stackbarview, when my YVals contains the value 0, and set drawValueAboveBarEnabled = NO, the display label values will overlap, like this.
![img_0008](https://cloud.githubusercontent.com/assets/7909993/12045397/110bbac4-aedd-11e5-9ef4-592543890da1.jpg)

If I remove the value 0, when I scaled when it will crash, 
any help?

**Comment by liuxuan30** [comment]
seems dup to #620
