### ISSUE TITLE
xcode 7.1 error at xctest

### ISSUE THREAD

**Issue by malkabani** [danielgindi/ios-charts#644]
i tried ti integrate charts in xcode 7.1 but i am getting error at xctest (cannot load underlying module for xctest)

**Comment by danielgindi** [comment]
The main target does not try to load XCTest. There's something different that you are doing that's wrong.

**Comment by petester42** [comment]
Don't import the tests into your project. I believe you are seeing this error because you added the test source files to your project.

**Comment by liuxuan30** [comment]
Seems solved

**Comment by smilydronavalli** [comment]
hi petester, i am also facing the same problem(cannot load underlying module for xctest), can you please say me what are the folders i want to import to integrate charts.
 Help me out to solve this problem

**Comment by petester42** [comment]
Don't add any folders or files that have test in the name.
