### ISSUE TITLE
The most top label of ChartYAxis doesn't render which seems a bug.

### ISSUE THREAD

**Issue by AntiMoron** [danielgindi/ios-charts#647]
Check line 251 of [THIS FILE](https://github.com/danielgindi/ios-charts/blob/master/Charts/Classes/Renderers/ChartYAxisRenderer.swift) 
It's `if (!_yAxis.isDrawTopYLabelEntryEnabled && i >= _yAxis.entryCount - 1)`
I think it should be
```swift
if (!_yAxis.isDrawTopYLabelEntryEnabled && i > _yAxis.entryCount - 1)
```

**Comment by danielgindi** [comment]
Nope :-)
The top entry is actually when `i == entryCount - 1`, that's the last entry. But we did write it as `i >= entryCount - 1` for safety. There were cases where people did weird things with data... Although it's much safer in the latest releases.
