### ISSUE TITLE
Multiple Chart View Within ScrollView

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#65]
Hi Daniel,
I have another problem to cope with,
I have multiple charts to view in One ViewController Scene,

i   - Pie Chart
ii  - Scattered Chart
iii - Bar Chart

Problem is : 
 - Start scrolling It works perfectly,
 - End scrolling and wait for 1-5 Seconds
 - Then start scrolling it will not scroll. 

I think Chart view is eating scroll of My Scroll view, Or am I missing something ?

Thanks.

**Comment by danielgindi** [comment]
Well I can't see your code so I can't tell- but it CAN diaable your scroll
if it is zoomed in for example, ir if "default touches" are disabled.


‏בתאריך יום שלישי, 5 במאי 2015, BurhanMughal <notifications@github.com> כתב:

**Comment by BurhanMughal** [comment]
well Code is simple I just put chart views in a scroll view, and that's it.

**Comment by danielgindi** [comment]
Well I'm sure the code is simple, but every setup is different. So you can
either debug and tell us what's happening, or provide a sample code :-)

**Comment by BurhanMughal** [comment]
How i can upload text file of my code ?

**Comment by danielgindi** [comment]
Just put a sample project on a git repo and send a link

**Comment by BurhanMughal** [comment]
https://github.com/BurhanMughal/MyFiles/blob/master/piechart.m Please have a look.

**Comment by BurhanMughal** [comment]
Waiting for your response.

**Comment by danielgindi** [comment]
That file won't compile. It's not a test case, but a piece of a very dependent code...
You can't send me to write code to test the bug that you are experiencing.

Anyway I've put 3 charts like you in a scrollview, and it scrolls just fine!

**Comment by BurhanMughal** [comment]
Hi Daniel How to check chart is zoomed in ?

**Comment by BurhanMughal** [comment]
Can we show Pie chart Value out of slice instead showing inside the slice ?

**Comment by BurhanMughal** [comment]
I got the Issue cause, chat.dragEnabled = YES; 
When saying NO to chart.dragEnabled it starts scrolling.

But I need both dragEnabled = YES and Scroll View scrolling as well.

Any Idea ??

**Comment by BurhanMughal** [comment]
Can one control 2 charts with one scroll, i.e. One View controller has two bar charts in it, If user scrolls one chart second chart should also be scrolled accordingly (Same for Pinch Zoom)?

Thanks.

**Comment by AlBirdie** [comment]
Holy moly this thread is a mess, so many different topics...

@BurhanMughal , regarding your last question, yes, you can do that. Simply disable all gesture recognizers of the charts and add those to your ScrollView. These recognizers then handle the transformations for all your charts.

**Comment by danielgindi** [comment]
I'm keeping this open- because I want when I get the time, to let the drag gesture know it's not needed when you are zoomed out, and maybe when it reaches the edge.

**Comment by danielgindi** [comment]
Seems like UiView is handli g the touches against the gestures and decides when to pass them on based on a delegate call so that's where I'll intervene.

**Comment by danielgindi** [comment]
In PieChart/RadarChart, you should now enable `rotationWithTwoFingers`, so the rotation gesture do not conflict with the dragging of the parent scrollView.

**Comment by danielgindi** [comment]
I'm working on a combination where you would be able to let all the Charts play together with ScrollView, by just disabling the `isHighlightPerDragEnabled`, without moving the gesture recognizers to the ScrollView. Not sure yet that it's possible though

**Comment by hudanavroz** [comment]
Can we scroll line chart horizontally?
