### ISSUE TITLE
Add To existing project and that too for iOS 7 

### ISSUE THREAD

**Issue by yogesh2209** [danielgindi/ios-charts#650]
Please help me to add this to my existing objective project for iOS7.
i am not able to add for iOS7.
how to add it for iOS7 ??

**Comment by liuxuan30** [comment]
just drag the Charts code files into your project as a group(folder) - I assume it's Objc based project.
And enable swift in Objective-C project, take a look at https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
And don't forget to read REAME.
