### ISSUE TITLE
Draw Straight Line on Line Chart with 2 fingers and show the Gradient of it

### ISSUE THREAD

**Issue by krumiro** [danielgindi/ios-charts#652]
the 2 fingers pressed represent the 2 points through which the line passes throw. As I move the fingers the line passing through them is shown in real time until I decide the final position. When I lift the fingers the line remains there (and can be changed later).  The drawn line also shows on top of itself a label indicating its value of y/x inclination (gradient). this gradient is also shown while choosing the line's position.  All of this happening on top of a line chart (to add personalized gradient lines or trend lines to help visualize trends of the graph)

Anyone knows how to add this on ios-charts?

Thanks!!!

**Comment by liuxuan30** [comment]
I guess first you need to organize the words, HARD to understand. Second, it seems you are aware what you want to achieve, so maybe you can ask more specific questions so we can better help.
Generally, you can draw anything you want if you know where to draw the line. You will need to modify the code and figure out what's the best way to add your coustomized lines.
