### ISSUE TITLE
LineChartView grid background

### ISSUE THREAD

**Issue by LuoPengFei** [danielgindi/ios-charts#655]
I have to create a custom chart like this. Everything is working except for the grid background color. Is that possible with this library?
<img width="396" alt="2016-01-07 4 33 52" src="https://cloud.githubusercontent.com/assets/10494635/12166058/dd87c77e-b55d-11e5-8fee-2ae493f4e022.png">

**Comment by LuoPengFei** [comment]
<img width="396" alt="2016-01-07 4 33 52" src="https://cloud.githubusercontent.com/assets/10494635/12166048/ce5da8cc-b55d-11e5-93b5-769c954aa486.png">


<img width="396" alt="2016-01-07 4 33 52" src="https://cloud.githubusercontent.com/assets/10494635/12166048/ce5da8cc-b55d-11e5-93b5-769c954aa486.png">

**Comment by liuxuan30** [comment]
Currently no. People has asked for this. dup to #186
