### ISSUE TITLE
xcode7.2 iOS 9 crash

### ISSUE THREAD

**Issue by wangwayhome** [danielgindi/ios-charts#656]
dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /var/mobile/Containers/Bundle/Application/36EF30E4-B321-4D9B-94AA-F5AC8F4CCB95/iOSChartsDemo.app/iOSChartsDemo
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/36EF30E4-B321-4D9B-94AA-F5AC8F4CCB95/iOSChartsDemo.app/Frameworks/Charts.framework/Charts: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/36EF30E4-B321-4D9B-94AA-F5AC8F4CCB95/iOSChartsDemo.app/Frameworks/Charts.framework/Charts'
![image](https://cloud.githubusercontent.com/assets/3345342/12171518/8b18bd90-b585-11e5-9f37-93988838dc88.png)

**Comment by wangwayhome** [comment]
![image](https://cloud.githubusercontent.com/assets/3345342/12171539/a5a9bcea-b585-11e5-8e7d-1a1e344525bd.png)

**Comment by wangwayhome** [comment]
what can i do

**Comment by wangwayhome** [comment]
Simulator no problem，but iPhone is crash

**Comment by liuxuan30** [comment]
Please first try search the key word Reason: no suitable image found or others in issues, some may help. To me, seems your certs problem. Is this release build? in-house distribution or app store distribution?

**Comment by wangwayhome** [comment]
@liuxuan30  this is a debug run，certs is no problem。
![image](https://cloud.githubusercontent.com/assets/3345342/12188612/ee8b96ec-b5f1-11e5-94f1-dbc365e8c00b.png)

**Comment by liuxuan30** [comment]
if debugging it on real device is broken, it's definitely your certs or project setting problem. You have to google or ask on SO, or provide more info then we can help. I can run ChartsDemo on iPhone device without issue.

key log:
Reason: no suitable image found. Did find:
/private/var/mobile/Containers/Bundle/Application/36EF30E4-B321-4D9B-94AA-F5AC8F4CCB95/iOSChartsDemo.app/Frameworks/Charts.framework/Charts: mmap() errno=1

**Comment by wangwayhome** [comment]
Just now，I tried in Xcode 7.1 and Mac os 10.10   and iOS8 is no problem。。。。but in Xcode 7.2 and Mac OS10.11.2 and iOS9.2 is  crash。。。OMG～

**Comment by wangwayhome** [comment]
I seem to find a reason，
 I create a new blank project in swift ，iPhone crash～
 but  create a new blank project in objective c ，is OK～

**Comment by wangwayhome** [comment]
@liuxuan30  i resolve;  is certs problem。i create a new cert and .mobileprovision, there are no more issues.

**Comment by wangwayhome** [comment]
closed ～  thanks！
