### ISSUE TITLE
Realtime data

### ISSUE THREAD

**Issue by gkaimakas** [danielgindi/ios-charts#657]
Hello,

I am trying to display realtime data on a linechartview. I want only the last 10 values to be visible at each time with or without the user to be able to scroll.

Can anyone hell?

**Comment by petester42** [comment]
There is no realtime data support yet but what you can do is have a method that processes your data and then reloads the chart.

**Comment by liuxuan30** [comment]
You can try search old issues about realtime data, I remember there are some.

**Comment by gkaimakas** [comment]
I figured it out. Each time I get a new reading I create a new dataset and a new data object and set the new data as the data of the chart. Works great

**Comment by petester42** [comment]
Yep. That is the proper way of doing it right now.
