### ISSUE TITLE
draw only the maximum and minimum values on the LineChartView

### ISSUE THREAD

**Issue by LuoPengFei** [danielgindi/ios-charts#662]
Can I only  draw the maximum and minimum values on the LineChartView.

**Comment by liuxuan30** [comment]
use
    /// if true, the y-labels show only the minimum and maximum value
    public var showOnlyMinMaxEnabled = false

**Comment by LuoPengFei** [comment]
<img width="406" alt="2016-01-13 10 50 24" src="https://cloud.githubusercontent.com/assets/10494635/12283721/0e2696fa-b9e4-11e5-8234-8285f0ecebb1.png">
Pictures that I want to draw the maximum position，not in the left axis.

**Comment by liuxuan30** [comment]
OK, then you need to override `drawValues` in line chart renderer
