### ISSUE TITLE
Programatically highlight a data point in line chart

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#668]
Hi,

I've been looking and haven't been able to find a way to programmatically select a data point in a linechart. Is there a method to do this? If there is how do i access it?

**Comment by osolano** [comment]
Nevermind I found it.

I used
    [self.chartView highlightValueWithXIndex:3 dataSetIndex:1 callDelegate:self];
Thanks!

**Comment by SagarDabhi** [comment]
@osolano thanks it's really helpful but can you please elaborate how I highlight two value at a time?

**Comment by muzoman** [comment]
@SagarDabhi Did you ever work out how to highlight multiple values?

**Comment by shashidhar34** [comment]
Calling highlightValue without passing y value didn't work for me. I had to pass y value as well using the call
chartView.highlightValue(x: x, y: y, dataSetIndex: 0, callDelegate: true)

**Comment by AdrianBinDC** [comment]
@shashidhar34 You can put in `Double.nan` for the Y value and it'll work. I had the same issue.
