### ISSUE TITLE
Allow control of circle line width in Line Chart.

### ISSUE THREAD

**Issue by terloon** [danielgindi/ios-charts#669]
I didn't see any way to modify the width of the circles in the line chart. This is my initial attempt at it. The current method performs a calculation halving the circle diameter. Right now I hard coded it to be the same value for the default radius, but it will look different for current implementations if they use this. 

Needs invalid value checks and maybe a calculation to match previous look of halving diameter.

I have a commit for this, but I've never really shared to a github project before so learning how to do that now.

**Comment by liuxuan30** [comment]
You can fork this repo, and create a new branch and you commit on this branch; when finished, push this branch to your forked repo, and create a Pull Request(PR) to this repo's master branch.
You can learn it from github, there are guidance like: https://help.github.com/articles/using-pull-requests/
Practice makes perfect :)
