### ISSUE TITLE
Refresh charts view when the data change

### ISSUE THREAD

**Issue by mlorenzeCDS** [danielgindi/ios-charts#672]
Hello, I have this problem: I like to refresh the chart when i change the values of the dataSet, but with an animation that pass from the actual values to the new values directly (not refresh the chart going to the begining).

If someone has the solution I will be grateful.

**Comment by marcantoinefortier** [comment]
:+1:

**Comment by danielgindi** [comment]
Duplicate https://github.com/danielgindi/ios-charts/issues/189
