### ISSUE TITLE
Convert it to percent bar graph system

### ISSUE THREAD

**Issue by yogesh2209** [danielgindi/ios-charts#674]
I want to show percent values  like if there are 2 values, then it must calculate 50% by default and show 50 bar graph on both sides.
is it possible or i have to do it by myself through code ?

**Comment by liuxuan30** [comment]
I don't get "then it must calculate 50% by default and show 50 bar graph on both sides"
will stacked bar chart is your case? Play with ChartsDemo to see if any matches.

**Comment by danielgindi** [comment]
I think that the viewport actually works the way you are (vaguely) describing.
When all of your data is visible, then the zoom is 100%. 
Play with the viewport and one way or another you'll achieve what you want

**Comment by HPRaval** [comment]
Will you please provide some example? I want same. Want stacked bar chart with percentage like this

![screen shot 2017-05-26 at 3 32 27 pm](https://cloud.githubusercontent.com/assets/24671241/26490366/99bdacb2-4228-11e7-9e0d-4e3bae03118d.png)

**Comment by CavalcanteLeo** [comment]
@HPRaval have you figured out how to do it?
