### ISSUE TITLE
Can't set x axis offset

### ISSUE THREAD

**Issue by pawelurb** [danielgindi/ios-charts#677]
Hello,

I have a problem with a CombinedChartView which I'm trying to fix but I can't find a decent solution. Here's a screenshot of the chart:
![chart_problem](https://cloud.githubusercontent.com/assets/5851058/12324864/2642a1ec-bac6-11e5-88a0-7c4e81b21ea8.png)

As you can see the LineChartDataSet which I have doesn't start directly at the beginning of horizontal axis. There is a small offset which I'm trying to eliminate and I would like the dataset to start directly from the zero position of X axis, so basically what I'm trying to achieve is that:
![chart_fixed](https://cloud.githubusercontent.com/assets/5851058/12324885/480676be-bac6-11e5-8f68-191c7eb55d33.png)
(actually that's not a screenshot but the previous one edited in an image editor, anyway I think you get the point)

I guess that's not a big deal to implement, but I'm trying to find a solution how to achieve that and I'm not able to. I hope that you will be able to help me with it. Thank you!

**Comment by petester42** [comment]
Can you not subtract an amount from your X values so that it does start at zero?

**Comment by pawelurb** [comment]
@petester42 thank you for reply! Could you show me an example code how to do that?

**Comment by petester42** [comment]
if you take the chart demo line chart and look at where the data set is created you can see it creates X and Y values. Just take the X array and loop through it while subtracting the correct amount from each one. 

As far as what the correct value is (if it is not constant) then you can subtract the smallest X value in your data set. 

That should result in what you are trying to achieve.
