### ISSUE TITLE
Apache license and correct attribution in an iOS app?

### ISSUE THREAD

**Issue by MHX792** [danielgindi/ios-charts#678]
When I use this for a commercial iOS App, where should I put the license attribution? In the AppStore description? In the App itself? Or just in the source coude? Do I need to publish the source code?

**Comment by petester42** [comment]
As long as you keep the header comments and the license file in your source you will be fine. If you want you can give attribution in the app but it isn't required.  

It's nice to have people actually ask about this and not just blindly using things. :tada:

**Comment by yas375** [comment]
Also a good idea might be to include Acknowledgements into Settings bundle so it's showed in Settings.app:

|   |  |
| ------------- | ------------- |
| ![img_5889](https://cloud.githubusercontent.com/assets/217368/12342274/e1593d4e-badd-11e5-9a93-c5ad3a49ad7b.jpg) | ![img_5890](https://cloud.githubusercontent.com/assets/217368/12342288/0a1784c0-bade-11e5-9bc2-d60ada4ffbd6.jpg) |


We generate it using [this instruction](https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements) (assuming you are using CocoaPods).

**Comment by danielgindi** [comment]
As @petester42 said, it's real nice to have people considering this, and not just passing by and grabbing the code... So thank you :-)

Anyway attribution is not required, but is a nice thing to do. In fact when I see an app with a list of attributions in the settings area - I tend to appreciate the developers more. It just says something about you...

Also a little off-topic - as this framework has become very popular, I think it's time to maintain a list of apps that use it, don't you think?

**Comment by SatishBirajdar007** [comment]
@danielgindi Hi Daniel, I am fan of your Chart.framework and created a 2 screen app and now wanting to submit my first (free) app on Appstore. But while submitting on AppStore, Apple asks if I have right permission to use Chart.framework in Canada, USA, UK and India. So was wondering to ask you, whether the framework is available for free or charged? 
Thanks again for an amazing framework. Cheers 👍

**Comment by MHX792** [comment]
I have never seen Apple asking for licenses for any of the dependencies that I use in my apps. How come they asked for it? Do you have a screenshot? I am curious why they asked for Charts licence in those countries in particular?

**Comment by SatishBirajdar007** [comment]
@MHX792 Actually this is my first time submitting an application to iTunes. 
As per comment on [https://github.com/danielgindi/Charts/issues/2904#issuecomment-338645984] Charts is under Apache 2.0 and is free. 
Should I select "Yes" for both question, as shown in the attachment?

<img width="1049" alt="screen shot 2017-10-23 at 4 39 32 pm" src="https://user-images.githubusercontent.com/29895237/31912243-399da8a0-b811-11e7-94f8-62a9991574d8.png">
