### ISSUE TITLE
Dynamic LineChartView

### ISSUE THREAD

**Issue by TigerBroker** [danielgindi/ios-charts#680]
<img width="164" alt="2016-01-15 3 36 04" src="https://cloud.githubusercontent.com/assets/10494635/12348554/626d9f36-bba3-11e5-9a8d-e65d94aa70fc.png">

How can that kind of dynamic graphing like figure,I tried a number of methods, but did not achieve the desired effect.Can you provide some ideas

**Comment by iostalk** [comment]
How to do this?

**Comment by chris-gunawardena** [comment]
`self.lineChartView.setVisibleXRange(minXRange: CGFloat(1), maxXRange: CGFloat(50))` with 
`self.lineChartView.moveViewToX(CGFloat(i))` worked for me.
