### ISSUE TITLE
Can I package the project in a dynamic library (.framework)?

### ISSUE THREAD

**Issue by carlosandresSanchez** [danielgindi/ios-charts#681]
I need to create the .framework library from the project in order to use it Appcelerator native module. I generate the .framework by making the build (Command + B) and i get it, but when I use it in a xcode project i get the following error : 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC6Charts12BarChartView", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by danielgindi** [comment]
You have probably compiled against it but not linked it.
You have to make sure that the framework is marked as Embedded.

Also, you can follow the README to use Carthage to build the framework as a ".framework" file, or take it from the releases.
