### ISSUE TITLE
Center text vertically

### ISSUE THREAD

**Issue by hiworld75018** [danielgindi/ios-charts#682]
When using big fonts, I noticed that text is not actually vertically centered.
Adding this in DrawUtils.drawText() makes it work:

if let font = attributes?[NSFontAttributeName] as? UIFont {
  point.y -= font.lineHeight / 2
}

**Comment by liuxuan30** [comment]
could you specify which font size are you using, also is it axis label text or value text? A screenshot is even better.

**Comment by hiworld75018** [comment]
In case there is a single value, I use the chartView.noDataText field to display it, using font size 36 (with chartView.data == nil).

**Comment by liuxuan30** [comment]
a single value, but no data? Can you post a screenshot?

**Comment by hiworld75018** [comment]
You may try this code, to display the "single" value converted into a string that will sit in the middle of the "chart":

UIFontDescriptor* bodyDescriptor = [UIFontDescriptor preferredFontDescriptorWithTextStyle:UIFontTextStyleBody];
UIFont* font = [UIFont fontWithDescriptor:bodyDescriptor size:36.]; // some BIG size

PieChartView* chartView = [[PieChartView alloc] initWithFrame:CGRectMake(0, 0, 300, 200)];

chartView.infoTextColor = [UIColor redColor];
chartView.infoFont = font;

chartView.noDataText = @"99%"; // the "single" value is converted into text here

// Remove the chart legend + label "description"
chartView.legend.enabled = NO;
chartView.descriptionText = @"";

**Comment by liuxuan30** [comment]
if your "single value" means `noDataText`, on my side I have no problem with it:
![pie](https://cloud.githubusercontent.com/assets/4375169/12601175/f01b619e-c4d9-11e5-9410-5552a9c8d074.png)

**Comment by liuxuan30** [comment]
OK I checked the code:

```swift
    public class func drawText(context context: CGContext, text: String, var point: CGPoint, align: NSTextAlignment, attributes: [String : AnyObject]?)
    {
        if (align == .Center)
        {
            point.x -= text.sizeWithAttributes(attributes).width / 2.0
        }
```
It seems it just tried to center x but no y. I will file a PR later.

**Comment by hiworld75018** [comment]
I think I've got a better way to fix it:

In ChartViewBase.drawRect(rect), use lineHeight to center vertically before calling ChartUtils.drawText()

CGContextSaveGState(context)
let lineHeight = infoFont.lineHeight
ChartUtils.drawText(..., point: CGPoint(x: frame.width / 2.0, y: frame.height / 2.0 - lineHeight / 2.0), ...)
if (noDataTextDescription != nil && (noDataTextDescription!).characters.count > 0)
{
	...
	ChartUtils.drawText(..., point: CGPoint(x: frame.width / 2.0, y: frame.height / 2.0 - lineHeight / 2.0 + textOffset), ...)
	...
}

I noticed the same in PieChartRenderer.drawValues(context)

// y -= lineHeight
if (drawXVals && drawYVals)
{
  y -= lineHeight
  ...
}
else if (drawXVals && !drawYVals)
{
  y -= lineHeight / 2
  ...
}
else if (!drawXVals && drawYVals)
{
  y -= lineHeight / 2
  ...
}

**Comment by liuxuan30** [comment]
You could file a PR for this. Mine is closed since I don't see the big picture. Hope you can fix them all from my PR.

**Comment by danielgindi** [comment]
Modifying drawText is the wrong approach and will make all text drawing in axises incorrect.
Fix coming...
