### ISSUE TITLE
Cubic line goes over the last point

### ISSUE THREAD

**Issue by jitu89** [danielgindi/ios-charts#683]
![linebar](https://cloud.githubusercontent.com/assets/1121878/12392075/4365eb54-be12-11e5-90bc-3fe79f63ff3b.png)

The line is coming out of the circle for the first point when it is cubic 

kindly help me in getting solution

**Comment by liuxuan30** [comment]
I don't see this in ChartsDemo combined chart

**Comment by danielgindi** [comment]
I do not see this in the demo. Was this maybe solved already by another cubic fix?

**Comment by danielgindi** [comment]
Oh wait. I do see this.

**Comment by danielgindi** [comment]
Yay! :-)
