### ISSUE TITLE
Issue with x-axis fixed label width

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#684]
Hi,
I'm trying to make sure that all data points on the line chart have a label showing below it. I've tried adjusting the _chartView.xAxis.labelWidth property to different values but it doesn't seem to make a difference. I simply just want to make sure that the label width between each data point is the same so that all the labels are shown. Any thoughts on how to adjust this?

The bottom image is what is shown when labelWidth is not set.

![image](https://cloud.githubusercontent.com/assets/280426/12404051/66880b6e-be06-11e5-880a-0ca3e454607c.png)

**Comment by liuxuan30** [comment]
xAxis.labelWidth is used to determine max label width, and use it to calculate the modulus. If you want to show every label, try:
```swift
    /// the modulus that indicates if a value at a specified index in an array(list) for the x-axis-labels is drawn or not. Draw when `(index % modulus) == 0`.
    public var axisLabelModulus = Int(1)
    
    /// Is axisLabelModulus a custom value or auto calculated? If false, then it's auto, if true, then custom.
    /// 
    /// **default**: false (automatic modulus)
    private var _isAxisModulusCustom = false
```

**Comment by osolano** [comment]
that worked for me thank you!
