### ISSUE TITLE
How to make CandleStickChart and BarChart do the same action

### ISSUE THREAD

**Issue by z404558** [danielgindi/ios-charts#685]
I have a CandleStickChart and a BarChart below it. When I make CandleStickChart zoom in or out or translate, I want BarChart do the same action.
Do you have a solution about this?

- (void)chartScaled:(ChartViewBase * __nonnull)chartView scaleX:(CGFloat)scaleX scaleY:(CGFloat)scaleY
{
    
    NSLog(@"1:_____scaleX:%f_____scaleY:%f_____",scaleX,scaleY);
    
    
    if (chartView.tag == 100) {
        
        [_dayK_squareView setVisibleXRangeMinimum:5];
        

        [_dayK_squareView zoom:scaleX scaleY:scaleY x:0 y:0];

        
    }
    
    if (chartView.tag == 200) {
        [_day_Candle_chartView setVisibleXRangeMinimum:5];
        

        [_day_Candle_chartView zoom:scaleX scaleY:scaleY x:0 y:0];

        
    }
}

**Comment by liuxuan30** [comment]
You can achieve this by 
```swift
public func zoom(scaleX scaleX: CGFloat, scaleY: CGFloat, x: CGFloat, y: CGFloat) -> CGAffineTransform
```
and other functions in ChartViewPortHandler
