### ISSUE TITLE
RadarChartView - Unknown type name

### ISSUE THREAD

**Issue by suddmahajan** [danielgindi/ios-charts#687]
I have used iOS chart library, I want to use Radar chart view. I have created 'BalloonMarker.swift' and added code into it. However I have facing the following errors- 
1)Undeclared identifier - 'BallonMarker'
2)Use of undeclared identifier 'marker'

Can you please help me to resolve it. I'm newbie for iOS.

**Comment by liuxuan30** [comment]
read README and search old issues and google for your keywords. You are not the first one
