### ISSUE TITLE
Need Help to setup this library on application with Objective C(No auto layout) with deployment target iOS 7.0

### ISSUE THREAD

**Issue by bhaumikdesai91** [danielgindi/ios-charts#688]
Hello Sir,

I am trying to integrate your library on a project with deployment target iOS 7.0 and it's in Objective C. I have tried the steps you have mentioned in Usage section but it turns out that swift is not supporting embedded Framework. Also regarding the Realm.Framework, Is this framework necessary as I am only willing to add Stacked Bar Chart with database driven data model. And It should be simple. Am I missing something?

**Comment by liuxuan30** [comment]
if you are supporting iOS 7, you should directly drag the code files into your project, and somer proper build settings for swift (just search old issues/google if you don't know how to), README has said it.

If you do not need/want support for Realm.io, you can make the Realm.framework optional in your Build Phases, or avoid copying the Realm folder and the Realm.framework.
