### ISSUE TITLE
Set label for each column in group bar chart

### ISSUE THREAD

**Issue by minhthuc251** [danielgindi/ios-charts#691]
I want to set label of xAxis for each column in each group bar chart .
I want  column 876 has label : cafe sua da and column 10 has Sinh to dau . But i don't know how to do that. 
<img width="373" alt="screen shot 2016-01-21 at 2 57 56 pm" src="https://cloud.githubusercontent.com/assets/5000594/12474699/ab14d7bc-c04f-11e5-940e-269a9d7e6082.png">

**Comment by liuxuan30** [comment]
You are having two data sets, and they share the same xIndex and x value. Either use a single data set so you can put x value for each data. Or you can override the x axis renderer 'renderAxisLabels' to what you need.

**Comment by minhthuc251** [comment]
How can i set dependency for each member if using single data set and how i can group 2 member in 1

**Comment by liuxuan30** [comment]
what you mean set dependency? There is axisDependency, not sure if you are asking for it.

If you are using single data set, you can just have single bar chart, or stacked bar chart.
One bar group means one data set. If you want to have two bars at same xIndex, you will need two data sets.

**Comment by minhthuc251** [comment]
I want to set axisDependency , one to left and one to right and i want to have two bars at same xIndex. So how i can set label for each member of group using two data sets. Can you give me an example about using drawLabels, liuxuan30

**Comment by liuxuan30** [comment]
As I said, you have to do some customizations about the x axis renderer.
If it just exists in horizontal bar chart, you could try set two lines of text like 'abc\n123', maybe a trick to let it draw two lines of labels automatically. If this trick does not work, you have to draw your text twice at different positions.
The example is drawLabels itself.
