### ISSUE TITLE
Not compatible with app extensions as a framework

### ISSUE THREAD

**Issue by adonaire-sage** [danielgindi/ios-charts#693]
We are using the library from an app extension, but there's a caveat with using a framework from an app extension, as explained in this Apple link: 

https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

In the section "Using an Embedded Framework to Share Code".

To sum up, in order to compile the app extension without the warning "“linking against dylib not safe for use in application extensions”, which would make the app review fail, we need to be able to set the flag "APPLICATION_EXTENSION_API_ONLY" to YES. That is telling whoever is using the framework that the framework is using extension safe APIs.

So the change is just setting the flag to YES in the project settings, because the library is already not using any unsafe APIs. This makes the library available to use from a Today Widget for example which is quite great since it's such a simple change.

**Comment by adonaire-sage** [comment]
Pull request that fixes this issue here: https://github.com/danielgindi/ios-charts/pull/694

**Comment by adonaire-sage** [comment]
Pull request that fixes this issue here: https://github.com/danielgindi/ios-charts/pull/708

**Comment by danielgindi** [comment]
Merged :-)

**Comment by adonaire-sage** [comment]
Thanks!
