### ISSUE TITLE
The delegate method is not getting called

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/ios-charts#695]
I am integrating the pie chart. I want to find the selected index of the Piechart. But the control doesn't go inside the delegate method.

I checked all the possible location for anything missed. But could not find. It took my 2 days. Anybody out there have any suggestions. 

Please check the screenshots attached. Following is description for the screen shots.
1) The view controller in storyboard is assigned with Class name "PieChartViewController".
2) The view on PieChartViewController is attached with PieChartView and and Charts module.
3) The delegate protocols is followed and delegate for pie charts is declared.
4) The delegate methods for the pie charts are implemented.

![screen shot 2016-01-21 at 4 27 13 pm](https://cloud.githubusercontent.com/assets/3005149/12478610/df774bf0-c05b-11e5-8a06-0ab1f7b0760c.png)

![screen shot 2016-01-21 at 4 14 13 pm](https://cloud.githubusercontent.com/assets/3005149/12478496/3dfd10fc-c05b-11e5-8e8b-295a297a0e8e.png)

![screen shot 2016-01-21 at 4 15 06 pm](https://cloud.githubusercontent.com/assets/3005149/12478506/47f9bace-c05b-11e5-981f-2f9ab692db23.png)

![screen shot 2016-01-21 at 4 15 28 pm](https://cloud.githubusercontent.com/assets/3005149/12478522/6185e29c-c05b-11e5-98b6-ddd31c1007d7.png)

**Comment by liuxuan30** [comment]
Well, ChartsDemo's pie chart is able to trigger the delegate, you can start from there. From your screenshot I can say nothing but debug more / add more break points.
Some hints:
1. whether your pie chart view is initialized correctly and you can see the pie chart
2. whether you enable user interaction (by default true)
3. whether pie chart view has detect your gesture (simply add bp inside @objc private func tapGestureRecognized` in `PieRadarChartViewBase`)

item 3 is the key to call delegate (tapGestureRecognized -> highlightValue ->  chartValueSelected)

**Comment by wganeshb** [comment]
@liuxuan30 Thank you very much for the quick reply.

I checked all the above scenarios. They are at its place. Also I checked ChartsDemo project. The delegate method is called perfectly. 

I tried this steps.
1) I directly drag and dropped the files "PieChartViewController.xib", "PieChartViewController.h", "PieChartViewController.m".
2) I used this pie chart as it is.

It shows the graph perfectly. But still not go in the delegate method. 

I tried 3rd hint from you. That control goes in that method. as shown in screen shot. 

![screen shot 2016-01-22 at 11 57 47 am](https://cloud.githubusercontent.com/assets/3005149/12503976/7d0ae9be-c0ff-11e5-92e3-c1ff7178026c.png)

I really need this to be done. Any suggestion are highly accepted.

**Comment by jrkingray** [comment]
I have the same issue. 
My chart is rendered correctly and it has user interactions like tap and pinch zoom. Also chart is able to detect my tap gesture. But somehow    

```
func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: Highlight){
        print("###################")
    }
```
cannot be called

really need some help here

**Comment by jrkingray** [comment]
Also, what do you mean by adding bp
