### ISSUE TITLE
Pie chart is too small in tableview header view 

### ISSUE THREAD

**Issue by pavm035** [danielgindi/ios-charts#696]
Hi,

I'm using pie chart in uitableview head review but the chart is too much small than its frame size, am I missing anything?

Thanks
Pavan

**Comment by petester42** [comment]
A pie chart is supposed to be round so I believe that it tries to fit itself inside the frame but stay round. Try increasing the height of your header to make it bigger.

**Comment by pavm035** [comment]
@petester42 Thanks for the quick response, yes if i increase height it will work, but i wanted to know whether any work around to increase the diameter of the circle within the same height?

**Comment by petester42** [comment]
No because that would lead to clipping the circle. You could increase the chart frame until it looks like you want without increasing the height. But that's kind of a hack. 

Have you tried to change the chart padding or offset? I forget what it's called.

**Comment by pavm035** [comment]
Offset did not work, but increasing height actually making circle appearing bigger, i believe there would be some API actually which controls it, unfortunately i could not find right one yet

**Comment by danielgindi** [comment]
You can zero all the offsets - by disabling the legend like `pieChart.legend.enabled = false`.
Then if the pie is still too small for you - just adjust the size of the view.

**Comment by pavm035** [comment]
Thanks

**Comment by fsjack** [comment]
There's one point that @danielgindi didn't mention, that PieChartView leave space for the highlight selection slice, so if you don't need the highlight selection function you could also set selectionShift of data set to 0 to get rid of the blank padding.

**Comment by SylarRuby** [comment]
Hi @fsjack, what exactly do you mean? How to remove the padding and disable the slice highlight?

**Comment by Sebulec** [comment]
@SylarRuby It means, when you are preparing the chart data for example: 
`let pieChartData = PieChartData(dataSet: pieChartDataSet)`
then you have to set selectionShift property to 0:
`pieChartDataSet.selectionShift = 0`

**Comment by kevinOlivet** [comment]
Hi,
This worked for me:
setExtraOffsets(left: -15, top: -15, right: -15, bottom: -15)
Before:
![Screen Shot 2019-07-16 at 4 17 05 PM](https://user-images.githubusercontent.com/28767089/61326610-34669c00-a7e5-11e9-864c-ed8311057fb9.png)
After:
![Screen Shot 2019-07-16 at 4 17 58 PM](https://user-images.githubusercontent.com/28767089/61326656-4ba58980-a7e5-11e9-8010-84da4e78846f.png)

**Comment by FutureAndroidDeveloper** [comment]
If you dont need to maintain the selection of a piece of the diagram, you need to set the selection shift to 0. 
This will remove extra padding from the bottom and top of your chart.

```
let dataSet = PieChartDataSet(entries: entries)
dataSet.selectionShift = 0
```
