### ISSUE TITLE
Grid with constant width cells

### ISSUE THREAD

**Issue by noais** [danielgindi/ios-charts#697]
As you can see in the image, the last grid column width is shorter than the others. I believe that this happens because the rightAxis hides the chart content view. How can i fix this problem?

![img_0049](https://cloud.githubusercontent.com/assets/1105727/12490207/5045dad0-c06c-11e5-9c54-8f8fdbea67ca.jpg)

**Comment by liuxuan30** [comment]
It's because value '45' is beyond the contentRect right side, so its grid line is not drawn. I don't think it's a bug
you can disable rightAxis if you don't need it to get some space or not draw the grid line.

**Comment by noais** [comment]
Thank you @liuxuan30 you are right, I'm going to close the issue.
