### ISSUE TITLE
Realm error

### ISSUE THREAD

**Issue by taihe** [danielgindi/ios-charts#699]
In Xcode 7.2, An new Swift Project

After Drag ios-charts to Project

import Charts

Command+B

Error:

1、Realm.h
   Realm.h:21:9: 'Realm/RLMArray.h' file not found

2、Charts-Swift.h
     Charts-Swift.h:93:9: Could not build module 'Realm'

**Comment by petester42** [comment]
You have to manually install realm of you want it. Otherwise just delete that folder.

**Comment by taihe** [comment]
Delete which folder?

**Comment by petester42** [comment]
The realm folder

**Comment by taihe** [comment]
@petester42  I have resolved by CocoaPod install.

Thank you very much

**Comment by liuxuan30** [comment]
maybe we should highlight 'how to remove Realm' in README? It's there but seems not everyone seeing it

**Comment by danielgindi** [comment]
@liuxuan30 Yes I will!
