### ISSUE TITLE
demo crashes, and no swift examples?

### ISSUE THREAD

**Issue by MarkLyck** [danielgindi/ios-charts#7]
When running your ChartsDemo app. I'm presented with the following errors:

dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/mobile/Containers/Bundle/Application/9F8BD568-2130-48D8-9F62-E123EB2451BA/ChartsDemo.app/ChartsDemo
  Reason: image not found
(lldb) 

It's also written in Obj-c and not swift. Making it very difficult to translate for developers who havn't learned Obj-C to figure out how you're supposed to implement these charts?

**Comment by wonderdude** [comment]
Fixed the error, by adding the framework where appropriately in the project settings. But beyond being able to test the usability of the chart system, I still have no way of implementing them. And for some one who've never touched a line of code for other devices. The Android "getting started guide" is useless. While all the parameters and how to change the chart, is fairly easy to comprehend. The lack of knowledge with an example of setting up a single thing. Makes the rest of the information useless :(

**Comment by danielgindi** [comment]
The ObjC demo is very simple to understand, even if you do not know the
language. The API is exactly the same even though sometimes there are
square brackets around function calls...

You also should not try to develop for iOS without knowledge in ObjC as
that's the language the system is written in, and all of the frameworks too.

>

**Comment by petatester** [comment]
I have same problem than MarkLyck. When I run on simulator there are no problems, but I try to run ChartsDemo on iPhone, but always the same problem:

dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/mobile/Containers/Bundle/Application/2FB00EB8-7E0F-4121-801D-D40C71E29C04/ChartsDemo.app/ChartsDemo
  Reason: image not found

How add the framework correctly to run demo on iPhone?

Thanks.

**Comment by danielgindi** [comment]
Note that Xcode 6.3 is in beta, and compiles best for iOS 8.3
You could try making sure that your target has a reference to the library's
output

**Comment by petatester** [comment]
I'm trying removing and adding framework reference from target but same result. Did you try with iOS 8.2 or below?

**Comment by danielgindi** [comment]
No, I haven't, because it's compiled with a BETA version of Xcode.

**Comment by danielgindi** [comment]
I've found a fix for your "library not found" error, you should pull now and try.
It runs on iOS >= 7 now, even though compiling from Xcode 6.3b4

**Comment by moninet** [comment]
I try to use it in my swift project, but always get: 

dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: ----
  Reason: image not found

a short swift demo ot HowTo would be really usefull.

**Comment by jhays** [comment]
I was able to resolve this issue by adding the Charts framework under "Embedded Frameworks" as described here: 
http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

**Comment by danielgindi** [comment]
Friends, this is in the README under instructions. I hate answering the
same question again and again. When adding a framework in Xcode 6, you have
to add as an embedded framework.

‏בתאריך יום שישי, 1 במאי 2015, jhays <notifications@github.com> כתב:

**Comment by alfredangkasa** [comment]
Hi DanielGindi,

I tried to implement your swift code into my code but still failed. Can you give an example how to implement it using swift?

I mean, your code is using ObjC consuming the swift file.

Thanks

**Comment by manuelolmos** [comment]
Something might help that was not marked yet is that if you are working on an Objective-C project you have to set: ```embedded content contains swift code``` to YES
