### ISSUE TITLE
Background Colour Changes

### ISSUE THREAD

**Issue by Shredivan** [danielgindi/ios-charts#701]
Hi, I was wondering is their a way to change background colours? We're doing a chart for our app which is colour coded and have yet to find a way to implement the coloured backgrounds in our designs.

Thanks,
Dave

**Comment by liuxuan30** [comment]
What you mean by background color? UIView already has it. of course you can override drawRect to fill the color you want I guess

**Comment by Shredivan** [comment]
Sorry i should have been more specific, I meant to colour of the background of the graph itself not the data been on it. I've attached an image to show you what I mean.

<img width="1119" alt="screen shot 2016-01-25 at 5 01 27 p m" src="https://cloud.githubusercontent.com/assets/14276542/12557988/516f7918-c385-11e5-8830-3286c610a81e.png">

**Comment by liuxuan30** [comment]
alright, if you are talking about the screenshot, it requires a lot of customization...
But it should not be hard:
the whole rect is defined as `contentRect`, so the bounding coordinates is known; 
You first figure out, how many rects there and what's the sub rect frame value; and then you simply set the color and render it like
```swift
CGContextSetFillColorWithColor(context, subRectColor.CGColor)
CGContextFillRect(context, subRect)
```
you can wrap it in a function, and call it in `drawExtras` or some where else.

**Comment by BilalSalam** [comment]
Hello Can you add the code that shows the green color
