### ISSUE TITLE
I couldn't find Charts.xcodeproj

### ISSUE THREAD

**Issue by KitajimaMasaru** [danielgindi/ios-charts#705]
I'm trying to use ios-charts in my app written in Objective-C.

First, I downloaded ios-charts from GitHub and read the README.md and found I could use cocoapods to install as it says "pod 'Charts'".

So I added this to my Podfile like
platform :ios, "9.0"
use_frameworks!

target 'chartTest' do
pod 'FMDB', '~> 2.0'
pod 'Charts', '~> 2.1'
end

And I did pod install, and get Charts in my Pods folder.

But I couldn't find Charts.xcodeproj.

Do I need to add it from ios-charts-master which I downloaded from GitHub manually?

**Comment by liuxuan30** [comment]
http://stackoverflow.com/questions/34970326/how-can-i-import-charts-xcodeproj-using-cocoapods
