### ISSUE TITLE
I can't change the default grey background on the line chart 

### ISSUE THREAD

**Issue by YHSX88** [danielgindi/ios-charts#706]
Guys can somebody point me how to change the colour mentioned in the title.

And something else to mention here is that i think the method "setHighLightColor(UIColor)" is not present in the API or at least I couldn't find it.

**"Line-, Bar-, Scatter-, Bubble- & CandleDataSet (below mentioned methods can be used for any of the mentioned DataSet classes)**

**setHighLightColor(int color): Sets the color that is used for drawing the highlight indicators. Don't forget to resolve the color using getResources().getColor(...) or Color.rgb(...) (or simply Color.BLACK)."**
![screen shot 2016-01-25 at 00 34 10](https://cloud.githubusercontent.com/assets/16823745/12539452/74a088b2-c2fb-11e5-8d90-ba5ee30998fe.png)

**Comment by liuxuan30** [comment]
1. use `gridBackgroundColor` or `UIView.backgroundColor`
2. use set.highlightColor. Have no idea why you are saying setHighLightColor if it does not exist

**Comment by YHSX88** [comment]
all cool, thank you very much
