### ISSUE TITLE
how to get a custom legend

### ISSUE THREAD

**Issue by stardust139** [danielgindi/ios-charts#710]
I subclass the ChartLegendRenderer , but how to use it. I notice that  the legendRenderer is readonly
```
/// \returns  the Legend object of the chart. This method can be used to get an instance of the legend in order to customize the automatically generated Legend.
@property (nonatomic, readonly, strong) ChartLegend * __nonnull legend;

/// \returns  the renderer object responsible for rendering / drawing the Legend.
@property (nonatomic, readonly, strong) ChartLegendRenderer * __null_unspecified legendRenderer;
```

**Comment by liuxuan30** [comment]
@danielgindi is this another class you want to make public? 
@stardust139 the bottom line is, you have to source code so you can modify it right now to your rendrer :)

**Comment by stardust139** [comment]
yeah， I found that . but a little precious to this

**Comment by vojto** [comment]
`_legendRenderer` is set `internal`, so you can't change its value from a subclass... Looking for other solutions...

**Comment by stardustWK** [comment]
_legendRenderer is not  a @objc  property  in Swift 4.0, so KVC is not work
