### ISSUE TITLE
how to disable zooming of graph on double click?

### ISSUE THREAD

**Issue by anjusr** [danielgindi/ios-charts#716]
Hey I m implementing grouped bar graph and when i double click on it, Its zooming I don't want that. Can anyone please tell me how to disable it.

**Comment by arjunnayak** [comment]
In Objective C, I've used: 
`[_chartView setDoubleTapToZoomEnabled: NO];`

**Comment by danielgindi** [comment]
And in Swift of course, `chartView.doubleTapToZoomEnabled = false`. As simple as that :-)
