### ISSUE TITLE
Margin insets not changing during zoom when formatter changes output width

### ISSUE THREAD

**Issue by MartinPajak** [danielgindi/ios-charts#72]
I created my own numberformatter for yAxis labels like this:

        var axisFormatter = NSNumberFormatter()
        axisFormatter.locale = NSLocale.currentLocale()
        axisFormatter.numberStyle = NSNumberFormatterStyle.DecimalStyle
        axisFormatter.usesGroupingSeparator = false
        axisFormatter.generatesDecimalNumbers = true

Later then, when I zoom into the data so that the formatter changes output width for example from 49 to 49.5 the margin of the chart doesn't change until I rotate to landscape/portrait. Without rotating there seems to be no chance to get the numbers full visible.

**Comment by danielgindi** [comment]
@PhilJay do you think we should recalculate the X axis width for each frame? or can we know that the axis has changed?

**Comment by danielgindi** [comment]
@PhilJay maybe we should call calculateOffsets() when done zooming/dragging, so the Y-Axis width will be recalculated according to the visible labels

**Comment by PhilJay** [comment]
Yes that could be an option :-)
I hope that the performance overhead is not too big tough

**Comment by danielgindi** [comment]
If we're doing it only when finishing a zoom - that would not have a
performance impact, it will work like when zooming in on maps - they zoom
in the original rasterized data, and when finishing zoom they re-render the
vector data
