### ISSUE TITLE
Draw a Line that connects dots in Scatter Chart (Simulate Line Chart not equidistant)

### ISSUE THREAD

**Issue by santibernaldo** [danielgindi/ios-charts#720]
Hi!

Is there a way to draw a line between all the dots in a scatter Chart? And fill the area with a color? Like in the example project with the Line Chart. I would like to simulate a Line Chart with no Equidistant spaces/padding between the points of the xAxis.

I only want to pass an array of values for the yAxis, and thats why Im trying to figure this out.

Thanks

**Comment by liuxuan30** [comment]
you just have to simulate `drawLinear` if you already draw the dots. But it's not as easy as it looks like, considering zoom/scale
