### ISSUE TITLE
2.2.0 not published yet

### ISSUE THREAD

**Issue by iostalk** [danielgindi/ios-charts#723]
As the title...?

```
[!] Unable to satisfy the following requirements:

- `Charts (= 2.2.0)` required by `Podfile`
```

**Comment by moorecode** [comment]
Having the same problem, I looked on the [cocoapods](https://cocoapods.org/pods/Charts) website and the listed version is still 2.1.6?

**Comment by petester42** [comment]
The pod spec needs to be updated to handle the realm subspec. I'll fix it and push it to cocoapods sometime tomorrow.
