### ISSUE TITLE
X-Axis at bottom of chart?

### ISSUE THREAD

**Issue by UberJason** [danielgindi/ios-charts#727]
Apologies if this is an obvious question. I noticed that all the graphs have the Y-axis on the left, and the X-axis at the top. But a lot of standard charts tend to put the X-axis on the bottom. Is there any API to set that? I noticed in the [MPAndroidChart API](https://github.com/PhilJay/MPAndroidChart/wiki/XAxis-(XLabels)), there's a setPosition function, but that doesn't seem to be included in ChartXAxis in iso-charts - instead there's a labelPosition property which seems only to relate to the position of the label relative to the X-axis.

**Comment by matheusaguiardev** [comment]
I do not know if I understood your question well, but on the charts-ios, It can be solved like this.
` lineChartView.xAxis.labelPosition = XAxis.LabelPosition.bottom`
