### ISSUE TITLE
LineChartData omits and misaligns values when data isn't continuous

### ISSUE THREAD

**Issue by UberJason** [danielgindi/ios-charts#728]
Hi,

I'm not sure if this is a bug or intended behavior, but it wasn't intuitive for me at least. Suppose you have the following array of **eight** ChartDataEntries, which is just entries from 0 to 9 but missing values for xIndex = 3 and 6:

```
let dataSet = [
ChartDataEntry(value: 0, xIndex: 0),
ChartDataEntry(value: 1, xIndex: 1),
ChartDataEntry(value: 2, xIndex: 2),
ChartDataEntry(value: 4, xIndex: 4),
ChartDataEntry(value: 5, xIndex: 5),
ChartDataEntry(value: 7, xIndex: 7),
ChartDataEntry(value: 8, xIndex: 8),
ChartDataEntry(value: 9, xIndex: 9),
]
```
The data is missing values for xIndex = 3 and 6. If my xVals array matches that set of ChartDataEntries exactly:

```
let xVals = ["0", "1", "2", "4", "5", "7", "8", "9"]
let data = LineChartData(xVals: xVals, dataSet: dataSet)
chartView.data = data
```
Then the chart comes out showing only **six** values which are misaligned:

![bad](https://cloud.githubusercontent.com/assets/5779307/12707817/9d5ee8a0-c866-11e5-8fdd-ad94ae447a25.PNG)

On the other hand, if my xVals array purposely includes the missing two xIndex values:

```
let xVals = ["0", "1", "2", "3", 4", "5", "6", "7", "8", "9"]
let data = LineChartData(xVals: xVals, dataSet: dataSet)
chartView.data = data
```

Then the chart comes out the way I expect it to, with eight values properly aligned:

![good](https://cloud.githubusercontent.com/assets/5779307/12707845/11d07b7c-c867-11e5-948e-acb72cab9a67.PNG)

My question is, is this a bug or intended functionality? I would expect these two graphs to match. In the first case, I would expect that the graph would be able to interpolate the gaps between the labels (and just leave them blank, if necessary). Even though the xVals array of labels alone doesn't inform where the gaps should go, the data set shows where the gaps are.

**Comment by liuxuan30** [comment]
This is intended. If you don't want a value at specific xIndex, simply add xIndex without any data entry for it.

**Comment by UberJason** [comment]
Is this documented somewhere that I've missed it? Personally I find that very unintuitive.

**Comment by liuxuan30** [comment]
In old issues, while talking for nil value. I think it's not intuitive, but desinging like this would have less issues. The idea is, the distance on x axis is equal, based on index. Because the line chart does not know how you want to ignore it. Using index is straightforward.
