### ISSUE TITLE
BarChartView when the value is negative the valuelabel is outside the AxisLine

### ISSUE THREAD

**Issue by jasonxiaochao** [danielgindi/ios-charts#729]
![chart](https://cloud.githubusercontent.com/assets/10300497/12712447/63285f70-c903-11e5-8c82-1a16ba2da21a.png)
 func setupBarChart(){
        let lineZero = ChartLimitLine(limit: 0)
        lineZero.lineColor = UIColor.grayColor()
        lineZero.lineWidth = 0.5
        //lineZero.lineDashLengths = [5,5]
        lineZero.labelPosition = ChartLimitLine.ChartLimitLabelPosition.RightTop
        
        barChart.delegate = self;
        barChart.drawValueAboveBarEnabled = true
        barChart.noDataText = ""
        barChart.descriptionText = "";
        barChart.noDataTextDescription = "";
        barChart.userInteractionEnabled = false
        barChart.dragEnabled = false
        barChart.doubleTapToZoomEnabled = false
        
        barChart.maxVisibleValueCount = 60;
        barChart.pinchZoomEnabled = false;
        barChart.drawBarShadowEnabled = false;
        barChart.drawGridBackgroundEnabled = false;
        
        barChart.leftAxis.drawLabelsEnabled = false
        barChart.leftAxis.drawGridLinesEnabled = false;
        barChart.leftAxis.drawAxisLineEnabled = false
        
        
        barChart.xAxis.spaceBetweenLabels = 0;
        barChart.xAxis.drawGridLinesEnabled = false;
        barChart.xAxis.drawLabelsEnabled = true
        barChart.xAxis.drawAxisLineEnabled = true
        barChart.xAxis.labelPosition = ChartXAxis.XAxisLabelPosition.Bottom
        barChart.xAxis.labelTextColor = UIColor.blackColor()
        barChart.xAxis.labelFont = UIFont.systemFontOfSize(10)
        
        barChart.rightAxis.drawGridLinesEnabled = false;
        barChart.rightAxis.drawLabelsEnabled = false
        barChart.rightAxis.drawAxisLineEnabled = false
        
        barChart.legend.enabled = false;

        barChart.rightAxis.addLimitLine(lineZero)
        
        setMoneyBarData()
    }
    
    func setMoneyBarData(){
        
        var xVals :[String] = []
        var yVals = [BarChartDataEntry]()
        var colors = [UIColor]()
                xVals.append("12-21")
                yVals.append(BarChartDataEntry(value: 65534, xIndex: 0))
            
                colors.append(UIColor.redColor())
        xVals.append("12-22")
        yVals.append(BarChartDataEntry(value: 65534, xIndex: 1))
        
        colors.append(UIColor.redColor())
        xVals.append("12-23")
        yVals.append(BarChartDataEntry(value: 12354, xIndex: 2))
        
        colors.append(UIColor.redColor())
        xVals.append("12-24")
        yVals.append(BarChartDataEntry(value: 2000, xIndex: 3))
        
        colors.append(UIColor.redColor())
        xVals.append("12-25")
        yVals.append(BarChartDataEntry(value: -67573, xIndex: 4))
        
        colors.append(UIColor.greenColor())
        
        
        
        let dataSet = BarChartDataSet(yVals: yVals)
        
        dataSet.colors =  colors
        dataSet.barSpace = 0.5
        
        //dataSet.axisDependency = ChartYAxis.AxisDependency.Left
        
        let data = BarChartData(xVals: xVals, dataSet: dataSet)
        
        barChart.data = data
    }

**Comment by liuxuan30** [comment]
Dup to  #481, and in  #481, there is a temp solution, you could try.
