### ISSUE TITLE
What files exactly should I drag to my project to make it work on iOS 7.0?

### ISSUE THREAD

**Issue by xinatanil** [danielgindi/ios-charts#73]
I would suggest you to make it clear readme what .swift  files exactly should developers drag to their project to make it work on iOS 7.0.
I created project in Xcode 6.3, with support of iOS 7.0. Readme cleary says that I need to drag .swift files to my project. I assumed, that I need to simply drag "Classes" folder but that didn't do the trick, I got tons of compiler errors, which can be fixed by importing UIKit and CoreGraphics.
Trying to drag Charts.xcodeproj doesn't help either, even if I drag corresponding "Classes" and "Supporting files" folders.

**Comment by AlBirdie** [comment]
You need to add ALL the Swift files from the "Classes" directory into your project.
