### ISSUE TITLE
Multi colors for linechart's circles

### ISSUE THREAD

**Issue by phuonglm86** [danielgindi/ios-charts#730]
How can I set multi colors for some circles of a line chart. Like this graph.
<img width="788" alt="screen shot 2016-02-02 at 2 55 11 pm" src="https://cloud.githubusercontent.com/assets/8994583/12743005/29309ade-c9bd-11e5-8071-f6d27193b564.png">

**Comment by siideffect** [comment]
Did you try the dataset property circlecolors? U must provide an array of colors for the circle
dataset.circleColors = [UIColor.whiteColor(),UIColor.blackColor()]

I don't know the programming language you working on but you have to look at dataset properties

**Comment by liuxuan30** [comment]
good job @siideffect

**Comment by phuonglm86** [comment]
@siideffect: array of colors only help you create circlecolors with this: white, black, white, black, white, black and so on... What if I told you that, how to present circlecorlors like this: white, white, black, white, .....

**Comment by jruipeixoto** [comment]
@phuonglm86 you can use an array of UIColors with the same amount of elements as you used to set the chart's data.

**Comment by ArsenalMyth** [comment]
hey, brother, I also need this.  How did you do that ?   I need the points colors are depend by the datas, so the circleColors colors array didn't work. You had solve this ?

**Comment by phuonglm86** [comment]
Sadly, I did not.
