### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by AmandineDB** [danielgindi/ios-charts#731]
Hello, 

I using Charts.framework in my objC Project. I had read and follow the readMe for integrated the Chart project. 

I have this error : 

> Charts.framework/Charts
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC6Charts13LineChartView", referenced from:
      objc-class-ref in StatsPriceView.o
ld: symbol(s) not found for architecture arm64

> 

and when I use `xcrun lipo -info Charts`
I have this : 

> Non-fat file: Charts is architecture: armv7

> 

Could-you help me please?

Have a good day :)

Amandine

**Comment by liuxuan30** [comment]
#681
