### ISSUE TITLE
Issue in valueFormatter

### ISSUE THREAD

**Issue by jiemi** [danielgindi/ios-charts#732]
130000 -> $130k
12000 -> $12k
10000000 ->$10M
it seems NSNumberFormatter can't  achieve it?

**Comment by danielgindi** [comment]
It can. There are multiple ways to do that, and stackoverflow is the place for such questions...
Anyway, here's one: http://stackoverflow.com/questions/11097064/nsnumberformatter-from-13000-to-13k

**Comment by jiemi** [comment]
thanks
