### ISSUE TITLE
Using BarChartDataSet default initializer causes a crash

### ISSUE THREAD

**Issue by natethegreat44** [danielgindi/ios-charts#734]
Hi,
I just tried using version 2.2.1 and my app crashed. I tracked it down to initializing BarChartDataSet with the default initializer.

i.e. in swift, BarChartDataSet(), or in objc [[BarChartDataSet alloc] init]

The error is:
fatal error: unexpectedly found nil while unwrapping an Optional value

Happens on line 57 of ChartDataSet.swift:
public var yVals: [ChartDataEntry] { return _yVals }

I love this library... thank you!
Nate

**Comment by liuxuan30** [comment]
well.. You could use other init methods right now. seems _yVals is not inited if you simply call init()

**Comment by liuxuan30** [comment]
@danielgindi the init method does not initialize _yVals in `init()` or `init(label: String?)`
so either we initialize them there, or we make _yVals has default values. What do you prefer

**Comment by liuxuan30** [comment]
lol, why you don't use default values? same code twice.. maybe more
