### ISSUE TITLE
is there a way to create a date scale for the x axis?

### ISSUE THREAD

**Issue by skrite** [danielgindi/ios-charts#736]
i am trying to chart the pressure of a transducer over the last week. However the transducer does not report at regular time intervales and I need to chart to reflect that. is there a way to make a date scale on the XAxis that will show these points this way?  I have included a version of the chart we use on our web page.
![draw_quick_chart](https://cloud.githubusercontent.com/assets/176528/12789962/9d203b90-ca65-11e5-9a38-0236c6eb62fa.png)

**Comment by liuxuan30** [comment]
Simple answer: you should generate full date values for xVals, and not insert data entry for those dates that don't have data.
Complicated answer: this has been asked and not having a good solution yet.

**Comment by skrite** [comment]
ok, thanks very much

**Comment by davigr** [comment]
@skrite @liuxuan30 Hi, do I need to create multiple datasets to implement his feature? (1 for the chart, 2 for the fake xAxis labels) I tried to create 2 data sets and merge them. This is my code:

//1 data set:
`var set1DataEntry: [ChartDataEntry] = [.......]`
`var primaryDataSet: [LineChartDataSet] = []`
...
`let set1 = LineChartDataSet(values: set1DataEntry, label: nil)`

//2 data set
`var set2DataEntry: [ChartDataEntry] = [empty]`
`let set2 = LineChartDataSet(values: set2DataEntry, label: nil)`

//merge sets
 `primaryDataSet.append(set1)`
 `primaryDataSet.append(set2)`
 `let lineChartData = LineChartData(dataSets: primaryDataSet)`
 `lineChartView.data = lineChartData`

//format labels
lineChartView.xAxis.valueFormatter = IndexAxisValueFormatter(values: [labels for set1 + fake labels])

As a result this code doesn't show fake set2, only set1. Could you please help me with that, what am I doing wrong?

**Comment by davigr** [comment]
> Simple answer: you should generate full date values for xVals, and not insert data entry for those dates that don't have data.

Do I need to append my dataEntries with (0,0) values for those dates that don't have data?

**Comment by davigr** [comment]
I solved the issue, just created two data sets, and fill second data sets with entries started x value from the last index of 1set.
