### ISSUE TITLE
Getting x,y values of points in LineChart

### ISSUE THREAD

**Issue by leonidster** [danielgindi/ios-charts#739]
Hi,

First of all, thank you for your great great project.

I'm using a LineChart and looking for an easy way to get the x/y of the last point,

in order to draw a customizable static bubble above/underneath it (not on Highlighting).

What is the easiest way to get these values?

Thanks :)

**Comment by liuxuan30** [comment]
I guess you have to first get the last point x, y and use delegate or you add a new method to draw the custom shape you want in `drawExtras`

**Comment by leonidster** [comment]
@liuxuan30 Thanks for reply. My question is how to get these values. I have the LineChart object, what is the method to get the last point x,y? I'd appreciate an example.

**Comment by liuxuan30** [comment]
I don't think currently there is method to return the pixel x,y to you. You have to change the code to get it, by delegate, that's the easiest one. Or you can walk through the code to calculate it directly.

**Comment by danielgindi** [comment]
Actually you can use the transformer for this. You give it a point on the chart which represents an xIndex and a yValue, and in return you get a pixel based x/y

**Comment by liuxuan30** [comment]
Yep but the left/right transformer is internal - so in some cases we cannot use it directly. 
Consider a API to provide pixel x,y? 

I used to write a delegate to get the x, y.
