### ISSUE TITLE
Display dataSet labels on axis for horizontal bar

### ISSUE THREAD

**Issue by timothybrandspencer** [danielgindi/ios-charts#741]
I can't find a way of getting the dataSet labels to display on the left axis of my horizontal bar chart.

Here is the chart: 

![labels](https://cloud.githubusercontent.com/assets/350228/12849498/d4eaff70-cc17-11e5-9901-0091b5ccc8b2.png)

For each of the bars, I would like to display a label on the axis, in addition to the main label.

Is this possible? Many thanks!

**Comment by liuxuan30** [comment]
If you want to display the data set label within the area of 15YO/13YO/11YO, you have to customize x axis renderer's draw labels method. 
It's by design that x axis just show up x axis value, without involving data sets.
