### ISSUE TITLE
Display values outside of the piechart

### ISSUE THREAD

**Issue by smilydronavalli** [danielgindi/ios-charts#743]
Hi,

It is not a issue.I want to know that whether it is possible or not.
![r6n4k](https://cloud.githubusercontent.com/assets/14346725/12887117/36815996-ce98-11e5-921b-192664622278.png)

is it possible to display like above image.

Please answer to my question.

Thanks in advance

**Comment by liuxuan30** [comment]
I would say it's possible as long as you know how to customize it. Such stuff requires you to write some code to get what you want. The framework cannot satisify all features, right?

**Comment by danielgindi** [comment]
I actually wanted to implement this feature in the past but hadn't had the time. It requires writing an algorithm that will prevent clashes between labels.

**Comment by maryamfekri** [comment]
You can set value positions to outsideSlice :
```
        pieChartDataSet.yValuePosition = .outsideSlice
        pieChartDataSet.xValuePosition = .outsideSlice
```
