### ISSUE TITLE
Remove border around linechart with gradient fill

### ISSUE THREAD

**Issue by timaktimak** [danielgindi/ios-charts#747]
I want to have a gradient fill for a linechart with no border around it. I basically copied the code from the obj-c demo Line Chart 1 (only wrote it using swift), but it draws a border around the fill.

I have (notice the green border, I want the left, right, bottom lines removed):
<img width="566" alt="screen shot 2016-02-10 at 16 14 33" src="https://cloud.githubusercontent.com/assets/7345940/12948292/2a4b87de-d012-11e5-938f-f8d9ac591576.png">

I want it like this (with no borders on the left, right, and bottom):
<img width="354" alt="screen shot 2016-02-10 at 16 16 16" src="https://cloud.githubusercontent.com/assets/7345940/12948312/4bd5a1c8-d012-11e5-871b-cc395e3c7737.png">

 Is there a way to do it in Swift that I am missing? Please help.

**Comment by liuxuan30** [comment]
Seems it's about drawCubic will introduce this border, while drawLinear does not have it. 
There is slightly difference for drawCubic. It will draw a sub path
```
        var pt1 = CGPoint(x: CGFloat(to - 1), y: fillMin)
        var pt2 = CGPoint(x: CGFloat(from), y: fillMin)
        pt1 = CGPointApplyAffineTransform(pt1, matrix)
        pt2 = CGPointApplyAffineTransform(pt2, matrix)
        
        CGPathAddLineToPoint(spline, nil, pt1.x, pt1.y)
        CGPathAddLineToPoint(spline, nil, pt2.x, pt2.y)
        CGPathCloseSubpath(spline)
```
@danielgindi you think this a bug or by design?

**Comment by danielgindi** [comment]
It does not draw a subpath - it adds the path to the context in order to draw.
There shouldn't be any borders around the fill.
If you see borders only in your code - then maybe your gradient is not configured correctly and has "borders", colors stretching past the beginning/end colors etc.

**Comment by liuxuan30** [comment]
@danielgindi I use ChartsDemo, and set set1.drawCubicEnabled = YES; and I could see it has bounding borders, while linear drawing not have the bounding border
![dash](https://cloud.githubusercontent.com/assets/4375169/13273874/b7828588-dae1-11e5-8625-072d0b07680f.png)

**Comment by danielgindi** [comment]
This screenshot is cubic- and does not have bounding borders... it has the line above the fill- which you can disable in many ways (transparent color, for example)

**Comment by liuxuan30** [comment]
@danielgindi I think the issue is, my screenshot has dash lines around the whole fill area, while linear line does not have, on right, left and bottom:
![no](https://cloud.githubusercontent.com/assets/4375169/13307408/f3ac0042-dba5-11e5-8c19-4e3d558fbdbc.png)
![have](https://cloud.githubusercontent.com/assets/4375169/13307412/f8e198a6-dba5-11e5-91bf-67319672cbbb.png)
How can I disable it? I simply enable draw cubic, and the lines are there.

**Comment by danielgindi** [comment]
I actually found where this issue might be coming from - let me know if this fixed it.

**Comment by liuxuan30** [comment]
the fix is positive on my side.

**Comment by danielgindi** [comment]
:+1:
