### ISSUE TITLE
Line charts have unintended breaks when next or previous point not visible.

### ISSUE THREAD

**Issue by hugey010** [danielgindi/ios-charts#748]
I've seen a few issues and even this PR for fixing this.  PR #713 does a good job explaining this bug. Issue #280 is describing this as a feature but just because the point isn't visible doesn't mean the line shouldn't be drawn.

I have a working fork here: https://github.com/DuetHealth/ios-charts/tree/lines_missing  based on #713 . I will make a PR if it will be considered. I think the number of people having issues with this speaks for itself.

**Comment by liuxuan30** [comment]
#280 is different, it's asking for feature 'breaking lines by intention'.
#713 is a bug that when you zoom and scroll the line chart, sometimes the line will disappear.
I am not sure what you want to solve, but you could file a PR and provide some screenshots, etc to help easy understanding the issue you try to solve.
