### ISSUE TITLE
Can you give me a swift's demo

### ISSUE THREAD

**Issue by wpf123** [danielgindi/ios-charts#75]
Thanks for your ios-charts, it' very beautiful. Can you give me a swift's demo, because i have never studied Obj-C.

**Comment by danielgindi** [comment]
No.

**Comment by AlBirdie** [comment]
For the record, the library is written in Swift, so you don't need to use ObjC.

**Comment by danielgindi** [comment]
There are many people coming here asking me to "give" them Swift demos, to teach them Swift, and the next one will probably ask me to give him a full app for free.
I'm starting to get sick of that insolence...
