### ISSUE TITLE
PieChart setMaxAngle

### ISSUE THREAD

**Issue by McGr** [danielgindi/ios-charts#757]
Has this method been implemented for the PieChart? I can't find it in the source code.
Is there some other way to produce a piechart that does not have an entire 360 sweep?

Thanks Mike.

**Comment by McGr** [comment]
I worked around this by including a dummy slice in the same color as the background and a slice size computed to match the excluded angles

**Comment by danielgindi** [comment]
You could even use a transparent color :-)

**Comment by McGr** [comment]
Yup - Thats a better solution - Thanks!
