### ISSUE TITLE
Error on RadarChart (drawFilledEnabled set to true)

### ISSUE THREAD

**Issue by julianrichie** [danielgindi/ios-charts#760]
hi i'm receiving this error  when using RadarChart and sets the drawFilledEnabled to true.
i have no issue with this in the previous build of ios-charts

![screen shot 2016-02-17 at 6 27 36 pm](https://cloud.githubusercontent.com/assets/1916616/13108203/39aa9016-d5a4-11e5-8a18-99e3f0c89644.png)

**Comment by liuxuan30** [comment]
can you provide more details, how to reproduce it, especially with ChartsDemo?
I see radar chart data set do implemented:
```swift
    public var drawFilledEnabled = false
    
    public var isDrawFilledEnabled: Bool
    {
        return drawFilledEnabled
    }
```

**Comment by julianrichie** [comment]
![screen shot 2016-02-18 at 1 39 12 pm](https://cloud.githubusercontent.com/assets/1916616/13135642/3e705bca-d645-11e5-8725-b554ec9c7de5.png)
![screen shot 2016-02-18 at 1 40 24 pm](https://cloud.githubusercontent.com/assets/1916616/13135644/44c8013a-d645-11e5-8f61-a73f759c892d.png)

**Comment by liuxuan30** [comment]
will you be able to debug more, or try the source code framework? Have no idea. ChartsDemo works fine though.

**Comment by danielgindi** [comment]
This seems like a compiler bug. Try latest Xcode version, and do a **Clean** build.
