### ISSUE TITLE
Ability to set linechart with fixed amount of x values shown and pan to other data points

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#762]
It would be great to have a feature where when you create a linechart with 10 data points, when rendering you focus on only the last 5 data points. When a user then swipes or pans to the left, the chart will pan to the other data points on the chart.

For example, there are 8 total points on the chart below, but there will be a setting when loading to only show 4, and then a user can pan/scroll to left to show other data points.
![image](https://cloud.githubusercontent.com/assets/280426/13147939/0e09d932-d629-11e5-9440-7757be0acb90.png)

**Comment by danielgindi** [comment]
There is. You use the `viewPortHandler` to change the viewport before showing.

**Comment by osolano** [comment]
Thank you @danielgindi  I will try it out.

**Comment by ravitejaobelisk** [comment]
Hi @osolano , I'm also trying to acheive

**Comment by ravitejaobelisk** [comment]
Hi @osolano , I'm also trying to get the same effect. If you got the solution please share it here. I have tried looking into `viewportHandler` but I was not able to get it to work.

**Comment by ravitejaobelisk** [comment]
@osolano Nevermind, I found it, using `setVisibleXRange(minXRange, maxXRange)` solved my issue

**Comment by liuxuan30** [comment]
@ravitejaobelisk take a look at `refresh()`, `translate()`, in view port handler. There is a method called `centerViewPort()`. These should be similar purpose.

**Comment by ravitejaobelisk** [comment]
@liuxuan30  got it... Many thanks
