### ISSUE TITLE
Tests failing after startAtZero was removed

### ISSUE THREAD

**Issue by petester42** [danielgindi/ios-charts#767]
I just looked into why the tests are failing and it seems to have happened [here](https://github.com/danielgindi/ios-charts/tree/f9ace6a9f4bb565866be622ffda2d293b799bfac) when `startAtZero` was deprecated. 

Setting the `customAxisMin = 0.0` in the tests does kind of make it look like it should but there is still an offset. @danielgindi any ideas?

**Comment by danielgindi** [comment]
Yes it seems like there's some kind of residue. Weird since `startAtZero` was effectively setting `customAxisMin` to `0.0`, just with a lot more code...
I'm looking into it

**Comment by danielgindi** [comment]
We can see the problem here:

<img width="369" alt="screen shot 2016-02-20 at 10 36 58 pm" src="https://cloud.githubusercontent.com/assets/366926/13199042/7534b082-d822-11e5-8ec1-8d62e60eac51.png">

@PhilJay I think that this originates here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java#L358
Do you know if we still need this?
This used to always render "a little bit more" of the grid - except when `startAtZero` was enabled, which meant we want to trim the axis there.
Maybe we should introduce a new property for how much more we want to draw past the min/max? Or just a boolean?

**Comment by PhilJay** [comment]
Yes, we draw a "little bit more" in that case. But that case should only occur if the range is 0 and hence all values in the dataset are equal. If that is not the case, this should not be an issue.

**Comment by danielgindi** [comment]
@PhilJay Yes it seems that that's not the source of the issue... But it still happens, on the Android side also.

Try to replace the code in `BarChartActivity` with this:

```java

        mChart = (BarChart) findViewById(R.id.chart1);

        // Sample data
        float[] values = new float[]{8, 104, 81, 93, 52, 44, 97, 101, 75, 28,
        76, 25, 20, 13, 52, 44, 57, 23, 45, 91,
        99, 14, 84, 48, 40, 71, 106, 41, 45, 61};

        ArrayList<BarEntry> entries = new ArrayList<>();
        ArrayList<String> xValues = new ArrayList<>();

        for (int i = 0; i < values.length; i++)
        {
            entries.add(new BarEntry(values[i], i));
            xValues.add(Integer.toString(i));
        }

        BarDataSet dataSet = new BarDataSet(entries, "Bar chart unit test data");

        mChart.setData(new BarData(xValues, dataSet));
```

**Comment by danielgindi** [comment]
Okay after further investigation - two things happened:

1. I was so tired that I didn't notice I've added the `customAxisMin` when testing after the `setData`, without calling `notifyDataSetChanged` or `calcMinMax` or anything like that.
2. Even when setting `customAxisMin` correctly - there's a slight difference in drawing the axis. Like the scale changed by a fraction. I'm still looking into the cause of this - as nothing should have actually changed.

**Comment by danielgindi** [comment]
So more info: axis ranges are multiplied by the spacing factor. But when there was `startAtZero` as a standalone property - the range was subtracted `0.0` instead of `min`.
It seems like the `range` does not take into account the `customAxisMin` (or max)

**Comment by danielgindi** [comment]
@PhilJay I've created a PR in MPAndroidChart
