### ISSUE TITLE
How to control which entries on xAxis be shown?

### ISSUE THREAD

**Issue by imgabe** [danielgindi/ios-charts#768]
Well, I have many entries in the xAxis， for example :

```
9:30
9:31
9:32
...
10:00
10:01
...
11:30
```

But I only want to show 9:30 and 10:30 and 11:30 on the xAxis, the entries are equidistant and must be the chosen ones, how to do with it ? Thanks

**Comment by imgabe** [comment]
By the way, the last entry label on xAxis(11:30) always invisible, how to make it visible?

**Comment by liuxuan30** [comment]
the x axis labels are controlled by some logic called axisLabelModulus. if you let ios-charts calculates it, it will calculate the axisLabelModulus to a proper value to let the labels displays properly. If you use resetLabelsToSkip(), then you should be able to show 9:30, 10:30, etc.

About the last one disappearing, try avoidFirstLastClippingEnabled = true.
```swift
    /// the modulus that indicates if a value at a specified index in an array(list) for the x-axis-labels is drawn or not. Draw when `(index % modulus) == 0`.
    public var axisLabelModulus = Int(1)

    /// if set to true, the chart will avoid that the first and last label entry in the chart "clip" off the edge of the chart
    public var avoidFirstLastClippingEnabled = false

    /// Sets the number of labels that should be skipped on the axis before the next label is drawn. 
    /// This will disable the feature that automatically calculates an adequate space between the axis labels and set the number of labels to be skipped to the fixed number provided by this method. 
    /// Call `resetLabelsToSkip(...)` to re-enable automatic calculation.
    public func setLabelsToSkip(count: Int)
    {
        ...
    }
```

**Comment by danielgindi** [comment]
That's not the first/last that's clipped explicitly - but the whole drawing
region. That should be controlled using a different flag...
בתאריך יום ב׳, 22 בפבר׳ 2016 ב-17:01 מאת Gabe Tse <notifications@github.com

**Comment by vrobles2008** [comment]
@liuxuan30 How do you go about changing the axisLabelModulus = Int(1) ?

**Comment by vrobles2008** [comment]
@liuxuan30 How would I use the resetLabelToSkip() method?
