### ISSUE TITLE
How to set position label radar chart. in Swift .

### ISSUE THREAD

**Issue by aomboy30** [danielgindi/ios-charts#770]

**Comment by liuxuan30** [comment]
please be more specific

**Comment by aomboy30** [comment]
EX:   ChartLegend *l = _chartView.legend;
          l.position = ChartLegendPositionRightOfChart; 
  
 error ChartLegendPositionRightOfChart no class in swift

**Comment by liuxuan30** [comment]
@objc
    public enum ChartLegendPosition: Int
    {
        case RightOfChart
        case RightOfChartCenter
        case RightOfChartInside
        case LeftOfChart
        case LeftOfChartCenter
        case LeftOfChartInside
        case BelowChartLeft
        case BelowChartRight
        case BelowChartCenter
        case AboveChartLeft
        case AboveChartRight
        case AboveChartCenter
        case PiechartCenter
    }
it's there.

**Comment by aomboy30** [comment]
Thank you for helping me.

**Comment by aomboy30** [comment]
![screen shot 2559-03-04 at 11 13 59 pm](https://cloud.githubusercontent.com/assets/12159652/13532594/d88e7280-e25e-11e5-87ea-a10766bd0855.png)

Can you help me.
How to add check box follow image ?

**Comment by liuxuan30** [comment]
that's something beyond this project. A checkbox can be implemented in many ways. StackOverflow is the better place to ask.
