### ISSUE TITLE
Multiline label on xAxis cutting off 

### ISSUE THREAD

**Issue by kamalahuja** [danielgindi/ios-charts#773]
Thanks for writing this awesome library. Saved us lot of time. We need to display multiline label on xAxis for bar charts. I made the label as word wrap -->    xAxis.wordWrapEnabled = YES; I find only first line displays in my project. Rest of characters are cutting. I tried to replicate in ChartsDemo. I changed the label "Mar test1 test2 test3 test4 test5 test6". On the screen I only see "Mar test1 test2"
![multiline label](https://cloud.githubusercontent.com/assets/17187731/13274354/87fd6698-da78-11e5-95c9-7d5c4c2dceec.png)

**Comment by danielgindi** [comment]
Labels are dynamic, and we cant know for sure how long will they be. 
So you just need to add extra padding for the legend.
