### ISSUE TITLE
CombinedChartView: Wrong positions of bars when using multiple Bar and Graph -Datasets

### ISSUE THREAD

**Issue by AndreasIgelCC** [danielgindi/ios-charts#775]
Hi together,

its a real cool SDK. Unfortunately there is a bug when using the CombinedChartView and multiple Graph-Datasets with Bar-Datasets. Please could you help me?

I did the follwing:

	for (index , sourceobject) in sourceObjectArray.enumerate()
	{
		xVals.append(numberFormatterYear.stringFromNumber(sourceobject.jahr)!)
		datenArray1.append(BarChartDataEntry(value: sourceobject.data1, xIndex: index) )
		datenArray2.append(BarChartDataEntry(value: sourceobject.data2, xIndex: index))
		datenArray3.append(ChartDataEntry(value: sourceobject.data3, xIndex: index))
		if sourceobject.data4 != nil {
			datenArray4.append(ChartDataEntry(value: sourceobject.data4!, xIndex: index))
		}
	}

	let dataSet1 = BarChartDataSet(yVals: datenArray1, label: "label1")
	dataSet1.setColor(UIColor(red: 158/255.0, green: 156/255.0, blue: 161/255.0, alpha: 1.0))
	dataSet1.barSpace = 0.2
	dataSet1.axisDependency = ChartYAxis.AxisDependency.Left
	dataSet1.drawValuesEnabled = false

	let dataSet2 = BarChartDataSet(yVals: datenArray2, label: "label2")
	dataSet2.setColor(UIColor(red: 75/255.0, green: 131/255.0, blue: 169/255.0, alpha: 1.0))
	dataSet2.barSpace =  dataSet1.barSpace
	dataSet2.axisDependency = ChartYAxis.AxisDependency.Left
	dataSet2.drawValuesEnabled = false

	let dataSet3 = LineChartDataSet(yVals: datenArray3, label: "label3")
	let dataSet3Color = UIColor(red: 175/255.0, green: 50/255.0, blue: 51/255.0, alpha: 1.0)
	dataSet3.setColor(dataSet3Color)
	dataSet3.setCircleColor(dataSet3Color)
	dataSet3.lineWidth = 2.5
	dataSet3.circleRadius = 4
	dataSet3.axisDependency = ChartYAxis.AxisDependency.Right
	dataSet3.drawValuesEnabled = false
	dataSet3.drawCirclesEnabled = true
	dataSet3.drawCubicEnabled = false
	dataSet3.drawCircleHoleEnabled = false
	dataSet3.visible = true

	let dataSet4 = LineChartDataSet(yVals: datenArray4, label: "label4")
	let dataSet4Color = UIColor(red: 20/255.0, green: 154/255.0, blue: 220/255.0, alpha: 1.0)
	let dataSet4ColorHole = UIColor(red: 243/255.0, green: 234/255.0, blue: 9/255.0, alpha: 1.0)
	dataSet4.setColor(dataSet4Color)
	dataSet4.setCircleColor(dataSet4Color)
	dataSet4.circleHoleColor = dataSet4ColorHole
	dataSet4.lineWidth = 2.5
	dataSet4.circleRadius = 6
	dataSet4.axisDependency = ChartYAxis.AxisDependency.Right
	dataSet4.drawValuesEnabled = false
	dataSet4.drawCirclesEnabled = true
	dataSet4.drawCubicEnabled = false
	dataSet4.drawCircleHoleEnabled = true
	dataSet4.visible = true

	let barChartData = BarChartData(xVals: xVals, dataSets: [dataSet2, dataSet1])
	barChartData.groupSpace = 0.2
	let graphChartData = LineChartData(xVals: xVals, dataSets: [dataSet3, dataSet4])

	let chartData = CombinedChartData(xVals: xVals)
	chartData.barData = barChartData
	chartData.lineData = graphChartData

	_chartView.data = chartData

The Result (bars not properly aligned with x-values):
<img width="513" alt="screenshot_277" src="https://cloud.githubusercontent.com/assets/2921976/13347733/e926cca4-dc6f-11e5-9e05-8433b85da846.png">

If just using a BarChart and not a combinedChart, the bars are correct (but the graphs are missing):
<img width="507" alt="screenshot_278" src="https://cloud.githubusercontent.com/assets/2921976/13347887/8f4095ac-dc70-11e5-8a7e-d738275c608f.png">

**Comment by liuxuan30** [comment]
current combined chart view does not support multiple bars (grouped bars). I had a PR for that, pending review and discussion.

**Comment by liuxuan30** [comment]
you know what, I just synced my PR with master, some conflicts to solve :) generally, there may have issues with highlighting if you need fine-grained control. Give a try with my branch, I had a view controller in ChartsDemo that demonstrate the grouped bar support.

**Comment by AndreasIgelCC** [comment]
Thx a lot! Worked as promised!

**Comment by liuxuan30** [comment]
np. be careful highlighting if you use it

**Comment by adad184** [comment]
need this
