### ISSUE TITLE
Consider draw map chart without location, navigation stuff?

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#78]
I am not sure how many have such requirements, but do we consider supporting drawing/rendering maps based on SVG, or other formats? 

e.g. US map with states borders, so we can highlight each state, mark each state with various kinds of numbers, like sales, population, etc?

**Comment by danielgindi** [comment]
Well that's not really a chart but a map, and will have a completely different structure and data structure - that you could say it will essentially be a stand alone View in the library...
So we need to consider if it even belongs there - as there are SVG renderers out there...

**Comment by onlyforart** [comment]
I think that what @liuxuan30 is asking for here is an equivalent on iOS of visualisation library D3.js

One can draw charts with D3.js but the reverse should not necessarily be true; personally, I do not believe that it's sensible to try turn iOS-Charts into a general purpose visualisation library.

**Comment by danielgindi** [comment]
I have come to a conclusion that its a nice feature but its place is in a graphics library (or SVG library) and not necessarily a charting library. We may come back to this in the future but we are not going in this direction right now.

**Comment by liuxuan30** [comment]
all right, I actually implemented one called map chart for my needs. Just bring me if you are actually want to carry it out in the future, I would love to help.
