### ISSUE TITLE
Positioning on changing of the screen orientation

### ISSUE THREAD

**Issue by oxodpavel** [danielgindi/ios-charts#786]
Hi!

There is a minor drawback, that when screen orientation changes, the vertical scale loses its position and goes to some range around original (previous).

Conditions:
* occurs only when some scaling has been performed
* occurs only on positions which are not aligned to the horizontal and vertical axes (to thier zero values)
* changing screen orientation back restores graph position to the original state (seems like, horiz and vert orientations have independent positioning parameters, am I write)
![test_app_land](https://cloud.githubusercontent.com/assets/17591717/13459119/8073139a-e082-11e5-9de6-1ad5a2b81b02.jpg)
![test_app_port](https://cloud.githubusercontent.com/assets/17591717/13459120/80758a30-e082-11e5-931b-5883b686c613.jpg)

**Comment by leoMehlig** [comment]
I had the same problem and solved it by overriding this method in my Chart-Class:

`public override func observeValueForKeyPath(
keyPath: String?,
ofObject object: AnyObject?, 
change: [String : AnyObject]?, 
context: UnsafeMutablePointer<Void>) {     `

        var oldPoint: CGPoint?
        if keyPath == "frame" || keyPath == "bounds" {
            oldPoint = viewPortHandler.contentRect.origin
            getTransformer(.Left).pixelToValue(&oldPoint!)
        }
        super.observeValueForKeyPath(keyPath, ofObject: object, change: change, context: context)
        if var p = oldPoint {
            getTransformer(.Left).pointValueToPixel(&p)
            viewPortHandler.centerViewPort(pt: p, chart: self)
        }
        
    } `

(Somehow the code function of the github md isn't working properly)

**Comment by liuxuan30** [comment]
I have it fixed @leoMehlig

**Comment by oxodpavel** [comment]
Yes, thank you! This patch works fine

**Comment by leoMehlig** [comment]
@liuxuan30 is this a feature that should be implemented internally?

**Comment by liuxuan30** [comment]
@leoMehlig I'm not sure if everyone has such requirements, some may want keep centered, while some want nothing changed :) If you think it's useful, than add a switch to turn it on and a PR :)
