### ISSUE TITLE
Stop hiding of xAxis label.

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#79]
Hi Daniel,
Hope you are doing good.

My question is can we stop chart to hide its xAxis label itself ?

Example: I have 4 labels to draw on xAxis i.e. "a,b,c and d"

Expected result: It should show all four labels at xAxis 
Actual result     : It shows only 2 labels i.e. a and b and hide the rest labels. 

How to get rid of this ?

Thanks.

**Comment by danielgindi** [comment]
There's a modulus designed to prevent clutter, showing only every `x` label, skipping the in-between. You can disable it or set a custom modulus.
