### ISSUE TITLE
Is there a way to have multi line labels in x axis.

### ISSUE THREAD

**Issue by niksdgr8** [danielgindi/ios-charts#790]
I have a label which has a very big text. So in portrait mode the label is shown only for alternate bars where as in landscape mode it shows for all bars. Please see the images for further clarification.
![simulator screen shot mar 3 2016 2 55 48 pm](https://cloud.githubusercontent.com/assets/16701331/13490048/4ae6c14e-e150-11e5-8b6b-95ce542566af.png)
![simulator screen shot mar 3 2016 2 55 51 pm](https://cloud.githubusercontent.com/assets/16701331/13490052/4f5362d2-e150-11e5-9419-e25910fc660a.png)

**Comment by liuxuan30** [comment]
x axis supports word wrapping. So check it out and turn it on:
```swift
    /// *Note: currently supports all charts except pie/radar/horizontal-bar*
    public var wordWrapEnabled = false
    
    /// the width for wrapping the labels, as percentage out of one value width.
    /// used only when isWordWrapEnabled = true.
    /// 
    /// **default**: 1.0
    public var wordWrapWidthPercent: CGFloat = 1.0
```

**Comment by zahidshaikh795** [comment]
Do you get the solution ?
I have set both:
lineChart.xAxis.wordWrapEnabled = true
lineChart.xAxis.wordWrapWidthPercent = 1
but with no effect.
