### ISSUE TITLE
xAxis end label is cutting down in Line chart

### ISSUE THREAD

**Issue by rv928** [danielgindi/ios-charts#791]
I am facing problem with xAxis end label is cut. even after zooming and scrolling it is cutting down in Line Chart.As you can see in below image on xAxis end label SA-Android is cutting.
![screen shot 2016-03-03 at 4 03 17 pm](https://cloud.githubusercontent.com/assets/17614089/13491680/c05df47a-e159-11e5-9dd0-f45d7bdd0974.png)

**Comment by liuxuan30** [comment]
can you try 
```
    /// if set to true, the chart will avoid that the first and last label entry in the chart "clip" off the edge of the chart
    public var avoidFirstLastClippingEnabled = false
```

**Comment by amish-infosys** [comment]
Even Setting "avoidFirstLastClippingEnabled" property to false doesn't work.

**Comment by liuxuan30** [comment]
please check ChartsDemo and play with it first. Need more info then as your screenshot is too big
