### ISSUE TITLE
ios 8.1 fatal error:value failed to bridge from Swift type to a Objective-C type

### ISSUE THREAD

**Issue by tcper** [danielgindi/ios-charts#792]
in ChartXAxisRenderer
the exc_bad_instruction line:
let labelSize = widthText.sizeWithAttributes([NSFontAttributeName: _xAxis.labelFont])

but in ios 9.2, there is no error here, but how to fix it ?

**Comment by tcper** [comment]
I fixed it by using :
```
let dict = [NSFontAttributeName: _xAxis.labelFont]
let labelSize = widthText.sizeWithAttributes(dict)
```
the very same meaning code, but it won't crash now, I don't know why

**Comment by danielgindi** [comment]
It's a Swift Compiler optimization bug. We have encountered such in another place. Apple fixes them from time to time. Please try to run it in latest Xcode beta - and let us know if they fixes this one :-)
