### ISSUE TITLE
How to make horizontal dotted line to solid line same as vertical line.

### ISSUE THREAD

**Issue by rv928** [danielgindi/ios-charts#793]
I have enabled line showing using below options. but it is showing dotted line. I want to make it solid line.
 public var drawAxisLineEnabled = true
public var drawGridLinesEnabled = true
![screen shot 2016-03-03 at 4 17 17 pm](https://cloud.githubusercontent.com/assets/17614089/13492331/6a2b56d4-e15d-11e5-9ece-dde007530ebf.png)

**Comment by liuxuan30** [comment]
check out yAxis.gridLineDashPhase, yAxis.gridLineDashLengths, yAxis.gridLineDashLengths.count
