### ISSUE TITLE
Color of crosshairs?

### ISSUE THREAD

**Issue by edalford11** [danielgindi/ios-charts#796]
I'm not seeing a way to change the color of the crosshairs. If there is can we see how to do that? If not, feature request?

**Comment by danielgindi** [comment]
What crosshairs?

**Comment by petester42** [comment]
I'm assuming he is referring to the selected line color.

**Comment by danielgindi** [comment]
In that case, it's the `highlightColor` of the dataset :-)

**Comment by edalford11** [comment]
Exactly what I needed. Thanks.
