### ISSUE TITLE
How to make the chart and the other chart with the same translation

### ISSUE THREAD

**Issue by z404558** [danielgindi/ios-charts#799]
I have a CandleStickChart and a BarChart below it. When I make CandleStickChart zoom in or out , I want BarChart translation.
Do you have a solution about this?

**Comment by z404558** [comment]
- (void)chartTranslated:(ChartViewBase * __nonnull)chartView dX:(CGFloat)dX dY:(CGFloat)dY
{
      // please code in here
}

**Comment by liuxuan30** [comment]
take a look at ChartTransformer and ChartViewPortHandler's methods. There are some playing with the matrix, like
```Swift
    public func refresh(newMatrix newMatrix: CGAffineTransform, chart: ChartViewBase, invalidate: Bool) -> CGAffineTransform
```
There are some guys asked about this quesiton already.
