### ISSUE TITLE
357 Compile Errors on framework files

### ISSUE THREAD

**Issue by kchung14** [danielgindi/ios-charts#8]
I compiled it with xcode 6.2 and 6.3 beta 4 and got 357 errors mostly from every time you call "as!" 

Before I go through and manually fix all the syntax errors, I just wanted to double check with you that I'm not missing a step..

**Comment by kchung14** [comment]
nvm. it works on beta4

**Comment by zxhfirefox** [comment]
@kchung14 , do you mean that the code need to to be compiled with xcode 6.3 beta 4?

**Comment by danielgindi** [comment]
Of course. Didn't you read the README?
