### ISSUE TITLE
Multiple legend entrys will be rendered outside of the view

### ISSUE THREAD

**Issue by MartinPajak** [danielgindi/ios-charts#80]
If a chart have multiple legend entrys and they width exceeds the screen width, they will be rendered outside of the view. It would be cleaner and nicer to open an additional line for the legend description that is longer than the screen width.

**Comment by danielgindi** [comment]
@PhilJay I think we'll need to think about wrapping the text to multiple lines. It requires more calculations but there's not running from it...

**Comment by PhilJay** [comment]
Yes I agree, it's gonna be significant effort though because of offset calculation.

**Comment by danielgindi** [comment]
Word wrapping is supported for a long time now

**Comment by liuxuan30** [comment]
I remember I have asked for a scrollable legend view :-) That can save space if many legends there.
