### ISSUE TITLE
Create Chart from data in Firebase db

### ISSUE THREAD

**Issue by tuzzo77** [danielgindi/ios-charts#800]
Hi.

I'm trying to create a PieChart from my data stored in Firebase DB. My probem is that the legend contains only the first element of the array. If i put the example code in ViewDidLoad (without any observer) all works good. How can I refresh legend to be regenerated?

```
 firebase.observeEventType(.Value, withBlock: { snapshot in
            for item in snapshot.children {
......
            }
   self.setChart(self.answers, values: self.counts)
```

**Comment by petester42** [comment]
1. Make sure this change is happening on the main thread.

2. Call `notifyDataSetChanged` to trigger rending of the chart for new data.

**Comment by tuzzo77** [comment]
notifyDataSetChanged solved!!! Thanks Sir :)
