### ISSUE TITLE
In iOS-Chart how to hide the x and y axis and all the grid lines.

### ISSUE THREAD

**Issue by LekhaP** [danielgindi/ios-charts#801]
I did try setting 
`           
  let xAxis:ChartXAxis = barChartView.xAxis
   xAxis.drawAxisLineEnabled = false
  xAxis.drawGridLinesEnabled = false`
but this doesnot seems to work.

<img width="264" alt="current" src="https://cloud.githubusercontent.com/assets/11720692/13539462/3bcc1d6e-e216-11e5-952c-95867df4cf73.png">

This is what i have right now.

I am trying to achieve
<img width="302" alt="expected_end_result" src="https://cloud.githubusercontent.com/assets/11720692/13539476/4cc48bb0-e216-11e5-9f95-91ed0cd9f3eb.png">

Could somebody help.
Thank you in advance.

**Comment by yijian166** [comment]
Try set `leftAxis` and `rightAxis`

**Comment by LekhaP** [comment]
Thank you so much.
It worked :)

**Comment by anishparajuli555** [comment]
Is there a way i can enable gridlines at specific locations?

**Comment by Sethmr** [comment]
Use limit lines like so:
let limitLine = ChartLimitLine(limit: 0, label: "")
limitLine.lineColor = UIColor.blackColor().colorWithAlphaComponent(0.3)
limitLine.lineWidth = 1

barChart.rightAxis.addLimitLine(limitLine)

**Comment by martindvsisoft** [comment]
leftAxis and rightAxis are only get properties,  how did you achieve it?

**Comment by sUCHIT1507** [comment]
Thank you.

**Comment by Bilal10Akram** [comment]
@LekhaP can you please share how you resolve that issue? Thanks!!!

**Comment by jonfabris** [comment]
how do I remove just the vertical lines?

**Comment by sethi-ishmeet** [comment]
@LekhaP Can you share the solution?

**Comment by Ali-Aqdas** [comment]
@LekhaP  Please share how to set bar labels

**Comment by Rakeshreddy593** [comment]
> Try set `leftAxis` and `rightAxis`

Can you share the solution?

**Comment by Rakeshreddy593** [comment]
@here Also can someone share solution to hide all the values and show only graph
