### ISSUE TITLE
Error in 'ChartPlatform.swift' while compiling : Expected #else or #endif at the end of configuration block 

### ISSUE THREAD

**Issue by mnziosdev** [danielgindi/ios-charts#803]
I have installed iOS charts using cocoa pod

target 'MyPerformance' do
pod 'Charts', '~> 2.2'
use_frameworks!
end

and when compiling , getting this error. i am integrating this in existing Objective c project:
```
Error in 'ChartPlatform.swift' while compiling : Expected #else or #endif at the end of configuration block
```

**Comment by aCorrado** [comment]
Same here in a full Swift project, Xcode 7.1.1

**Comment by danielgindi** [comment]
You should compile with Xcode 7.2
