### ISSUE TITLE
Gap issues on latest version

### ISSUE THREAD

**Issue by acegreen** [danielgindi/ios-charts#804]
Hello,

I'll start off by saving, great work on this library, I have been using it for a while now with no issues. I came across something interesting with the new update.

1. Gap between bars and bottom axis with a barChart
As I recall, this gap was not present before. You can see in the image below, there is a gap between the bars and the bottom line

![simulator screen shot mar 6 2016 9 10 54 am](https://cloud.githubusercontent.com/assets/10794609/13554645/58291550-e37b-11e5-9299-e64eb3f2b597.png)

**Comment by liuxuan30** [comment]
Latest release has deprecated startAtZeroEnabled, which seems is your case.
Please try set customAxisMax and customAxisMin to get the expcted range. e.g.
```
leftAxis.customAxisMin = 0.0; // this replaces startAtZero = YES
```
I used ChartsDemo, and the 0-yaxis still at the bottom

**Comment by acegreen** [comment]
Yea startAtZeroEnabled but by default .customAxisMin = 0.0 anyway. Still getting that gap though

**Comment by liuxuan30** [comment]
@danielgindi This question has been asked twice (another is from SO:http://stackoverflow.com/questions/35798915/issue-in-display-of-barchart-with-latest-ioscharts) 

I debugged a little with ChartsDemo:
Reproduce code, just to insert a small value to stablely trigger it:
```Swift
        double val =  (double) (arc4random_uniform(mult));
        if (i == 0)
            [yVals addObject:[[BarChartDataEntry alloc] initWithValue:1 xIndex:i]];
        else
            [yVals addObject:[[BarChartDataEntry alloc] initWithValue:val xIndex:i]];
```
and in calcMinMax line 337:
```Swift
        // Use the values as they are
        _leftAxis.axisMinimum = !isnan(_leftAxis.customAxisMin)
            ? _leftAxis.customAxisMin
            : (minLeft - bottomSpaceLeft)
```
at this moment, my minLeft is 1.0, while bottomSpaceLeft is 3.5 (35 * 0.1), so the axisMinimum < 0, and we see the additional space.
so when `leftRange * Double(_leftAxis.spaceBottom)` is larger than minLeft, we can always reproduce it.
Shall we force axisMinimum to 0 if customAxisMin is NaN?

**Comment by liuxuan30** [comment]
@acegreen could you specificly call 
leftAxis.customAxisMin = 0.0; // this replaces startAtZero = YES
or leftAxis.startAtZeroEnabled = YES;
on left or right axis? (if you are using both, call on each axis)
I tried with ChartsDemo, when I call them, the gap is gone.

**Comment by acegreen** [comment]
Its always nice to link to a SO question where the only answer is 
> If you still cannot get the y axis bottom as 0, please file a bug on github page

I also already tried to specify leftAxis.customAxisMin = 0.0 and leftAxis.startAtZeroEnabled = YES  with no effect. 

My data sets are on the xAxis in my case so it also make sense that the left or right axis are irrelevant

**Comment by liuxuan30** [comment]
hmm, could you try add break point, and print out minLeft, bottomSpaceLeft, and _leftAxis.axisMinimum
after 
```
_leftAxis.axisMinimum = !isnan(_leftAxis.customAxisMin)
            ? _leftAxis.customAxisMin
            : (minLeft - bottomSpaceLeft)
```
I think `_leftAxis.axisMinimum < 0` is the reason why you see the gap. I will try insert 0 in my demo.

**Comment by liuxuan30** [comment]
I insert 0 in ChartsDemo bar chart, no gap if I call `leftAxis.startAtZeroEnabled = YES;` or the other one
![0](https://cloud.githubusercontent.com/assets/4375169/13559678/c3b79284-e451-11e5-881d-ae35e00be925.png)

**Comment by acegreen** [comment]
I'm confused so you made your first entry a 0 and called leftAxis.startAtZeroEnabled = YES??

Just a side note: None of my entries are less than 0.0

**Comment by liuxuan30** [comment]
I see you have 3 zero values, while I don't, so I manually insert zero values to see if there is bug. In my first test, I only have values >= 1
leftAxis.startAtZeroEnabled = YES or leftAxis.customAxisMin = 0.0; is to force the y axis starts from 0

**Comment by acegreen** [comment]
The zeros are random, but the case is not isolated to the above. In all my attempts, the gap is there. Also none of my entries are less than 0.0

**Comment by acegreen** [comment]
Side note #2: If I leave all my entries at 0, the labels are shifted to the middle of the chart.

![simulator screen shot mar 6 2016 9 21 09 pm](https://cloud.githubusercontent.com/assets/10794609/13559733/4c3e8d14-e3e5-11e5-837a-9750c6344b8f.png)

**Comment by liuxuan30** [comment]
@acegreen yeah, I just want to simulate your data sets in ChartsDemo. that's why I said
 I need your help to print out minLeft, bottomSpaceLeft, and _leftAxis.axisMinimum, I think it should not happen if you called leftAxis.customAxisMin = 0.0
It's at BarLineChartViewBase.swift line 338

**Comment by liuxuan30** [comment]
I also tried your all zero values in ChartsDemo, still no gaps. please try print out minLeft, bottomSpaceLeft, and _leftAxis.axisMinimum at BarLineChartViewBase.swift line 338 if possible;
![all0](https://cloud.githubusercontent.com/assets/4375169/13559849/5192e8d2-e453-11e5-8981-7da6d7e9ca05.png)
If you are using ios-charts embedded framework, well.. Could you try ChartsDemo and reproduce it? Or if we can have a live chat?

**Comment by acegreen** [comment]
**Result:**
2016-03-06 22:00:18.032 StockSwipe[44628:1603879] minLeft 0, bottomSpaceLeft 0, and _leftAxis.axisMinimum 0

**Case:**
![simulator screen shot mar 6 2016 9 54 49 pm](https://cloud.githubusercontent.com/assets/10794609/13559886/e951f464-e3e6-11e5-9b49-b757155bbfc4.png)

**Comment by liuxuan30** [comment]
can we have a live chat? your _leftAxis.axisMinimum seems fine...
seems the matrix is not correct? I am confused

**Comment by acegreen** [comment]
Skype? **Acegreen1989**

**Comment by liuxuan30** [comment]
try http://chat.stackoverflow.com/rooms/105523/ios-charts-issue-804, I create a room

**Comment by liuxuan30** [comment]
So during the chat, it turned out that @acegreen is setting data first, after that is setting the chart without calling notifyDataSetChanged(). reversing the order and problem solved.

Le't get back to the table @danielgindi 
Shall we force axisMinimum to 0 if customAxisMin is NaN? Or we let user to explicitly call customAxisMin = 0?

**Comment by acegreen** [comment]
@liuxuan30 Appreciate the effort on this one.

**Comment by liuxuan30** [comment]
@acegreen we still need to discuss the default behavior with @danielgindi , I will manage this issue, thanks

**Comment by acegreen** [comment]
@liuxuan30 sure. I have my 2 cents above. Unsubscribing to let you guys discuss

**Comment by danielgindi** [comment]
Actually, `axisMinimum` is the property that is `automatically calculated`, and should not be used for that.
In order to constrain the axis range instead of the values calculated from the dataset - there's `customAxisMin`/`customAxisMax`.
Which is what you are doing, and it seems that the `notify...()` is the only thing you were missing :-)

**Comment by st-small** [comment]
@acegreen Can you help me with my values? How did you make your values without .00 (for example 23.00 now showing as 23)??? Thank you very much!

**Comment by liuxuan30** [comment]
@st-small check out `valueFormatter` for any format issues.
