### ISSUE TITLE
Will ios-charts supoprt non-uniform data

### ISSUE THREAD

**Issue by guoyiGOGO** [danielgindi/ios-charts#806]
Will you support the non-uniform data?

can  it？

**Comment by liuxuan30** [comment]
what you mean non-uniform data?

**Comment by guoyiGOGO** [comment]
Not equidistant data.

**Comment by liuxuan30** [comment]
give some examples please

**Comment by guoyiGOGO** [comment]
![2cc9626a-8d8a-4458-a0a2-fd568af96f96](https://cloud.githubusercontent.com/assets/12403934/13565214/b5dfc25c-e489-11e5-8a19-abbe80684b38.png)

**Comment by guoyiGOGO** [comment]
Between two points is not equal

**Comment by liuxuan30** [comment]
you mean x axis? It does not support right now. But Have been asked several times.

**Comment by liuxuan30** [comment]
dup to #194

**Comment by guoyiGOGO** [comment]
ok，thank  you  all the same
