### ISSUE TITLE
multiple datasets with different x-values in chart

### ISSUE THREAD

**Issue by rlimberger** [danielgindi/ios-charts#807]
Thanks for an awesome library! We are just starting to integrate it into a few projects and came across an issue we have with multiple lines in 1 chart. We may just be missing the obvious solution, but looking at the demo projects, it seems a limitation. 

We have multiple datasets we want to show as lines in 1 chart. Each dataset has different xValues. Some of the xValues are shared, but some are unique to each set. 

When looking at the demo, we see:

`LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];`

which seems to assume that all xValues need to be the same for all datasets. 

Is there a way to work around this limitation?

Thanks!

**Comment by liuxuan30** [comment]
yeah currently, the share the same xVals, and x axis is index based, so technically they share the same xIndex. 
you may want to think from the index way, to see if you can merge the different xValues.
you can ignore adding an entry for a specific xIndex, so it will jump to next, which means the line will ignore this xIndex and connect to the next available dot
Releated feature: line breaking #280 and Making X-Values Properly Scaled (Not Equidistant) #194

**Comment by rlimberger** [comment]
Is this possible with the v3 branch?

**Comment by liuxuan30** [comment]
if you are not talking about showing two x axis at same position, I think it's possible. v3 branch is using a different way to calculate x axis (like y axis), so different x values can share the same x axis.
