### ISSUE TITLE
BalloonMarker - display X data

### ISSUE THREAD

**Issue by mondellopaese** [danielgindi/ios-charts#808]
hello,

about the ballon marker, is there the possibility to display also the X data? When I tap on the graph, I need to display not only the value, but also the corresponding X value.

in the file: BalloonMarker.swift
I have tried to modify the label from "value" to "xIndex", but I will see the index and not the dataX(index)

    public override func refreshContent(entry entry: ChartDataEntry, highlight: ChartHighlight)
    {
       // let label = entry.value.description
        let label = entry.xIndex.description

compliments for this good library to create the graph, it is the most beautiful for iPhone!

thanks,
Andrea

**Comment by liuxuan30** [comment]
You could subclass the marker and pass through a x value array, so you can get the value, since you already know the xIndex
data entry object does not have x value right now
