### ISSUE TITLE
Legend Height Adjustment

### ISSUE THREAD

**Issue by MichaelMcGuire** [danielgindi/ios-charts#81]
Let me start by saying I appreciate the library!  It's been great to work with.

I had a question regarding adjusting the height of the `ChartLegend` (when in one of the bottom positions).  In the Demo project's "Line Chart 2 Chart", by default the legend looks like this:

![ios-charts-image-1](https://cloud.githubusercontent.com/assets/429790/7571980/04e452ac-f7d0-11e4-887e-4b9940e189aa.png)

I've been looking for an API to adjust the space set aside for the legend.  I saw that the `ChartLegend` has a property `yOffset`.  When changing the default value from 6.0 to something like 20.0, you get this:

![ios-charts-image-2](https://cloud.githubusercontent.com/assets/429790/7572073/9666b8a0-f7d0-11e4-98c6-b52c83aebfbd.png)

This moved the legend up 20 points (which would be expected based on the name), but didn't actually change the space used for the legend.  I'd like to be able to move the legend closer and/or adjust the space allowed for the legend so as to not have unnecessary space.  It appears the height for a `ChartLegend` is calculated in the `BarLineChartViewBase` on [line 338](https://github.com/danielgindi/ios-charts/blob/master/Charts/Classes/Charts/BarLineChartViewBase.swift#L338) where it is set to 3 times the line height, which makes for a good visual default, but it not customizable.

I'd like to add something to API so I can configure it the way I want, but before doing so, was wondering if this is something you would be interested in seeing?  If so, do you think an additional property on the `ChartLegend` itself is the appropriate place?  Or something on `BarLineChartViewBase` itself?

**Comment by MichaelMcGuire** [comment]
Hey Daniel, sorry to bump this, but was wondering if you've had any chance to think this over?

**Comment by danielgindi** [comment]
I hadn't had time yet- having a busy week...

‏בתאריך יום חמישי, 14 במאי 2015, Michael McGuire <notifications@github.com>
כתב:

**Comment by danielgindi** [comment]
This is an old issue - but it should have been closed long ago, as there are many customizations that allow this now.
