### ISSUE TITLE
Codesign error to physical device on latest

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#810]
I'm currently experiencing an issue with building my app using the Charts project. This seems to only happen when I build the app pointing to a physical device.
The error is

CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.2'

This error doesn't come up if I build pointing to a simulator.

**Comment by osolano** [comment]
Nevermind, somehow this error just went away.

**Comment by shhejianjian** [comment]
@osolano hello? How to do it?
