### ISSUE TITLE
Can we support 2 more than y scales/ multiple Y axis ?

### ISSUE THREAD

**Issue by AnuragDix** [danielgindi/ios-charts#812]
I have a very specific requirement with graph....you saved a lot of work but need to modify with respect to multiple Y axis in Charts... Can you please help me out ? @Philipp Jahoda @danielgindi  @PhilJay  @liuxuan30, @petester42 and @AlBirdie

**Comment by PhilJay** [comment]
Currently thats not possible. You can of course realize it youself. I might add this feature some time in the future.
