### ISSUE TITLE
Linechart X Labels overlap feature

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#813]
When you have a chart with too many values, the following happens

![image](https://cloud.githubusercontent.com/assets/280426/13601732/1dd16d5e-e500-11e5-8357-9cb6ffae3a7f.png)

This is not an issue when you have maybe 6 or 7 values viewable at a time since the width is large enough for them to fit. Is there a way to avoid this and have the labels overlap?

FYI I use setLabelsToSkip, but this only skips labels to show, it doesn't handle the label width

**Comment by petester42** [comment]
You can change the text size.

**Comment by osolano** [comment]
@petester42 That is one approach, but since I made space available I was hoping to use that. Also, many of my users are very old, so keeping text as large as possible is key.

**Comment by danielgindi** [comment]
What you are experiencing is called "word wrapping".
Set `wordWrapEnabled = false` on the x axis.

**Comment by osolano** [comment]
ah yes that was it thank you!

**Comment by danielgindi** [comment]
:+1:
