### ISSUE TITLE
LineChart Delegate for line values

### ISSUE THREAD

**Issue by osolano** [danielgindi/ios-charts#816]
Was wondering if there is a way to do this for a line chart? I was looking for a delegate similar to the x-axis labels, but wasn't able to find it.

![image](https://cloud.githubusercontent.com/assets/280426/13619051/1f3968d6-e555-11e5-8d59-ac06b1fa8522.png)

**Comment by liuxuan30** [comment]
you want add some string ONLY for the last value?

**Comment by osolano** [comment]
Yes, it saves me the trouble of having a legend and allows me to have both lines have the same color.

**Comment by liuxuan30** [comment]
well.. this customization can be done by overriding line chart renderer's `drawValues()`, when it comes to the last value, you manually add one text.
