### ISSUE TITLE
Can we define minor and major grid lines  with specification like (line color, line thickness, on/off )?

### ISSUE THREAD

**Issue by AnuragDix** [danielgindi/ios-charts#817]
I have following requirement related to grid lines in line char graph - 
1) Define minor and major grid lines 
2) We have to give them specification like line grid line color, line thickness and on/off control
3)Tracing graph lines to provide detailed information
4)Range highlight to provide summary information
5)Set the number of decimal place for scale label 

Can you please give the inline comment , what can we achieve or not ? 
Kindly help me out 
 @PhilJay  @danielgindi @liuxuan30, @petester42 and @AlBirdie

**Comment by liuxuan30** [comment]
first please don't "@" every one. We manage the issues on regular basis as possible as we can.
for the questions, please walk through the code carefully, you will find answer there.
For grid lines, what we support is already coded in ChartAxisBase, like:
```swift
    public var gridColor = NSUIColor.grayColor().colorWithAlphaComponent(0.9)
    public var gridLineWidth = CGFloat(0.5)
    public var gridLineDashPhase = CGFloat(0.0)
    public var gridLineDashLengths: [CGFloat]!
    public var gridLineCap = CGLineCap.Butt
```

**Comment by AnuragDix** [comment]
Ok sry for tht.

I have put some more features on comment box. Please have a look on it .

BR, 
Anurag
