### ISSUE TITLE
import Charts: Error No Such Module Charts?

### ISSUE THREAD

**Issue by stephenbai** [danielgindi/ios-charts#818]
Hi there,

I have copied the Charts.xcodeproj from the template to my current working project; but Swift is still unable to find the module "Charts". I have added Charts.framework (all types) under Embedded Binaries... 

I have been online searching for a soln for hours. Has anyone run into a similar situation as I have??

Thanks in advance
Any tips would be appreciated!!!! =)

**Comment by liuxuan30** [comment]
try search old issues, peole has asked about this.
if you are new to importing Swift projects, take a look at https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by stephenbai** [comment]
Hi Xuan,
But the Charts.xcodeproj is written in Swift ( I believe?); So should not Swift adapt frameworks of its own syntax?

**Comment by liuxuan30** [comment]
it's in swift yes. if your project is swift, then simply follow README

**Comment by kzuik** [comment]
I'm having the same issue. Readme doesn't help.
