### ISSUE TITLE
The return value is a problem with the calculateMinimumRadiusForSpacedSlice method

### ISSUE THREAD

**Issue by hachinobu** [danielgindi/ios-charts#819]
Hi!

The return value is a problem with the calculateMinimumRadiusForSpacedSlice method 

![simulator screen shot 2016 03 09 22 11 06](https://cloud.githubusercontent.com/assets/1317847/13636185/dbfec116-e643-11e5-95bd-84a7952d7c93.png)

To reproduce and change the `- (void)setDataCount:(int)count range:(double)range` method of PieChartViewController.m in the ChartsDemo project

```PieChartViewController.m

- (void)setDataCount:(int)count range:(double)range
{    
    NSMutableArray *yVals1 = [[NSMutableArray alloc] init];
    
    // IMPORTANT: In a PieChart, no values (Entry) should have the same xIndex (even if from different DataSets), since no values can be drawn above each other.
    for (int i = 0; i < count; i++)
    {
        if (i == 0) {
            [yVals1 addObject:[[BarChartDataEntry alloc] initWithValue:70000.0 xIndex:i]];
        }
        else {
            [yVals1 addObject:[[BarChartDataEntry alloc] initWithValue:10.0 xIndex:i]];
        }
    }
    //below, no change
}

```

I want to use the slice property, even if there is a great differece in the value of the BarChartDataEntry

what should i do?

**Comment by danielgindi** [comment]
I'm looking into this. Seems like the value becomes gigantic then an angle reaches a very small value (or the opposite, near 360)
