### ISSUE TITLE
Incorrect chart view adjustment after moveViewtoX(xIndex: Int)

### ISSUE THREAD

**Issue by creisterer-db** [danielgindi/ios-charts#82]
Calling chartView.moveViewToX does not appear to be functioning as expected. The chart jumps to a different index, and when scrolling begins the chart will jump again to another different index. Neither seem to be the correct xIndex specified.

This can be replicated by appending two lines in the ChartsDemo project in `LineChart1ViewController.m` after `_chartView.data = data` (line 147):
`[_chartView setVisibleXRange:10];`
` [_chartView moveViewToX:10];`

![moveviewtox](https://cloud.githubusercontent.com/assets/10132604/7591014/55c3e1f0-f899-11e4-9876-90f43cb2605f.jpg)

**Comment by gjpc** [comment]
I can confirm this. Calling moveViewToX: 200 on my simple line chart alternates the view between 0 on the first call and 511 on the next call and back to 0 on the next call etc.

**Comment by danielgindi** [comment]
@creisterer-db your example is irrelevant, as you are trying to move even before the chart has a size or is properly calculated according to that size. *But* still the bug exists!

Working on a fix.

**Comment by mkubenka** [comment]
+1

**Comment by danielgindi** [comment]
It was actually fixed, marked incorrectly as a fix for #129...
https://github.com/danielgindi/ios-charts/commit/4cbd20f77794d0ff063a96920ac354bd2bbb1167
