### ISSUE TITLE
How to draw a rectangle,or how to get the last point's CGPoint?

### ISSUE THREAD

**Issue by yumazaki** [danielgindi/ios-charts#827]
I want to draw this rectangle.
![20160310230629](https://cloud.githubusercontent.com/assets/12462386/13673860/ee3ede60-e715-11e5-878f-5f7a1b053b31.png)
I've searched several hours, how to get it or how to draw?

**Comment by liuxuan30** [comment]
drawing the rect has many options; but I guess you can use ChartMarker and change the coordinates, or you write a new method to draw this;
for the last point - if you can know the lat value's xIndex and it's value, you can convert it into pixels; ChartTransformer's method is doing the job. Take a look at how line dot is drawn; it's in line chart renderer.
