### ISSUE TITLE
[Feature] Double-tap Gesture

### ISSUE THREAD

**Issue by IgorGalay** [danielgindi/ios-charts#829]
Hello guys!

Amazing library! Thank you!

One question. I have to implement double-tap gesture on chart. It should behave like Apple's Stocks app (screenshot attached). Is it possible with iOS-Charts?

![img_4483](https://cloud.githubusercontent.com/assets/5337019/13675694/dffd60d2-e6f3-11e5-994f-c927274deed3.PNG)

Thank in advance!

**Comment by liuxuan30** [comment]
there is a double tap gesture already; you can provide a custom handler for it.
```
        _doubleTapGestureRecognizer = NSUITapGestureRecognizer(target: self, action: Selector("doubleTapGestureRecognized:"))
        _doubleTapGestureRecognizer.nsuiNumberOfTapsRequired = 2
```

BTW, I am curious, how do you implement the filling area visual effect? the gradient effect with many thin and askew lines

**Comment by danielgindi** [comment]
@liuxuan30 that could be a tiled UIImage

**Comment by danielgindi** [comment]
The interesting thing is drawing part of the fill and stroke with a different color. It must be a different layer, as you can't have a gradient account for both the vertical gradient in the picture, and the difference between the black/gray and the highlighted blue. So my guess is "clip to the highlighted region, draw the same dataset with a different colorset".
