### ISSUE TITLE
LineChartView avoid painting 0 values

### ISSUE THREAD

**Issue by cepages** [danielgindi/ios-charts#830]
Hi I'm using LineChartView and I'm trying to remove 0 values from the graph.

![screen shot 2016-03-10 at 17 09 19](https://cloud.githubusercontent.com/assets/5259830/13677794/714d2e16-e6e3-11e5-9fd0-76e0d00415ec.png)

I tried to remove the values from the list:

![screen shot 2016-03-10 at 17 09 26](https://cloud.githubusercontent.com/assets/5259830/13677808/823436ca-e6e3-11e5-9542-e88fafb7ad56.png)

But I'm still want the full list of days. Is there any easy way to do it?

Thanks

**Comment by liuxuan30** [comment]
you just don't create entry with zero values for the xIndex into data set and continue. The line dot will connect to the next available dot, e.g. in your first chart, the '7' dot will connect to '6.7' directly

**Comment by cepages** [comment]
Yeah! Thanks a lot @liuxuan30

**Comment by or1onsli** [comment]
Hi, I am facing the same issue. Can you put a sample-code to show me how you solved this? I already removed the zero-value entries from the dataset but I don't understand how to write all the labels correctly on the xAxis...

Thank you for the help!
