### ISSUE TITLE
Can I change fonts of labels on x And y axis in a bar graph.

### ISSUE THREAD

**Issue by niksdgr8** [danielgindi/ios-charts#832]
I am making an universal app where I have to run it on iPhone as well as iPad. So is there a way to control the font sizes of the lables on  x and y axis.

**Comment by niksdgr8** [comment]
I am sorry. I got what I needed. I am sorry to be asking fairly dumb questions consistently. Actually I am fairly new to iOS and do not have a lot of experience on how to look out for things. But I am learning these things consistently

**Comment by petester42** [comment]
No questions are dumb questions. Don't be sorry. :)

**Comment by harrison0723** [comment]
@niksdgr8 How did you change the font size of the labels? I'm fairly new to Swift too and couldn't find the documentation for this...

**Comment by harrison0723** [comment]
Nevermind I got it, I'll just put it here for future references:

`barChartView.xAxis.labelFont = UIFont.systemFont(ofSize: 20)
`
