### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value error when I set barChartView.noDataText

### ISSUE THREAD

**Issue by patcharaploy** [danielgindi/ios-charts#833]
Hello experts,

I am totally new to this library. I tried to follow the tutorial: http://www.appcoda.com/ios-charts-api-tutorial/. 
However after installing via cocoa pods the library to my project and type

`
barChartView.noDataText = "You need to provide data for the chart."
`

I got the EXEC_BAD_INSTRUCTION error as shown in the below image. 

![screen shot 2559-03-11 at 2 42 21 pm](https://cloud.githubusercontent.com/assets/15868623/13696242/a31d4ee4-e797-11e5-9c47-6989c41957b2.png)

Please suggest me where I am wrong.  

P.S. I already set the view inside of BarChartView as 
Class: BarChartView
Module: Charts

P.S. Actually, the noDataTextDescription method and others also doesn't work.

**Comment by patcharaploy** [comment]
Sorry everyone, I got what I am wrong now.

**Comment by franigam** [comment]
And what is it?

**Comment by Ryan128** [comment]
got same trouble...T_T...
