### ISSUE TITLE
ScatterChart - Is it possible to create a background color like this?

### ISSUE THREAD

**Issue by SergioSCF** [danielgindi/ios-charts#835]
I have a chart that I should separate the points using colors (green for good, yellow for attention, orange for more attention, red for bad) and these values depends of the location of the point (1~3 - green, 4~6 - yellow, 7~8 - orange, 9 or more - red)

![chart](https://cloud.githubusercontent.com/assets/2027565/13711509/b40128ce-e79d-11e5-8ede-2964b3fa5643.png)

Is it possible to make the background of a ScatterChart like this image?

Thank you!

**Comment by SergioSCF** [comment]
PS: The colors are upside down

**Comment by liuxuan30** [comment]
You can write your own logic to render the background. Currently it does not support this.
