### ISSUE TITLE
Horizontal zoom in line chart

### ISSUE THREAD

**Issue by whatsthebeef** [danielgindi/ios-charts#837]
I have implemented a line chart on OSX with panning and vertical zoom working very nicely however the horizontal zoom doesn't work at all? I have a port of the app on the iPad where it is working. Is this expected behavior? If so how come? If not can you think of something I might need to change for OSX or something I might have left out?

**Comment by liuxuan30** [comment]
the horizontal zoom should works fine. Do you see this in ChartsDemo?

**Comment by whatsthebeef** [comment]
Yep, it's working in the demo so it must be something I'm missing. I will close the issue and add the reason why it wasn't working for me when I find it.

**Comment by whatsthebeef** [comment]
Actually horizontal zoom isn't working on the demo, only vertical zoom.

**Comment by danielgindi** [comment]
It depends on which zoom axes you have enabled.
The gesture recognizers on OSX are not mature yet, and do not allow detection of direction. So we can't deduce which axis should be scaled like we do on the iPad.
You can disable zoom on the Y, or allow pinch zooming.

**Comment by whatsthebeef** [comment]
I've enabled pinch zoom but results are the same. How do I disable pinch on the Y axis only and will it not just disable zooming completely?

If it's a case of developing the gesture recognizers further I will take a look?

**Comment by danielgindi** [comment]
You have 3 properties to play with: `pinchZoomEnabled`, `scaleXEnabled`, `scaleYEnabled`.
