### ISSUE TITLE
custom BallonMaker text

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/ios-charts#838]
sorry to trouble, I'm newbie to integrate this smart chart to my project from demo source code, but I have no idea to custom `BalloonMarker` text, what should I do?

regards.

**Comment by liuxuan30** [comment]
you can do whatever you like with ChartMarker. BalloonMarker is just an example. It supports text and image. Take a look at the code

**Comment by L-Jovi** [comment]
thanks a lot, I'll try it.
