### ISSUE TITLE
Custom text over bar chart.

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#84]
*Hi Daniel,* 
Hope you are doing good.

Can we show our custom value/Text over every bar in Bar chart ?

**Currently** : Bar value is shown above bar.
**Expected Behavior**: Show custom value/text over every bar.

Thanks.

**Comment by BurhanMughal** [comment]
**Waiting for positive reply**

**Comment by danielgindi** [comment]
Use a custom number formatter

**Comment by BurhanMughal** [comment]
I think you didn't get my point. 

Data values are something like this : 105,115,120,129,154 etc.

I have type against every data value i.e. Walking,Running,Cycling etc.

I want to draw graph on the bases of values and draw my type over each bar. 

I think I have explained much.

**Comment by danielgindi** [comment]
I didn't quite understand you.

**Comment by BurhanMughal** [comment]
Well this is what I am looking to achieve.
Thanks.

![screenshot_2015-05-15-12-37-48](https://cloud.githubusercontent.com/assets/12183139/7650616/b9b85b3a-fb11-11e4-8bd6-ead385184bcb.png)

**Comment by danielgindi** [comment]
Still you can use a custom NSNumberFormatter. You will receive the value
that you need - and output a String...

**Comment by BurhanMughal** [comment]
I think I can only pass two arrays i.e. xAxis and yAxis containing numbers. How can I pas number and string simultaneously ?

**Comment by danielgindi** [comment]
Well you do not pass a String. You said you do not want the value to show,
only a String right?
If so - then you can use a custom NSNumberFormatter - that will return your
custom String per value.
If you want to show both numeric value and a custom String - that's a
different case that we would have to consider.

**Comment by BurhanMughal** [comment]
Sorry I couldn't quite get your idea, If it will return my custom string not value then how the graph will be populated ?
Getting confused.

**Comment by danielgindi** [comment]
The charts are populated with real values. The NSNumberFormatter is used to
generate the Strings that are rendered on the chart.

**Comment by BurhanMughal** [comment]
You mean to use numberFromString ?

**Comment by BurhanMughal** [comment]
Should I modify ChartViewBase or ChartRenderer ?

**Comment by danielgindi** [comment]
Neither. When I say custom NSNumberFormatter, I mean custom
NSNumberFormatter.

**Comment by BurhanMughal** [comment]
I can't understand your idea of using NSNumberFormatter :(

**Comment by danielgindi** [comment]
Subclass the damn thing. You should really read some of Apple's
documentation on their APIs.

**Comment by BurhanMughal** [comment]
I solved it.. Thanks for your support. I just made changes in swift code and it works fine :) :+1:

**Comment by danielgindi** [comment]
That is not the correct approach, as updated to the project will keep coming. There are APIs for almost anything, and standard ways to customize things.

**Comment by BurhanMughal** [comment]
Yes you are right, It will take some time to apply your suggested approach and I can't afford time loss at this moment that's y I did this. Thanks anyway for suggestion I will eventually apply that one.

Regards.

**Comment by BurhanMughal** [comment]
I found ultimately **Daniel** there are two methods for init the BarDataEntry object one is without data and other one with additional **(id) data __nullable** parameter. I just populate my custom text in that parameter against each data entry and use it in drawText method in BarChartRenderer :).

**Comment by rajasekharmagna** [comment]
Hi BurhanMughal..please send your Applied  code ..i want to show as it is your functionalities..

**Comment by ChetanPTPote** [comment]
hello Sir

**Comment by ChetanPTPote** [comment]
![image 2018-02-26 11 39 12](https://user-images.githubusercontent.com/36834524/36655601-af734310-1ae9-11e8-9e27-03da3f8c45a5.jpg)

how to set that blue bubble  on stacked bar chart in Charts

**Comment by kamrulhassansabuj** [comment]
> I solved it.. Thanks for your support. I just made changes in swift code and it works fine :) 👍

hey, can you please share the solution. I'm facing the same problem. i have grouped bar with budget and actual expenses but i want to show custom data (subcategory of budget and actual) in the marker view. please help.
