### ISSUE TITLE
How can I draw bubble charts in swift project.

### ISSUE THREAD

**Issue by idrisyildiz7** [danielgindi/ios-charts#841]
I spend too much time but I could not find any documents and example for bubble charts.

**Comment by neel4r** [comment]
check the demo app code

**Comment by liuxuan30** [comment]
@neel4r is right

**Comment by idrisyildiz7** [comment]
There is ob-c code but I converted to swift. Thanks.

 func setChartBubble(dataPoints: [String], values1: [Double],values2: [Double],values3: [Double],sortIndex:Int) {
        
        
        var dataEntries1: [BubbleChartDataEntry] = []
        var dataEntries2: [BubbleChartDataEntry] = []
        var dataEntries3: [BubbleChartDataEntry] = []
        
        
        for i in 0..<dataPoints.count {
            
            let dataEntry = BubbleChartDataEntry(xIndex: i, value: values1[i], size: CGFloat(values1[i])*10)
            dataEntries1.append(dataEntry)
        }
        
        
        for i in 0..<dataPoints.count {
            
            let dataEntry = BubbleChartDataEntry(xIndex: i, value: values2[i], size: CGFloat(values2[i])*10)
            dataEntries2.append(dataEntry)
        }
        
        
        for i in 0..<dataPoints.count {
            
            let dataEntry = BubbleChartDataEntry(xIndex: i, value: values3[i], size: CGFloat(values3[i])*10)
            dataEntries3.append(dataEntry)
        }
        
        let chartData1 = BubbleChartDataSet(yVals: dataEntries1,label: "label1" )
        
        let chartData2 = BubbleChartDataSet(yVals: dataEntries2,label: "label2")
        
        let chartData3 = BubbleChartDataSet(yVals: dataEntries3,label: "label3")
        
        chartData1.colors =  [UIColor(red: 33/255, green: 150/255, blue: 254/255, alpha: 1)]
        chartData2.colors =  [UIColor(red: 62/255, green: 89/255, blue: 254/255, alpha: 1)]
        chartData3.colors =  [UIColor(red: 255/255, green: 70/255, blue: 48/255, alpha: 1)]
        
        let dataSets: [BubbleChartDataSet] = [chartData1,chartData2,chartData3]
        
        let data = BubbleChartData(xVals: dataPoints, dataSets: dataSets)
        
        bubbleChartView.data = data;
        bubbleChartView.descriptionText = ""
        bubbleChartView.animate(xAxisDuration: 2.0, yAxisDuration: 2.0, easingOption: .EaseInBounce)
        
    }
