### ISSUE TITLE
integrate native chart display incorrectly

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/ios-charts#842]
I try to integrate this smart lib to my [react native](https://github.com/facebook/react-native) project, but when I moving in chart view, it's messy immediately like below.

details of my question live on [stackoverflow](http://stackoverflow.com/questions/35972015/integrate-native-chart-display-incorrectly) with relevant code, I really want to figure out the reason which cause this, maybe some suggestion will also help me.

thanks for your time.

regards.

![chart](https://cloud.githubusercontent.com/assets/7262199/13737876/ae218d12-e9fb-11e5-904e-a0e8b81a73af.png)

**Comment by L-Jovi** [comment]
be solved [here](https://github.com/facebook/react-native/issues/6440)

**Comment by danielgindi** [comment]
This happens when your view is `opaque=true` and `backgroundColor=UIColor.clearColor()`.

If your view is opaque you must supply an opaque color. Otherwise- set it to `opaque=true`.
