### ISSUE TITLE
Change dataSet axis dependency

### ISSUE THREAD

**Issue by 4074** [danielgindi/ios-charts#845]
Hi.
I want to render two lines on a LineChart. One dataSet dependent on leftAxis. The other dependent on rightAxis.

However, Xcode tell me "axisDependency" is a get-only property when I change the "axisDependency" property of the second dataSet.

So, how can i do this?
Thank you!

**Comment by liuxuan30** [comment]
use `dataSet.axisDependency = AxisDependencyRight;`
