### ISSUE TITLE
how to start graph from (0,0) points instead of 60 on y-Axis?

### ISSUE THREAD

**Issue by rv928** [danielgindi/ios-charts#846]
![screen shot 2016-03-15 at 4 53 16 pm](https://cloud.githubusercontent.com/assets/17614089/13776118/5663b84c-eace-11e5-9ac6-4cad10fce4ac.png)

**Comment by liuxuan30** [comment]
I don't understand it, your chart starts at 0.0 in your screenshot

**Comment by niksdgr8** [comment]
You need to add an extra value to your data source i.e. both x and y data with 0 as a value for Y data at the first index.

**Comment by danielgindi** [comment]
`chart.leftAxis.customAxisMin = 0.0`
