### ISSUE TITLE
Remove text above dot in iOS Charts

### ISSUE THREAD

**Issue by rushabh0999** [danielgindi/ios-charts#848]
Hello Team,

I have user in iOS Charts in my app i want to remove text above Graph dot in iOS
![img_1392](https://cloud.githubusercontent.com/assets/1721285/13809090/1d3b2cc8-eb8f-11e5-8de6-a32f9e3d136f.png)

**Comment by danielgindi** [comment]
Have you tries ChartsDemo?... There's a menu with options there
