### ISSUE TITLE
BarChart adds double x axis

### ISSUE THREAD

**Issue by andretti1977** [danielgindi/ios-charts#849]
A strange effects happens: a not removable xAxis is added to BarChart.
This is the configuration for the axis (data are provided via another method that doesn't interact with axis) and you can see in the attached image that there is a xAxis line in black with no gap to the bars that can't be hidden and a light gray xAxis with gap from the bars that is the one i can configure accessing xAxis.

I want to remove the black one.

```
chartView = [[BarChartView alloc] initWithFrame:CGRectMake(8, 0, tableView.frame.size.width-16, 130)];            
chartView.delegate = self;
            chartView.userInteractionEnabled = NO;
            chartView.backgroundColor = [UIColor colorWithHexString:@"#88FFFFFF"];
            chartView.descriptionText = @"";
            chartView.noDataTextDescription = @"You need to provide data for the chart.";
            
            chartView.drawGridBackgroundEnabled = NO;
            chartView.drawBarShadowEnabled = NO;
            chartView.gridBackgroundColor = [UIColor clearColor];

            
            ChartYAxis *rightAxis = chartView.rightAxis;
            rightAxis.drawGridLinesEnabled = NO;
            rightAxis.drawAxisLineEnabled = NO;
            rightAxis.drawLabelsEnabled = NO;
            
            ChartYAxis *leftAxis = chartView.leftAxis;
            leftAxis.drawGridLinesEnabled = NO;
            leftAxis.drawAxisLineEnabled = NO;
            leftAxis.drawLabelsEnabled = NO;
            
            
            ChartXAxis *xAxis = chartView.xAxis;
            xAxis.labelPosition = XAxisLabelPositionBottom;
            xAxis.drawGridLinesEnabled = NO;
            xAxis.drawAxisLineEnabled = YES;
            xAxis.axisLineWidth = 1.0;
            xAxis.axisLineColor = [UIColor lightGrayColor];
            xAxis.labelTextColor = [UIColor lightGrayColor];
            xAxis.labelFont = [UIFont systemFontOfSize:10 weight:UIFontWeightLight];

```
![schermata 2016-03-16 alle 16 37 21](https://cloud.githubusercontent.com/assets/856429/13818243/6fdb3634-eb95-11e5-87c4-6830b9e2d98d.png)

**Comment by liuxuan30** [comment]
never seeing this before. make sure you call chartView.data = data after you setup your chart view property. it seems like you set the the x axis line color to grey, but the view is not refreshed?

**Comment by imsg** [comment]
I have the same issue, and how can I remove one? 
![bug](https://cloud.githubusercontent.com/assets/3077692/13874801/0dd6e964-ed35-11e5-92cb-ec6813a412db.jpg)

**Comment by danielgindi** [comment]
Maybe you have a "zero line" enabled?

**Comment by danielgindi** [comment]
Well, it seems like when we added the zero line feature, we've set it to `true` by default, by mistake.
@PhilJay we need to change it to `false`

**Comment by andretti1977** [comment]
How can i remove the zero line?

**Comment by PhilJay** [comment]
Yep, that needs to be changed to false.

`dataSet.drawZeroLineEnabled = false`

**Comment by danielgindi** [comment]
We need to change the default on the Android side too, as it will break users' defaults and they'll come filling up the issues section :-)

**Comment by PhilJay** [comment]
Done :-)

**Comment by danielgindi** [comment]
:+1:

**Comment by andretti1977** [comment]
well i have a problem on iOS: can't find drawZeroLineEnabled. Can you post me the exact objective-c code to invoke on the BarChartDataSet?

**Comment by andretti1977** [comment]
i solved it, i was confused by PhilJay comment dataSet.drawZeroLineEnabled = false. had a look at the commit and found it was a feature of ChartYAxis. Thanks fo the help
