### ISSUE TITLE
Make ChartXAxisRenderer calculate labelsWidth based on string output by custom ChartXAxisValueFormatter

### ISSUE THREAD

**Issue by DarkInsight** [danielgindi/ios-charts#851]
XAxis values for my chart is a series of date string in the format of "2016-02-15T06:00:00.000Z";
I format these date strings using a custom ChartXAxisValueFormatter, for example, if the chart is zoomed out, the x axis labels are shown as "16 Mar", "17 Mar" and etc; if the chart is zoomed in, the labels are shown as "04:30pm", "05:00pm" and etc.

Using a default ChartXAxisRenderer, I noticed that it calculate the labelsWidth using the original date string like "2016-02-15T06:00:00.000Z", instead of the formatted string output. May I know how should I solve this issue?

**Comment by danielgindi** [comment]
This is a duplicate (https://github.com/danielgindi/ios-charts/issues/561), we're working on this.
