### ISSUE TITLE
Zoomin Graphview

### ISSUE THREAD

**Issue by rushabh0999** [danielgindi/ios-charts#852]
Hello,

I have large amount of data to display on chart so need to maximum zoom scale to display that data so i can i set maximum zoom scale.I am using below code to display data.but not zoom properly after certain level

```
  [_chartView.viewPortHandler setMaximumScaleY: 10.0];
  [_chartView.viewPortHandler setMaximumScaleX: 10.0];
```

**Comment by danielgindi** [comment]
Please, we cannot understand what does "not zoom properly" mean.
You need to explain yourself clearly, possibly with visual assets.
