### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by wolikeq** [danielgindi/ios-charts#853]
hi, I'm use this chart.framework, Every time when program runs to here,it crash`BarChartDataEntry *en  = [[BarChartDataEntry alloc] initWithValue:[[self.characteristics[i] objectForKey:@"value"] doubleValue] xIndex:i];` but these two parameters have value, The error that the program throws is ‘object can not be nil’.could you help me?

**Comment by danielgindi** [comment]
This is definitely **not** due to `initWithValue`. 
So you may want to separate the statements to different lines, and debug those.
