### ISSUE TITLE
How to prevent xAxis values and dataset value get overlapped ?

### ISSUE THREAD

**Issue by rv928** [danielgindi/ios-charts#854]
I have enabled **public var wordWrapEnabled = true**  for multiple line labels on xAxis. but now facing problem with xAxis label is overlapping below labels.
![screen shot 2016-03-17 at 5 04 34 pm](https://cloud.githubusercontent.com/assets/17614089/13844957/00256908-ec63-11e5-9add-6bb3f95d61bf.png)

**Comment by liuxuan30** [comment]
@danielgindi seems another bug that calculating the legend position not considering wrapping?

**Comment by danielgindi** [comment]
There's no way to know ahead of time how much space you will need, especially considering the visible labels could change when interacting with the chart, and how costly it is to calculate text bounds.

So if you suspect that your chart may have really long labels and with word-wrapping enabled - just add extra padding on the bottom. There's a property for that :-)

**Comment by rv928** [comment]
ok thanks, can you please let me know from where or which class i can change padding to solve this issue?

**Comment by danielgindi** [comment]
That's the chart view

**Comment by rv928** [comment]
LineChartView ?

**Comment by rv928** [comment]
hi thanks issue solved.
