### ISSUE TITLE
DrawCubicEnabled line starts from wrong position

### ISSUE THREAD

**Issue by Havusoft** [danielgindi/ios-charts#855]
When I have a line with two data points and the DrawCubicEnabled is set to true this oddity appears. The line starts before the first point of data. If there is more than two points, no problem.

![screenshot 2016-03-17 02 56 59](https://cloud.githubusercontent.com/assets/9077747/13846600/fcf2846c-ec50-11e5-856f-8728cbfe3eb9.png)

**Comment by danielgindi** [comment]
Yeah, dammit, we know about this (https://github.com/danielgindi/ios-charts/issues/683)
