### ISSUE TITLE
Infinite loop when setting data on ChartDataEntry object

### ISSUE THREAD

**Issue by justinswart** [danielgindi/ios-charts#86]
I'm setting additional data on the ChartEntryObject to pass it to the Marker view:

```Swift
for accountBalance in accountBalances
{
    var entry = ChartDataEntry(value: accountBalance.amount.floatValue, xIndex: count++)
    entry.data = dateFormatter.stringFromDate(accountBalance.date)

    yVals.append(entry)
}
```
This causes EXC_BAD_ACCESS infinite loop in ChartDataEntry.swift:
![screen shot 2015-05-14 at 3 34 13 pm](https://cloud.githubusercontent.com/assets/3735375/7632580/c349f71c-fa4e-11e4-8c5d-938455154772.png)

The problem is fixed by changing line 64 of ChartDataEntry.swift from:

```Swift
if (object!.data !== data && !object!.isEqual(self))
```
to
```Swift
if (object!.data !== data)
```

Is it safe to do so?

**Comment by danielgindi** [comment]
Actually it isn't, the correct fix would be to changed line 54 to be === instead of ==

**Comment by justinswart** [comment]
Hi, thanks for the quick reply.  I changed that line as you suggested but it's now causing EXC_BAD_ACCESS on the line that I thought may be the problem:

![screen shot 2015-05-14 at 3 48 01 pm](https://cloud.githubusercontent.com/assets/3735375/7632823/ae60822e-fa50-11e4-87c8-82f01c658e2f.png)

Making this change does appear to fix it:

```Swift
if (object!.data !== data)
```

I'm new to Swift so I'm just not sure of the full implications of this.  Is !object!.isEqual(self) not somehow causing an infinite isEqual() loop on itself?

**Comment by danielgindi** [comment]
It was just another thing I missed. It should have been isEqual(data)... A commit coming right up.

**Comment by justinswart** [comment]
Thanks!
