### ISSUE TITLE
Different spacing between same width bars in BarChartView

### ISSUE THREAD

**Issue by Aft3rmathpwnz** [danielgindi/ios-charts#860]
I'm sorry for asking this question here, but is there any way to get chart like this?
<img width="495" alt="2016-03-18 23 02 01" src="https://cloud.githubusercontent.com/assets/4174224/13890618/da66d234-ed65-11e5-84d0-1f0be185b310.png">
X-axis here represents daily timeline (24 hours), Y-axis - time (minutes count). The idea is that every bar "grows" from x-daytime-value, when user became online, and its height (y) is time he was online. Is there no more appropriate solution than set `barSpace = 0` and add 24 yVals (every is 0 except ones in which user became online)? Thanks in advance!

**Comment by liuxuan30** [comment]
there is a `groupSpace` you can try, it defines the space between bar groups.
for the time style x axis, right not it's a drawback, you have to insert some nonsense on x axis. Some people are working on the time(float) x axis. Just not have ETA yet.
