### ISSUE TITLE
auto scale min/max option doesn't seem to change anything

### ISSUE THREAD

**Issue by StephanieB5** [danielgindi/ios-charts#863]
The option "Toggle auto scale min/max" doesn't seem to do anything.  I'm not too sure if I'm missing something that should trigger the auto scale min/max.  Thanks.

**Comment by danielgindi** [comment]
The change happens when you're zooming and scrolling a chart

**Comment by StephanieB5** [comment]
I don't see any change in behaviour for zooming/scrolling in Line Charts when using "Toggle auto scale min/max".  From looking at the code I see where _autoScaleLastLowestVisibleXIndex/_autoScaleLastHighestVisibleXIndex are set but they don't seem to be used anywhere.

**Comment by StephanieB5** [comment]
I see it now.  It's more visible in the scrolling and the shift of the graph from the recalculated offset values.  My mistake.
