### ISSUE TITLE
How to move data points with finger drag at run time.

### ISSUE THREAD

**Issue by Monika-Tapadiya** [danielgindi/ios-charts#865]
Hello,
I want to move data points (dot circles) to another x,y points on linechart with finger drag at run time. Can you please tell me it is possible ? I didn't find anything like that.
Thanks

**Comment by liuxuan30** [comment]
when you want to know if it's possible, then it is possible, because you have the source code and idea to carry out. You just cusomize it yourself to whatever you like.

**Comment by Monika-Tapadiya** [comment]
Ok thanks.. will try
