### ISSUE TITLE
Marker behind line limit

### ISSUE THREAD

**Issue by mosaic6** [danielgindi/ios-charts#867]
Hi Daniel,

I'm working on loading multiple charts with different datasets. Most of the charts have a line limit and marker called on each data point. For some reason my marker is being drawn behind the line. Any thoughts?
<img width="374" alt="screenshot 2016-03-21 14 00 58" src="https://cloud.githubusercontent.com/assets/735492/13928759/62e85bec-ef6d-11e5-8ee6-85bbd6579f9b.png">

**Comment by liuxuan30** [comment]
I checked the code, drawLimitLine is called before drawMarkers, so it should not happen...
I tried with ChartsDemo's line chart, negative as well.
Could you debug on your side?

**Comment by mosaic6** [comment]
Ok I looked into it more and I think the issue is on our custom BarChart class. We have implemented the limit line on drawRect 

// after render chart, render limit line again
    override func drawRect(rect: CGRect) {
        super.drawRect(rect)
        
        // we want to render the limit line label (7k) to the left of the data. The default impl clips the drawing context
        // we need to redraw it here w/o clipping the context
        if let context = UIGraphicsGetCurrentContext() {
            leftYAxisRenderer.renderLimitLines(context: context)
        }
    }

If I remove this the marker appears on top of the line but the left axis value doesn't show up (7,000)

**Comment by liuxuan30** [comment]
in your custom bar chart class, usually you don't have to change drawRect, just override the drawing functions.
If you don't want the limit line to be clipped beyond contentRect, then you have to change your rendering order.
I think this can be closed since you find the root cause.
