### ISSUE TITLE
Request for enhancement: combined chart(BarChart (grouped DataSets) and linechart)

### ISSUE THREAD

**Issue by jessjpj** [danielgindi/ios-charts#871]
Hi I have seen BarChart (grouped DataSets) and Combined-Chart (bar- and linechart). But is there any possible way to do combined chart(BarChart (grouped DataSets) and linechart). Please comment your thoughts. Thanks in advance.

**Comment by liuxuan30** [comment]
this is known already. I had a PR https://github.com/danielgindi/ios-charts/pull/269 for this. You could try my branch. This is a huge work and daniel does not have time to review yet.
