### ISSUE TITLE
Carthage & Xcode 7.3 Pre-Built Binaries Error

### ISSUE THREAD

**Issue by DanielAllsoppSage** [danielgindi/ios-charts#874]
It would seem that the pre-built binaries which are downloaded from the ios-charts GitHub repository, version 2.2.3, have been built with a different version of Swift than the one supplied with Xcode 7.3, which results in the following error when the app is run:

`dyld: Symbol not found: __TMPdCSs18_HeapBufferStorage`

The only solution we have at the moment if to use the --no-use-binaries flag and have Carthage build the library, which on our CI server is currently taking 25 minutes to build, and which doesn't work every time. 

Amongst the multiple deprecation warnings, the build sometimes fails completely:

`clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	Ld /Users/xxxxx/Library/Developer/Xcode/DerivedData/ChartsRealm-dueqjgquumbdmuersunznehakala/Build/Intermediates/Charts.build/Release-iphoneos/Charts-OSX.build/Objects-normal/armv7/Charts normal armv7
	Ld /Users/xxxxx/Library/Developer/Xcode/DerivedData/ChartsRealm-dueqjgquumbdmuersunznehakala/Build/Intermediates/Charts.build/Release-iphoneos/Charts-OSX.build/Objects-normal/arm64/Charts normal arm64
(2 failures)`

Any ideas when we might be able to get a newer version of the pre-built binaries from this repository? We've also tried the 'swift3' branch, and get the same linking error with ChartsRealm as shown above.

Thanks

**Comment by adonaire-sage** [comment]
+1 

This might be related to carthage, there is an issue in their repo: https://github.com/Carthage/Carthage/issues/1200

**Comment by gianues** [comment]
+1
I have the same problem with XCode 7.3. After running the 'carthage update' command and rebuilding my project, I get a build error.
Error message: "Module file was created by an older version of the compiler; rebuild 'Charts' and try again. .../Build/iOS/Charts.framework/Modules/Charts.swiftmodule/x86_64.swiftmodule' 

Is there a way to tell Carthage to get the 'Charts' sources and build them itself?

**Comment by petester42** [comment]
Use the `--no-use-binaries` flag. This will recompile all dependencies instead of downloading the prebuilt one.

**Comment by petester42** [comment]
As far a new prebuilt binary goes. It will be with the next version. You can commit the build folder if ci is really slow and building the dependencies.

**Comment by gianues** [comment]
@petester42 `carthage update --no-use-binaries` worked for me, thx

**Comment by danielbmarques** [comment]
When using `--no-use-binaries` I also get `clang: error: linker command failed` etc. a lot of the time.
@DanielAllsoppSage Did you figure this out?
