### ISSUE TITLE
How to make the ChartXAxis has an offset between the zero point

### ISSUE THREAD

**Issue by billxie1988** [danielgindi/ios-charts#875]
Just like the image supposed. Is there any way to move the xAxis starpoint  from zero point?Or what I mean is to make the xAxis label text aligenment center
![default](https://cloud.githubusercontent.com/assets/8359662/14010097/1e105b66-f1cd-11e5-89d3-903959788263.png)

**Comment by billxie1988** [comment]
I find that may be I can do something in calcMinMax()

**Comment by billxie1988** [comment]
I check the combine viewchart set
_chartXMin = -0.5
_chartXMax =  - 0.5 
make it work.But I still don't understand these param meanings
![default](https://cloud.githubusercontent.com/assets/8359662/14014944/bf5ef5ae-f1f0-11e5-9be9-ee9a1f9290ab.png)

**Comment by liuxuan30** [comment]
_chartXMin = -0.5
_chartXMax = - 0.5  is used defining the matrix. when you change it, the matrix will change, so you see waht you got.
Be careful changing it, might get unexpected results if it goes wild
