### ISSUE TITLE
avoidFirstLastClippingEnabled Still be clipped in CombinedChartView

### ISSUE THREAD

**Issue by gabetse** [danielgindi/ios-charts#876]
I 've tried _chartView.xAxis.avoidFirstLastClippingEnabled = true, not use

I seem that the last point was not shown still

**Comment by gabetse** [comment]
I am sure that the last xVal was putted  in the last xVals:
```
for (var i : Int = 0; i < entryCount; i++) {
            let item = entries![i]
            let minute = String(item[0].stringValue)
            let minuteArr = minute.componentsSeparatedByString(":")
            xVals.append(minuteArr[0]+":"+minuteArr[1])
            if i == entryCount-1 {
                print(xVals[i]) //here print the xVals
            }
```

**Comment by gabetse** [comment]
![image](https://cloud.githubusercontent.com/assets/659130/14058492/10aa4298-f35d-11e5-88a7-60443894f1d8.png)

![image](https://cloud.githubusercontent.com/assets/659130/14058485/ec5c96de-f35c-11e5-9fe3-
a621d0635772.png)


The right label was not shown, as if being clipped.

**Comment by liuxuan30** [comment]
could you try to debug a little and fix? I think you are able to, and you will be appreciated.
Otherwise, could you use ChartsDemo code to reproduce? I don't have your data and code, so it will be more efficient on your side.

**Comment by gabetse** [comment]
@liuxuan30 Let me have a check, thank you and have a nice vestval!

**Comment by saxxi** [comment]
Hi, I'm also **not able to show the last label** on the xAxis.

Example:
- I have `50` data points
- I'd like to to show the first `[0]`, a mid point `[24]` and the last `[49]` labels

Here's a set of different attempts:
- `view.xAxis.setLabelsToSkip(25)`
- `view.xAxis.setLabelsToSkip(24)`
- `view.xAxis.axisLabelModulus = 24`

(I'm using `avoidFirstLastClippingEnabled` which is fitting only the first label)

I followed [Stackoverflow](http://stackoverflow.com/questions/35413887/barchartview-xaxis-label-doesnt-display-all-labels/35422530) and apparently the Android version have the [same issue](https://github.com/PhilJay/MPAndroidChart/issues/1689).

Thank you!

**Comment by liuxuan30** [comment]
@saxxi try v3 first. and don't reply a closed issue.. hard to track

**Comment by 29satnam** [comment]
I still have this issue, any solution guys?
