### ISSUE TITLE
Swift 2.2

### ISSUE THREAD

**Issue by EmirTola** [danielgindi/ios-charts#877]
Do the changes work with Swift 2.2? Would be nice to know before I update XCode.

**Comment by james-ff** [comment]
@EmirTola 
I am using this framework with Carthage and it currently does not compile for the Swift 2.2 compiler. 
- I would advise holding off updating until the code has been updated.

This framework is a crucial component of my university project and I'm relying on it to be useable again in Xcode 7.3. Does anyone know when compatibility will be restored? Thanks!

**Comment by EmirTola** [comment]
I looked at the commit and saw only changes that should work with swift 2.2 as well. Can you give me an example where the compiler complaines?

**Comment by Cal-um** [comment]
I am also receiving a compile error having updated to Swift 2.2. 

"Module file was created by an older version of the compiler; rebuild 'Charts' and try again:...."

**Comment by danielgindi** [comment]
The framework is completely compatible with Swift 2.2 and 3.0.

The only problem is with the precompiled Carthage release files.
We will have a version release soon, and in the meantime- I think that you can configure Carthage to just recompile it by itself.

**Comment by moh1122** [comment]
and how i can configure Carthage to just recompile it by itself.

**Comment by petester42** [comment]
Use `--no-use-binaries` option

**Comment by moh1122** [comment]
thnk u

**Comment by leancmscn** [comment]
didn't find swift demo
