### ISSUE TITLE
App Submission - API analysis file too large

### ISSUE THREAD

**Issue by arjunnayak** [danielgindi/ios-charts#878]
While loading up an iOS App using Application Loader (for TestFlight purposes), I received a warning concerning the API Analysis File:

<img width="633" alt="screen shot 2016-03-24 at 12 00 13 pm" src="https://cloud.githubusercontent.com/assets/8644499/14028088/0955afe2-f1b8-11e5-9b63-588b096283ff.png">
The only library I'm using is the Charts Library. 
Without the Charts Library/Functionality, I don't receive the warning. With some research, it's possible that this could also just be an XCode bug. 

This isn't much of a Charts bug per say, and doesn't affect submission, but I wanted to bring this up in case anyone has already solved this issue.

**Comment by liuxuan30** [comment]
I get this warning all the time and I just ignore it. No harm so far. I have no idea where does it comes from. And you see we followed the swift standard, no dark magic :)
If someone knows more about it, please share.

**Comment by wjacker** [comment]
@arjunnayak, It is just an informational message from apple
It can't do the API analysis before upload. It does this to check if you use any restricted API's from the SDK. Because it's too large, you will get the informational message..
