### ISSUE TITLE
defaultTouchEventsEnabled

### ISSUE THREAD

**Issue by jonflanders** [danielgindi/ios-charts#88]
I see you've removed defaultTouchEventsEnabled.  The android version has "setTouchEnabled" - how do I now turn off user interaction - I do not want user interaction.

Thanks

**Comment by danielgindi** [comment]
Every UIView has `userInteractionEnabled`

**Comment by jonflanders** [comment]
ah - thanks!  I didn't see that in the API.  Great work BTW.

Also - is there a way to get the data to only appear animated to start with?   I'm trying to animate as the chart comes into view - but it flashes even when I try to animate right after setting the data - is there a way to delay rendering until the animation methods are called?

Thanks again - great stuff

**Comment by danielgindi** [comment]
I didn't experience this problem - as we usually animate on the first frame
that displays... Otherwise you have a logical problem there.
But you can try setting the data only when you really need to

**Comment by jonflanders** [comment]
should I be setting the animation up before I set the data?   Is there a sample that guarantees animation on the first render?

**Comment by danielgindi** [comment]
Just use the first frame that is supposed to render.Ina view controller it
would be view*Will*Appear.
