### ISSUE TITLE
Could leftAxis and rightAxis's border be hidden?

### ISSUE THREAD

**Issue by gabetse** [danielgindi/ios-charts#884]
![snip20160326_10](https://cloud.githubusercontent.com/assets/659130/14060651/1739e1ce-f3a6-11e5-9168-f0db3603b726.png)
Hi, I want to hide the boder of leftAxis and rightAxis but leave the label on them, how could I achieve this?

**Comment by gabetse** [comment]
Maybe set a transparent border color?

**Comment by liuxuan30** [comment]
disable axisLineEnabled
