### ISSUE TITLE
Set the leftAxis label color differently

### ISSUE THREAD

**Issue by gabetse** [danielgindi/ios-charts#885]
I want set the top label color and the bottom label color separately, set red color for the top label and set green color to the bottom label, how can I do this?
![snip20160326_12](https://cloud.githubusercontent.com/assets/659130/14060709/3fd54550-f3a7-11e5-9da4-0eb537bcf4e2.png)

**Comment by liuxuan30** [comment]
customize it by yourself in axis renderer code.

**Comment by gabetse** [comment]
You mean I should change the ios-charts' source code?

**Comment by liuxuan30** [comment]
yes.
