### ISSUE TITLE
Could not find `Charts.framework` in the "Embedded Binaries"

### ISSUE THREAD

**Issue by gabetse** [danielgindi/ios-charts#891]
I've clone from the git , drag the Charts.xcodeproj to my project explorer , but I Could not find `Charts.framework` in the "Embedded Binaries". My gesture is wrong?

![snip20160328_16](https://cloud.githubusercontent.com/assets/659130/14081060/406d551c-f53b-11e5-989d-19791521da6b.png)

![snip20160328_15](https://cloud.githubusercontent.com/assets/659130/14081123/9dba86ea-f53b-11e5-8811-331246b2d9fd.png)

**Comment by liuxuan30** [comment]
Can you check ChartsDemo and what's the differences between yourrs. 
BTW, you you target should >= 8.0
I checked they are all there for embedded binaries
