### ISSUE TITLE
The view hierarchy is not prepared for the constraint

### ISSUE THREAD

**Issue by tachang** [danielgindi/ios-charts#893]
I seem to get this every so often when working with the view in the Storyboard:

The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x7ff1fb61cbb0 V:[Charts.BarChartView:0x7ff1fb939500(0)]>

	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView(UIConstraintBasedLayout) _viewHierarchyUnpreparedForConstraint:] to debug.

I sometimes try to do some auto layout stuff but even then I am not exactly sure what is happening. I am able to see the chart fine though. Anyone have any idea what causes this or what is going on?

**Comment by liuxuan30** [comment]
I guess you asked in a wrong place.. SO can much better help you.
Your constraints has troubles, the error message tells you.
