### ISSUE TITLE
UISwipeGestureRecognizer for BarChartView

### ISSUE THREAD

**Issue by amitvyawahare** [danielgindi/ios-charts#895]
How can I use UISwipeGestureRecognizer on BarChartView? I wrote some code but it didn't work.

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let gestureRight = UISwipeGestureRecognizer(target: self, action: Selector("handleRightSwipe:"))
        gestureRight.direction = .Right
        barChartView.addGestureRecognizer(gestureRight)
}

    func handleRightSwipe(sender: UISwipeGestureRecognizer) {
        print("Right Direction")
    }

Do I need to disable any gesture from BarChartView to get Right and left swipe ?

**Comment by liuxuan30** [comment]
the library has pan gesture, tap gesture, and pinch gesture. I am not sure if any conflict in your app, but you should check if any view captured your touch event or the library handled it

**Comment by BHZiva** [comment]
@liuxuan30 I have written the same code and its not working for me too. Can you please tell how to handle swipe gesture in this case on bar chart.

**Comment by BHZiva** [comment]
Same code works well on other view but not on BarChartView.
