### ISSUE TITLE
Custom X Axis for BarChartView

### ISSUE THREAD

**Issue by amitvyawahare** [danielgindi/ios-charts#896]
I am using BarChartView. So far I am able to get following BarChartView. My question, is there any way to Customize X Axis that way, it will only show min (left most value 37.03), max (right most value 37.31 which is hiding), value for green bar (37.17) and value for orange bar (37.18 which is hiding again). In a nutshell I want to hide some value from XAxis which is not important in my case. (I have asked this question on stackoverflow as well http://stackoverflow.com/questions/36286416/custom-x-axis-for-barchartview)

![screen shot 2016-03-29 at 9 46 09 am](https://cloud.githubusercontent.com/assets/635098/14114321/7e35d28e-f5a4-11e5-8d1f-e7c6948bb225.png)

**Comment by liuxuan30** [comment]
answered in the SO post. I used to write a smilar one. You can take it as an example. I am using it, so should be bug free. But no guarentee LOL
