### ISSUE TITLE
Multiple 'Charts.framework'. Build fails due to dependencies.

### ISSUE THREAD

**Issue by murrayjl03** [danielgindi/ios-charts#897]
Hi, I have dragged the Charts.xcodeproj into my project and when I go to add the Charts.framework I have multiple options:
![screen shot 2016-03-29 at 18 20 09](https://cloud.githubusercontent.com/assets/17050528/14117160/3ef76402-f5db-11e5-904d-05e2d8605994.png)

When I add any of these i get 'build failed' with the following errors: 
![screen shot 2016-03-30 at 10 09 00](https://cloud.githubusercontent.com/assets/17050528/14137594/57365278-f660-11e5-9f15-c5345fb8407d.png)

 I am using Xcode 7 and swift 2 if that helps at all! Any help would be appreciated as this looks like exactly what i need!

**Comment by liuxuan30** [comment]
You will have error messages if you cannot compile for the warning and error's tab on left panel. You should check why you cannot build first.

**Comment by hardikdevios** [comment]
@murrayjl03 my personal recommendation would be to use the **CocoaPods**. If you are targeting over iOS 8

**Comment by murrayjl03** [comment]
@liuxuan30 Thanks for the tip! My Errors are:
![screen shot 2016-03-30 at 10 09 00](https://cloud.githubusercontent.com/assets/17050528/14137398/8ddda822-f65f-11e5-8e90-165e3fe43435.png)


@hardikdevios I tried using cocopods following (https://cocoapods.org/pods/Charts) however I'm still getting stuck with the errors when i try 'hit the “+” under the “Embedded Binaries” section, and select the Charts.framework' as i don't know, out of the 3 which to select and also getting the errors above.

Thanks!

**Comment by murrayjl03** [comment]
@hardikdevios I am new to CocoaPods. When looking at the tutorial (https://www.raywenderlich.com/97014/use-cocoapods-with-swift) it uses the dependencies "pod 'Alamofire', '2.0.2'", what would I use in this case? Thanks for your suggestion :)

**Comment by danielgindi** [comment]
First try to run ChartsDemo. If you can compile and run that - then you should be able to drag into your project without any trouble. If you cannot compile that - then you are not using the correct Xcode version. Xcode 7.3 was release recently and we moved the codebase to Swift 2.2.
