### ISSUE TITLE
Cannot turn off Barchart Zoom Propertry

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#91]
Hi **Daniel**
I am trying to disable zoom feature for **Bar Chart** with no success.

This is what I am applying : 

    _barChartView.dragEnabled = NO;
    _barChartView.pinchZoomEnabled = NO;
    _barChartView.doubleTapToZoomEnabled = NO;
    _barChartView.defaultTouchEventsEnabled = NO;

Still I can zoom it.

Any idea ?
Thanks.

**Comment by danielgindi** [comment]
There are 3 different kinds of zoom:

1. X scaling
2. Y scaling
3. Pinch to zoom

When pinch to zoom is enabled, x/y scaling is disabled, as they can't work together. You either scale them together or separately. When it is disabled, then scaling x/y depends of separate properties.

`dragEnabled` has nothing to do with it, and so does doubleTap.
`defaultTouchEventsEnabled` does not exist anymore, so you are using an older version ;-)

What you want is `scaleXEnabled` or `scaleYEnabled`. Or you can disable `userInteractionEnabled` to block touches altogether.

**Comment by BurhanMughal** [comment]
Thanks a lot :) :+1:

**Comment by hernanarber** [comment]
Thanks :-)
