### ISSUE TITLE
Bar Chart Delegate.

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/ios-charts#96]
Hi **Daniel**,
Hope you are doing great.
I ran into a strange problem, i.e. Bar chart Delegate method.

**What I want to achieve :** 
Click on the bar and Segue to another view controller.

**Scenario :**
I have bar chart with max visible count of 23, With adjustXLable true.
I have only two values to show on the graph 16,26 on index 15,17 respectively.

**What is actually happening :**
When I click anywhere (left) in the graph it perform segue with value of bar containing value 16.
When I click anywhere (right) in the graph it perform segue with value of bar containing value 26.

Can you please help me in this regard ?
What is possible solution for this ?
**Thanks.**

**Comment by danielgindi** [comment]
Where's the problem?

**Comment by BurhanMughal** [comment]
The problem is it perform segue when I click on the Bar as well as anywhere in the graph, i.e. Area of Graph where no Bar exists.

**Comment by danielgindi** [comment]
Yes this is the way that the charts work, it finds the closest value. If you think this behaviour is wrong you can open an issue in the MPAndroidCharts repo.

**Comment by BurhanMughal** [comment]
Ok Thanks for your reply.
